### ISSUE TITLE
Cache2 - invalid store if number of items is 1

### ISSUE THREAD

**Issue by SebastianBr** [unbit/uwsgi#1003]
We found that if you save only one item in the cache, the store file seems to be invalid:
1.) Configure a cache with a TTL, say 20 seconds
2.) Log the results retrived from the cache. Lets assume it is X
2.) Wait until the store file has been created
3.) Update the single value that shall be cached, e.g a database entry, with value Y
4.) Immediatley after updating the value, restart the uwsgi server such that the store file is read
5.) Log the results retrieved from the cache
=> You will see that even after 20 seconds the cache still returns value X and not Y

Now change the usage of your cache such that two items will be added to cache and repeat the above procedure. Now it will work and the cache will return Y.

We tried the same without the store file and it works fine. It seems the store file is invalid for some reason. We were not able to find the expire time in the store, so we are not sure whats the problem.

BTW: we use version 2.0.8

**Comment by unbit** [comment]
Hi, the store_sync flag of cache2 forces the msync() of caches. Maybe you want to set it to a low value and check again

**Comment by xrmx** [comment]
3 months without followup, closing.
