### ISSUE TITLE
Ragnarok evoked

### ISSUE THREAD

**Issue by ashep** [unbit/uwsgi#1008]
Sometimes I get following error in my emperor's log file after which all the vassals stop working.
```
[emperor] *** RAGNAROK EVOKED ***
```
Where I should search for reasons of such behaviour? Thanks.

**Comment by unbit** [comment]
Ragnarok is the procedure of the Emperor triggered when you send SIGINT to it. All of the vassal will be destroyed (as well as the Emperor itself)

**Comment by ashep** [comment]
Can it happen in case of OS kills emperor's process due to insufficient memory?

**Comment by unbit** [comment]
Generally OS brutally kills processes when out of memory, so it is unlikely unless you have some external process monitor doing it

**Comment by ashep** [comment]
Thank you.
