### ISSUE TITLE
perl-auto-reloader do not reload PSGI application

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1012]
I expect that this option `perl-auto-reloader` also check `psgi = /home/user/public_html/my-app.psgi`
for changes and 'gracefully (RE)spawn' it

**Comment by unbit** [comment]
For the loader the .psgi file is the 'main' app (it is passed as a string blob). Just add it touch-reload

```
touch-reload = %(psgi)
```

The auto-reloader works by checking the loaded modules and their path

**Comment by KES777** [comment]
How to touch-reload in multiapp environment like this:

`mount = =/home/feelsafe/public_html/feel-safe.net.psgi`
?

**Comment by unbit** [comment]
```
mount = /=/home/user/public_html/my-app.psgi
touch-reload = /home/user/public_html/my-app.psgi
```

(sorry not a big fan of the = = form ;) )

or

```
app001 = /home/user/public_html/my-app.psgi
mount = /=%(app001)
touch-reload = %(app001)
```

**Comment by KES777** [comment]
Thank you again. This work file:
```
myapp = /home/feelsafe/public_html/feel-safe.net.psgi
mount = =%(myapp)
manage-script-name = true
perl-auto-reload = 3
touch-reload = %(myapp)
```

And as I noted [here](https://github.com/unbit/uwsgi/issues/263#issuecomment-134212999)
**This does not work!!!**
`mount = /=%(app001)`

**Comment by KES777** [comment]
will be good to see NOTE about this [here](http://uwsgi-docs.readthedocs.org/en/latest/Perl.html#the-auto-reloader-from-uwsgi-1-9-18)
