### ISSUE TITLE
Memory leak while extend the definition of PATH

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1013]
Suppose in your config you have:
```
[uwsgi]
perl-auto-reload = 2
touch-reload = %(psgi)
env = PATH=/home/user/perl5/bin:$(PATH)
```
When psgi app is gracefully reload n billion times this will eat whole memory, because of with each reload this string will be attached '/home/user/perl5/bin:'

EXPECTED:
You must save environment when master process is starting into master space and then extend that environment and not the current worker environment

**Comment by unbit** [comment]
This will break various established behaviour (like counting reloads in environment vars). I think it would be better to add if-not-reload before env that append values:

```
[uwsgi]
if-not-reload =
env = PATH=/home/user/perl5/bin:$(PATH)
endif =
```

**Comment by KES777** [comment]
Thank you. This works well.
Glad to see this NOTE [here](http://uwsgi-docs.readthedocs.org/en/latest/Perl.html#the-auto-reloader-from-uwsgi-1-9-18)

**Comment by unbit** [comment]
The uwsgi-docs repository is opened for pull requests, we are always happy to receive them ;) Thanks a lot for your reports
