### ISSUE TITLE
Missing info in the doc

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1014]
Can not google and find info in the [doc](http://uwsgi-docs.readthedocs.org/en/latest/ParsingOrder.html#expanding-variables-placeholders)

How to access psgi env variables in uwsgi configuations file?

For example:
```
myapp = $(DOCUMENT_ROOT)/$(SERVER_NAME).psgi
mount = =%(myapp)

perl-auto-reload = 2
touch-reload = %(myapp)
```

**Comment by unbit** [comment]
They are available only in the internal routing framework as it is the only part that operates during requests:

http://uwsgi-docs.readthedocs.org/en/latest/InternalRouting.html

the syntax for accessing var is

```
${VAR}
```

**Comment by KES777** [comment]
Ok. Please add info into DOC about [`${VAR}`](http://uwsgi-docs.readthedocs.org/en/latest/InternalRouting.html#accessing-request-vars) [here](http://uwsgi-docs.readthedocs.org/en/latest/ParsingOrder.html#expanding-variables-placeholders)

It is complex to understand. How do next trick that if were opened: s1.example.com than s1.example.com.psgi is executed, when s2.example.com -- s2.example.com.psgi
I suppose:
`myapp = ${DOCUMENT_ROOT}/${SERVER_NAME}` (i understand, this is not ok)
Is this possible at all? help please.

**Comment by unbit** [comment]
That variables are not available out of request context. Try to explain what you want to do, maybe route requests to specific app based on complex rules instead of simple prefix/SCRIPT_NAME ?

**Comment by KES777** [comment]
I want to make template configuration for many sites which will mount psgi applications based on document root of those sites

**Comment by unbit** [comment]
The DOCUMENT_ROOT is available only during a request not at server spawn, maybe you want to try dynamic apps ? http://uwsgi-docs.readthedocs.org/en/latest/Perl.html#multi-app-support

Basically you load applications only after server is started (obviously you will lose prefork cow) passing their path via the UWSGI_SCRIPT variabile.Beware, it is a vey complex setup with lot of corner cases

**Comment by KES777** [comment]
Seems it is. But this example is not explicit and I have miss it before. I think, because of lack info.
Actually:
1. UWSGI_SCRIPT/**UWSGI_FILE** is just mentioned and there is no description what is going on
2. Below in example you use UWSGI_APPID, there are also no description
3. how UWSGI_SCRIPT influence to SCRIPT_NAME when `manage-script-name` true or not
4. Why we need use foo1.pl in uwsgi config and in nginx config (twice usage)
5. What will happen if UWSGI_SCRIPT will have 'psgi.pl' and in uwsgi config we have `mount = app1= psggggi.pl
6. Can I silence script name when mounting application and UWSGI_SCRIPT is initialized?
7. Can I skip initialization UWSGI_SCRIPT in nginx config and just set script name while mounting: `mount = app1=script.name.pl`

This questions are arised reading that DOC

**Comment by unbit** [comment]
Your best bet is checking how people use it for python (before Emperor was available, in 2010/2011 it was a common scenario). Always remember that hosting multiple apps in the same process is not the best approach (Emperor + multiple vassals is way more solid and featurerful).

**Comment by KES777** [comment]
>Emperor + multiple vassals is way more solid and featurerful
Maybe, but I do not understand its mechanism/logic from DOC too and need to google. So I just note you about this lack and questions I had while reading. When I became more experienced all that will obvious for me, I think. So I will not require your DOC at all. 
I hope that these notes will be clue to make DOC clear

**Comment by unbit** [comment]
The problem is that writing docs is often harder than writing good code. You did not catch my previous suggestion to help in improving them :) We try to do our best, but as you can see from github issues is way more easier to get code contributions than docs contributions :)

By the way i think the Emperor docs are one of those that are over the average (i suppose it is because it is one of the most used features) http://uwsgi-docs.readthedocs.org/en/latest/Emperor.html

I think that once you get a bit of confidence with the project you can grasp it in few steps.

**Comment by KES777** [comment]
Maybe some one see this issue and try to contribute to Doc (I do not exclude myself)
If this note will be closed - none will contribute and make DOC clear. 

PS. Closed issue - do not close the questions ;-)

**Comment by KES777** [comment]
Thank you for answers and help

**Comment by unbit** [comment]
There are other issue about it (at least a couple), and the result is always the same, all want to do funny things (contributing code and features), not the boring ones :)
