### ISSUE TITLE
ambigious logging

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1015]
When I configure my application
```
myapp = app.psgi
mount = =%(myapp)
```
I see at logs:
```
Tue Aug 25 12:12:53 2015 - mounting app.psgi on
Tue Aug 25 12:12:53 2015 - Error while loading /app.psgi: No such file or directory at (eval 15) line 4.
```

When:
```
myapp = /app.psgi
mount = =%(myapp)
```
```
Tue Aug 25 12:14:41 2015 - mounting /app.psgi on
Tue Aug 25 12:14:42 2015 - Error while loading /app.psgi: No such file or directory at (eval 15) line 4.
```

Here uwsgi wrongly assume that application is located at root '/' of file system.
In both cases it is trying to load /app.psgi, but mounts different app.psgi's.
Last example is good and MUST work when /app.psgi exists.
First example is ugly congigured and **MUST** fail, because no current directory (NOTICE lack of `chdir`

------------------

Another examples:
```
chdir = /home/user/public_html
myapp = app.psgi
mount = =%(myapp)
```
log:
```
Tue Aug 25 12:22:36 2015 - mounting app.psgi on
Tue Aug 25 12:22:36 2015 - Error while loading /home/feelsafe/public_html/app.psgi: No such file or directory at (eval 15) line 4.
```

And
```
myapp = /home/user/public_html/app.psgi
mount = =%(myapp)
```
log:
```
Tue Aug 25 12:25:14 2015 - mounting /home/user/public_html/app.psgi on
Tue Aug 25 12:25:14 2015 - Error while loading /home/user/public_html/app.psgi: No such file or directory at (eval 15) line 4.
```
As you can see here the target file uwsgi is loading is `/home/user/public_html/app.psgi`
bug in first case it is mounting something different (???)
In case of successfull loading I get:
for first case:
```
Tue Aug 25 12:29:51 2015 - mounting app.psgi on
Tue Aug 25 12:29:51 2015 - PSGI app 0 (app.psgi) loaded in 0 seconds at 0x25f6f40 (interpreter 0x1ecdf30)
```
and second:
```
Tue Aug 25 12:28:04 2015 - mounting /home/user/public_html/app.psgi on
Tue Aug 25 12:28:05 2015 - PSGI app 0 (/home/user/public_html/app.psgi) loaded in 1 seconds at 0x172f2a8 (interpreter 0x
```
As you can see in first case it is hard to say which application is started user1/app.psgi or user2/app.psgi.

So:
1. Use absolute path while logging
2. Do not assume something unexpected/nasty (like '/') instead warn about `chdir` is missing

**Comment by unbit** [comment]
I think all of the reports related to mountpoints are related to the problem that the mountpoints have never been intended for / (or empty). Fixing this should address all of them. For now just use the 'psgi' directive to load the main app

**Comment by KES777** [comment]
Ok. will wait new version of uwsgi =)

**Comment by unbit** [comment]
Moving this to #1011
