### ISSUE TITLE
wrong chdir

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1017]
Why you chdir to '/' ?
```
Wed Aug 26 05:41:32 2015 - worker 1 buried after 1 seconds
Wed Aug 26 05:41:32 2015 - binary reloading uWSGI...
Wed Aug 26 05:41:32 2015 - chdir() to /    <<<<<<<<<<
Wed Aug 26 05:41:32 2015 - closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
....
Wed Aug 26 05:41:32 2015 - pcre jit disabled
Wed Aug 26 05:41:32 2015 - detected number of CPU cores: 2
Wed Aug 26 05:41:32 2015 - current working directory: /   <<<<<<<<<<<
Wed Aug 26 05:41:32 2015 - detected binary path: /usr/bin/uwsgi-core
Wed Aug 26 05:41:32 2015 - your processes number limit is 23874
```
I am not sure, just guess that chdir to '/' is wrong behaviour.

**Comment by unbit** [comment]
When restarting chdir returns the server back to where it was on startup. Without this step relative paths would break.

**Comment by KES777** [comment]
It were not on '/' path on sturtup

**Comment by unbit** [comment]
The current working directory is reported on startup (current working directory: xxx) unless something seriously changes (chroot, dead symlinks...) this dected directory is set-back during reload

**Comment by KES777** [comment]
I understand that is reported, but why it is root '/' and Why it is not the uwsgi bin is located or /tmp for example?

**Comment by unbit** [comment]
This is not a uWSGI choice, it is the cwdir from which it was run, it has nothing to do with the binary path. To have solid reloads you need to rebuild the status of when the server was executed, your cwd was / (maybe because you run it via upstart/systemd/init.d).

**Comment by KES777** [comment]
OK. But logs says that you `chdir() to /` and then shows that `current working directory: /`

```
Wed Aug 26 05:41:32 2015 - chdir() to /    <<<<<<<<<<
...
Wed Aug 26 05:41:32 2015 - current working directory: /   <<<<<<<<<<<
```

Can you do another log (for testing purpose) of cwd before `chdir() to /` log message?

**Comment by unbit** [comment]
Empty cwd by itself has no meaning, i think you are referring to the init.d option of calling chdir before spawning a process, historically UNIX daemons move to / before doing the double fork, and generally init.d (as well as the other modern init systems) do the same (unless you override it). You need to trust what uWSGI reports on the beginning because it is what the os tells to it. You can change (with the chdir option) the cwd after the server has started but this has nothing to do with the initial cwd that is required for consistent paths. There is even an option (force-cwd) to bypass the cwd detection (useful when doing chroot or similar) Just to be clear:

 * uWSGI starts with cwd from / (or whatever it is) and report it, the option chdir move it to another place.
* in reload uWSGI chdir back to / (or whatever it was), patch itself (re-execve) and then chdir to the specified path

**Comment by KES777** [comment]
>and then chdir to the specified path

So you must **do log message about this change**.

Now only message about cwd is / despite on option in uwsgi config:
`chdir = /home/user/public_html`

```
Wed Aug 26 15:07:47 2015 - *** Starting uWSGI 2.0.7-debian (64bit) on [Wed Aug 26 15:07:47 2015] ***
Wed Aug 26 15:07:47 2015 - compiled with version: 4.9.1 on 25 October 2014 19:17:54
Wed Aug 26 15:07:47 2015 - os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24)
Wed Aug 26 15:07:47 2015 - nodename: vpn.guru
Wed Aug 26 15:07:47 2015 - machine: x86_64
Wed Aug 26 15:07:47 2015 - clock source: unix
Wed Aug 26 15:07:47 2015 - pcre jit disabled
Wed Aug 26 15:07:47 2015 - detected number of CPU cores: 2
Wed Aug 26 15:07:47 2015 - current working directory: /
Wed Aug 26 15:07:47 2015 - detected binary path: /usr/bin/uwsgi-core
Wed Aug 26 15:07:47 2015 - your processes number limit is 23874
Wed Aug 26 15:07:47 2015 - your memory page size is 4096 bytes
Wed Aug 26 15:07:47 2015 - detected max file descriptor number: 1024
Wed Aug 26 15:07:47 2015 - lock engine: pthread robust mutexes
Wed Aug 26 15:07:47 2015 - thunder lock: disabled (you can enable it with --thunder-lock)
Wed Aug 26 15:07:47 2015 - uwsgi socket 0 inherited UNIX address /run/uwsgi/app/app/socket fd 3
Wed Aug 26 15:07:47 2015 - initialized Perl 5.20.1 main interpreter at 0xabadc0
Wed Aug 26 15:07:47 2015 - your server socket listen backlog is limited to 100 connections
Wed Aug 26 15:07:47 2015 - your mercy for graceful operations on workers is 60 seconds
Wed Aug 26 15:07:47 2015 - mapped 145536 bytes (142 KB) for 1 cores
Wed Aug 26 15:07:47 2015 - *** Operational MODE: single process ***
Wed Aug 26 15:07:47 2015 - mounting app.psgi on
Wed Aug 26 15:07:47 2015 - PSGI app 0 (app.psgi) loaded in 0 seconds at 0x1a21cf8 (interpreter 0xabadc0)
Wed Aug 26 15:07:47 2015 - gracefully (RE)spawned uWSGI master process (pid: 12366)
Wed Aug 26 15:07:47 2015 - spawned uWSGI worker 1 (pid: 13322, cores: 1)
Wed Aug 26 15:07:47 2015 - *** Stats server enabled on /tmp/uwsgitop.socket fd: 11 ***
```

What is cwd for `app.psgi` here??

**Comment by unbit** [comment]
Infact it logs it: https://github.com/unbit/uwsgi/blob/master/core/uwsgi.c#L2651

I do not know why you do not receive it, maybe the debian version does not have it, frankly i do not remember if it was a later addition.

Btw uWSGI has lot of hooks to do things at the various stages, you can use them to increase info or change behaviours at runtime:

http://uwsgi-docs.readthedocs.org/en/latest/Hooks.html

**Comment by KES777** [comment]
>Infact it logs it
>I do not know why you do not receive it 
Bugs?? ) In next week I'll try start uwsgi on LinuxMint. If it will same - it is some sort of bug.
Hm... Closed issue - kill desire to check what is wrong and leave question opened in any case.

**Comment by unbit** [comment]
We cannot check distro packages or old releases. If you can reproduce the error on a stable/official release it is absolutely ok.

**Comment by unbit** [comment]
And infact: https://github.com/unbit/uwsgi/commit/1a636343597c6b272bd2bc57caeb6cd5fdedf51e

this was added 1 year ago :)
