### ISSUE TITLE
When we can expect Zeus mode

### ISSUE THREAD

**Issue by wysekm** [unbit/uwsgi#1019]
Hi,

I'm enjoying using uwsgi, however there's one feature which interests me (and probably a lot more people) and it's zeus mode. Do you have any plans to work on it in the nearest future? Is the work more advanced than the architecture draft in zeus.c?

Cheers,
Michal

**Comment by unbit** [comment]
Work is going on in the intellisurvey branch, as you can see it allows to pass commands (via udp or unix) to the Emperor to determine which vassal to spawn/stop/respawn. It should merge in 2.1 by the end of the month. The branch already allows you to govern the Emperor via subscriptions. Now that we have a way to easily govern the Emperor, zeus mode should be easy to implement.

**Comment by wysekm** [comment]
Thank you for your quick reply, that's great news. I was a little bit worried after not seeing zeus files being updated for over a year, but it looks like the majority of the work has been done elsewhere.
