### ISSUE TITLE
Defferent behaviour for 'mount' and 'psgi', but expect same

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1020]
When trying to mount psgi script - no any app is loaded:
```
myapp = /home/user/public_html/lib/PSGIHandler
mount = =%(myapp)
```

```
Wed Aug 26 16:08:05 2015 - *** Operational MODE: single process ***
Wed Aug 26 16:08:05 2015 - mounting /home/user/public_html/lib/PSGIHandler on
Wed Aug 26 16:08:05 2015 - *** no app loaded. going in full dynamic mode ***
```

But same script sucessfully works when use it under `psgi` option
`psgi = /home/user/public_html/lib/PSGIHandler`

```
Wed Aug 26 16:06:38 2015 - *** Operational MODE: single process ***
Wed Aug 26 16:06:39 2015 - PSGI app 0 (/home/user/public_html/lib/PSGIHandler) loaded in 1 seconds at 0x19a6908 (interprete
Wed Aug 26 16:06:39 2015 - spawned uWSGI master process (pid: 15943)
Wed Aug 26 16:06:39 2015 - spawned uWSGI worker 1 (pid: 15967, cores: 1)
```

**Comment by KES777** [comment]
as work around I can change extention to `.pl`
```
myapp = /home/feelsafe/public_html/lib/PSGIHandler.pl
mount = =%(myapp)
```

```
Wed Aug 26 16:12:19 2015 - *** Operational MODE: single process ***
Wed Aug 26 16:12:19 2015 - mounting /home/user/public_html/lib/PSGIHandler.pl on
Wed Aug 26 16:12:20 2015 - PSGI app 0 (/home/user/public_html/lib/PSGIHandler.pl) loaded in 1 seconds at 0x249a1d0 (interpr
Wed Aug 26 16:12:20 2015 - spawned uWSGI master process (pid: 16315)
Wed Aug 26 16:12:20 2015 - spawned uWSGI worker 1 (pid: 16339, cores: 1)
```

But that is ugly. It force me to check whole project who is reference `/home/user/public_html/lib/PSGIHandler` and add to it `.pl`

**Comment by unbit** [comment]
The extension of the file is what instructs the core on which plugin to use for loading the app. The only exception is CPython for which colon is used as module/function separator in addition to .py

It is important to understand that --mount and --psgi are different as the first one is language-independent and the second one is exposed by the plugin itself

**Comment by KES777** [comment]
But I use explicit `uwsgi_modifier1 5;` Which must instruct uwsgi that I run perl CGI application

**Comment by unbit** [comment]
Modifiers works at request level, loading/mounting app happens on startup

**Comment by KES777** [comment]
so `uwsgi_modifier1` this is instruction to nginx and not to uwsgi? Which told to nginx speak to uwsgi as *perl*?

**Comment by unbit** [comment]
The cgi plugin does not support the ->mount plugin hook. uwsgi_modifier1 is the nginx option to set in the request that it must be routed to the perl plugin (or whatever the admin mapped to 5).

P.S. take in account that using github issues for support/learning is not the best thing, you should use the #uwsgi irc channel

**Comment by KES777** [comment]
you think this https://github.com/unbit/uwsgi/issues/1020#issue-103307720  is not related to issue?

**Comment by KES777** [comment]
I work around the problem. It seems I can mount 'psgi' too.

```
Example1:
[uwsgi]
psgi = lib/MasonHandler
mount = =%(psgi)

log:
 *** Operational MODE: single process ***
 PSGI app 0 (lib/MasonHandler) loaded in 0 seconds at 0x1b89
 mounting lib/MasonHandler on
 spawned uWSGI worker 1 (pid: 11861, cores: 1)
 *** Stats server enabled on /tmp/uwsgitop.feel-safe.net.soc



Example2:
[uwsgi]
myapp = lib/MasonHandler.psgi
mount = =%(myapp)

log:
 *** Operational MODE: single process ***
 mounting lib/MasonHandler.psgi on
 PSGI app 0 (lib/MasonHandler.psgi) loaded in 1 seconds at 0
 spawned uWSGI worker 1 (pid: 11872, cores: 1)
 *** Stats server enabled on /tmp/uwsgitop.feel-safe.net.soc



Example3:
[uwsgi]
psgi = lib/MasonHandler

log:
 *** Operational MODE: single process ***
 PSGI app 0 (lib/MasonHandler) loaded in 0 seconds at 0x1eab
 spawned uWSGI worker 1 (pid: 11896, cores: 1)
 *** Stats server enabled on /tmp/uwsgitop.feel-safe.net.so
```

Some notes:
example1: Put info into doc, that I can mount 'psgi'
example2: it is strange to see that we mounting application before it were loaded.
example3: if no mount is found the application is mounted by default, I guess. But no log message about that.

**Comment by unbit** [comment]
The first example is wrong, you are loading the app (with the psgi option that triggers the loading of the psgi plugin) and then re-mounting it. I do not think it is what you want to do. Same for the second example.

The third is ok, no mountpoint has been defined, your loaded app will be responsable for every kind of request for the modifier 5

**Comment by KES777** [comment]
first is OK. I do not see other way to load handlers without extensions and mount them to some points
Actually I use:
```
psgi = lib/MasonHandler
mount = /bbc=%(psgi)
psgi = lib/MasonHandler
mount = /abs=%(psgi)


- *** Operational MODE: single process ***
- PSGI app 0 (lib/MasonHandler) loaded in 1 seconds at 0x1647518 (interpreter 0x
- mounting lib/MasonHandler on /bbc
- mounting lib/MasonHandler on /abs
- gracefully (RE)spawned uWSGI master process (pid: 11808)
- spawned uWSGI worker 1 (pid: 12259, cores: 1)
- *** Stats server enabled on /tmp/uwsgitop.feel-safe.net.socket fd: 18 ***
```

But with extention the 'psgi' works differently:

```
psgi = lib/MasonHandler.psgi
mount = /bbc=%(psgi)
psgi = lib/MasonHandler.psgi
mount = /abs=%(psgi)


- *** Operational MODE: single process ***
- PSGI app 0 (lib/MasonHandler.psgi) loaded in 0 seconds at 0x15d5328 (interpret
- mounting lib/MasonHandler.psgi on /bbc
- PSGI app 1 (lib/MasonHandler.psgi) loaded in 0 seconds at 0x32ab598 (interpret
- mounting lib/MasonHandler.psgi on /abs
- PSGI app 2 (lib/MasonHandler.psgi) loaded in 1 seconds at 0x4f79ca8 (interpret
- gracefully (RE)spawned uWSGI master process (pid: 11808)
- spawned uWSGI worker 1 (pid: 12269, cores: 1)
- *** Stats server enabled on /tmp/uwsgitop.feel-safe.net.socket fd: 26 ***
```

In first case there only one APP in second three APPs

**Comment by KES777** [comment]
and, again, it is strange to see mounting before application is loaded

**Comment by unbit** [comment]
The psgi option loads a psgi application. The mount option load and mount an application. If you specify both you load the app two times. You are using the 'psgi' option only to trigger autoloading, but it is really ugly, just add plugin = psgi

**Comment by KES777** [comment]
yes, I have `plugins=logfile,psgi`

But why with same count of options I have different count of loaded applications?

**Comment by unbit** [comment]
Because psgi is a single option, specifying it multiple times results in using only the last one.

The mount option without an extension cannot work, you are only seeing the server announcing that is trying to mount an app but you then do not see any result as none of the plugins is getting rid of it.

Just to be clear, mounting without extension is not supported. There is no way in current code to bypass it, albeit technically is obviously possible:

https://github.com/unbit/uwsgi/blob/master/plugins/psgi/psgi_plugin.c#L751


just hack on the uwsgi_perl_mount_app to force it to load in a different way

**Comment by KES777** [comment]
thank you

**Comment by xrmx** [comment]
This looks sorted out, closing.
