### ISSUE TITLE
Do not ambigios logging about loggers

### ISSUE THREAD

**Issue by KES777** [unbit/uwsgi#1022]
In log I have:
` Aug 30 16:30:03 2015 - unable to find logger`

Here I can not understand which logger was not founded.
Please log logger name also, so I can understand which plugin to connect.

**Comment by unbit** [comment]
this is what the code already does:

https://github.com/unbit/uwsgi/blob/master/core/logging.c#L379

maybe you are using some wrong form like:

```
[uwsgi]
logger =
logger = :
logger = :foobar
```

**Comment by KES777** [comment]
oh, yes, I am :(

**Comment by KES777** [comment]
It will be better if you log logger name in quotes. What do you think?

```
---uwsgi_log("unable to find logger %s\n", name);
+++uwsgi_log("unable to find logger '%s'\n", name);
```

So in log I will have:
```
Aug 30 16:30:03 2015 - unable to find logger ''
```
Instead of uninformative
```
Aug 30 16:30:03 2015 - unable to find logger
```

What do you think?

**Comment by xrmx** [comment]
@KES777 makes sense please open a pull request :)
