### ISSUE TITLE
If WSGI app returns unicode strings the HTTP client gets empty response

### ISSUE THREAD

**Issue by ionelmc** [unbit/uwsgi#1023]
This happens on Python 3 where I mistakenly returned normal strings (instead of byte-strings), eg:

```python
def application(env, sr):
    sr('200 OK', [('Content-Type', 'text/plain'), ('Content-Length', '2')])
    yield 'OK'   # dooh! this should be b'OK'
```

Maybe uWSGI should raise some sort of error somewhere if you don't return byte strings on Python 3? The current handling is too silent.

**Comment by unbit** [comment]
Check #556 the main problem is supporting well-established middlewares. We are investigating if the proposed solution (raising error only on non-empty strings) will be enough

**Comment by xrmx** [comment]
Dup of #556. @ionelmc please subscribe to the other bug.
