### ISSUE TITLE
Python 3 compilation broken on master

### ISSUE THREAD

**Issue by robotclarke** [unbit/uwsgi#1026]
`make` fails with Python 3 on the master branch with the following errors:

```
plugins/python/uwsgi_pymodule.c:14:5: error: suggest braces around initialization of
      subobject [-Werror,-Wmissing-braces]
    PyObject_HEAD_INIT(NULL)
    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m/object.h:86:5: note: 
      expanded from macro 'PyObject_HEAD_INIT'
    1, type },
    ^~~~~~~
plugins/python/uwsgi_pymodule.c:16:5: error: incompatible pointer to integer
      conversion initializing 'Py_ssize_t' (aka 'long') with an expression of type
      'char [21]' [-Werror,-Wint-conversion]
    "uwsgi.RequestContext",
    ^~~~~~~~~~~~~~~~~~~~~~
plugins/python/uwsgi_pymodule.c:34:5: error: incompatible integer to pointer
      conversion initializing 'const char *' with an expression of type
      'unsigned long' [-Werror,-Wint-conversion]
    Py_TPFLAGS_DEFAULT,
    ^~~~~~~~~~~~~~~~~~
/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m/object.h:643:29: note: 
      expanded from macro 'Py_TPFLAGS_DEFAULT'
#define Py_TPFLAGS_DEFAULT  ( \
                            ^~~
plugins/python/uwsgi_pymodule.c:35:5: error: incompatible pointer types initializing
      'traverseproc' (aka 'int (*)(PyObject *, visitproc, void *)') with an
      expression of type 'char [1]' [-Werror,-Wincompatible-pointer-types]
    "",
    ^~
4 errors generated.
```

It's caused by a difference in `object.h` between Python 2 and 3; here's [Python 2](https://hg.python.org/cpython/file/2.7/Include/object.h#l83) and [Python 3](https://hg.python.org/cpython/file/3.4/Include/object.h#l84).  I've traced it back to a commit made by @yueyoum in `plugins/python/uwsgi_pymodule.c` where we initialize a `PyTypeObject`, if they have another chance to look at it.

https://github.com/robotclarke/uwsgi/commit/bf77e8a80d028719ddc7fb91054351f49ce92e90 fixes the problem for Python 3, but breaks Python 2.  (Sorry for the whitespace changes, my editor removes trailing whitespace).  I don't know how to conditionally check for the version of Python in C (or in fact if that is the best way to fix this!), so hopefully there's enough information here for one of you to fix it for me :smile:

**Comment by yueyoum** [comment]
Sorry for that,  I don't test it on Python3...   :(
