### ISSUE TITLE
Can't run app with custom Python (2.7.10):  undefined symbol: Py_GetArgcArgv

### ISSUE THREAD

**Issue by carlopires** [unbit/uwsgi#1030]
I have a custom python 2.7.10 installed in /opt/python. I installed uwsgi for it using `pip install uWSGI`. When I try to run an application using this custom uwsgi I get the following error:

    [uWSGI] getting INI configuration from uwsgi_config.ini
    *** Starting uWSGI 2.0.11.1 (64bit) on [Thu Sep  3 12:17:06 2015] ***
    compiled with version: 4.8.4 on 03 September 2015 11:59:05
    os: Linux-3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014
    nodename: ubuntu
    machine: x86_64
    clock source: unix
    pcre jit disabled
    detected number of CPU cores: 2
    current working directory: /home/ubuntu/test
    writing pidfile to uwsgi.pid
    detected binary path: /opt/python/bin/uwsgi
    your processes number limit is 59762
    your memory page size is 4096 bytes
     *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
    detected max file descriptor number: 1024
    lock engine: pthread robust mutexes
    thunder lock: disabled (you can enable it with --thunder-lock)
    uwsgi socket 0 bound to UNIX address /var/run/test/uwsgi_test.sock fd 3
    Python version: 2.7.10 (default, Sep  3 2015, 01:59:55)  [GCC 4.8.4]
    *** Python threads support is disabled. You can enable it with --enable-threads ***
    Python main interpreter initialized at 0x269f030
    your server socket listen backlog is limited to 100 connections
    your mercy for graceful operations on workers is 60 seconds
    mapped 1115840 bytes (1089 KB) for 10 cores
    *** Operational MODE: preforking ***
    Traceback (most recent call last):
      File "/home/ubuntu/test/test.py", line 13, in <module>
        from av_logger import configure_logger
      File "./av_logger.py", line 5, in <module>
        import av_utils
      File "./av_utils.py", line 11, in <module>
        from watchdog.av_watchdog import WatchDog
      File "./watchdog/av_watchdog.py", line 12, in <module>
        import setproctitle
    ImportError: /opt/python/lib/python2.7/site-packages/setproctitle.so: undefined symbol: Py_GetArgcArgv
    unable to load app 0 (mountpoint='') (callable not found or import error)

It looks like a problem loading setproctitle module, but I can load it fine from python prompt:

    ubuntu@carlo:~/test$ /opt/python/bin/python
    Python 2.7.10 (default, Sep  3 2015, 01:59:55) 
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import setproctitle
    >>>

uwsgi configuration file is as following:

    [uwsgi]
    gid = 1000
    uid = 1000
    socket = /var/run/test/uwsgi_test.sock
    chmod-socket = 664
    #chown-socket = ubuntu:www-data
    wsgi-file = /home/ubuntu/test/test.py
    callable = app
    
    ; create the uwsgi master process
    master = 1
    pidfile = uwsgi.pid
    single-interpreter = 1
    buffer-size = 32768
    ignore-sigpipe = true
    cheaper-algo = spare
    cheaper = 2
    cheaper-initial = 5
    workers = 10
    cheaper-step = 1
    harakiri = 60

**Comment by cenkalti** [comment]
I installed Python 2.7.11 from [this PPA](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7?field.series_filter=precise) and have the same import error when running my application with uWSGI.

**Comment by xrmx** [comment]
@cenkalti have you recompiled the python plugin with that python? There could some issues on the build system when building against non standard include / lib dirs as it probably won't work automagically. So some clue is needed when poking with non system python installation.

**Comment by gregwym** [comment]
I'm having the same issue that `setproctitle` won't load in uwsgi due to `Symbol not found: _Py_GetArgcArgv`. But it can be imported fine in python shell. 

My setup use https://github.com/yyuu/pyenv and https://github.com/yyuu/pyenv-virtualenv. py. The virtualenv is based on system python 2.7.10 from OS X 10.10.5.

**Comment by gregwym** [comment]
In uWSGI,
```
*** Operational MODE: single process ***
--Return--
> /path/to/djangoapp/myapp/apps.py(10)ready()->None
-> import pdb; pdb.set_trace()
(Pdb) import ctypes
(Pdb) ctypes.pythonapi
<PyDLL 'None', handle fffffffffffffffe at 10d30e7d0>
(Pdb) ctypes.pythonapi.Py_GetArgcArgv
*** AttributeError: dlsym(RTLD_DEFAULT, Py_GetArgcArgv): symbol not found
(Pdb)
```

In python shell, 
```
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.pythonapi
<PyDLL 'None', handle fffffffffffffffe at 1057b1490>
>>> ctypes.pythonapi.Py_GetArgcArgv
<_FuncPtr object at 0x10566ebb0>
>>> 
```

**Comment by gregwym** [comment]
Update, this is no longer an issue in uWSGI 2.0.12.

**Comment by xrmx** [comment]
@gregwym is it just because you have compiled uwsgi *after* installing / updating the custom python version?

**Comment by gregwym** [comment]
@xrmx i don't think so. I have tried recreating virtualenv and reinstalling uwsgi and all dependencies freshly. It never worked until I upgrade uwsgi from 2.0.6 to 2.0.12.

**Comment by xrmx** [comment]
@gregwym thanks for checking! I am going to close this, other reports haven't update the bug / answered my questions for a few so it's fixed for you we are all good :)

**Comment by rhfung-zenefits** [comment]
I also encountered this problem. When re-installing and rebuilding uwsgi, make sure to `pip install uwsgi --no-cache`.
