### ISSUE TITLE
Connecting to uWSGi queues from external processes

### ISSUE THREAD

**Issue by thinkwelltwd** [unbit/uwsgi#1035]
I'm hoping that [Django Q](https://github.com/Koed00/django-q/issues/59#issuecomment-139603853) can use uWSGI as broker, but the developer comments that:

_Basically I just need to know how to connect to an uWSGI queue externally, like you can with the cache._

Is that possible? If not, could that feature be added?

**Comment by unbit** [comment]
Currently there are no plans to improve the queuing system. You can eventually spawn a thread in your uWSGI/app stack bound to a port that will receive requests and manipulate queues accordingly. But i am doubtful the django-q author will merge an ad-hoc adapter. But once you spawn an additional context is probably way easier to use something like zmq. The problem with uWSGI queuing is that once you add IPC over it (like when working over a network) you lose all of its performance advantages.

Btw, if you need it, you can fill a commercial request at unbit.com
