### ISSUE TITLE
buffer-size documentation incorrect

### ISSUE THREAD

**Issue by density** [unbit/uwsgi#1048]
The documentation for the `buffer-size` option states

>Set the max size of a request (**request-body excluded**), this generally maps to the size of request headers. By default it is 4k. If you receive a bigger request (for example with big cookies or query string) you may need to increase it. It is a security measure too, so adapt to your app needs instead of maxing it out.

[emphasis added]

However, It appears that the request body is actually included in this amount and uWSGI will close the connection prematurely if this limit is exceeded.

**Comment by unbit** [comment]
Nope, buffer-size is only for headers, as it is limited to 64k it would be soon a huge problem if the request body is included. Are you sure you did not hit the webserver limit ? (for example the nginx one) or you are mapping the request body to a uwsgi var ?

**Comment by density** [comment]
ok, i will try to isolate the issue i'm experiencing and come up with a simple test case. i am proxying to uwsgi from nginx using the uwsgi protocol. for some reason, when the request is large, the connection is dropped. but if i increase buffer size, the request works fine.

**Comment by density** [comment]
i fixed this by setting the following in nginx:

```
uwsgi_buffering off;
```
no need to change `buffer-size`, apparently.

no idea why it works tho. it seems to be a problem with the way nginx receives responses from uwsgi. but i'm happy now. you can close this. thanks for your help.

**Comment by xrmx** [comment]
Let's close this then.
