### ISSUE TITLE
uwsgi handle POST req slowly than fastcgi

### ISSUE THREAD

**Issue by jinsust** [unbit/uwsgi#1049]
I found uwsgi model is slowly than fastcgi , when I use ab testtool to test my site. 
For the test result:

ab test command: 
ab -c 10 -n 1000 -p test.json http://ironman2.taosem.com/mojing/shop_info_get
ab -c 10 -n 1000 -p test.json http://ironman3.taosem.com/mojing/shop_info_get
test.json:
 {"wws":["凶猛熊猫panda"],"include_items":false,"moyan_fields":"shop_sales30,shop_amount30"} 

ironman2 use uwsgi, the result is:
Time taken for tests: 223.194765 seconds
Requests per second: 4.48 [#/sec] (mean)
Time per request: 2231.948 [ms] (mean)
Time per request: 223.195 [ms] (mean, across all concurrent requests)
Transfer rate: 3.41 [Kbytes/sec] received 1.12 kb/s sent 4.54 kb/s total

ironman3 use fastcgi, the result is:
Time taken for tests: 111.17977 seconds
Requests per second: 9.01 [#/sec] (mean)
Time per request: 1110.180 [ms] (mean)
Time per request: 111.018 [ms] (mean, across all concurrent requests)
Transfer rate: 6.86 [Kbytes/sec] received 2.26 kb/s sent 9.13 kb/s total

And when I increase concurrency , the test failed
ab -c 1000 -n 10000 -p test.json http://ironman2.taosem.com/mojing/shop_info_get
apr_socket_recv: Connection timed out (110)

Bellow is my uwsgi command:
uwsgi -s 0.0.0.0:17006 --post-buffering-bufsize 65536 -w ironman_uw -l 4096 -L --optimize=2

**Comment by unbit** [comment]
can you paste the fastcgi command line ? do you mean --fastcgi-socket uwsgi option or a completely another application server ?

**Comment by jinsust** [comment]
another application server, fastcgi command like:
spawn-fcgi -n -p 17014 -- /usr/local/bin/python ironman_nosession.py

**Comment by unbit** [comment]
And how it manages concurrency ? because your uWSGi setup has no concurrency at all

**Comment by jinsust** [comment]
How to setup concurrency for uWSGI ? Is the param "-l 4096" not right?
Or you means I should use -p ?

Fastcgi for web.py only support 1024 connections, and it don't need any extra config.

**Comment by unbit** [comment]
For "concurrency" i mean the concurrency model (multiprocess, multithreading, async...), your uWSGI instance is running in single process mode, os it can manage a single request concurrently. I do not know which fastcgi implementation web.py uses, but if it is flup, it is by default multithreaded with auto thread scaling.

**Comment by jinsust** [comment]
Thank you~ I will try it ~

**Comment by jinsust** [comment]
It's great~ I add 100 threads for each app server and test again
It's faster than fastcgi now~ thank U~
