### ISSUE TITLE
http-keep-alive won't work for 304 response without Content-Length.

### ISSUE THREAD

**Issue by hirokiky** [unbit/uwsgi#1051]
304 not modified response won't have `Content-Length` header basically, so uWSIG's Keep-Alive setting won't work.
Because it requires `Content-Length` header (refs http://uwsgi-docs.readthedocs.org/en/latest/HTTP.html#http-keep-alive)

I'm using [whitenoise](https://github.com/evansd/whitenoise/), a WSGI middleware to serve static files
and it will return 304 response without `Content-Length`.

I think uWSGI should guarantee Keep-Alive for this case.
Do you have any ideas?

**Comment by unbit** [comment]
as stated in the docs you can use frontend keepalive only if your backend correctly cooperates with it.

Eventually you can fix response haders using uWSGI internal routing.

**Comment by hirokiky** [comment]
@unbit Thank you! I didn't know internal routing. I'll try it.
