### ISSUE TITLE
What is correct format for upstream in Nginx?

### ISSUE THREAD

**Issue by david-xie** [unbit/uwsgi#1062]
I got errors during deploying my application with uwsgi and nginx, the strangest thing I saw is nginx logs.

First, I tried to use socket, so I got errors like:

    2015/10/07 09:09:04 [crit] 19190#0: *1 connect() to unix:///tmp/daimaduan-preview.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///tmp/daimaduan-preview.sock:", host: "127.0.0.1"

or

    2015/10/07 09:09:43 [crit] 19216#0: *1 connect() to unix:/tmp/daimaduan-preview.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/tmp/daimaduan-preview.sock:", host: "127.0.0.1"

What I don't understand is why upstream is like `uwsgi://unix://`, I don't know if it is correct. So I did another test and got errors like:

    2015/10/07 08:56:48 [error] 18646#0: *3 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:3031", host: "127.0.0.1"

This upstream `uwsgi://127.0.0.1:3031` makes much more sense and looks like a correct one.

My question is if I want to socket, what is the correct way to set socket? I paste my conf here:

    [uwsgi]
    plugin = python
    chdir = /var/www/daimaduan/preview/current
    master = true
    threads = 20
    processes = 4
    http-socket = /tmp/daimaduan-preview.sock
    ; uid = vagrant
    ; gid = vagrant
    logto = /var/log/daimaduan/preview/uwsgi.log
    virtualenv = /var/www/daimaduan/preview/venv
    ; wsgi-file = /var/www/daimaduan/preview/current/deploy.wsgi
    module = deploy

PS: `uid`, `gid` and `wsgi-file` don't work here.
PS2: `/tmp/daimaduan-preview.sock` does exist

**Comment by xrmx** [comment]
Hello, you can start by reading the documentation, like this tutorial:
http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html
In your config you are confusing http-socket with socket, one speaks http the other the uwsgi protocol.
Then please keep in mind that github issues are not a support forum, better ask on mailing list, irc, stackoverflow this kind of questions.

**Comment by david-xie** [comment]
@xrmx you are right, this is not correct place.
Can you answer my question in mailing list?

**Comment by xrmx** [comment]
@david-xie I've already pointed you to the documentation that explain how to connect nginx and uwsgi. First read that, then if something is not clear feel free to ask questions on the mailling list. Thanks!
