### ISSUE TITLE
uwsgi worker not load balance 

### ISSUE THREAD

**Issue by xinghua** [unbit/uwsgi#1063]
hello

 I use uwsgtop to monitor my uwsgi server, and I found that uwsgi worker not load balance.

 1      6.8     19789   4790    1       12      0       idle    5ms     0       0       12.0M   218633
 3      6.9     19791   4855    1       13      0       idle    6ms     0       0       13.0M   228017
 4      7.2     19792   5024    1       14      0       idle    6ms     0       0       13.0M   231173
 2      8.0     19790   5649    1       14      0       idle    13ms    0       0       13.0M   223331
 5      8.5     19793   5963    1       9       0       idle    7ms     0       0       16.0M   283505
 6      9.6     19794   6731    2       8       0       idle    12ms    0       0       19.0M   295866
 7      13.3    19795   9339    3       20      0       idle    20ms    0       0       30.0M   457206
 8      39.7    23503   27883   16      24      0       busy    16ms    0       0       108.0M  1266708

obviously, worker 8 (wid) has accepted request (27883) request much more than other woker. and the worker which has the biggest worker id ( in above is 8) accepts the most request. how can I handle this situation? thanks.

**Comment by unbit** [comment]
What you are getting is the best load distribution choosen by the kernel. Except for very specific scenarios the kernel knows best which worker will answer the request faster.

If for some reason you want to distribute eavenly, check cpu affinity options or this article:

http://uwsgi-docs.readthedocs.org/en/latest/articles/SerializingAccept.html

**Comment by xinghua** [comment]
thanks !

**Comment by Gatsby-Lee** [comment]
@unbit Thank you for link.
@xinghua Thank you for your question.
