### ISSUE TITLE
uGreen time resolution limit of async_sleep

### ISSUE THREAD

**Issue by barczynsky** [unbit/uwsgi#1075]
Right now I'm having a really annoying issue, while trying to use uWSGI to handle a LOT? of quite small JSON requests. Paired with Flask, but somehow managed to solve major problems coming from such pairing.

I've decided to use uGreen instead of threading to squelch the performance problems with GIL, while handling MULTIPLE not quite 'async' requests. There is just one last hurdle to overcome left...

Green threads are supposed to help with building concurrency oriented services, yet somehow, thou maybe it's just my own wrongdoings there, I'm having heavy (green)thread switching issues. If, one say, I want to use suspend() to often switch context to another (green)thread, it easily becomes a nuke war, with (green)threads flying left and right. So then, I decided to take longer stops by using async_sleep().... And there I may have done wrong, yet again.

The problem is, that lowest supported sleep period outcomes equal to 1000ms, which is like eternity in some cases...

Can't You, please, stop killing my float sleeps mercilessly? As far as I'm aware, most host machines nowadays supply with time resolution at much lower than just single seconds - even at milli/micro or sometimes tens of nano seconds.

Why not just allow lightly sleeping good people (or greenthreads) for short periods of time, like only for 10ms or 20ms?

Cheers,
-- Emil

**Comment by gatopeich** [comment]
Same issue here.
My prototype needs `async_sleep()` for a few milliseconds to simulate calls to external servers and I/O waits, so I can evaluate the framework's performance for a distributed service architecture...

**Comment by unbit** [comment]
Hi, the uGreen api got no updates in the last 4 years, i strongly suggest you to look at gevent.

**Comment by gatopeich** [comment]
Thanks I was misguided by the docs mentioning uGreen first 🙂

**Comment by barczynsky** [comment]
Switched to gevent long time ago where needed, and sadly - when we have gevent already, we just use gevent's built-in WSGI server with proper patching. Also aside from other obvious choices (for some, like gunicorn, twisted, etc.), we were also fond of Waitress server, in case we use threading heavily in other submodules, so that it doesn't randomly crash head on with gevent/asyncio loops. Well, life's full of caveats...

Good luck ;)

-- Emil
