### ISSUE TITLE
When using the pypy with  uswgi has an error

### ISSUE THREAD

**Issue by qzn928** [unbit/uwsgi#1079]
I buid a flask item with pypy, when i use:
uwsgi -s /tmp/uwsgi.sock --pypy-wsgi-file wsgi.py   
to run server, get the under error:
From cffi callback <function uwsgi_pypy_file_loader at 0x00000000016d7538>:
Traceback (most recent call last):
  File "c callback", line 315, in uwsgi_pypy_file_loader
AttributeError: 'module' object has no attribute 'application'
I don't know how to solve it, can you help me?

**Comment by xrmx** [comment]
Hello, does your uwsgi file load with the python plugin? thanks

**Comment by qzn928** [comment]
Yes， using python plugin is ok. I create the  pypy environment with virtualenv. Python version is 2.7.3
My wsgi.py file is:
#! /usr/bin/env pypy
# -*- coding:utf-8 -*-
from myweb import app
if __name__ == "__main__":
    app.run()

and uwsgi config file:
[uwsgi]
virtualenv = /var/www/dream/httpredirect/env/
socket = /tmp/uwsgi.sock
chdir = /var/www/dream/httpredirect/
wsgi-file = wsgi.py
callable = app
workers = 8
master = true
enable-threads = true
gevent-monkey-patch = true
disable-logging = true
plugin = pypy

pip freeze:
Cython==0.23.4
Flask==0.10.1
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.10.4
cffi==1.3.0
distribute==0.6.24
gevent==1.1b7.dev0
greenlet==0.4.7
gunicorn==19.3.0
itsdangerous==0.24
pylibmc==1.5.0
readline==6.2.4.1
requests==2.8.1
uWSGI==2.0.11.2
wsgiref==0.1.2

**Comment by xrmx** [comment]
Il 21/10/2015 04:38, qzn928 ha scritto:
> Yes， using python plugin is ok. I create the pypy environment with virtualenv.
> Python version is 2.7.3
> My wsgi.py file is:
> #! /usr/bin/env pypy
>
>
>   -/- coding:utf-8 -/-
>
> from myweb import app
> if *name* == "*main*":
> app.run()

That looks like a way to run flask as standalone http server no? But you are 
asking pypy to load a wsgi file which this is not. Please take a look at flask 
documentation to see how to create a file that a wsgi application server can load.


-- 
Riccardo Magliocchetti
@rmistaken

http://menodizero.it

**Comment by qzn928** [comment]
@xrmx Thank you very much, I have found the problem. It's working  now.
