### ISSUE TITLE
uwsgi stats-push

### ISSUE THREAD

**Issue by myworking82** [unbit/uwsgi#1080]
Hi. I try to set push statistic to may uwsgi app like this
stats-push = file:path=/tmp/test.stats,freq=10

but when i run my uwsgi ini config i got this answer:
unable to find "file" stats_pusher

on my plugin dir for uwsgi for push i have this plugin
root@dev-1:/usr/lib/uwsgi/plugins# ls -l |grep push
-rw-r--r-- 1 root root   10760 Oct 25  2014 stats_pusher_statsd_plugin.so

on official site are say that:
By default the ‘file’ stats pusher is available up to 1.9.18. Starting from 1.9.19 is available as a plugin (stats_pusher_file).

i have installed 
root@dev-1:/home/zinga# uwsgi --version
2.0.7-debian

so i try and put to ini config this:
stats-push = stats_pusher_file:path=/tmp/test.stats,freq=10
and got this message
unable to find "stats_pusher_file" stats_pusher

What i do wrong?
Thanks for answer!!!

**Comment by xrmx** [comment]
Github issues are not for user support, please ask on the mailing list. Said that since *Starting from 1.9.19 is available as a plugin (stats_pusher_file).* you probably need to load that in your config file before using it.
