### ISSUE TITLE
uwsgi.add_timer doesn't accept iterations parameter

### ISSUE THREAD

**Issue by dakra** [unbit/uwsgi#1088]
According to the docs http://uwsgi-docs.readthedocs.org/en/latest/PythonModule.html?highlight=timer#uwsgi.add_timer ``uwsgi.add_timer`` should accept an iterations parameter.

But in the code https://github.com/unbit/uwsgi/blob/master/plugins/python/uwsgi_pymodule.c#L298-L312 you can see that only ``uwsgi.add_rb_timer`` actually accepts `iterations`.

**Comment by xrmx** [comment]
@dakra your analysis looks good so you have opened the issue on the wrong repository. Please close this one and create a new one in the uwsgi-docs repo. Thanks!

**Comment by dakra** [comment]
OK, I made a pull request there https://github.com/unbit/uwsgi-docs/pull/264
