### ISSUE TITLE
from uwsgidecorators import postfork  generates Attribute error

### ISSUE THREAD

**Issue by AnderUstarroz** [unbit/uwsgi#1099]
Many apps  are using the following approach for running either the development or the uwsgi production server: 

	try:
		from uwsgidecorators import postfork
	except ImportError:
		# Start development db connections
	else:
		@postfork
		def start_uwsgi():
	    	#Start uwsgi db connections 

But seems like with uwsgi **2.0.11.2** it doesn't work anymore, It throws the following error:
```
 ../site-packages/uwsgidecorators.py", line 12, in <module>
    if uwsgi.masterpid() == 0:
AttributeError: 'module' object has no attribute 'masterpid'
```

**Comment by xrmx** [comment]
@AnderUstarroz that is quite strange, what python version are you using? what does dir(uwsgi) say? From what version where you upgrading?

**Comment by AnderUstarroz** [comment]
- Running a Virtual env with Python **3.4.2**. 
- Updated from uwsgi version **2.0.9** to **2.0.11.2**.

If I execute dir(uwsgi):
```
import uwsgi
dir(uwsgi) # Response:  ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by xrmx** [comment]
@AnderUstarroz wow, the uwsgi module does not really look like what it's supposed to be. Can you please provide a reduced version of your uwsgi config that shows the problem?

**Comment by AnderUstarroz** [comment]
You should get the same result just creating a virtual env with Python **3.4.2**, installing uwsgi with pip:
```
pip install uwsgi==2.0.11.2
```
 and  just running `from uwsgidecorators import postfork` in a empty script or console. 
My platform is OS X  **10.11.1** "El Capitan", pip (**7.1.2**), setuptools (**18.4**)

**Comment by xrmx** [comment]
@AnderUstarroz the uwsgi module is not a canonical python module, it's exported by uwsgi itself only when running under uwsgi.

**Comment by AnderUstarroz** [comment]
But what should happen if it is not running under uwsgi? Shouldn't throw a import error? I think that was the previous behavior right?

**Comment by methane** [comment]
@AnderUstarroz Isn't there `uwsgi.py` or `uwsgi.pyc` in your directory?

**Comment by AnderUstarroz** [comment]
oh god.. there was an empty folder called  uwsgi/ on the root of my project that was generating this unexpected behavior... Thanks @methane and @xrmx
