### ISSUE TITLE
worker dies by signal 6 + Fatal Python error: Inconsistent interned string state.

### ISSUE THREAD

**Issue by thestick613** [unbit/uwsgi#1111]
I keep getting these in my logs:

    DAMN ! worker 1 (pid: 12639) died, killed by signal 6 :( trying respawn ...
    Respawned uWSGI worker 1 (new pid: 12644)
    DAMN ! worker 5 (pid: 12641) died, killed by signal 6 :( trying respawn ...
    Respawned uWSGI worker 5 (new pid: 12645)
    DAMN ! worker 12 (pid: 12642) died, killed by signal 6 :( trying respawn ...
    Respawned uWSGI worker 12 (new pid: 12646)
    DAMN ! worker 9 (pid: 12643) died, killed by signal 6 :( trying respawn ...
    Respawned uWSGI worker 9 (new pid: 12647)

And lots of:

    Fatal Python error: Inconsistent interned string state.

I'm running

    uwsgi 2.0.9
    Python 2.7.10
    nginx version: nginx/1.6.2

uwsgi is running like this:

    uwsgi --ini /home/www-data/webserver/uwsgi_conf.conf --wsgi-env-behaviour=holy

/home/www-data/webserver/uwsgi_conf.conf

    [uwsgi]
    socket = /socket/my_app.uwsgi
    stats = /socket/stats_socket.uwsgi
    chdir = /home/www-data/
    limit-as = 14000
    processes = 32
    threads = 1
    master = true
    max-requests = 2048
    max-worker-lifetime = 1800
    wsgi-file = webserver.py

nginx relevant config

    server {
            listen 80;
            server_name Minifier;
            location / {
                    include uwsgi_params;
                    uwsgi_pass unix:///socket/my_app.uwsgi;
            }
    }

my app is something very basic, such as:

    import gevent.pywsgi as pywsgi
    import wsgiref

    def application(environ, start_response):
        if YYY:
            start_response("302 Found", headers + [("Location", "XXX"),])
        else:
            start_response('404 Not Found', headers)
        return [""]
    if __name__ == "__main__":
            server = pywsgi.WSGIServer(('', 8888), application=application, backlog=1024, log=None)
            server.serve_forever()

I have quite some errors in nginx logs:

    2015/11/11 13:26:29 [error] 6623#0: *199487 recv() failed (104: Connection reset by peer) while reading response header from upstream
    2015/11/11 12:37:56 [error] 6626#0: *109585 upstream prematurely closed connection while reading response header from upstream
    2015/11/08 17:25:52 [error] 9977#0: *246601736 connect() to unix:///socket/my_app.uwsgi failed (11: Resource temporarily unavailable) while connecting to upstream

But the vast majority of requests go just fine. Reloading a link that failed once usually works.

I'm planning on upgrading the machine today with newer versions of gevent, uwsgi and python, but in case that fails, i'd love to find some pointers on why my app is failing or how to debug it. I've also experimented with no as-limit, bigger and smaller as-limit, bigger and smaller backlog and bigger and smaller number of processes. Is there a way i could convince uwsgi not to drop the request or nginx to reload it in the mean time? Thankx.

**Comment by xrmx** [comment]
Any reason you are not using uwsgi gevent plugin?
http://uwsgi-docs.readthedocs.org/en/latest/Gevent.html

**Comment by thestick613** [comment]
Pasted too much code, since i'm not actually using gevent at all, because uwsgi loads from `webserver.py` the `application` function. I remember trying multiple configurations 6 months ago when i deployed this, and this was the most performant one. The gevent imports are useless in there.

**Comment by xrmx** [comment]
Il 11/11/2015 14:15, thestick613 ha scritto:
> I keep getting these in my logs:
>
> |DAMN ! worker 1 (pid: 12639) died, killed by signal 6 :( trying respawn ...
> Respawned uWSGI worker 1 (new pid: 12644) DAMN ! worker 5 (pid: 12641) died,
> killed by signal 6 :( trying respawn ... Respawned uWSGI worker 5 (new pid:
> 12645) DAMN ! worker 12 (pid: 12642) died, killed by signal 6 :( trying respawn
> ... Respawned uWSGI worker 12 (new pid: 12646) DAMN ! worker 9 (pid: 12643)
> died, killed by signal 6 :( trying respawn ... Respawned uWSGI worker 9 (new
> pid: 12647) |

Your config says to restart workers after 2048 requests and, if i understand it 
correctly, ensure they do not stay up more than 1800 seconds, could it be just that?

> And lots of:
>
> |Fatal Python error: Inconsistent interned string state. |

This is strange but that looks like a python interpreter error. Tried googling 
for that string?

> I'm running
>
> |uwsgi 2.0.9 Python 2.7.10 nginx version: nginx/1.6.2 |
>
> uwsgi is running like this:
>
> |uwsgi --ini /home/www-data/webserver/uwsgi_conf.conf --wsgi-env-behaviour=holy |
>
> /home/www-data/webserver/uwsgi_conf.conf
>
> |[uwsgi] socket = /socket/my_app.uwsgi stats = /socket/stats_socket.uwsgi chdir =
> /home/www-data/ limit-as = 14000 processes = 32 threads = 1 master = true
> max-requests = 2048 max-worker-lifetime = 1800 wsgi-file = webserver.py |

does the stats give you any hints?

> nginx relevant config
>
> |server { listen 80; server_name Minifier; location / { include uwsgi_params;
> uwsgi_pass unix:///socket/my_app.uwsgi; } } |
>
> my app is something very basic, such as:
>
> |import gevent.pywsgi as pywsgi import wsgiref def application(environ,
> start_response): if YYY: start_response("302 Found", headers + [("Location",
> "XXX"),]) else: start_response('404 Not Found', headers) return [""] if __name__
> == "__main__": server = pywsgi.WSGIServer(('', 8888), application=application,
> backlog=1024, log=None) server.serve_forever() |
>
> I'm planning on upgrading the machine today with newer versions of gevent, uwsgi
> and python, but in case that fails, i'd love to find some pointers on why my app
> is failing or how to debug it. I've also experimented with no as-limit, bigger
> and smaller as-limit, bigger and smaller backlog and bigger and smaller number
> of processes. Is there a way i could convince uwsgi not to drop the request or
> nginx to reload it in the mean time? Thankx.

which os is this?

-- 
Riccardo Magliocchetti
@rmistaken

http://menodizero.it

**Comment by thestick613** [comment]
I have increased max-requests up to 100.000 and have decreased it to 100 - no change. The workers  do
n't restart with signal 6 but with

    ...The work of process 11107 is done. Seeya!
    worker 1 killed successfully (pid: 11107)
    Respawned uWSGI worker 1 (new pid: 11108)

Almost all of the referenced errors of "Fatal Python error: Inconsistent interned string state." are older than 2008-2009, which looks very bad to me. They usually mean some C code went bad. This may or may not mean something to me, as i'm using PySmaz, PyNaCl and redis, which all have C code for perfomance.

I'm using debian 8 on the production machine.

I have also setup an additional machine running Ubuntu 14.04.3 LTS, Python 2.7.6, uwsgi 2.0.11.2, with latest packages for PySmaz, PyNaCl and redis and i have mirrored traffic using gor from the real environment to the staging one. I had the same errors :(

As a last resort, i disabled `--wsgi-env-behaviour=holy`. I don't remember why i enabled that, but the issue disseapeared on staging so i made the same change to live. It works ok now.

This probably suggests a bug in uwsgi more than in my application, as i also tested my application using nginx and regular, simple proxy_pass and backends, using the same gor tool without any problems.

**Comment by thestick613** [comment]
One more hint is that when it fails, it fails for good, for a few miliseconds. Nothing works in that time, and that is why the errors 
DAMN ! worker 12 (pid: 12642) died, killed by signal 6 :( trying respawn ...
Respawned uWSGI worker 12 (new pid: 12646)

came grouped in the logs. As the apps run in the same folder, maybe there is something in the wsgi environment behaviour code which is messed up.

**Comment by xrmx** [comment]
@thestick613 could it be that one of the libraries or python calls abort()? do you have enough memory?

**Comment by thestick613** [comment]
The app has now been running since 2 days with no problems after removing `--wsgi-env-behaviour=holy`. I *think* i have no memory leaks, because the machine has 32gb ram, `limit-as = 8192` and `max-requests = 8192` and `max-worker-lifetime = 3600`, so it would be hard to see them come. I barely use 10% of RAM anyway right now.

I've manually tested all the classes i use in the application and loaded them with 1.000.000 requests sequentially . At the end, there was no memory leak. I will try to make a reproducible test case later this week, maybe someone else can replicate it.

**Comment by xrmx** [comment]
@thestick613 i'm not worried about memory leaks, i'm worried that if your application doesn't have enough memory to run allocations may fail and call abort(). Anyway if you think is resolve we can close the issue.

**Comment by thestick613** [comment]
I restarted the application with --wsgi-env-behaviour=holy and i got the errors back in less than 15 seconds, without using too much memory. i've also tried increasing as-limit and it behaved in the same way. You can close the ticket, and i will make a new one when i can reproduce it.

**Comment by xrmx** [comment]
Well, just don't use --wsgi-env-behaviour=holy then :)
