### ISSUE TITLE
mod_proxy_uwsgi does not work with HTTP/2

### ISSUE THREAD

**Issue by fladi** [unbit/uwsgi#1113]
The Problem seems to be the the call to [`apr_date_checkmask`](https://github.com/unbit/uwsgi/blob/master/apache2/mod_proxy_uwsgi.c#L329) which expects a HTTP version in the form of `HTTP#.#`. This does not support HTTP/2 status lines in the form of `HTTP/#`. Overall, I think that `apr_date_checkmask` should be replaced by `apr_strmatch`.

I'll make a PR that takes HTTP/2 into account with `apr_date_checkmask` to fix this problem and maybe later come up with a version for `apr_strmatch`.

**Comment by xrmx** [comment]
Patch has been merged, closing.

**Comment by fladi** [comment]
Thanks!
