### ISSUE TITLE
uwsgi 2.0.9 segmentation faults

### ISSUE THREAD

**Issue by wzrd-clss** [unbit/uwsgi#1119]
I get a segmentation fault each time I visit a particular page. The traceback seems to be slightly different each time. what could be causing this issue?

traceback:
https://gist.github.com/wzrd-clss/336e5b5926252e5d7ca6

config:
```config
start on runlevel [2345]
stop on runlevel [!2345]

respawn
exec /usr/local/bin/uwsgi --thunder-lock --enable-threads --threads 2 --processes 4 --stats 127.0.0.1:9192 --stats /tmp/prodstatsock --die-on-term --reload-mercy 8 --limit-as 512 --max-requests 2000 --reload-on-as 256 --reload-on-rss 192 --no-orphans --vacuum --memory-report --home /home/wwwdata/web/app --uid wwwdata --master --touch-reload /home/wwwdata/web/mango.git/index --socket /home/wwwdata/web/productionuwsgi.sock --chmod-socket --module wsgi --pythonpath /home/wwwdata/web/ -H /home/wwwdata/web/venv
```

my environment:
django + uwsgi + nginx
python 2.7.6

**Comment by xrmx** [comment]
@wzrd-clss can you trace the crash to a line of your code? Are you using any fancy library? Also please try reproducing with latest stable.

**Comment by wzrd-clss** [comment]
the problem still persists. sorl-thumbnail, django-storages and boto manage all of my images. the problem seems to only occur occasionally on the pages of a particular app when there is an image on the page and when this image is being retrieved from amazon's s3 service.
Ive upgraded sorl-thumbnail from 11.2 to 12.3
Ive also upgraded uwsgi to 2.0.11.2

I have django's loggers set up to email me when an exception occurs but none have been sent to me regarding this issue. is there any way to get more information from uwsgi?

**Comment by unbit** [comment]
@wzrd-clss  remove the address space limit nd retry. It is unlikely you will be able to manipulate mages with virtual memory limited

**Comment by wzrd-clss** [comment]
@unbit that fixed the issue. thanks
