### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by lystor** [unbit/uwsgi#1124]
Hi
PHP 7 has been released.
uwsgi php plugin doesn't build with PHP 7.
Please add PHP 7 support to uwsgi.
Thank you

P.S. One of the uwsgi php 7 plugin implementations:
https://github.com/mow/uwsgi-php7

**Comment by rfnx** [comment]
Is there any news on this ? Php 7 is so good I really want to use it with uWSGI :)

**Comment by unbit** [comment]
Hi, the next stable release is postponed to december 30th just to include php7 support :)

**Comment by rfnx** [comment]
Thanks !! :)

**Comment by unbit** [comment]
php7 support has been merged in both master and stable branches

**Comment by rfnx** [comment]
Thanks again for your amazing work :+1: ! :)

**Comment by nri-pl** [comment]
Hi, what I'm doing wrong?

**Comment by xrmx** [comment]
@nri-pi please don't hijack issues! Yours looks like https://github.com/unbit/uwsgi/issues/654

**Comment by xrmx** [comment]
Closing as php7 plugin has been available since a few.
