### ISSUE TITLE
Ending slash for static pages which are directories

### ISSUE THREAD

**Issue by 153957** [unbit/uwsgi#1133]
We have a uWSGI server serving a Django site and some static pages.
For one of the static directories it is important that the URL ends in a slash to make the relative links in the HTML/CSS work properly.
So this link works fine: http://data.hisparc.nl/media/jsparc/
But this link does not: http://data.hisparc.nl/media/jsparc

This is the static part of the uWSGI config:
```
static-map = /media/jsparc=/srv/publicdb/jsparc
static-index = index.html
```

How do we force the `/` on the end of the URL?
Either redirect it automatically to the `/` version, or return a 404 if it is missing.

**Comment by xrmx** [comment]
github issues are not a support forum, please move the discussion to the mailing list or to the irc channel. Thanks. 
ps. i don't think relative urls are a good idea

**Comment by 153957** [comment]
Very well, if it turns out this is not possible with uWSGI I will file a new feature request.

P.S. Relative urls are a good idea for this specific project.
