### ISSUE TITLE
System processes not equals number of workers

### ISSUE THREAD

**Issue by morsik** [unbit/uwsgi#1144]
Simple situation:
```ini
processes = 8
cheaper = 2
cheaper-idle = 600
```

After doing more requests so 3rd worker appeared, I still saw statistics/metrics about 3rd worker which looks correct (`cheaper-idle` is set to 10 minutes), but `htop` showed only 2 rack processes.

Is this bug, or my misunderstanting of how uWSGI works?

**Comment by xrmx** [comment]
If you are unsure please don't open an issue here, github is for reporting issues not for support, use mailing list or irc for that. Said that, what do you find strange? metrics are reset at restart so if worker 3 did some work i can't see why it should not be accounted.

**Comment by morsik** [comment]
Issue is:
There are 2 system processes, but 3 active workers (as uWSGI stats and `cheaper-idle` config says).
