### ISSUE TITLE
Reloading vassal does not recreate unix socket

### ISSUE THREAD

**Issue by morsik** [unbit/uwsgi#1145]
Consider emperor:
```ini
[uwsgi]
emperor = /etc/uwsgi.d
```
and put there any application:
```ini
[uwsgi]
socket = /tmp/some.socket
; rest doesn't matter
```

Creating vassal, creates socket — OK
Removing vassal, deletes socket — OK
But reloading vassal (`touch /etc/uwsgi.d/vassal.ini`) not recreates socket, nor changes chown (after changing/adding `chown-socket`). Socket is not recreated when I manually removed socket file and reloaded vassal.

**Comment by unbit** [comment]
hi, this is the expected (and common in unix world) behaviour as during reload the process could not have the privileges to re-create the socket.
