### ISSUE TITLE
Apps and mount using so files

### ISSUE THREAD

**Issue by druppy** [unbit/uwsgi#1147]
First sorry for all the noise, but I really like to make good use of uwsgi.

I have been looking at apps and mount, and it seems after some initial problems that I can now do both, but not combined.

But I am not sure if I quite understand the foundations here, and I can't find any good documentation on the subject, either. I like to use mount and app in order to push more flexibility into the uwsgi config, a philosophy I really like in uwsgi.

I have a plugin where I like to make some apps (named request entry points as I understand it), and I like the mount option in the config to route requests to these apps related to the mount point.

So I thought ... if I register 2 apps in my plugin named "app_a" and "app_b", i would like these to be bound to two different mount points, like this : 

mount= /a=app_a 
mount= /b=app_b

I my plugin the "mount_app" callback will be called with these mount arguments, but I have no idea as to how to relate these to the apps I have registered.

Can anyone provide some basic info on the ideas as to how this should work, or maybe point to some documentation. 

Kind regards 

/BL

**Comment by xrmx** [comment]
Please move this discussion to the mailing list, using github issues is not the right medium for this. Thanks!

**Comment by druppy** [comment]
Sorry, will do ...

**Comment by unbit** [comment]
@druppy yep move it to the mailing-list so other people can help. This part is a bit a complex to manage here :)
