### ISSUE TITLE
can't compile php plugin on centos 7

### ISSUE THREAD

**Issue by luk911** [unbit/uwsgi#1177]
➜  uwsgi git:(master) python uwsgiconfig.py --plugin plugins/php
using profile: buildconf/default.ini
detected include path: ['/usr/include', '/usr/local/include']
*** uWSGI building and linking plugin plugins/php ***
[gcc -pthread] ./php_plugin.so
/usr/bin/ld: cannot find -ledit
/usr/bin/ld: cannot find -lncurses
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lxml2
collect2: error: code 1
*** unable to build php plugin ***

**Comment by xrmx** [comment]
It looks like you are missing libraries that that are needed to link the plugin, installed them and it should be fine. Please don't use github for support issues, file an issue here only if it's a bug in uwsgi.

**Comment by luk911** [comment]
Ok, for to do it

cd /tmp
git clone https://github.com/unbit/uwsgi/

yum -y install libuuid-devel libcap-devel \
openssl-devel glibc-static libstdc++-static \
libxml2-devel ncurses-devel libedit-devel
python uwsgiconfig.py --plugin /uwsgi/plugins/php
mkdir /usr/lib64/uwsgi/
mv php_plugin.so /usr/lib64/uwsgi/
rm -Rf /uwsgi

yum -y erase libuuid-devel libcap-devel \
openssl-devel glibc-static libstdc++-static \
libxml2-devel ncurses-devel libedit-devel
