### ISSUE TITLE
100% CPU load on 120 concurrence with php plugin

### ISSUE THREAD

**Issue by luk911** [unbit/uwsgi#1178]
my setup:
////////////////////////////////////////////////////////////////
i7-6700 CPU @ 3.40GHz (Cores 8)
   Memory:  64157 MB

Centos 7

*** Starting uWSGI 2.0.12 (64bit)  ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-4)
os: Linux-3.10.0-327.4.4.el7.x86_64

########## php plugin for uwsgi  ########
cd /tmp
git clone https://github.com/unbit/uwsgi/

yum -y install libuuid-devel libcap-devel \
openssl-devel glibc-static libstdc++-static \
libxml2-devel ncurses-devel libedit-devel

python uwsgiconfig.py --plugin /uwsgi/plugins/php

mkdir /usr/lib64/uwsgi/
mv  /uwsgi/php_plugin.so /usr/lib64/uwsgi/
rm -Rf /uwsgi

yum -y erase libuuid-devel libcap-devel \
openssl-devel glibc-static libstdc++-static \
libxml2-devel ncurses-devel libedit-devel
###########################################

php -v

PHP 5.6.17 (cli) 
Zend Engine v2.6.0
    with Zend OPcache v7.0.6-dev

[uwsgi]
pidfile = /var/run/uwsgi/uwsgi.pid
autoload = true
master = true
no-orphans = true
log-date = true
emperor = /etc/uwsgi.d

Vassal

[uwsgi]
socket = /var/run/uwsgi/test.sock
pidfile = /var/run/uwsgi/test.pid
daemonize = /var/log/uwsgi/test.log
master = true

close-on-exec = 1
harakiri = 600
#harakiri-verbose = true 
#max-requests = 128
max-requests = 100000
processes = 16
cheaper = 8
async = 200
ugreen = true
chown-socket = nginx:nginx
chmod-socket = 660
uid = nginx
gid = nginx
vacuum = true
chmod = 666
log-5xx = 1
buffer-size = 32768
post-buffering = 8192
disable-logging = true
optimize = 2

plugins = php
php-sapi-name = apache
early-php-sapi-name = apache
early-php = true

////////////////////////////////////////////////////////////////

siege -c 120 -r 1000 -b http://test.com/

Transactions:		        9036 hits
Availability:		      100.00 %
Elapsed time:		       22.82 secs
Data transferred:	       96.50 MB
Response time:		        0.30 secs
Transaction rate:	      395.97 trans/sec
Throughput:		        4.23 MB/sec
Concurrency:		      118.96
Successful transactions:        9036
Failed transactions:	           0
Longest transaction:	        0.38
Shortest transaction:	        0.12

And all 8 CPU 100% load

same configuration with php-fpm - only 50-60% CPU

**Comment by xrmx** [comment]
So what? is it serving the same number of requests? It is taking the same time? CPU usage without context is pointless. And again fine tuning your machine is not a thing to discuss in github. Please use the mailing list for this kind of discussion. This is the second issue you are opening for no good reason in a short amount time, please stop.

**Comment by luk911** [comment]
CPU load on 100% from start

**Comment by Darvame** [comment]
100% while standing by?
