### ISSUE TITLE
Newly installed uwsgi is not an executable in virtualenv

### ISSUE THREAD

**Issue by ar-qun** [unbit/uwsgi#1179]
```
-rw-r--r-- 1 ar-qun ar-qun    2087 Feb  6 20:45 activate
-rw-r--r-- 1 ar-qun ar-qun    1029 Feb  6 20:45 activate.csh
-rw-r--r-- 1 ar-qun ar-qun    2227 Feb  6 20:45 activate.fish
-rw-r--r-- 1 ar-qun ar-qun    1137 Feb  6 20:45 activate_this.py
-rwxr-xr-x 1 ar-qun ar-qun     257 Feb  6 20:45 easy_install
-rwxr-xr-x 1 ar-qun ar-qun     257 Feb  6 20:45 easy_install-3.5
-rwxr-xr-x 1 ar-qun ar-qun     229 Feb  6 20:45 pip
-rwxr-xr-x 1 ar-qun ar-qun     229 Feb  6 20:45 pip3
-rwxr-xr-x 1 ar-qun ar-qun     229 Feb  6 20:45 pip3.5
lrwxrwxrwx 1 ar-qun ar-qun       7 Feb  6 20:45 python -> python3
-rwxr-xr-x 1 ar-qun ar-qun   10376 Feb  6 20:45 python3
lrwxrwxrwx 1 ar-qun ar-qun       7 Feb  6 20:45 python3.5 -> python3
-rwxr-xr-x 1 ar-qun ar-qun    2346 Feb  6 20:45 python-config
-rw-r--r-- 1 ar-qun ar-qun 1263864 Feb  6 20:46 uwsgi
-rwxr-xr-x 1 ar-qun ar-qun     236 Feb  6 20:45 wheel
```
It is easy to solve of course, but I have decided to report it any way. Verified it in ubuntu and archlinux.

**Comment by xrmx** [comment]
It works fine for me on debian and pip 1.5.6
```
-rwxr-xr-x 1 rm rm 1265920 Feb  7 14:36 uwsgi
```

**Comment by ar-qun** [comment]
In my case it happened to me with pip 8.0.2 and 7.0.0. I am not sure, but I think something related filesystem may be the cause. In all cases I use btrfs, but I have just created a user with home directory on different subvolume and executed it without any problem. It is strange though that error happens in ubuntu too, which is also in a different subvolume.

Probably I lack some knowledge in regards to btrfs or user configuration. Will report later on.

**Comment by xrmx** [comment]
@ar-qun upgrade pip to 8.0.2 and permissions are still fine for me. I'll close this but please reopen if you have any hint that shows it's an issue in our packaging. Thanks!
