### ISSUE TITLE
Alarms & req-log

### ISSUE THREAD

**Issue by erion** [unbit/uwsgi#1183]
Alarms are not firing when try to use it with req-logger.
I made a script to mail me every requisition with status 500. 200 while testing.
When I comment the line defining the req-logger variable, I recive the email with the requisition.

Is that a bug or am I doing something wrong?
(sry if i cant freely open issues but I didnt found a better place)

**Comment by xrmx** [comment]
@erion a better place would be the mailing list or irc :) Without providing uwsgi version, logs and configuration there's not much one can do to help you. Please write to the mailing list with the needed informations.
