### ISSUE TITLE
Build fails on gcc 6

### ISSUE THREAD

**Issue by jhdulaney** [unbit/uwsgi#1186]
GCC 6 has added several new warnings, and as uwsgi build treats warnings as errors, build fails.

For instance:

plugins/corerouter/cr_map.c: In function ‘uwsgi_cr_map_use_static_nodes’:
    plugins/corerouter/cr_map.c:159:6: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
          while (tmp_node != next_node) {
          ^~~~~
    plugins/corerouter/cr_map.c:156:5: note: ...this ‘if’ clause, but it is not
         if (!next_node)
         ^~

**Comment by xrmx** [comment]
This has been already been fixed in git, in both master and uwsgi-2.0 branch. See https://github.com/unbit/uwsgi/issues/1162#issuecomment-181259742

**Comment by jhdulaney** [comment]
ah, thanks.
