### ISSUE TITLE
Cron jobs running in worker processes?

### ISSUE THREAD

**Issue by WST** [unbit/uwsgi#1201]
Hi,

Hope you remember me :) sorry to bother you again.

I’m having an issue with uWSGI 1.9.17.1-debian. I am running a Django webapp under it, and things go well… Until I try to add a heavy cron job. I use a Python decorator “cron” and I call a heavy (taking long time to call) function.

``` Python
@cron(-10, -1, -1, -1, -1)
def job(num):
	call_command('some_long_command')
```

Am I doing something wrong? This seems to get executed in a worker process, and if the thread number is 1, I cannot load the website until the task finishes.

I am expecting it to run in the master process, but it still runs in a worker. I have no idea why, but I beleive, I am doing something in a wrong way. Or maybe misunderstanding things a bit, and the command should run in a worker (that’s what I think now, because the app is loaded into workers). Can you tell me what is right?

**Comment by WST** [comment]
Okay, I succeeded to do it within a mule process by passing `target = 'mule'` and adding a signal-only mule to the vassal’s configuration file. My sincere apologies for being in rush and disturbing you :blush: :heart:

**Comment by xrmx** [comment]
@WST github is not for support request, please use the irc channel or the mailing list for that.
