### ISSUE TITLE
Add classifiers for supported python versions to setup.py

### ISSUE THREAD

**Issue by jaapz** [unbit/uwsgi#1206]
It would be neat if you'd add classifiers to your setup.py so tools like caniusepython3.com can check if uwsgi is actually supported for python3.

**Comment by xrmx** [comment]
Thanks, feel free to open a pull request to update setup.py.

**Comment by xrmx** [comment]
caniusepython3.com and http://py3readiness.org/ already sets uwsgi as supported though.

**Comment by jaapz** [comment]
Weird, for me caniusepython3.com does not
