### ISSUE TITLE
uwsgi broken pipe when running it as systemd service

### ISSUE THREAD

**Issue by tamjd1** [unbit/uwsgi#1208]
I am running a python flask app under uwsgi v. 2.0.8 in a conda virtual environment using python v. 2.7.11 on CentOS 7

Everything (config and code) works fine if I manually call the start script for my app (`sh start-foo.sh`) but when I try to start it as a systemd service (`sudo systemctl foo start`) it starts the app but then uwsgi fails right away with the following error:

```
WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x14c38d0 pid: 3504 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3504)
emperor_notify_ready()/write(): Broken pipe [core/emperor.c line 2463]
VACUUM: pidfile removed.
```

Here is my systemd Unit file:

```
[Unit]
Description=foo

[Service]
ExecStart=/bin/bash /app/foo/bin/start-foo.sh
ExecStop=/bin/bash /app/foo/bin/stop-foo.sh

[Install]
WantedBy=multi-user.target
```
Here are my uwsgi emperor and vassal configs:

Emperor

```
[uwsgi]
emperor = /app/foo/conf/vassals/
daemonize = /var/log/foo/emperor.log
```

Vassal

```
[uwsgi]
http-timeout = 500
chdir = /app/foo/scripts
pidfile = /app/foo/scripts/foo.pid
#socket = /app/foo/scripts/foo.soc
http = :8888
wsgi-file = /app/foo/scripts/foo.py
master = 1
processes = %(%k * 2)
threads = 1
module = foo
callable = app
vacuum = True
daemonize = /var/log/foo/uwsgi.log
```

This is not a blocker because I can still start/stop my app by executing the scripts manually, but I would like to be able to run it as a service and automatically launch it on startup using systemd.

**Comment by xrmx** [comment]
Sorry but this kind of issue should be discussed on mailing list or irc. Please don't use github issues for support. I'm pretty we have documentation on using uwsgi with systemd so start reading it. I hope it doesn't involve calling bash for loading a shell script.
