### ISSUE TITLE
mod_proxy_uwsgi doesn't parse HTTP/2 status correctly

### ISSUE THREAD

**Issue by OGAWAHirofumi** [unbit/uwsgi#1213]
Hi,

mod_proxy_uwsgi allows HTTP/2 status line though, current code doesn't parse it correctly.
The cause of it is difference of length between HTTP/2 and HTTP/1.x

Now, using fixed 12 length, but it should be 10 for HTTP/2.

I tested following patch, and for now, it is working without any problem with HTTP/2.

<pre>
diff -puN apache2/mod_proxy_uwsgi.c~http2-status-fix apache2/mod_proxy_uwsgi.c
--- uwsgi-2.0.12/apache2/mod_proxy_uwsgi.c~http2-status-fix	2016-03-21 15:32:20.689744270 +0900
+++ uwsgi-2.0.12-hirofumi/apache2/mod_proxy_uwsgi.c	2016-03-21 15:40:02.585952424 +0900
@@ -326,27 +326,36 @@ static int uwsgi_response(request_rec *r
 
 	backend->worker->s->read += len;
 
-	if (!(apr_date_checkmask(buffer, "HTTP/#.# ###*") ||
-	    apr_date_checkmask(buffer, "HTTP/# ###*")) ||
-	    len >= sizeof(buffer)-1) {
+	if (len >= sizeof(buffer)-1) {
 		// oops
 		return HTTP_INTERNAL_SERVER_ERROR;
 	}
+	/* Position of http status code */
+	int status_start;
+	if (apr_date_checkmask(buffer, "HTTP/#.# ###*"))
+		status_start = 9;
+	else if (apr_date_checkmask(buffer, "HTTP/# ###*"))
+		status_start = 7;
+	else {
+		// oops
+		return HTTP_INTERNAL_SERVER_ERROR;
+	}
+	int status_end = status_start + 3;
 
-	char keepchar = buffer[12];
-	buffer[12] = '\0';
-	r->status = atoi(&buffer[9]);
+	char keepchar = buffer[status_end];
+	buffer[status_end] = '\0';
+	r->status = atoi(&buffer[status_start]);
 
 	if (keepchar != '\0') {
-		buffer[12] = keepchar;
+		buffer[status_end] = keepchar;
 	} else {
 		/* 2616 requires the space in Status-Line; the origin
 		* server may have sent one but ap_rgetline_core will
 		* have stripped it. */
-		buffer[12] = ' ';
-		buffer[13] = '\0';
+		buffer[status_end] = ' ';
+		buffer[status_end + 1] = '\0';
 	}
-	r->status_line = apr_pstrdup(r->pool, &buffer[9]);
+	r->status_line = apr_pstrdup(r->pool, &buffer[status_start]);
 
 	// start parsing headers;
 	while ((len = ap_getline(buffer, sizeof(buffer), rp, 1)) > 0) {
_
</pre>

**Comment by xrmx** [comment]
Thanks for reporting.

**Comment by xrmx** [comment]
Merged, thanks.

**Comment by unbit** [comment]
@xrmx i think this is good too for 2.0

**Comment by xrmx** [comment]
@unbit yeah, need to backport the patch it fixes and my cleanup on top of it before :)
