### ISSUE TITLE
uwsgi max-worker-lifetime kills worker but doesnt seem to restarted it

### ISSUE THREAD

**Issue by bqumsiyeh** [unbit/uwsgi#1221]
Hello.

I'm on uWSGI version 1.9.21.

Over the last week, I have been seeing very random occurrences of a worker passing its allowed lifetime limit and then getting killed but not restarted.  Just started happening out of nowhere

I have two total workers on my setup, and I see this in the logs:
```
worker 1 lifetime reached, it was running for 86401 second(s)
worker 2 lifetime reached, it was running for 86401 second(s)
```
My  `max-worker-lifetime` var is set to 86400.  After both workers are killed, nothing seems to happen.  My Django site becomes unreachable and nginx eventually returns a 504 timeout.  I have to manually reload uwsgi in order to fix the issue and start the workers up again

Any ideas on why this would happen? 

Thanks in advance

**Comment by xrmx** [comment]
Please update to latest stable: 1.9.21 is more than two years old. If it's still an issue reopen and post your full configuration.
