### ISSUE TITLE
uWSGI workers hang when serving a Django app

### ISSUE THREAD

**Issue by WST** [unbit/uwsgi#1225]
I’m running a Django 1.9.4 website on uWSGI 1.9.17.1-debian and for some reason the workers hang after serving `max_requests` requests. This is what I see in the log:

...The work of process 7535 is done. Seeya!
```
Mon Apr  4 14:43:18 2016 - worker 2 (pid: 7536) is taking too much time to die...NO MERCY !!!
Mon Apr  4 14:43:19 2016 - worker 1 (pid: 7535) is taking too much time to die...NO MERCY !!!
```

Is it a bug of the mentioned uWSGI version?

This is my test ini file (the issue happens in production as well):

```ini
[uwsgi]
http-socket = 127.0.0.1:8080
master = 1
threads = 2
processes = 2
env = DJANGO_SETTINGS_MODULE=appname.settings
virtualenv = /home/ilya/venvs/appname
module = appname.wsgi:application
plugins = python3
static-map = /static=/home/ilya/projects/appname/portal/static
mule = 1
auto-procname = true
procname-prefix-spaced = [appname]
max-requests = 10
```

**Comment by xrmx** [comment]
Il 04/04/2016 13:46, Ilya I. Averkov ha scritto:
> I’m running a Django 1.9.4 website on uWSGI 1.9.17.1-debian and for some reason
> the workers hang after serving |max_requests| requests. This is what I see in
> the log:
>
> ...The work of process 7535 is done. Seeya!
>
> |Mon Apr 4 14:43:18 2016 - worker 2 (pid: 7536) is taking too much time to
> die...NO MERCY !!! Mon Apr 4 14:43:19 2016 - worker 1 (pid: 7535) is taking too
> much time to die...NO MERCY !!! |
>
> Is it a bug of the mentioned uWSGI version?

You tell us :) Please test with latest stable release. Reporting bugs against 
unmaintaned old version is kinda pointless since nobody will fix it.


-- 
Riccardo Magliocchetti
@rmistaken

http://menodizero.it

**Comment by WST** [comment]
Well, I can test it with the latest version from git on my local machine, but in production it’s kind of a requirement to use that version. In other words, I may not have a “right” to use a newer version. Thank you anyway — at least your reply confirms my idea that the issue could be caused by using an outdated version, I’ll see what I can do…
