### ISSUE TITLE
Version number in C compiler string causing error

### ISSUE THREAD

**Issue by justsostephen** [unbit/uwsgi#1235]
On line 33 of `uwsgiconfig.py`, `os.environ.get('CC', sysconfig.get_config_var('CC'))` is used to detect the installed C compiler. On OS X 10.11.3 with Xcode 7.2.1 the `CC` environment variable isn't set by default, so `sysconfig.get_config_var('CC')` is used. On my system, this returns `gcc-4.2`, which is stored as the constant `GCC`.

Consequently, when `gcc_version = spcall("%s -dumpversion" % GCC)` runs on line 682, Bash reports that the command `gcc-4.2` cannot be found. Seemingly taking this into account, `llvm-` is prepended onto the `GCC` constant, resulting in the string `llvm-gcc-4.2`. On line 688, `gcc_version = spcall("%s -dumpversion" % GCC)` runs again using the modified value, however Bash once again reports that the command cannot be found.

Neither `gcc-4.2` or `llvm-gcc-4.2` are valid commands. Removing `-4.2` makes them both valid. Unless I'm missing something (and that could well be the case!), revising `uwsgiconfig.py` to remove the version number from the string returned by `sysconfig.get_config_var('CC')` would fix this issue.

**Comment by xrmx** [comment]
thanks for the reports, i think the less painful way to handle this would be to special case os x and use clang as default compiler. All supported mac os x versions have clang as default compiler and gcc is just a symlink.

**Comment by xrmx** [comment]
Does this work for you?
```
diff --git a/uwsgiconfig.py b/uwsgiconfig.py
index 617d6b3..d64a775 100644
--- a/uwsgiconfig.py
+++ b/uwsgiconfig.py
@@ -30,9 +30,12 @@ except ImportError:
 
 PY3 = sys.version_info[0] == 3
 
-GCC = os.environ.get('CC', sysconfig.get_config_var('CC'))
-if not GCC:
-    GCC = 'gcc'
+if uwsgi_os == 'Darwin':
+    GCC = os.environ.get('CC', 'clang')
+else:
+    GCC = os.environ.get('CC', sysconfig.get_config_var('CC'))
+    if not GCC:
+        GCC = 'gcc'
 
 def get_preprocessor():
     if 'clang' in GCC:
```

**Comment by justsostephen** [comment]
Yes, that works! Does `sysconfig.get_config_var('CC')` return a string that doesn't contain a version number on other operating systems?

**Comment by xrmx** [comment]
It doesn't matter on other operating systems, they don't play games making a compiler chain look like another one.

**Comment by justsostephen** [comment]
Noted!

**Comment by justsostephen** [comment]
@xrmx, should I submit another PR containing your patch?

**Comment by xrmx** [comment]
@justsostephen, no thanks, i can push my own patches by myself :)

**Comment by justsostephen** [comment]
@xrmx, forgive my enthusiasm! :-)
