### ISSUE TITLE
Please add documentation how to run python apps with pyenv

### ISSUE THREAD

**Issue by COLABORATI** [unbit/uwsgi#1251]
Unfortunately there is no documentation about how to use uwsgi with [pyenv](https://github.com/yyuu/pyenv) - it would be great if you could some info about how to integrate uwsgi with pyenv. It looks like this might be possible with the virtualenv option, but I am not sure how that will use the local pyenv setting - any official docs about this would be great to have, thanks!

**Comment by xrmx** [comment]
Documentation is tracked on the https://github.com/unbit/uwsgi-docs repository. Said that instead of opening feature requests it would be really nice from you to try installing uwsgi in pyenv, discuss eventual issues on irc / mailing list and then provide the documentation for others.

**Comment by COLABORATI** [comment]
Ah, ok, I will ask on the mailing list.

**Comment by TomGoBravo** [comment]
I struggled with this too. http://lists.unbit.it/pipermail/uwsgi/2017-December/008806.html on the mailing list didn't look good but I'm pretty happy with what I described at https://github.com/pyenv/pyenv/issues/598#issuecomment-468173396 so far.

**Comment by xrmx** [comment]
@TomGoBravo please open a PR on uwsgi-docs!
