### ISSUE TITLE
2.0.13 breaks python2.6 support.

### ISSUE THREAD

**Issue by PriceChild** [unbit/uwsgi#1253]
I'm afraid I'm still on Centos 6... I can't find any details in this repository or on https://uwsgi-docs.readthedocs.io about minimum required python versions so I'm hoping this is an oversight? Or is python2.6 support being intentionally dropped?

> [vagrant@www1 ~]$ sudo pip install uwsgi
> DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
> Collecting uwsgi
> /usr/lib/python2.6/site-packages/pip-8.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /usr/lib/python2.6/site-packages/pip-8.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Downloading uwsgi-2.0.13.tar.gz (784kB)
>     100% |████████████████████████████████| 788kB 1.3MB/s 
> Installing collected packages: uwsgi
>   Running setup.py install for uwsgi ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3Lhlfy/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rVPB52-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     using profile: buildconf/default.ini
>     detected include path: ['/usr/local/include', '/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include', '/usr/include']
>     Patching "bin_name" to properly install_scripts dir
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-3Lhlfy/uwsgi/setup.py", line 124, in <module>
>         distclass=uWSGIDistribution,
>       File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
>         dist.run_commands()
>       File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
>         cmd_obj.run()
>       File "/tmp/pip-build-3Lhlfy/uwsgi/setup.py", line 79, in run
>         uc.build_uwsgi(conf)
>       File "uwsgiconfig.py", line 277, in build_uwsgi
>         gcc_list, cflags, ldflags, libs = uc.get_gcll()
>       File "uwsgiconfig.py", line 894, in get_gcll
>         report['ucontext'] = has_usable_ucontext()
>       File "uwsgiconfig.py", line 198, in has_usable_ucontext
>         }""")
>       File "uwsgiconfig.py", line 176, in test_snippet
>         cmd = "{} -xc - -o /dev/null".format(GCC)
>     ValueError: zero length field name in format
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3Lhlfy/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rVPB52-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3Lhlfy/uwsgi/
> /usr/lib/python2.6/site-packages/pip-8.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning

For now, 2.0.12 works.

> [vagrant@www1 ~]$ sudo pip install uwsgi==2.0.12
> DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
> Collecting uwsgi==2.0.12
> /usr/lib/python2.6/site-packages/pip-8.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /usr/lib/python2.6/site-packages/pip-8.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Downloading uwsgi-2.0.12.tar.gz (784kB)
>     100% |████████████████████████████████| 788kB 1.4MB/s 
> Installing collected packages: uwsgi
>   Running setup.py install for uwsgi ... done
> Successfully installed uwsgi-2.0.12

**Comment by unbit** [comment]
This is a regression in 2.0.13. We have already addressed it. 2.0.13.1 should be out soon

**Comment by PriceChild** [comment]
Awesome, thanks @unbit & apologies if I've missed an existing ticket.
