### ISSUE TITLE
uwsgi with not setting enable-thread, but thread really run

### ISSUE THREAD

**Issue by andyxning** [unbit/uwsgi#1256]
I have develop an Flask wsgi app. In this app i have a cron task runed by `threading.task`, in my configuration i have no configuration about `enable-thread`, however under the log i can really find the evidence that a thread is really running. 

Here is the XML configuration file:

    <uwsgi>
    <http-socket>0.0.0.0:3030</http-socket>
    <socket>/tmp/uwsgi_cache.sock</socket>
    <module>bootstrap</module>
    <callable>app</callable>
    <workers>10</workers>
    <listen>2048</listen>
    <socket-timeout>1</socket-timeout>
    <reload-mercy>100</reload-mercy>
    <harakiri>15</harakiri>
    <harakiri-verbose/>
    
    <logto>../../../log/uwsgicache.log</logto>
    <log-maxsize>2147483647</log-maxsize>
    <log-slow>500</log-slow>
    
    <master/>
    <lazy/>
    <py-tracebacker>/tmp/uwsgi_traceback_cache</py-tracebacker>
    <buffer-size>65536</buffer-size>
    <post-buffering>65536</post-buffering>
    </uwsgi>

The log info:

    INFO 2016-05-18 17:00:11 ./cron/conf.py:198 10.6.131.78 process=106901 thread=139854427588352 data=conf reloaded at 2016-05-18T17:00:11.347496
    INFO 2016-05-18 17:00:11 ./cron/conf.py:198 10.6.131.78 process=106906 thread=139854427588352 data=cache reloaded at 2016-05-18T17:00:11.349265

**Comment by methane** [comment]
See #1141

**Comment by andyxning** [comment]
Still can not get it. Can you give me a detailed explanation. :)

**Comment by xrmx** [comment]
@andyxning github issues are not for user support, please use the mailing list. Closing as dup of #1141
