### ISSUE TITLE
pip failed to install uWSGI package

### ISSUE THREAD

**Issue by markshao** [unbit/uwsgi#1258]
OSX Version: 10.11.4
Python version: Python 2.7.10

`Building wheels for collected packages: uWSGI
  Running setup.py bdist_wheel for uWSGI
  Complete output from command /Users/shaoyuliang/xiaohongshu/gitlab/.virtualenvs/fulishe/bin/python -c "import setuptools;__file__='/private/var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-build-mqcl87/uWSGI/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/tmpsPWlY9pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying uwsgidecorators.py -> build/lib
  installing to build/bdist.macosx-10.11-intel/wheel
  running install
  core/socket.c:708:28: error: use of undeclared identifier 'SOL_TCP'
                  if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                                           ^
  1 error generated.

  ----------------------------------------
  Failed building wheel for uWSGI
Failed to build uWSGI
Installing collected packages: uWSGI, uwsgitop, virtualenv, xlrd, XlsxWriter, immortal, redalarm
  Running setup.py install for uWSGI
    Complete output from command /Users/shaoyuliang/xiaohongshu/gitlab/.virtualenvs/fulishe/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-build-mqcl87/uWSGI/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-mgEkBs-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shaoyuliang/xiaohongshu/gitlab/.virtualenvs/fulishe/include/site/python2.7/uWSGI:
    running install
    core/socket.c:708:28: error: use of undeclared identifier 'SOL_TCP'
                    if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                                             ^
    1 error generated.

    ----------------------------------------
Command "/Users/shaoyuliang/xiaohongshu/gitlab/.virtualenvs/fulishe/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-build-mqcl87/uWSGI/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-mgEkBs-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shaoyuliang/xiaohongshu/gitlab/.virtualenvs/fulishe/include/site/python2.7/uWSGI" failed with error code 1 in /private/var/folders/pk/qsqn5vts05l94tyhthvn7qrw0000gn/T/pip-build-mqcl87/uWSGI
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by xrmx** [comment]
It looks to me you are not installing latest stable release but 2.0.11.1 or so.

**Comment by xrmx** [comment]
@markshao ping
