### ISSUE TITLE
Configuration over etcd/console/.. similar to LDAP

### ISSUE THREAD

**Issue by cw-aleks** [unbit/uwsgi#1274]
are there any plans to have the option to configure uwsgi with some of the key/value server out there?

Something similar like ldap.

http://uwsgi-docs.readthedocs.io/en/latest/LDAP.html

I have seen this for example in traefik
https://github.com/containous/traefik

**Comment by xrmx** [comment]
Please use the mailing list to ask questions, not the bug tracker. Thanks.
