### ISSUE TITLE
uWSGI does not deserve to be on the Python 3 Wall of Shame!!

### ISSUE THREAD

**Issue by cclauss** [unbit/uwsgi#1275]
http://python3wos.appspot.com

https://github.com/unbit/uwsgi/blob/master/setup.py#L127 shows that uWSGI supports Python 3 but [it's PyPI record](https://pypi.python.org/pypi/uWSGI) does not yet contain the same appropriate trove classifier `Programming Language :: Python :: 3`.

**Comment by xrmx** [comment]
@unbit care to update? I don't have pypi rights :)

**Comment by unbit** [comment]
done
