### ISSUE TITLE
pip install uwsgi fails with "undefined reference to `clock_settime'" error

### ISSUE THREAD

**Issue by kuzmak** [unbit/uwsgi#1279]
This issue occurs on Ubuntu 12.04.05 LTS x64 with GCC 4.6.3, Python 3.5.1 and uwsgi 2.0.13.1.

**$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

**$ uname -a**
Linux myhostname 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**$ gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

**Python 3.5.1 install**
wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
tar xzf Python-3.5.1.tgz
cd Python-3.5.1
sudo ./configure
sudo make altinstall

**$ pip install uwsgi**
Collecting uwsgi
  Using cached uwsgi-2.0.13.1.tar.gz
Installing collected packages: uwsgi
  Running setup.py install for uwsgi ... error
    Complete output from command /opt/envs/denali-production/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-komougyi/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cb4xphrs-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/envs/denali-production/include/site/python3.5/uwsgi:
    running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/4.6/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
    Patching "bin_name" to properly install_scripts dir
    detected CPU cores: 24
    configured CFLAGS: -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format -Wno-format-security -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_VERSION="\"2.0.13.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="13" -DUWSGI_VERSION_REVISION="1" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -I/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(ugreen);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(ugreen);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
    *** uWSGI compiling server core ***
    [thread 3][gcc -pthread] core/utils.o
    [thread 2][gcc -pthread] core/protocol.o
    [thread 5][gcc -pthread] core/socket.o
    [thread 7][gcc -pthread] core/logging.o
    [thread 6][gcc -pthread] core/master.o
    [thread 0][gcc -pthread] core/master_utils.o
    [thread 9][gcc -pthread] core/emperor.o
    [thread 11][gcc -pthread] core/notify.o
    [thread 4][gcc -pthread] core/mule.o
    [thread 12][gcc -pthread] core/subscription.o
    [thread 1][gcc -pthread] core/stats.o
    [thread 10][gcc -pthread] core/sendfile.o
    [thread 13][gcc -pthread] core/async.o
    [thread 14][gcc -pthread] core/master_checks.o
    [thread 15][gcc -pthread] core/fifo.o
    [thread 17][gcc -pthread] core/offload.o
    [thread 16][gcc -pthread] core/io.o
    [thread 18][gcc -pthread] core/static.o
    [thread 19][gcc -pthread] core/websockets.o
    [thread 20][gcc -pthread] core/spooler.o
    [thread 21][gcc -pthread] core/snmp.o
    [thread 23][gcc -pthread] core/exceptions.o
    [thread 8][gcc -pthread] core/config.o
    [thread 22][gcc -pthread] core/setup_utils.o
    [thread 10][gcc -pthread] core/clock.o
    [thread 11][gcc -pthread] core/init.o
    [thread 22][gcc -pthread] core/buffer.o
    [thread 15][gcc -pthread] core/reader.o
    [thread 21][gcc -pthread] core/writer.o
    [thread 23][gcc -pthread] core/alarm.o
    [thread 19][gcc -pthread] core/cron.o
    [thread 13][gcc -pthread] core/hooks.o
    [thread 14][gcc -pthread] core/plugins.o
    [thread 20][gcc -pthread] core/lock.o
    [thread 18][gcc -pthread] core/cache.o
    [thread 1][gcc -pthread] core/daemons.o
    [thread 17][gcc -pthread] core/errors.o
    [thread 4][gcc -pthread] core/hash.o
    [thread 10][gcc -pthread] core/master_events.o
    [thread 2][gcc -pthread] core/chunked.o
    [thread 8][gcc -pthread] core/queue.o
    [thread 12][gcc -pthread] core/event.o
    [thread 6][gcc -pthread] core/signal.o
    [thread 11][gcc -pthread] core/strings.o
    [thread 19][gcc -pthread] core/progress.o
    [thread 22][gcc -pthread] core/timebomb.o
    [thread 16][gcc -pthread] core/ini.o
    [thread 17][gcc -pthread] core/fsmon.o
    [thread 4][gcc -pthread] core/mount.o
    [thread 14][gcc -pthread] core/metrics.o
    [thread 10][gcc -pthread] core/plugins_builder.o
    [thread 23][gcc -pthread] core/sharedarea.o
    [thread 15][gcc -pthread] core/rpc.o
    [thread 20][gcc -pthread] core/gateway.o
    [thread 2][gcc -pthread] core/loop.o
    [thread 21][gcc -pthread] core/cookie.o
    [thread 0][gcc -pthread] core/querystring.o
    [thread 13][gcc -pthread] core/rb_timers.o
    [thread 1][gcc -pthread] core/transformations.o
    [thread 8][gcc -pthread] core/uwsgi.o
    [thread 22][gcc -pthread] proto/base.o
    [thread 7][gcc -pthread] proto/uwsgi.o
    [thread 5][gcc -pthread] proto/http.o
    [thread 19][gcc -pthread] proto/fastcgi.o
    [thread 12][gcc -pthread] proto/scgi.o
    [thread 17][gcc -pthread] proto/puwsgi.o
    [thread 16][gcc -pthread] lib/linux_ns.o
    [thread 10][gcc -pthread] core/zlib.o
    [thread 4][gcc -pthread] core/regexp.o
    [thread 0][gcc -pthread] core/routing.o
    [thread 21][gcc -pthread] core/yaml.o
    [thread 15][gcc -pthread] core/ssl.o
    [thread 11][gcc -pthread] core/legion.o
    [thread 2][gcc -pthread] core/xmlconf.o
    [thread 1][gcc -pthread] core/dot_h.o
    [thread 9][gcc -pthread] core/config_py.o
    *** uWSGI compiling embedded plugins ***
    [thread 20][gcc -pthread] plugins/python/python_plugin.o
    [thread 6][gcc -pthread] plugins/python/pyutils.o
    [thread 1][gcc -pthread] plugins/python/pyloader.o
    [thread 9][gcc -pthread] plugins/python/wsgi_handlers.o
    [thread 13][gcc -pthread] plugins/python/wsgi_headers.o
    [thread 7][gcc -pthread] plugins/python/wsgi_subhandler.o
    [thread 12][gcc -pthread] plugins/python/web3_subhandler.o
    [thread 23][gcc -pthread] plugins/python/pump_subhandler.o
    [thread 4][gcc -pthread] plugins/python/gil.o
    [thread 22][gcc -pthread] plugins/python/uwsgi_pymodule.o
    [thread 19][gcc -pthread] plugins/python/profiler.o
    [thread 17][gcc -pthread] plugins/python/symimporter.o
    [thread 10][gcc -pthread] plugins/python/tracebacker.o
    [thread 16][gcc -pthread] plugins/python/raw.o
    [thread 21][gcc -pthread] plugins/gevent/gevent.o
    [thread 2][gcc -pthread] plugins/gevent/hooks.o
    [thread 14][gcc -pthread] plugins/ping/ping_plugin.o
    [thread 18][gcc -pthread] plugins/cache/cache.o
    [thread 5][gcc -pthread] plugins/nagios/nagios.o
    [thread 19][gcc -pthread] plugins/rrdtool/rrdtool.o
    [thread 13][gcc -pthread] plugins/carbon/carbon.o
    [thread 4][gcc -pthread] plugins/rpc/rpc_plugin.o
    [thread 15][gcc -pthread] plugins/corerouter/cr_common.o
    [thread 12][gcc -pthread] plugins/corerouter/cr_map.o
    [thread 16][gcc -pthread] plugins/corerouter/corerouter.o
    [thread 7][gcc -pthread] plugins/fastrouter/fastrouter.o
    [thread 10][gcc -pthread] plugins/http/http.o
    [thread 23][gcc -pthread] plugins/http/keepalive.o
    [thread 14][gcc -pthread] plugins/http/https.o
    [thread 17][gcc -pthread] plugins/http/spdy3.o
    [thread 6][gcc -pthread] plugins/ugreen/ugreen.o
    [thread 9][gcc -pthread] plugins/signal/signal_plugin.o
    [thread 5][gcc -pthread] plugins/syslog/syslog_plugin.o
    [thread 18][gcc -pthread] plugins/rsyslog/rsyslog_plugin.o
    [thread 1][gcc -pthread] plugins/logsocket/logsocket_plugin.o
    [thread 2][gcc -pthread] plugins/router_uwsgi/router_uwsgi.o
    [thread 21][gcc -pthread] plugins/router_redirect/router_redirect.o
    [thread 19][gcc -pthread] plugins/router_basicauth/router_basicauth.o
    [thread 11][gcc -pthread] plugins/zergpool/zergpool.o
    [thread 3][gcc -pthread] plugins/redislog/redislog_plugin.o
    [thread 12][gcc -pthread] plugins/mongodblog/mongodblog_plugin.o
    [thread 9][gcc -pthread] plugins/router_rewrite/router_rewrite.o
    [thread 15][gcc -pthread] plugins/router_http/router_http.o
    [thread 6][gcc -pthread] plugins/logfile/logfile.o
    [thread 13][gcc -pthread] plugins/router_cache/router_cache.o
    [thread 23][gcc -pthread] plugins/rawrouter/rawrouter.o
    [thread 5][gcc -pthread] plugins/router_static/router_static.o
    [thread 1][gcc -pthread] plugins/sslrouter/sslrouter.o
    [thread 2][gcc -pthread] plugins/spooler/spooler_plugin.o
    [thread 18][gcc -pthread] plugins/cheaper_busyness/cheaper_busyness.o
    [thread 21][gcc -pthread] plugins/symcall/symcall_plugin.o
    [thread 14][gcc -pthread] plugins/transformation_tofile/tofile.o
    [thread 19][gcc -pthread] plugins/transformation_gzip/gzip.o
    [thread 11][gcc -pthread] plugins/transformation_chunked/chunked.o
    [thread 4][gcc -pthread] plugins/transformation_offload/offload.o
    [thread 7][gcc -pthread] plugins/router_memcached/router_memcached.o
    [thread 3][gcc -pthread] plugins/router_redis/router_redis.o
    [thread 0][gcc -pthread] plugins/router_hash/router_hash.o
    [thread 9][gcc -pthread] plugins/router_expires/expires.o
    [thread 20][gcc -pthread] plugins/router_metrics/plugin.o
    [thread 12][gcc -pthread] plugins/transformation_template/tt.o
    [thread 6][gcc -pthread] plugins/stats_pusher_socket/plugin.o
    *** uWSGI linking ***
    gcc -pthread -o /opt/envs/denali-production/bin/uwsgi  core/utils.o core/protocol.o core/socket.o core/logging.o core/master.o core/master_utils.o core/emperor.o core/notify.o core/mule.o core/subscription.o core/stats.o core/sendfile.o core/async.o core/master_checks.o core/fifo.o core/offload.o core/io.o core/static.o core/websockets.o core/spooler.o core/snmp.o core/exceptions.o core/config.o core/setup_utils.o core/clock.o core/init.o core/buffer.o core/reader.o core/writer.o core/alarm.o core/cron.o core/hooks.o core/plugins.o core/lock.o core/cache.o core/daemons.o core/errors.o core/hash.o core/master_events.o core/chunked.o core/queue.o core/event.o core/signal.o core/strings.o core/progress.o core/timebomb.o core/ini.o core/fsmon.o core/mount.o core/metrics.o core/plugins_builder.o core/sharedarea.o core/rpc.o core/gateway.o core/loop.o core/cookie.o core/querystring.o core/rb_timers.o core/transformations.o core/uwsgi.o proto/base.o proto/uwsgi.o proto/http.o proto/fastcgi.o proto/scgi.o proto/puwsgi.o lib/linux_ns.o core/zlib.o core/regexp.o core/routing.o core/yaml.o core/ssl.o core/legion.o core/xmlconf.o core/dot_h.o core/config_py.o plugins/python/python_plugin.o plugins/python/pyutils.o plugins/python/pyloader.o plugins/python/wsgi_handlers.o plugins/python/wsgi_headers.o plugins/python/wsgi_subhandler.o plugins/python/web3_subhandler.o plugins/python/pump_subhandler.o plugins/python/gil.o plugins/python/uwsgi_pymodule.o plugins/python/profiler.o plugins/python/symimporter.o plugins/python/tracebacker.o plugins/python/raw.o plugins/gevent/gevent.o plugins/gevent/hooks.o plugins/ping/ping_plugin.o plugins/cache/cache.o plugins/nagios/nagios.o plugins/rrdtool/rrdtool.o plugins/carbon/carbon.o plugins/rpc/rpc_plugin.o plugins/corerouter/cr_common.o plugins/corerouter/cr_map.o plugins/corerouter/corerouter.o plugins/fastrouter/fastrouter.o plugins/http/http.o plugins/http/keepalive.o plugins/http/https.o plugins/http/spdy3.o plugins/ugreen/ugreen.o plugins/signal/signal_plugin.o plugins/syslog/syslog_plugin.o plugins/rsyslog/rsyslog_plugin.o plugins/logsocket/logsocket_plugin.o plugins/router_uwsgi/router_uwsgi.o plugins/router_redirect/router_redirect.o plugins/router_basicauth/router_basicauth.o plugins/zergpool/zergpool.o plugins/redislog/redislog_plugin.o plugins/mongodblog/mongodblog_plugin.o plugins/router_rewrite/router_rewrite.o plugins/router_http/router_http.o plugins/logfile/logfile.o plugins/router_cache/router_cache.o plugins/rawrouter/rawrouter.o plugins/router_static/router_static.o plugins/sslrouter/sslrouter.o plugins/spooler/spooler_plugin.o plugins/cheaper_busyness/cheaper_busyness.o plugins/symcall/symcall_plugin.o plugins/transformation_tofile/tofile.o plugins/transformation_gzip/gzip.o plugins/transformation_chunked/chunked.o plugins/transformation_offload/offload.o plugins/router_memcached/router_memcached.o plugins/router_redis/router_redis.o plugins/router_hash/router_hash.o plugins/router_expires/expires.o plugins/router_metrics/plugin.o plugins/transformation_template/tt.o plugins/stats_pusher_socket/plugin.o -lpthread -lm -rdynamic -ldl -lz -L/usr/lib/x86_64-linux-gnu -lpcre -lssl -lcrypto -L/usr/lib/x86_64-linux-gnu -lxml2 -lpthread -ldl -lutil -lrt -lm /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a -lutil -lcrypt
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(pytime.o): In function `pygettimeofday':
    /home/ubuntu/Python-3.5.1/Python/pytime.c:494: undefined reference to `clock_gettime'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(pytime.o): In function `pymonotonic':
    /home/ubuntu/Python-3.5.1/Python/pytime.c:633: undefined reference to `clock_gettime'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(pytime.o): In function `pygettimeofday':
    /home/ubuntu/Python-3.5.1/Python/pytime.c:494: undefined reference to `clock_gettime'
    /home/ubuntu/Python-3.5.1/Python/pytime.c:508: undefined reference to `clock_getres'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(pytime.o): In function `pymonotonic':
    /home/ubuntu/Python-3.5.1/Python/pytime.c:633: undefined reference to `clock_gettime'
    /home/ubuntu/Python-3.5.1/Python/pytime.c:646: undefined reference to `clock_getres'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(timemodule.o): In function `py_process_time':
    /home/ubuntu/Python-3.5.1/./Modules/timemodule.c:977: undefined reference to `clock_gettime'
    /home/ubuntu/Python-3.5.1/./Modules/timemodule.c:983: undefined reference to `clock_getres'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(timemodule.o): In function `time_clock_getres':
    /home/ubuntu/Python-3.5.1/./Modules/timemodule.c:205: undefined reference to `clock_getres'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(timemodule.o): In function `time_clock_gettime':
    /home/ubuntu/Python-3.5.1/./Modules/timemodule.c:151: undefined reference to `clock_gettime'
    /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a(timemodule.o): In function `time_clock_settime':
    /home/ubuntu/Python-3.5.1/./Modules/timemodule.c:182: undefined reference to `clock_settime'
    collect2: ld returned 1 exit status
    *** error linking uWSGI ***

**Comment by unbit** [comment]
The error is triggered by /usr/local/lib/python3.5/config-3.5m/libpython3.5m.a. I suppose you build that python by hand. Can you re-compile it with --enable-shared ?

**Comment by kuzmak** [comment]
Thank you. I added few flags to configure (highlighted below) and now uwsgi compiles just fine.

wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
tar xzf Python-3.5.1.tgz
cd Python-3.5.1
**sudo ./configure --enable-shared --prefix=/usr/local LDFLAGS="-Wl,--rpath=/usr/local/lib"**
sudo make altinstall

$ pip install uwsgi
Collecting uwsgi
  Using cached uwsgi-2.0.13.1.tar.gz
Installing collected packages: uwsgi
  Running setup.py install for uwsgi
Successfully installed uwsgi-2.0.13.1
