### ISSUE TITLE
mod_proxy_uwsgi does not work with ProxyErrorOverride + ErrorDocument

### ISSUE THREAD

**Issue by smallredbean** [unbit/uwsgi#1282]
We are using Apache as our proxy server and switching from mod_wsgi to mod_proxy_uwsgi + uWSGI. Since we server multiple VirtualHost in one wsgi app, we'd love to reuse the existing ErrorDocument defined for individual VirtualHost. Unfortunately I cannot get it to work. In the apache config, ProxyErrorOverride is turned on, and it works for other proxy module (e.g., mod_proxy_http to assets on CDN). Was wondering if I missed anything?

**Comment by unbit** [comment]
Just looked at how e ProxyErrorOverride works. It looks like it is something we must explicitely manage (honouring the ->error_override struct field like in proxy_http).

**Comment by smallredbean** [comment]
I reached to the same place after looking into mod_wsgi too.

Also, even without customized settings on ErrorDocument, i.e., using default Apache error pages, the "->error_override" support is required too. Otherwise, the empty response from uWSGI would go directly to user browsers.

**Comment by xrmx** [comment]
This looks fixed, closing.
