### ISSUE TITLE
uWSGI scrubbing subprocess environment vars?

### ISSUE THREAD

**Issue by ecederstrand** [unbit/uwsgi#1283]
I have a Django view that calls sqlplus, the Oracle client, in a subprocess:

```
import subprocess
environ = dict(LD_LIBRARY_PATH='/usr/lib/compat:/usr/local/lib:/usr/local/lib/compat/pkg:/usr/local/instantclient')
proc = subprocess.Popen(
    args=['/usr/local/instantclient/sqlplus', '-S', connect_string(), '@input.sql'], 
    env=environ, 
    shell=False, 
    stdout=open('output.dat', 'w'), 
    stderr=subprocess.PIPE
)
```

If I run this code in a standalone Python script, it works. However, when I run it within a Django view, I get the following:

> /usr/local/instantclient/sqlplus: error while loading shared libraries: libsqlplus.so: cannot open shared object file: No such file or directory

This is the error message I expect when /usr/local/instantclient is not in LD_LIBRARY_PATH. Somehow, LD_LIBRARY_PATH is not passed to my subprocess when the subprocess is started within uWSGI. Why is that?

I tried adding 

> env= LD_LIBRARY_PATH=/usr/lib/compat:/usr/local/lib:/usr/local/lib/compat/pkg:/usr/local/instantclient

to my uwsgi.ini but that didn't help.

I'm using uWSGI 2.0.13 and Python 3.4.4 on FreeBSD 10.1.

**Comment by ecederstrand** [comment]
I have verified that  `os.environ['LD_LIBRARY_PATH']` contains the correct value before the `subprocess.Popen` call when run through uWSGI. I have tried deleting the `env` argument, and I have tried passing `env=os.environ`, but I still always get the same error.

This worked in a previous version of uWSGI, but I can't recall exactly which version just now.

**Comment by ecederstrand** [comment]
The subprocess also works from Django run server, and from gunicorn. Any ideas how to debug this?

**Comment by ecederstrand** [comment]
Closing. This is a really convoluted situation where I'm calling a Linux binary on FreeBSD using the 64bit Linux compatibility layer, so I suspect I'm quite alone in having this problem.

I ended up editing `/compat/linux/etc/ld.so.conf` to add my custom `LD_LIBRARY_PATH` and then running `/compat/linux/sbin/ldconfig` to have it picked up. This fixed my problem.

**Comment by defulmere** [comment]
I realize you've closed this, but I'm having the exact same problem when running uwsgi as an unprivileged user on CentOS 7 Linux - so I don't believe it's unique to your setup at all.

In my case, I've got `LD_LIBRARY_PATH` set to pick up an updated `sqlite3` from `/opt`: 
- When I run the app via Django's dev server, the app picks up the new sqlite (verified with `sqlite3.sqlite_version`)
- When I run it under uwsgi, the application picks up the old system sqlite.

In both cases, `os.environ` reports that `LD_LIBRARY_PATH` is set as it should be, but uwsgi ignores it.

While researching this I've read a lot about how setuid and setgid apps scrub unsafe variables from the environment, but I don't have setuid/setgid set on my uwsgi binary so there should not be any privilege escalation/deescalation stuff going on (I think).

Anyway, just adding my notes here in case someone else is bumping into this and has something to add.
