### ISSUE TITLE
When cheaping, master worker may cheap busy workers

### ISSUE THREAD

**Issue by shoham-stratoscale** [unbit/uwsgi#1288]
When cheaper algorithm says it's ok to cheap workers, the master kills the oldest worker. When doing so, it doesn't check if the worker is busy, and it may kill a worker while it's handling a request.

https://github.com/unbit/uwsgi/blob/fb3628d7295772615004a03cdbc67de702b81c2a/core/master_utils.c#L193

**Comment by shoham-stratoscale** [comment]
Fix was merged

**Comment by abarghou** [comment]
Hi,
Is this fix released? If not, is there any estimate for when it would be?
Thanks

**Comment by unbit** [comment]
They are already merged in uwsgi-2.0, next stable release should be out during the week
