### ISSUE TITLE
Tabs and Spaces are mixed

### ISSUE THREAD

**Issue by Brightcells** [unbit/uwsgi#1296]
Such as codes in https://github.com/unbit/uwsgi/blob/master/core/uwsgi.c
![image](https://cloud.githubusercontent.com/assets/5810063/16218104/880f4cb4-37ac-11e6-961e-ac27eccb55c2.png)

I think it is necessary to make it unified.

**Comment by xrmx** [comment]
Yeah, we know that no need to open a bug report, thanks
