### ISSUE TITLE
GIL is not not re-acquired in py_uwsgi_farm_get_msg poll error case

### ISSUE THREAD

**Issue by joshuahlang** [unbit/uwsgi#1326]
Noticed this when looking at another issue. GIL should probably be reclaimed here:

https://github.com/unbit/uwsgi/blob/master/plugins/python/uwsgi_pymodule.c#L1517

**Comment by xrmx** [comment]
@joshuahlang ehm, haven't this already reported by you in #1320 and fixed already?

**Comment by joshuahlang** [comment]
Indeed... Seems some caching somewhere was hiding the updated line in github's source view.
