### ISSUE TITLE
<type 'exceptions.TypeError'>

### ISSUE THREAD

**Issue by peterswang** [unbit/uwsgi#1329]
Hi,

I'm getting this error and haven't been able to find a way to trace down the real issue. The html log file shows:
Python 2.7.10: /usr/local/Cellar/uwsgi/2.0.11.2_2/bin/uwsgi
Wed Aug 3 02:03:38 2016

The corresponding entry in uwsgi.log is:
Aug  3 12:58:51 2016] GET /?callback=jQuery31000655199522152543_1470254331606&api=get_proj_overview&_=1470254331607 => generated 0 bytes in 49 msecs (HTTP/1.1 200) 1 headers in 51 bytes (1 switches on core 0)

The Python logging out from my WSGI app shows:
INFO:root:Request method = GET
DEBUG:root:GET data:
callback=jQuery31000655199522152543_1470254331606&api=get_proj_overview&_=1470254331607
DEBUG:root:API service requested: get_proj_overview
DEBUG:root:Response body: jQuery31000655199522152543_1470254331606({"data": [{"ProjName": "311", "NCats": 19}, {"ProjName": "322", "NCats": 3}]})
DEBUG:root:Completing HTTP request!

If I run my Python WSIG app directly, as in 'python wsgi.py', there's no problem with the JS-Python communication. 

The Nginx config entry is:
    location /web_tdc/ {
        try_files $uri $uri.py  @web_tdc ;
        include uwsgi_params;
        # uwsgi_pass 127.0.0.1:3032;
        uwsgi_pass 127.0.0.1:8080;
        uwsgi_param SCRIPT_NAME web_tdc_server;
        uwsgi_modifier1 30;
        uwsgi_buffering off;
    }

My JS shows 'JSON response error'.

I'm running Python 2.7.12 on OS X 10.11.6, which appears to the version that comes with OS X. Could this be an issue?  How could I configure uWSGI to use the the latest Python?

Or might be a Ning config issue?

Spent several hours on this already.  Any help would be greatly appreciated.

Thx,
Peter

**Comment by peterswang** [comment]
Sorry, forgot to include my uWSGI.ini content, for completeness:

[uwsgi]
# plugins param requried for wsgi-file, file, module, callable
plugins = python

# for listening/routing HTTP requests
http-socket = 127.0.0.1:8080

master = true
enable-threads = true
threads = 1
chdir = /var/www/web_tdc
pythonpath = /usr/local/lib/python2.7/site-packages/

touch-reload = /var/www/web_tdc/web_tdc_server.py
wsgi-file = /var/www/web_tdc/web_tdc_server.py
callable = application

**Comment by xrmx** [comment]
Looks like a print in your app?
