### ISSUE TITLE
invalid uwsgi request (current strsize: 55272). skip.

### ISSUE THREAD

**Issue by jason9797** [unbit/uwsgi#1334]
Hi, I use uwsgi+django
some requests don't send to django,just skip by uwsgi
request's method is GET with much params, I have set buffer-size 65535
Question is like [this](http://serverfault.com/questions/733602/show-config-of-running-uwsgi-instance) 
so how to fix it;
thx

**Comment by xrmx** [comment]
You have configured something wrong, possibly sending http to a socket expecting uwsgi protocol? Please use the mailing list for support.
