### ISSUE TITLE
websockets does not support continuation frames

### ISSUE THREAD

**Issue by acrich** [unbit/uwsgi#1350]
The uwsgi_websocket_recv_do() function treats opcode %x0 the same as opcode %x1 or %x2. This results in continuation frames getting to the application as if they are separate websockets messages. Because the application can't know what the opcode was, it can't aggregate frames into complete messages itself.

This results in a situation where large JSONs are received in pieces and cannot be parsed.

I'm not a C developer, so I might be mistaken, but I couldn't find any check for the FIN flag in the receive function as well.

To verify the issue, I recompiled uWSGI with a log message for the received opcode, just before running parse:

```
uwsgi_log("[uwsgi-websocket] \"%.*s %.*s\" (%.*s) received opcode: %d \n", REQ_DATA, wsgi_req->websocket_opcode );
return uwsgi_websockets_parse(wsgi_req);
```

I then ran the websockets_chat_2 test, and pasted Descartes' meditations from Project Gutenberg:
http://www.gutenberg.org/cache/epub/23306/pg23306.txt
In the middle of page 113, the first frame ends, and a continuation message is received with opcode %x0. That second frame is sent to the websockets_chat_2 application as a separate message.

**Comment by fobdy** [comment]
👍

**Comment by ecamaj** [comment]
It seems that I encountered this problem too. It is connected with Chrome/Safari browsers, everything works fine with Safari, Firefox.
I prepared docker that clearly shows the problem, you can build the docker container and test the problem with https://github.com/ecamaj/socketproblem.git 

I have pre-production system and I need to fix this as soon as possible, and would really appreciate if anyone could take a look at this.
For me, alternative is to switch all parts of the system to Gunicorn or something, which I would like to avoid if possible.

@acrich , how did you manage to avoid the problem? 

Thanks everyone, 
Eduard

**Comment by acrich** [comment]
@ecamaj I switched the websockets handling part to autobahn, it runs as a separate service, and talks directly with nginx. I kept uwsgi for the parts that run on django.

You could in theory limit the size of messages sent by the client. I never tried it.

**Comment by ecamaj** [comment]
That is regular situation on my side, client is sending JSON that contains base64 encoded image inside it.

**Comment by acrich** [comment]
@ecamaj if you use python-socketio, why do you need uwsgi's websockets implementation?

also, uwsgi implement the websockets protocol and not socketio.
I'm not sure if it's possible to mix the two, and wouldn't try to do so.

if somehow it all just works together, and you'd like to bypass uwsgi's limitation on long messages, you can force socketio to use only long-polling. that way, maybe you won't need to rewrite any code.

**Comment by ecamaj** [comment]
Long-polling is expensive (CPU/memory?) if large number of clients, isn't it? And I hope that large number of clients will use the system one day. :)

I'm not sure how those two exactly work together, python-socketio and uwsgi, I guess uwsgi is used for accepting raw websocket frames and python-socketio/engineio builds on that, but @miguelgrinberg could know more and if that part on uwsgi is possible to avoid. 

But all that just aims to avoid the bug (?) on uwsgi, which would be very nice to be fixed, right? You seem to have found the part of code in uwsgi that has the problem, I prepared environment how to replicate and test, should be enough...?

**Comment by unbit** [comment]
@ecamaj @acrich pull request would be highly appreciated, just to give my 2 cents: yes there is no support for continuation frames, it was not a problem when this part of the code was written (5/6 years ago) but now its becoming a huge limit.
