### ISSUE TITLE
can't start the uwsgi server with socket ports

### ISSUE THREAD

**Issue by aibati2008** [unbit/uwsgi#1354]
I try to build the web server with nginx+flask+uwsgi , it works fine when I configure http ports, but it can't work when I change to socket ports.

http port config:
**
[uwsgi]
#application's base folder
base = /data/scripts/token_server
buffer-size = 65535
post-buffering = 4096
 
#python module to import
app = app_10053
module = %(app)
 
#socket file's location
#start port and way
http = 0.0.0.0:10053
socket-timeout=10

chdir = /data/scripts/token_server
 
#the variable that holds a flask application inside the module imported at line #6
callable = app

#open viriturl host
vhost = true

#setting processes master and son
master = true
processes = 4
threads = 2
listen = 1024

stats = 0.0.0.0:1717

#pid file
pidfile = /var/run/uwsgi_10053.pid

#location of log files
logto = /data/logs/%n.log
**

I only change "http = 0.0.0.0:10053" to "socket = 0.0.0.0:10053", it return the below error:
![image](https://cloud.githubusercontent.com/assets/10130476/18160057/1faf5bc4-705e-11e6-9499-72dda69017fd.png)

  can anyone knows what's the matter?

**Comment by xrmx** [comment]
Socket is for uwsgi protocol, not http, checkout http-socket. Please don't use github for support requests.
