### ISSUE TITLE
Don't pass `-Werror` except during development.

### ISSUE THREAD

**Issue by zenhack** [unbit/uwsgi#1368]
I just had a pip `install -r requirements.txt` fail when trying to install another project which transitively depends on uwsgi; It gave me the following error:

```
  plugins/corerouter/cr_map.c: In Funktion »uwsgi_cr_map_use_static_nodes«:
  plugins/corerouter/cr_map.c:154:5: Fehler: this »if« clause does not guard... [-Werror=misleading-indentation]
       if (!next_node)
       ^~
  plugins/corerouter/cr_map.c:157:6: Anmerkung: ...this statement, but the latter is misleadingly indented as if it is guarded by the »if«
        while (tmp_node != next_node) {
        ^~~~~
  cc1: Alle Warnungen werden als Fehler behandelt
  
  ----------------------------------------
  Failed building wheel for uWSGI
```

I'm building uwsgi 2.0.13.1 with gcc 6.2.1. It's not immediately obvious to me what the problem gcc is complaining about is; the indentation for the source code in question looks fine to me. However, the issue I wanted to bring up is this: release sources should never pass `-Werror`, since the set of warnings that compilers issue is completely non-portable; even if the compiler doesn't complain on the developer's system, the compiler on a user's system may issue other warnings. For me it was fairly obvious what had happened, and just doing `CFLAGS=-Wno-error pip ...` works around the problem, but for python developers not familiar with C, this could be a highly confusing build error.

This is just a general best practice issue for C/C++ code; you want to use `-Werror` *only* for development, but *not* for releases, because of the above problem.

**Comment by xrmx** [comment]
Are you sure you are installing 2.0.13.1, this should have been fixed in 2.0.13 and building the uwsgi-2.0 branch works fine here with 6.2.0.

**Comment by zenhack** [comment]
You're right, I was mistaken about the version that was being pulled in; 2.0.13.1 does build fine for me.

That said, it does look like `-Werror` is still being passed by default, even on master, which was more the point of this report.

**Comment by xrmx** [comment]
We may drop the -Werror on uwsgi-2.0 but it's useful for master being picky by default. Otherwise things get unnoticed.

**Comment by zenhack** [comment]
Quoting Riccardo Magliocchetti (2016-09-29 03:29:12)

>    We may drop the -Werror on uwsgi-2.0 but it's useful for master being
>    picky by default. Otherwise things get unnoticed.

I agree; you definitely want this on for development.
