### ISSUE TITLE
Unable to resolve error

### ISSUE THREAD

**Issue by Tyomkeen** [unbit/uwsgi#1370]
I'm trying to run uwsgi + django using socket like this:
$ sudo uwsgi --socket prj.sock --module prj.wsgi
as a result I have:
*** Starting uWSGI 2.0.13.1 (64bit) on [Tue Sep 27 22:13:17 2016] ***
compiled with version: 5.3.0 on 27 September 2016 21:49:57
os: Linux-4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015
nodename: localhost
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /vagrant/ce/source/ce
detected binary path: /home/vagrant/.env/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1954
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Operation not permitted [core/socket.c line 230]

Running uwsgi using port like this:
$ uwsgi --socket :8001 --module prj.wsgi
works fine.

I guess this is not a permissions issue cause there are no prj.sock at all.

**Comment by xrmx** [comment]
First read this http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html#if-that-doesn-t-work then if you haven't figured out your issues please use the mailing list for debugging configuration issues.

**Comment by Tyomkeen** [comment]
did you understand the answer or even read it until the end?
I can't do all this checks from the doc cause I can't run uwsgi using socket at all.
So there is not connected to nginx...

Nice answer btw. Thx for RTFM.

**Comment by xrmx** [comment]
@Tyomkeen sorry for closing in a rush but "Operation not permitted" looks like a permission error to me. Are you sure you don't have *prj.sock*? Anyway please use the mailing list for this kind of issues, there's a lot more people there than the one that gets the notification from github.

**Comment by Tyomkeen** [comment]
I'm pretty sure that there no prj.sock. This is not the first time I'm using uwsgi that's why I was surprised with this strange behaviour.
Any way I will follow your advice and will use mailing list.
Thank you.
