### ISSUE TITLE
uwsgi doesn't quit when receiving a SIGQUIT signal

### ISSUE THREAD

**Issue by Shir0kamii** [unbit/uwsgi#1373]
Hi,

I believe uwsgi was supposed to exit after having received a SIGQUIT signal, or at least it does in the latest release. But on the current master branch, this behavior is not respected, and it reloads the application instead of exiting.

Hope this helps!

**Comment by unbit** [comment]
Hi, in 2.1 we moved towards a more 'classic' logic, where TERM destroy the instance (while now the instance is reloaded, causing lot of headaches)

**Comment by Shir0kamii** [comment]
I see, thank you for the clarification.

Is there a place to see the changelog between current release vs master? I would be interested to take a look!

**Comment by xrmx** [comment]
Looks we can close this.
