### ISSUE TITLE
[bug] uwsgi.opt doesn't return list for multi-item options in python 3

### ISSUE THREAD

**Issue by raulchen** [unbit/uwsgi#1374]
Hi there,

If I set a multi-item option in `uwsgi.ini`, e.g.

```
cache2 = name=1,items=100,blocksize=100
cache2 = name=2,items=200,blocksize=200
```

In python 2, `uwsgi.opt['cache2']` would return a list of 2 items: `["name=1,items=100,blocksize=100", "name=2,items=200,blocksize=200"]`;
While in python 3, `uwsgi.opt['cache2']` only returns a string with the last item: `"name=2,items=200,blocksize=200"`

Is there other ways that can get this option as a list? Otherwise I'll read `uwsgi.ini` file directly.

Thanks!

**Comment by econtal** [comment]
Is there any fix or workaround for this issue? It seems it's still present in uwsgi 2.0.18. Thanks!

**Comment by grascm** [comment]
Hi! @xrmx 
I've downloaded recent source code from https://projects.unbit.it/downloads/uwsgi-2.0.20.tar.gz
And for some weird reason this issue still actual in it, despite the fact it was fixed 5 years ago.
Commit with fix is not included in release, can you, please, explain why is it happened? And you should probably fix it.
