### ISSUE TITLE
Please provide wheel packages to PyPI

### ISSUE THREAD

**Issue by kissgyorgy** [unbit/uwsgi#1376]
Currently installing uWSGI for different distributions is a PITA, because one has to install a bunch of development packages, C compiler, etc.
Wheel format has huge benefits, is really fast and very easy to make.
There is the [manylinux platform tag](https://www.python.org/dev/peps/pep-0513/) which is portable for many distributions.

**Comment by xrmx** [comment]
I don't think the manylinux is a good base for us kernel wise. Closing as dup of #1218
