### ISSUE TITLE
document --mule=package.module:callable

### ISSUE THREAD

**Issue by akvadrako** [unbit/uwsgi#1387]
When this feature was implemented in #967, the documentation wasn't updated. I had to search the issue tracker to see if it's supported.

**Comment by xrmx** [comment]
Pull request against https://github.com/unbit/uwsgi-docs repository very much welcome

**Comment by xrmx** [comment]
Fixed in https://github.com/unbit/uwsgi-docs/commit/f7ff115820656d0f24b17ce7c6143a0b61f22d38 . Thanks!
