### ISSUE TITLE
uwsgi seg fault (php config directive `phar.cache_list` + OpenSSL signed PHAR file)

### ISSUE THREAD

**Issue by maki-tompson** [unbit/uwsgi#1393]
I'm not sure is it uwsgi or php related issue ...

php directive [`phar.cache_list`](https://secure.php.net/manual/en/phar.configuration.php#ini.phar.cache-list) which point to openssl signed phar file, cause uwsgi segfault.

<table>
<tr><th>phar.cache_list directive set (yes/no)</th><th>PHAR with OpenSSL signature (yes/no)</th><th>uWSGI (work/crash)</th></tr>
<tr><td>✘</td><td>✔</td><td>✔</td></tr>
<tr><td>✔</td><td>✘</td><td>✔</td></tr>
<tr><td>✔</td><td>✔</td><td>✘</td></tr>
</table>

PHP Version 5.6.27-0+deb8u1
PHP Version 5.6.11-1ubuntu3.4

> [uWSGI] getting JSON configuration from uwsgi.json
> [uwsgi-static] added check for /srv/public_html/
> **\* Starting uWSGI 2.0.7-debian (64bit) on [Tue Oct 25 22:56:30 2016] ***
> compiled with version: 4.9.1 on 25 October 2014 19:17:54
> os: Linux-4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016
> nodename: 31889b187207
> machine: x86_64
> clock source: unix
> pcre jit disabled
> detected number of CPU cores: 4
> current working directory: /srv
> detected binary path: /usr/bin/uwsgi-core
> ...
> 
> uwsgi socket 0 bound to TCP address 127.0.0.1:46767 (port auto-assigned) fd 6
> !!! uWSGI process 1 got Segmentation Fault !!!
> **\* backtrace of 1 ***
> /usr/bin/uwsgi(uwsgi_backtrace+0x30) [0x4635f0]
> /usr/bin/uwsgi(uwsgi_segfault+0x21) [0x4639b1]
> /lib/x86_64-linux-gnu/libc.so.6(+0x350e0) [0x7f6ca11930e0]
> /usr/lib/libphp5.so(zend_hash_find+0x17d) [0x7f6c9f72895d]
> /usr/lib/libphp5.so(+0x3d052b) [0x7f6c9f71c52b]
> /usr/lib/libphp5.so(zend_is_callable_ex+0x368) [0x7f6c9f721f28]
> /usr/lib/libphp5.so(zend_fcall_info_init+0x25) [0x7f6c9f722395]
> /usr/lib/libphp5.so(+0x21187e) [0x7f6c9f55d87e]
> /usr/lib/libphp5.so(phar_verify_signature+0x159) [0x7f6c9f560959]
> /usr/lib/libphp5.so(+0x22c909) [0x7f6c9f578909]
> /usr/lib/libphp5.so(phar_open_from_filename+0x10a) [0x7f6c9f5790da]
> /usr/lib/libphp5.so(phar_ini_cache_list+0x1c8) [0x7f6c9f579388]
> /usr/lib/libphp5.so(zend_register_ini_entries+0x6b) [0x7f6c9f72fd5b]
> /usr/lib/libphp5.so(zm_startup_phar+0x10) [0x7f6c9f573740]
> /usr/lib/libphp5.so(zend_startup_module_ex+0x10e) [0x7f6c9f71f7ee]
> /usr/lib/libphp5.so(+0x3d3899) [0x7f6c9f71f899]
> /usr/lib/libphp5.so(zend_hash_apply+0x43) [0x7f6c9f728263]
> /usr/lib/libphp5.so(zend_startup_modules+0x2a) [0x7f6c9f71fb7a]
> /usr/lib/libphp5.so(php_module_startup+0x7b3) [0x7f6c9f6b59f3]
> /usr/lib/uwsgi/plugins/php_plugin.so(+0x365c) [0x7f6c9fee265c]
> /usr/lib/uwsgi/plugins/php_plugin.so(uwsgi_php_init+0xb3) [0x7f6c9fee3093]
> /usr/bin/uwsgi(uwsgi_start+0x51e) [0x464bee]
> /usr/bin/uwsgi(uwsgi_setup+0x1073) [0x466c33]
> /usr/bin/uwsgi(main+0x9) [0x416989]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f6ca117fb45]
> /usr/bin/uwsgi() [0x4169b7]
> **\* end of backtrace ***

**Comment by xrmx** [comment]
Could you please try to reproduce with latest stable release?

**Comment by maki-tompson** [comment]
Sure. uwsgi from master branch (is it ok?).

> *** Starting uWSGI 2.1-dev (64bit) on [Wed Oct 26 15:37:21 2016] ***
> compiled with version: 5.2.1 20151010 on 26 October 2016 15:02:23
> os: Linux-4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016
> ...
> --- PHP custom config ---
> 
> phar.cache_list = /srv/app.phar
> 
> --- end of PHP custom config ---
> !!! uWSGI process 11223 got Segmentation Fault !!!
> *** backtrace of 11223 ***
> ./uwsgi(uwsgi_backtrace+0x2c) [0x4726ec]
> ./uwsgi(uwsgi_segfault+0x21) [0x472af1]
> /lib/x86_64-linux-gnu/libc.so.6(+0x35250) [0x7faaf7908250]
> /usr/lib/libphp5.so(zend_hash_find+0x186) [0x7faaf40be5c6]
> /usr/lib/libphp5.so(+0x3d16e4) [0x7faaf40b26e4]
> /usr/lib/libphp5.so(zend_is_callable_ex+0x368) [0x7faaf40b7c48]
> /usr/lib/libphp5.so(zend_fcall_info_init+0x25) [0x7faaf40b80a5]
> /usr/lib/libphp5.so(+0x21bf44) [0x7faaf3efcf44]
> /usr/lib/libphp5.so(phar_verify_signature+0x159) [0x7faaf3f00029]
> /usr/lib/libphp5.so(+0x237213) [0x7faaf3f18213]
> /usr/lib/libphp5.so(phar_open_from_filename+0x10a) [0x7faaf3f1840a]
> /usr/lib/libphp5.so(phar_ini_cache_list+0x1c8) [0x7faaf3f186b8]
> /usr/lib/libphp5.so(zend_register_ini_entries+0x6b) [0x7faaf40c596b]
> /usr/lib/libphp5.so(zm_startup_phar+0x10) [0x7faaf3f12c70]
> /usr/lib/libphp5.so(zend_startup_module_ex+0x10e) [0x7faaf40b17ee]
> /usr/lib/libphp5.so(zend_hash_apply+0x5b) [0x7faaf40bde5b]
> /usr/lib/libphp5.so(zend_startup_modules+0x2a) [0x7faaf40b58ca]
> /usr/lib/libphp5.so(php_module_startup+0x7bb) [0x7faaf404b79b]
> ./php_plugin.so(+0x392c) [0x7faaf48ac92c]
> ./php_plugin.so(+0x436e) [0x7faaf48ad36e]
> ./uwsgi(uwsgi_start+0x55e) [0x473d5e]
> ./uwsgi(uwsgi_setup+0x2631) [0x477411]
> ./uwsgi(main+0x9) [0x41ffa9]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7faaf78f3ac0]
> ./uwsgi(_start+0x29) [0x41ffd9]
> *** end of backtrace ***
> Wed Oct 26 15:37:21 2016 - !!! /tmp/builder-sandbox/uwsgi-master/uwsgi (pid: 11223) exited with status 1 !!!
> Wed Oct 26 15:37:21 2016 - !!! Fallback config to /srv/uwsgi.json:safe !!!
> Segmentation fault (core dumped)

**Comment by xrmx** [comment]
Could you please share your config?

**Comment by maki-tompson** [comment]
Sure. I will prepare MWE (minimal working example).

**Comment by maki-tompson** [comment]
@xrmx, i hope this will help. If you need any additional information let me know.

[issue-1393-mwe.tar.gz](https://github.com/unbit/uwsgi/files/553663/issue-1393-mwe.tar.gz)
