### ISSUE TITLE
Uwsgi with need-app and lazy-apps return 0 when no app are found.

### ISSUE THREAD

**Issue by gossel-j** [unbit/uwsgi#1397]
I have an application that need to run with lazy-apps because different libraries that we use cannot work without it. I added the need-app option in order to Fail-Fast then restart when my app cannot start.

When I don't use lazy-apps uwsgi fail with return code 22. With lazy-apps enabled it fail and return error code 0.

I don't feel that it is normal to fail with a return code of 0 and would like to know if it's normal or not.

**Comment by unbit** [comment]
It is absolutely wrong, can you try this patch: 

https://github.com/unbit/uwsgi/commit/65a8d676f3e63a04b07fdcb4e1f92bb6502f024d

thanks

**Comment by gossel-j** [comment]
Yes looks good !
When can we hoping a release with this fix ?

**Comment by unbit** [comment]
@xrmx i am about to backport it, is it ok for you ?

**Comment by xrmx** [comment]
@unbit sure, fine for me

**Comment by gossel-j** [comment]
@unbit it is ok for me too

**Comment by xrmx** [comment]
Fix backported to uwsgi-2.0, closing.
