### ISSUE TITLE
set multiple env parameter in uwsgi ini file not working ??

### ISSUE THREAD

**Issue by tyan4g** [unbit/uwsgi#1398]
I'm trying to set multiple env int my uwsgi ini file .
```
[uwsgi]
http = 127.0.0.1:5000
chdir = /home/kali/Code/test
wsgi-file = envtest.py
callable = app
env = DB_NAME=demo
env = DB_USER=test
processes = 1
virtualenv = /home/kali/Code/test/venv
```

when i'trying to get env in my script

`os.getenv('DB_NAME')`     //this is working
`os.getenv('DB_USER')`   //this is not working 

I can only get the first set env param DB_NAME, 

so what's the problem here??

**Comment by xrmx** [comment]
Works for me on 2.0.14 on linux.

**Comment by tyan4g** [comment]
If I use the method
```
for-readline = /etc/test/db.conf
  env = %(_)
end-for =
```

and if I put 
```
DB_NAME=demo
DB_USER=test
```

in db.conf

it works .just don't know what's the difference between what I mentioned above

I'm install uwsgi using pip in a virtual-env...on a ubuntu liunx machine..

**Comment by xrmx** [comment]
Does this work for you?
```
$ cat multipletestenv.ini 
[uwsgi]
http = :8080
wsgi-file = testmultipleenv.py
env = foo=bar
env = foo2=bar
$ cat testmultipleenv.py
import os

assert os.getenv('foo') == 'bar'
assert os.getenv('foo2') == 'bar'

def application(e, sr):
    sr('200 OK', [('Content-Type', 'text/html')])
    return b'Hello world'

$ uwsgi --ini multipletestenv.ini
```

**Comment by tyan4g** [comment]
your code works.I test it on my Mac.
thanks for your reply. at least I know that I'm not doing something wrong.
I guess I have to figure out why it's not working on my liunx machine by myself.

at first I didn't install uwsgi using pip, instead I install it from the ubuntu repo using

`sudo apt-get install uwsgi`

maybe this is my problem..because it's version is 1.9.0..
main reason Is that I don't want to write a upstart job by myself.it comes with a init.d script which is easy to use..

**Comment by tyan4g** [comment]
I find the my problem here.
cause I print the env varible to the browser.

but browser cache the result .

makes it looks unchanged...

such a waste of time..

**Comment by xrmx** [comment]
Closing then
