### ISSUE TITLE
linux build python35_plugin.so  error

### ISSUE THREAD

**Issue by fanfanfeng** [unbit/uwsgi#1400]
dear all:
         i want to build uwsgi plugins for python3.5. so i follow the docs and run:
PYTHON=python3.5 ./uwsgi --build-plugin "plugins/python python35"

it' come out error like:
/usr/bin/ld: /opt/Python3.5/lib/python3.5/config-3.5m/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_PyObject_NextNotImplemented' can not be used when making a shared object; recompile with -fPIC
/opt/Python3.5/lib/python3.5/config-3.5m/libpython3.5m.a: could not read symbols: Bad value

but ,where i run :
PYTHON=python2.6 ./uwsgi --build-plugin "plugins/python python26"

it come ok:
 python26 plugin built and available in python26_plugin.so **

my system is:
Linux x86_64 

anyone can help me?thanks

**Comment by xrmx** [comment]
I think you have to recompile your python3.5 with -fPIC which i think is used when building python with the --enable-shared flag.

**Comment by fanfanfeng** [comment]
Thanks xrmx:
i follow you suggestion and success:
1.rebuild python3.5 with  --enable-shared flag. 
2. copy libpython3.5* to /usr/lib64
3.rebuild:PYTHON=python3.5 ./uwsgi --build-plugin "plugins/python python35",it's success
