### ISSUE TITLE
Periodic broken connections between Nginx and uWSGI

### ISSUE THREAD

**Issue by artemrizhov** [unbit/uwsgi#1414]
Hi! My Django site is hosted under Nginx/uWSGI. The site becomes unreachable from time to time for a period from few minutes to few hours. It just returns 500 after long waiting.

I can see harakiri messages in uWSGI log when this happens. The requests do not reach the Django application at all (I've tried debugging). Instead I'm getting errors in Nginx log:

```
2016/12/03 01:18:40 [error] 1330#0: *363441461 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <ip address>, server: site.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi/app/site/socket", host: "site.com", referrer: "<page url>"
2016/12/03 01:19:27 [error] 1330#0: *363441461 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <ip address>, server: site.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi/app/site/socket", host: "site.com", referrer: "<page url>"
2016/12/03 01:20:15 [error] 1330#0: *363441461 upstream prematurely closed connection while reading response header from upstream, client: <ip address>, server: site.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi/app/site/socket:", host: "site.com", referrer: "<page url>"
```

In uWSGI logs I see this kind of messages:

```
Sat Dec  3 01:19:00 2016 - HARAKIRI [core 2] <ip address> - GET / since 1480727890
Sat Dec  3 01:20:15 2016 - HARAKIRI [core 2] <ip address> - GET / since 1480727999
Sat Dec  3 01:20:32 2016 - HARAKIRI [core 0] <ip address> - GET / since 1480727937

Sat Dec  3 05:04:15 2016 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 238] during GET / (<ip address>)
```

It seems the uwsgi messages depend on harakiri value. I can't be sure because the problem is on the heavy loaded production server and I can't do enough experiments. I've set harakiri 15 the last time this pappened, and now I can't return previous value 40 because the site hangs up again.

Nginx settings:

```
uwsgi_read_timeout 30;
limit_conn addr 100;

location ^~ / {
    limit_conn session 5;
    limit_req zone=session_req burst=5;

    proxy_set_header X-Forwarded-Proto $scheme;
    uwsgi_pass unix:///var/run/uwsgi/app/site/socket;
    include uwsgi_params;
    uwsgi_param UWSGI_SCHEME $scheme;
}
```

uWSGI settings:

```
module = deploy.wsgi:application
master
processes = 10
threads = 5
listen = 3072
thunder-lock
cpu-affinity = 1

reload-on-rss = 200
harakiri = 15
reload-mercy = 20
py-autoreload = 0
vacuum
```

**Comment by xrmx** [comment]
Which uwsgi version?
If you use an nginx timeout bigger than the uwsgi one and your requests takes more that the uwsgi harakiri timeout it's normal to see nginx warning about upstream stopping responding, no?
Your problem may be a mix of not enough workers for the traffic and a slow application.

**Comment by artemrizhov** [comment]
We have updated uWSGI from 2.0.6-debian to 2.0.14, but the problem persists.

> If you use an nginx timeout bigger than the uwsgi one and your requests takes more that the uwsgi harakiri timeout it's normal to see nginx warning about upstream stopping responding, no?

But if nginx timeout is less than the uwsgi one then it's also normal to see the "Broken pipe" messages, right?

Ok, let's suppose the problem is in my app, that's really possible. The problem is worse because I can't debug it while all workers are busy. I'm just getting error 500 in browser, while the most upper code in my app is never reached. If I've got all threads stolen, how do I debug this? How do I know which line of my code is buttleneck, if any?

**Comment by artemrizhov** [comment]
I'm going to use [this module](https://gist.github.com/niccokunzmann/6038331) that prints all hanging threads that are dead locked. I hope to check (and discover) if the buttleneck is in my code. Then I'll report the result.
Please let me know if you know another method to debug such cases.

**Comment by xrmx** [comment]
@artemrizhov you can try removing threads and using only processes

**Comment by xrmx** [comment]
Reopen if you find hints that this an uwsgi issue.

**Comment by Kazanz** [comment]
@artemrizhov Did you find a solution to your problem?  We are experiencing a similar issue where uwsgi hangs until harikari.

**Comment by artemrizhov** [comment]
@Kazanz I have not found the cause of the problem, because we were not experiencing this problem last months. I'd try to use this app if the problem happens again. https://github.com/niccokunzmann/hanging_threads
