### ISSUE TITLE
mule with '--mule=pkg.module:callable' do not start

### ISSUE THREAD

**Issue by baverman** [unbit/uwsgi#1424]
uwsgi 2.0.14

module.py:
<pre>
def worker():
    print 'START'

if __name__ == '__main__':
    worker()
</pre>

`uwsgi --mule=module.py --http :8000` shows START in output
but `uwsgi --mule=module:worker --http :8000` does not.

How callable syntax should be used?

**Comment by unbit** [comment]
Hi, thanks for reporting, i have backported support for the callable syntax from master branch to stable branch. Let me know if it works for you

**Comment by xrmx** [comment]
Closing then.
