### ISSUE TITLE
Backward incompatible changes in php 7.1 (sigh)

### ISSUE THREAD

**Issue by gdamjan** [unbit/uwsgi#1427]
https://github.com/php/php-src/commit/2809a676b55cebd4c6f8a8895ffe286db0704e87#diff-c6995589f3b41ca3c9b4c17c8327f7f9

so compiling uwsgi + php fails with:

```
plugins/php/php_plugin.c:600:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  sapi_uwsgi_log_message,         /* Log message */
  ^~~~~~~~~~~~~~~~~~~~~~
plugins/php/php_plugin.c:600:2: note: (near initialization for ‘uwsgi_sapi_module.log_message’)
```

they added a `int syslog_type_int` argument to the log function. dunno how they expect this API to be used through versions.

**Comment by xrmx** [comment]
ifdef all the things!
