### ISSUE TITLE
python uwsgiconfig.py --build go (is broken..)

### ISSUE THREAD

**Issue by biggiesmallsAG** [unbit/uwsgi#1431]
hey guys,

the buildconf for go is missing, cant execute a go build.

```
using profile: buildconf/go.ini
Traceback (most recent call last):
  File "uwsgiconfig.py", line 1601, in <module>
    uc = uConf(bconf, is_cflags)
  File "uwsgiconfig.py", line 653, in __init__
    self.config.readfp(open_profile(filename))
  File "uwsgiconfig.py", line 631, in open_profile
    return open(filename)
IOError: [Errno 2] No such file or directory: 'buildconf/go.ini'
```

**Comment by xrmx** [comment]
Have you found references of this go.ini conf file in the documentation? You are trying to building a non existent profile, i don't think that's a bug.

**Comment by biggiesmallsAG** [comment]
http://uwsgi-docs.readthedocs.io/en/latest/Go.html?highlight=golang

Does this not exist as a build option anymore?

**Comment by unbit** [comment]
@biggiesmallsAG it was supported until uWSGI 1.4, then the go runtime changed so much that embedding it was basically impossible. We currently maintain support only for gcco (basically for writing plugins in go instead of c)
