### ISSUE TITLE
Environment variables keys as bytes instead string

### ISSUE THREAD

**Issue by abusquets** [unbit/uwsgi#1432]
I load env variables like:

for-readline = %d/vars.ini
  env = %(_)
endfor =

With python 2.7 I don't have any problem but with python 3.5 when uwsgi app starts I have this errors:

Traceback (most recent call last):
  File "/usr/lib/python3.5/os.py", line 729, in __setitem__
    key = self.encodekey(key)
  File "/usr/lib/python3.5/os.py", line 798, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes

For each environment variable

**Comment by manelclos** [comment]
Hi! more info on this issue:
- uwsgi 2.0.14
- running on python 3.5.2
- on a very simple example application where django is not involved this is also happening
- we can see variables not in vars.ini, in fact removing for-readline does not solve the issue

This seems to be a problem with creating the environment, if printing the key and value in os.py:729 we can see this:

```
KEY: b'OLDPWD' b'/'
Traceback (most recent call last):
  File "/usr/lib/python3.5/os.py", line 730, in __setitem__
    key = self.encodekey(key)
  File "/usr/lib/python3.5/os.py", line 800, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
KEY: b'PS1' b'(venv3) # '
Traceback (most recent call last):
  File "/usr/lib/python3.5/os.py", line 730, in __setitem__
    key = self.encodekey(key)
  File "/usr/lib/python3.5/os.py", line 800, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
```

**Comment by xrmx** [comment]
This is python telling you have to reference elements in the environ as string and not as bytes.

```
$ python3.5
Python 3.5.3rc1 (default, Jan  3 2017, 04:40:57) 
[GCC 6.3.0 20161229] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ[b'OLDPWD']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/os.py", line 722, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.5/os.py", line 798, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
>>> os.environ['OLDPWD']
'/home/rm'
```

**Comment by manelclos** [comment]
Found the problem that was causing this issue. We were running a Python 2.7 app with a Python 3.5 virtualenv. Once we fixed the virtualenv the error went away.

Thanks!

**Comment by manelclos** [comment]
Hi @xrmx, I've spent some hours today debugging this problem, tried Python 3.6 no luck, and latest uwsgi from command line, which didn't show the problem, so I debugged my .ini till I found the problem. The problem is with the option "reload-os-env" which seems to affect a small piece of code at pyloader.c. This can be easily reproduced on the command line:

```
# this does not show the issue:
uwsgi --mount /apps/example5=wsgi.py --socket uwsgi.sock --uid www-data
# this will show the issue:
uwsgi --mount /apps/example5=wsgi.py --socket uwsgi.sock --uid www-data --reload-os-env
```

Would you consider reopening the bug?

Thanks!

**Comment by avkoval** [comment]
^ comment above helps. thank you.
