### ISSUE TITLE
[Question] config settings for cron

### ISSUE THREAD

**Issue by MorphBonehunter** [unbit/uwsgi#1433]
Hello,

i've search a while on google and on github but can not get an answer to my question.
I've use uwsgi with the php plugin and define different extensions to load and an cron in my config.
The cron executes an php script and at the moment i must write this in this way (snippet):

```
; set php configuration for this instance of php, no need to edit global php.ini
php-index = index.php
php-set = date.timezone=Europe/Berlin
php-set = expose_php=false
php-set = open_basedir=
php-set = session.save_path=/tmp
php-set = post_max_size=200M
php-set = upload_max_filesize=200M

; php extensions
php-set = extension=pdo_mysql.so
php-set = extension=gd.so
php-set = extension=iconv.so
php-set = extension=curl.so
php-set = extension=bz2.so
php-set = extension=zip.so
php-set = extension=intl.so
php-set = extension=mcrypt.so
php-set = extension=exif.so
php-set = zend_extension=opcache.so

; housekeeping cron
cron = -15 -1 -1 -1 -1 php -d extension=pdo_mysql.so -d extension=gd.so -d extension=zip.so -d extension=curl.so -f cron.php
```

Is there a way to make the cron use the "php-set" directives defined in the config so that i must not define it on command line with the "-d" switch?

**Comment by MorphBonehunter** [comment]
Seems that there is no possibility.

**Comment by unbit** [comment]
Sorry, completely missed that issue. What do you think about using a php ini file that you can load the in the cron command ?

```ini
;place here all of the php settings...

;place here all of the uwsgi-related configs
[uwsgi]
; load the php ini from the uwsgi config file
php-ini = %p
cron = -15 -1 -1 -1 -1 php -c %p
```

**Comment by MorphBonehunter** [comment]
@unbit no problem i count no comment as nobody has an idea :smile:
Maybe one more Question, if i use php-ini-append, is then the "normal" php.ini (system) available or must then the "whole" php.ini included?

**Comment by unbit** [comment]
Hi, with append you only add your new options to the default one

**Comment by MorphBonehunter** [comment]
Ok, thanks for your answer it seems that i was able to get this work.
