### ISSUE TITLE
No option to pass AUTH in redislog plugin 

### ISSUE THREAD

**Issue by heera-jaiswal** [unbit/uwsgi#1434]
While running uwsgi with redislog plugin defined, there is no option where  `AUTH` parameter can be specified for authentication with redis server if redis server is enabled with authentication.

`--logger redislog[:<host>,<command>,<prefix>]`

**Comment by unbit** [comment]
The plugin is pretty simple (well tiny, indeed): https://github.com/unbit/uwsgi/blob/master/plugins/redislog/redislog_plugin.c

would you like to make a pull request ?

**Comment by heera-jaiswal** [comment]
It could be included in redis URI like
`my_auth@host:6379`

After connecting to server, client just needs to execute.
`AUTH my_auth`

Please help me where I can change the code to do same because I can't disable authentication in the server.
