### ISSUE TITLE
Fail to start app on boot. Class random.Random returned a result with an error set

### ISSUE THREAD

**Issue by viirak** [unbit/uwsgi#1442]
This only happen on system startup. wsgi apps are fail to start due to this random class error.
However, after system is up, restarting uwsgi service again wsgi app start perfectly.

import random
  File "/srv/http/xxx/.env/lib/python3.6/random.py", line 742, in <module>
    _inst = Random()
SystemError: <class 'random.Random'> returned a result with an error set

Anyone have any idea? Thanks.

**Comment by lopsided98** [comment]
I have the same problem, restarting the service fixes it. I believe this started happening when I upgraded to Python 3.6.

**Comment by lepture** [comment]
It seems a bug of Python 3.6.

**Comment by lopsided98** [comment]
Yes, it appears to have been fixed, but not yet released: https://bugs.python.org/issue29208

**Comment by applecat** [comment]
Update from python3.6 to python3.6.3 fixes this problem.
