### ISSUE TITLE
how to test uwsgi unix socket ? 

### ISSUE THREAD

**Issue by rfyiamcool** [unbit/uwsgi#1443]
how to test uwsgi unix socket ?  same as curl tool .

**Comment by xrmx** [comment]
I don't think there's anythink like curl for the uwsgi protocol.

**Comment by xrmx** [comment]
Actually google suggests there's https://github.com/andreif/uwsgi-tools

**Comment by ralfeus** [comment]
> 
> 
> Actually google suggests there's https://github.com/andreif/uwsgi-tools

It seems uwsgi_curl can only TCP or UDP but not Unix socket
