### ISSUE TITLE
Can uwsgi share data among different processes?

### ISSUE THREAD

**Issue by xuxiaoyuspallow** [unbit/uwsgi#1451]
My uwsgi's setting is like `--processes 4 ` .And I change an object of my application via an API,but when I get the value of the object,it sometimes shows the unchange value and sometimes shows the changed value. But when I change the setting "processes" to 1, the problem disappear. How can I sovle the problem 
without change setting?

**Comment by unbit** [comment]
Hi, check the sharedarea (low-level):

http://uwsgi-docs.readthedocs.io/en/latest/SharedArea.html

and/or the cache (higher-level):

http://uwsgi-docs.readthedocs.io/en/latest/Caching.html
http://uwsgi-docs.readthedocs.io/en/latest/tutorials/CachingCookbook.html

but if the object is a complex one (something that cannot be easily serialized) you should rethink your stack, maybe introducing a micro services managing the object centrally
