### ISSUE TITLE
Extend ldap plugin so ldapauth supports group membership

### ISSUE THREAD

**Issue by jaceq** [unbit/uwsgi#1454]
Currently ldapauth (plugin ldap) does not support checking for group membership of user.
This option would be really useful and would enable ldapauth to be nicely fine grained.

**Comment by unbit** [comment]
Hi, adding features to the ldap plugin should be easy:

(for adding a new option)
https://github.com/unbit/uwsgi/blob/master/plugins/ldap/ldap.c#L539

(for adding new field)
https://github.com/unbit/uwsgi/blob/master/plugins/ldap/ldap.c#L377

(for improving the auth check)
https://github.com/unbit/uwsgi/blob/master/plugins/ldap/ldap.c#L388

i suppose adding a gid/group field to the parser should be enough

**Comment by jaceq** [comment]
this is hopeless, closing
