### ISSUE TITLE
address space usage big difference?

### ISSUE THREAD

**Issue by daoiqi** [unbit/uwsgi#1458]
1. When restart uwsgi, and request same data, the `address space usage` is not equals and big difference ?

```
# is not enough!
reload-on-as = 512
```

> {address space usage: 1008615424 bytes/961MB} {rss usage: 21594112 bytes/20MB} [pid: 30420|app: 0|req: 1/1] 127.0.0.1 () {34 vars in 570 bytes} [Sat Jan 28 21:10:14 2017] POST /find-vm => generated 2151 bytes in 1313 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)

> {address space usage: 555581440 bytes/529MB} {rss usage: 21487616 bytes/20MB} [pid: 30588|app: 0|req: 1/1] 127.0.0.1 () {34 vars in 570 bytes} [Sat Jan 28 21:10:40 2017] POST /find-vm => generated 2151 bytes in 1297 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)

2. Has My app bug?

**Comment by unbit** [comment]
Address space is touched by every part of the process, so basically it is impossible to understand what is going on, but yes, your app definitely can show this kind of behaviour, but being the RSS value consistent i do not think it is something to worry about

**Comment by daoiqi** [comment]
I google Internet article, many uWSGI `reload-on-as` is 128MB or 256MB, But my app is Easy to 961MB, so increase value to `reload-on-as = 2048`? 

So, I think `reload-on-as` is unnecessary? We are care about RSS value. Is there a problem with this idea?

**Comment by unbit** [comment]
Limiting on address space is useful only for hosters that cannot rely on more solid solutions (like containers) for limiting users/customers. If it is not your use-cuse i strongly suggest you to not rely on it. Eventually (as you already suggested) work with rss.
