### ISSUE TITLE
Question. Is it possible to log incoming request when it was accepted but not processed yet?

### ISSUE THREAD

**Issue by svetlyak40wt** [unbit/uwsgi#1460]
I need this to debug strange situation which is looks like uwsgi accepts connection but not return the response.

**Comment by xrmx** [comment]
We have a mailing list for open questions, please.

**Comment by svetlyak40wt** [comment]
I didn't find in README at https://github.com/unbit/uwsgi :(

**Comment by svetlyak40wt** [comment]
Well, I wrote to the mailing list but no response was given. I'm not sure if my email reached a destination. Mailing lists are like from 19 centure, aren't they? May be somebody had hit down a raven carrying my email?
