### ISSUE TITLE
uwsgi_latest_from_installer still doesn't include patch 6456e76

### ISSUE THREAD

**Issue by jef-sure** [unbit/uwsgi#1480]
The patch was committed on Aug 22, 2016, I thought it was in 2.014 already. Installing uwsgi with `curl http://uwsgi.it/install | bash -s coroae /tmp/uwsgi` brings uwsgi with half-backed PSGI websocket support.

Patch: https://github.com/unbit/uwsgi/commit/6456e76a66f4146d97ab004afc585e43753f8b7e

**Comment by unbit** [comment]
cherry-picked. Thanks for reporting
