### ISSUE TITLE
max-requests-delta and strict mode

### ISSUE THREAD

**Issue by philtay** [unbit/uwsgi#1488]
It looks like that the `max-requests-delta` can't be used in `strict` mode.
Steps to reproduce:

1. Create `foo.ini`:

```ini
[uwsgi]
strict = true
max-requests-delta = 100
```

2. Start uWSGI:

```sh
$ uwsgi --ini foo.ini
```

Result:

```
[uWSGI] getting INI configuration from foo.ini
[strict-mode] unknown config directive: max-requests-delta
```

uWSGI version 2.0.14

**Comment by unbit** [comment]
max-requests-delta is a 2.1 option

**Comment by tuky** [comment]
I am pretty sure, this has been backported, but `strict` mode still complains about `max-requests-delta` in `2.0.21`. More surprisingly, the even newer option `max-worker-lifetime-delta` is allowed in `strict` mode :sweat_smile:

**Comment by amaddio** [comment]
@unbit I can find no release for 2.1. The latest version is `2.0.22`. The problem still exists in `2.0.21`

```bash
/bin/uwsgi --ini bin/uwsgi_config.ini
[uWSGI] getting INI configuration from bin/uwsgi_config.ini
[strict-mode] unknown config directive: max-requests-delta
```

**Comment by pavanvarma08** [comment]
the problem still exists on 2.0.26 version (current latest version)

```shell
(venv) ➜  demo git:(master) ✗ pip freeze | grep uWSGI
uWSGI==2.0.26
(venv) ➜  demo git:(master) ✗ uwsgi --ini uwsgi/uwsgi.ini
[uWSGI] getting INI configuration from uwsgi/uwsgi.ini
[strict-mode] unknown config directive: max-requests-delta
```

**Comment by mroczek123** [comment]
uWSGI 2.0.28
`uwsgi: unrecognized option '--max-requests-delta'`
I can find this setting in docs https://uwsgi-docs.readthedocs.io/en/latest/Options.html#max-requests-delta

But there is no info in docs in which version or when this setting is available
