### ISSUE TITLE
Weirdy reply timings in log

### ISSUE THREAD

**Issue by AMDmi3** [unbit/uwsgi#1489]
FreeBSD 11.0 amd64, uwsgi 2.0.14.

Sometimes there are weird timings in the log with signs of integer overflows:

```[pid: 813|app: 0|req: 1137/1137] X.X.X.X () {38 vars in 550 bytes} [Wed Mar  1 15:32:48 2017] GET /metapackage/adminer-skins-pilot/versions => generated 9411 bytes in 18446744073709524 msecs (HTTP/1.1 200) 2 headers in 81 bytes (2 switches on core 0)```

Most other log entries are normal though.

**Comment by unbit** [comment]
I have added a check for invalid timings, is it a virtualized system ? It is not so common to have a clock skew (even at microseconds resolution)

**Comment by AMDmi3** [comment]
Yes it is, running under KVM. Thank you!
