### ISSUE TITLE
maintenance/bugfix release?

### ISSUE THREAD

**Issue by sixninetynine** [unbit/uwsgi#1500]
Hi!

Would it be possible to release a bugfix version (2.0.14.1) to pypi? Specifically would love to see #1494 so we can start migrating our apps to py3 (we depend on python's TimedRotatingFileHandler)

Thanks so much!

**Comment by unbit** [comment]
2.0.15 has been scheduled 20170330: https://github.com/unbit/uwsgi-docs/blob/master/Changelog-2.0.15.rst

**Comment by sixninetynine** [comment]
awesome thanks!!
