### ISSUE TITLE
PHP plugin gives “php_session_register_module: symbol not found” on Alpine Linux

### ISSUE THREAD

**Issue by WST** [unbit/uwsgi#1528]
I’m trying to compile PHP plugin on the current Alpine Linux, as it’s not available in the repositories.
PHP is: 7.1.4
uWSGI is: 2.0.14
I’ve tried to build PHP plugin from 2.0.14, 2.0.15 and current development version. All of them compile successfully and give the same error when trying to run the server:

`!!! UNABLE to load uWSGI plugin: Error relocating /usr/lib/uwsgi/php_plugin.so: php_session_register_module: symbol not found !!!`

Is it a bug, or I am doing something in a wrong way?

**Comment by xrmx** [comment]
You are missing some plugins from your php build:
https://github.com/unbit/uwsgi/issues/654
