### ISSUE TITLE
Internal Server Error with Django and crispy_forms

### ISSUE THREAD

**Issue by saatomic** [unbit/uwsgi#1530]
I've been successfully using uwsgi with my Django project for a while, but I've recently added [crispy forms](http://django-crispy-forms.readthedocs.io/en/latest/) resulting in quite some issues.

Django-1.11.1, uwsgi 2.0.15, nginx 1.10.3-1, django-crispy-forms 1.6.1 on Debian Jessie.
I've also elaborate the issue on a [StackOverflow question](http://stackoverflow.com/questions/43884539/crispy-django-forms-results-in-internal-server-error-when-accessed-via-uwsgi), as I'm not sure if this is a bug of uwsgi or an issue of mine.

Once I remove `crispy_forms` from my `INSTALLED_APPS` in the django settings, the internal server error is gone.

If I run the project with Djangos `manage.py runserver`, it works perfectly fine.

I did try to run uwsgi as a Unix socket instead of a port, which results in the same problems.

Did I miss some uWSGI configuration, or is this a bug of uWSGI?

**Comment by xrmx** [comment]
Look at the logs, what did break? this looks like an issue with your application though.

**Comment by saatomic** [comment]
I'm looking at the logs, which aren't very informative:

```
--- no python application found, check your startup logs for errors ---                                                               
[pid: 22173|app: -1|req: -1/1] 10.0.2.15 () {48 vars in 823 bytes} [Wed May 10 07:35:28 2017] GET / => generated 21 bytes in 0 msecs (
HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
```

After some research, I'm guessing this is indeed an issue with my uwsgi configuration. But I have no idea why/how.

The uwsgi configuration for the django application:
```
[uwsgi]
chdir           = /<dir>/<django_project>
module          = <django_project>.wsgi
home            = /<dir>/<virtualenv>
master          = true
processes       = 10
socket          = /<dir>/<socket>.sock
vacuum          = true
uid             = 33 # www-data
```

I believe uWSGI is somehow unable to access/find the `django_crispy_forms` application. Any clue how I can fix that?

**Comment by xrmx** [comment]
Il 10/05/2017 11:11, SaAtomic ha scritto:
> I'm looking at the logs, which aren't very informative:
>
> |--- no python application found, check your startup logs for errors --- [pid:

How is this not informative? Reload the server and see the stacktrace

**Comment by saatomic** [comment]
> How is this not informative? Reload the server and see the stacktrace

Can you help me out there? I've restarted uWSGI numerous times, I'm a bit lost what stacktrace?

**Comment by xrmx** [comment]
You should see some python stacktrace in the logs because the django app is not loading for some reason.

**Comment by saatomic** [comment]
I've run `strace` for uWSGI and it states `write(2, "ImportError: No module named 'cr"..., 44ImportError: No module named 'crispy_forms'`.

What prerequisites does uWSGI have, to be able to access crispy_forms?

**Comment by saatomic** [comment]
This can be closed. Apparently the `home = <dir>` was the culprit, I've removed it and now it appears to be working fine.

**Comment by xrmx** [comment]
You possibly installed crispy outside the virtualenv?

**Comment by saatomic** [comment]
Correct.
