### ISSUE TITLE
uwsgi returns truncated html.

### ISSUE THREAD

**Issue by rivmar** [unbit/uwsgi#1542]
My configuration:
Ubuntu 16.04.2 LTS
Nginx version: 1.10.0-0ubuntu0.16.04.4
uWSGI 2.0.15 (64bit)
Python 3.5.2 
The problem is that I get truncated HTML on some pages. I think that the problem is in uWSGI because every time I get truncated page I find the same error in log:

> {address space usage: 162361344 bytes/154MB} {rss usage: 55721984 bytes/53MB} [pid: 1809|app: 0|req: 17/17] 79.164.161.118 () {56 vars in 1301 bytes} [Tue May 30 12:26:15 2017] GET /admin/shop/product_collection_to_pdf/ => generated 90168 bytes in 167 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 29)
epoll_ctl(): File exists [core/event.c line 655]
OSError: write error
epoll_ctl(): No such file or directory [core/event.c line 639]

My ini file:

> [uwsgi]
uid = www-data
gid = www-data
autorestart=true
async=31
enable-threads=True
thread=8
socket-timeout = 240
memory-report = true
max-requests = 1000
harakiri = 300
procname-prefix = broswil
buffer-size=32768
post-buffering = 8192
max-fd=262144
wsgi-file=/var/www/broswil/wsgi.py
module = project.wsgi
chdir = /var/www/broswil
master = true
processes = 1
socket = /run/uwsgi/broswil.sock
daemonize = /var/log/uwsgi/broswil.log

My uwsgi log:

> [uWSGI] getting INI configuration from broswil.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue May 30 12:17:53 2017] ***
compiled with version: 5.4.0 20160609 on 15 May 2017 16:22:00
os: Linux-4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017
nodename: broswil
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /etc/uwsgi/apps-enabled
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/broswil
your processes number limit is 3831
your memory page size is 4096 bytes
setrlimit(): Operation not permitted [core/uwsgi.c line 2664]
detected max file descriptor number: 1024
async cores set to 31 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /run/uwsgi/broswil.sock fd 3
Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x156e0b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 3048848 bytes (2977 KB) for 31 cores
*** Operational MODE: async ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x156e0b0 pid: 577 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 577)
spawned uWSGI worker 1 (pid: 1809, cores: 31)
*** DANGER *** async mode without coroutine/greenthread engine loaded !!!
{address space usage: 154013696 bytes/146MB} {rss usage: 46555136 bytes/44MB} [pid: 1809|app: 0|req: 1/1] 91.209.147.226 () {54 vars in 1048 bytes} [Tue May 30 12:18:32 2017] GET /stores/magazin_myzhskoy_odezhdyi_roberto_metro_schelkovskaja/ => generated 24554 bytes in 498 msecs (HTTP/1.1 200) 2 headers in 73 bytes (2 switches on core 30)
announcing my loyalty to the Emperor...
{address space usage: 155062272 bytes/147MB} {rss usage: 47693824 bytes/45MB} [pid: 1809|app: 0|req: 2/2] 79.164.161.118 () {56 vars in 1312 bytes} [Tue May 30 12:19:15 2017] GET /admin/shop/product_collection_to_pdf/ => generated 90168 bytes in 251 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 30)
{address space usage: 155324416 bytes/148MB} {rss usage: 47783936 bytes/45MB} [pid: 1809|app: 0|req: 3/3] 79.164.161.118 () {56 vars in 1276 bytes} [Tue May 30 12:19:20 2017] GET /admin/shop/clients/ => generated 47683 bytes in 111 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 30)
Tue May 30 12:19:23 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /admin/shop/clients_active/ (ip 79.164.161.118) !!!
Tue May 30 12:19:23 2017 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during GET /admin/shop/clients_active/ (79.164.161.118)
OSError: write error
{address space usage: 157933568 bytes/150MB} {rss usage: 50675712 bytes/48MB} [pid: 1809|app: 0|req: 4/4] 79.164.161.118 () {56 vars in 1272 bytes} [Tue May 30 12:19:21 2017] GET /admin/shop/clients_active/ => generated 0 bytes in 2117 msecs (HTTP/1.1 200) 2 headers in 0 bytes (2 switches on core 30)
epoll_ctl(): File exists [core/event.c line 655]
OSError: write error
epoll_ctl(): No such file or directory [core/event.c line 639]
{address space usage: 160481280 bytes/153MB} {rss usage: 53227520 bytes/50MB} [pid: 1809|app: 0|req: 5/5] 79.164.161.118 () {56 vars in 1272 bytes} [Tue May 30 12:19:23 2017] GET /admin/shop/clients_active/ => generated 621175 bytes in 1579 msecs (HTTP/1.1 200) 2 headers in 73 bytes (3 switches on core 29)

Thank you in advance.

**Comment by unbit** [comment]
Hi, async without a coroutine engine is not supported (and does not lead to any advantage). I think enabling ugreen or greenlet should solve it, but you should check gevent that is battle tested.

**Comment by rivmar** [comment]
Thanks a lot for fast reply.
I added ugreen=True to ini file and it helped.
