### ISSUE TITLE
ValueError: invalid literal for int() with base 10 in pip install uwsgi

### ISSUE THREAD

**Issue by pirDOL** [unbit/uwsgi#1546]
on my platform uname -a outputs:
2.6.32_1-15-0-0

there is a _1 after third version number, it seems that uwsgi/setup.py does not support this case. 

can this problem be fixed?

**Comment by xrmx** [comment]
Is this a custom built kernel right?

**Comment by pirDOL** [comment]
yes, it's a customized kernal, so minor version has a _1 suffix.
but 2.6.32 is a valid kernal version, k_minor 32 should be extracted

**Comment by xrmx** [comment]
Fixed in #1547

**Comment by xrmx** [comment]
I won't being able to backport to uwsgi-2.0 until next week.
