### ISSUE TITLE
issue with multiprocessing.Pool and uwsgi

### ISSUE THREAD

**Issue by pratheekms** [unbit/uwsgi#1552]
Hey all,

I have a CPU intensive process which takes about 8-10 minutes to run using multiprocessing.Pool

It works fine most of the times but occasionally the process just hangs in the middle while the parallel processing is happening. I dont see any error or traceback and thereafter uwsgi just freezes and I get 504 for all requests. The funny thing is that the first few requests get the response just fine and then the issue pops up. When I run the server via the python development server I do not see this issue so my guess is that I'm doing something wrong with uwsgi.

Here is my uwsgi.ini config
```
[uwsgi]
chdir=/home/pratheek/projects/platform_v2/platformV2
uid=pratheek
gid=pratheek
module=platformV2.wsgi:application
master=True
worKers=1
pidfile=/tmp/platfromv2.pid
vacuum=True
close-on-exec=True
memory-report=True
enable-threads=True
daemonize=/home/pratheek/workspace/platformv2.log
socket=/home/pratheek/workspace/platformv2.sock
chmod-socket=777
```
I have attached the log file as well. The last request has just freezed in the middle of processing.

[log.temp.txt](https://github.com/unbit/uwsgi/files/1070669/log.temp.txt)

**Comment by xrmx** [comment]
Are you using multiprocessing on a uwsgi worker? If you have cpu intensive work it may be better to use a mule, the spooler or a external queue like celery.

**Comment by pratheekms** [comment]
Yes Celery would be a great idea and more suitable for something like this. It would be a major overhaul and something that I am currently contemplating. What I do not understand is that is there something in uwsgi which prevents me from doing a CPU intensive multiprocessing task?

**Comment by xrmx** [comment]
The problem is not with the cpu intensive work (which is not a great idea to do on workers), the problem is forking workers like you do with multiprocessing, i expect you end up with broken workers.

**Comment by pratheekms** [comment]
I have close-on-exec set to True and I make sure that I wait and close all processes before moving out of the context. You are saying despite that I can end up with broken workers :| 

I guess I'll move my system to uwsgi spoolers/celery and close the issue. If this is a known a behavior, better to put a note in the docs. [This](http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html) page says forking the worker is safe as long as you set close-on-exec, which can be misleading.

**Comment by xrmx** [comment]
Yeah, but the name of the options makes me think it'll set the bit to close them on execve and not on fork. Haven't looked at the code though. Anyway let me state again that calling multiprocessing inside a worker is a bad pattern.
