### ISSUE TITLE
Whats the max request parameters length?

### ISSUE THREAD

**Issue by kakulukia** [unbit/uwsgi#1573]
Hi,

im currently stuck as to how i might solve my invalid request error.
uWSGI is not helping me much and only logs this line:

    invalid uwsgi request (current strsize: 41266). skip.

Since similar requests do work, i believe that in this very example the request parameters are simply exceeding the limits of uWSGI. Can somebody confirm this and / or state the maximum length of a GET request URI including parameters?
BTW: buffer-size ist set to 1000000 which is higher than the problematic request size

**Comment by xrmx** [comment]
Looks like you are passing http (or something else) when uwsgi expects the uwsgi protocol.

**Comment by kakulukia** [comment]
That is very unlikely, because like i said the with smaller content those requests DO work. Just it seems that when some threshold is met it breaks.
The feature in question is a copy functionality of our CMS which is supposed to copy elements from one language to another. It only breaks with one large page.

**Comment by unbit** [comment]
For uwsgi protocol you can tune the maximum value to 65535 (it is a 16bit number)

**Comment by kakulukia** [comment]
so my value is ignored because its too high?
Okay that explains why its still not working even tho my buffer size should be high enough. I will let the CMS guys know to not build any more of those large pages. :)

**Comment by unbit** [comment]
Note that the buffer is only meaningful for http headers. The body response is not relevant to them.

**Comment by kakulukia** [comment]
That copy plugin is using GET parameters which results in a 41k URI .. so this should be covered by the buffer size, right?
I dont blame you for not accepting longer URIs, because lets face it: this plugin is coded with bad karma .. i just wanted to know, why uwsgi bails out on this request :)

**Comment by unbit** [comment]
Yep, supposing you set the limit of the request buffer to 40k, it means that all of the headers must be serialized into 40k :)

**Comment by kakulukia** [comment]
one last question: with the page URI still being under the 64k limit and nginx with a buffer of 50k (large_client_header_buffers 4 50k) accepting the request (will otherwise result in 414 (Request-URI Too Large)) uwsgi should still process the 41k request. Any clue of why it bails out before the 64k limit?

**Comment by unbit** [comment]
Becase the uri is only a field of the request, very probably there are other additional data (like cookies) that increases the whole size.

**Comment by kakulukia** [comment]
nope, the total request header is 656 chars .. but never mind, im not blaming uwsgi
at max for not being more specific in the error message than _invalid uwsgi request_

**Comment by ace-han** [comment]
@kakulukia  How do you deal with the situation you were referring to at last? I've come to the same issue(I might need to change to `http-socket` instead of `socket` style)...
> one last question: with the page URI still being under the 64k limit and nginx with a buffer of 50k (large_client_header_buffers 4 50k) accepting the request (will otherwise result in 414 (Request-URI Too Large)) uwsgi should still process the 41k request. Any clue of why it bails out before the 64k limit

**Comment by ace-han** [comment]
@kakulukia, @unbit  My point is 

why uwsgi fail to process the request before its size hits the configured `buffer-size=65535`, .

I believe the log gives a msg about the request line size

```shell
invalid uwsgi request (current strsize: 41266). skip.
```

which 41266 is not reaching 65535

Is the `buffer-size` means a total that all request fields sum up? 

Which means some of the fields from http://productforums.google.com/d/topic/chrome/_MQkdqZBlPI

**Comment by kakulukia** [comment]
i cant answer that :(

**Comment by unbit** [comment]
@ace-han because strsize refers to the currently processing string not the already processed buffer

**Comment by unbit** [comment]
@ace-han you can move to plain http (http-socket), but take into account that your proxy could limit it too. I would strongly advice against having such a huge header.

**Comment by ace-han** [comment]
@unbit I've tried http(http-socket) with nginx proxy_pass, unfortunately, for those bigger requests still failures... 
(I am sure that other smaller requests are working in the same wsgi.ini with the same nginx config).

| proto | result | buffer-size | uwsgi log |
| ---- |  ---- |  ---- | ---- |
| http | failure | 65535 | N/A |
| http | failure | 655350 | N/A |
| http-socket | failure | 65535 | invalid HTTP request size (max 65535)...skip |
| http-socket | failure | 655350 | invalid HTTP request size (max 65535)...skip |

**Comment by unbit** [comment]
@ace-han you need to use master (2.1) branch to have bigger buffer_size in http-socket. (in 2.0 that field is a uint16 so on bigger values it will overflow)
