### ISSUE TITLE
Static files serving does not respect the If-Range header

### ISSUE THREAD

**Issue by GaretJax** [unbit/uwsgi#1587]
uWSGI unconditionally returns a Partial Response for Range requests, even if the If-Range does not match the condition (with `--honour-range`).

References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range
- https://tools.ietf.org/html/rfc7233#section-3.2

**Comment by unbit** [comment]
Hi, thanks for reporting, you may want to check this part of the code:  

https://github.com/unbit/uwsgi/blob/master/core/protocol.c#L231

and eventually make a pull request.

Thanks again

**Comment by GaretJax** [comment]
Thank *you* for your efforts.

I'd happily do a PR, but sadly I'm not fluent enough in C. I'll happily trade it for a python-based PR though. 😄

**Comment by unbit** [comment]
No problem, i will try to address it asap

**Comment by GaretJax** [comment]
That would be great, thank you. However, this isn't a big issue for us, I just though to write it down so other people can find it and not spend too much time debugging.

**Comment by GaretJax** [comment]
Yay, thanks @funkybob !
