### ISSUE TITLE
installing the library fails

### ISSUE THREAD

**Issue by fabianfrz** [unbit/uwsgi#1591]
The installation of uwsgi fails on Windows:
```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\Temp\pip-build-knoowy4t\uwsgi\setup.py", line 3, in <module>
	import uwsgiconfig as uc
  File "...\Temp\pip-build-knoowy4t\uwsgi\uwsgiconfig.py", line 8, in <module>
	uwsgi_os = os.uname()[0]
AttributeError: module 'os' has no attribute 'uname'
```

**Comment by unbit** [comment]
There is no support for plain windows. Only cygwin.

**Comment by fabianfrz** [comment]
Can you mention that in the readme file then?

**Comment by unbit** [comment]
http://uwsgi-docs.readthedocs.io/en/latest/SupportedPlatforms.html

feel free to make a pull request to the uwsgi-docs repository if you want to make some modification

**Comment by white-gecko** [comment]
Same as this one: https://github.com/unbit/uwsgi/issues/1930
