### ISSUE TITLE
[uWSGI+nginx+AWS]uWSGI is running in multiple interpreter mode

### ISSUE THREAD

**Issue by stealingchen** [unbit/uwsgi#1606]
I set up on the AWS server Django + Nginx + Uwgsi,  502 BadGateway when visit http://54.254.199.36/facerec/index,What's wrong?

This is my uwsgi.log  error:

*** Starting uWSGI 2.0.15 (64bit) on [Thu Aug 10 10:33:56 2017] ***
compiled with version: 5.4.0 20160609 on 10 August 2017 05:01:18
os: Linux-4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017
nodename: ip-172-30-0-174
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/ubuntu/test3
writing pidfile to uwsgi.pid
detected binary path: /home/ubuntu/anaconda2/bin/uwsgi
chdir() to /home/ubuntu/test3
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8099 fd 3

Python version: 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Python main interpreter initialized at 0xd116d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 415280 bytes (405 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd116d0 pid: 24017 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24017)
spawned uWSGI worker 1 (pid: 24019, cores: 2)
spawned uWSGI worker 2 (pid: 24020, cores: 2)
spawned uWSGI worker 3 (pid: 24021, cores: 2)
spawned uWSGI worker 4 (pid: 24022, cores: 2)

Configure:
This is my Nginx configure:

server {
        #listen 80 default_server;
        listen 172.30.0.174:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
                include uwsgi_params;
                uwsgi_pass 172.30.0.174:8099;
        }

        location /static {
                alias /var/www/test3/static/;
        }
}

server {
        #listen 80 default_server;

        server_name 54.254.199.36;
        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

#       server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
                include uwsgi_params;
                uwsgi_pass 127.0.0.1:8099;
        }

        location /static {
                alias /var/www/test3/static/;
        }
}

This is my uWSGI.ini configure:

[uwsgi]
socket=127.0.0.1:8099
#http=172.30.0.174:8099
chdir=/home/ubuntu/test3
wsgi-file=test3/wsgi.py
processes=4
threads=2
master=True
pidfile=uwsgi.pid
daemonize=uswgi.log

**Comment by unbit** [comment]
Your pasted configuration has been clobbered by markdown so i am not sure to correctly follow it. By the way i am noticing that you use two different addresses 127.0.0.1:8099 and 172.30.0.174:8099 with two different protocols. Could it be the problem ?

**Comment by stealingchen** [comment]
Thank you very much,I am very depressed until you reply to me.now Now I have commented one server,Look at the following configuration code.
server {
        #listen 80 default_server;
        listen 80;
        server_name api.sg36.com;
        access_log /home/ubuntu/access.log;
        error_log /home/ubuntu/error.log;
        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

#       server_name _;

        location / {
#               # First attempt to serve request as file, then
#               # as directory, then fall back to displaying a 404.
#               # try_files $uri $uri/ =404;
                include uwsgi_params;
                uwsgi_pass 127.0.0.1:8099;
        }

        location /static {
                alias /var/www/test3/static/;
        }

	}
This is my uWSGI.ini configure:

[uwsgi]
socket=127.0.0.1:8099
#http=172.30.0.174:8099
chdir=/home/ubuntu/test3
wsgi-file=test3/wsgi.py
processes=4
threads=2
master=True
pidfile=uwsgi.pid
daemonize=uswgi.log

Fortunately
error.log updated

2017/08/15 06:44:15 [error] 12301#12301: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com", referrer: "http://api.sg36.com/facerec/index"
2017/08/15 06:44:16 [error] 12301#12301: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /facerec/index HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com"
2017/08/15 06:44:16 [error] 12301#12301: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com", referrer: "http://api.sg36.com/facerec/index"
2017/08/15 06:44:23 [error] 12301#12301: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /facerec/index HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com"
2017/08/15 06:44:25 [error] 12301#12301: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com", referrer: "http://api.sg36.com/facerec/index"
2017/08/15 06:44:50 [error] 12309#12309: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /facerec/index HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com"
2017/08/15 06:44:51 [error] 12309#12309: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 171.221.147.249, server: api.sg36.com, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8099", host: "api.sg36.com", referrer: "http://api.sg36.com/facerec/index"

access.log

171.221.147.249 - - [15/Aug/2017:06:44:15 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "http://api.sg36.com/facerec/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:16 +0000] "GET /facerec/index HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:16 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "http://api.sg36.com/facerec/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:23 +0000] "GET /facerec/index HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:25 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "http://api.sg36.com/facerec/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:50 +0000] "GET /facerec/index HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
171.221.147.249 - - [15/Aug/2017:06:44:51 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "http://api.sg36.com/facerec/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"

uwsgi.log is not updated

I am a novice, can you help me?
Looking forward to your reply.

**Comment by stealingchen** [comment]
you can visit this link http://api.sg36.com/facerec/index,502 bad gateway

**Comment by stealingchen** [comment]
Has been resolved, now can visit the site, but there is another problem.Click the button to displayServer Error (500)

![Uploading 1111server.png…]()
![1111index](https://user-images.githubusercontent.com/20882610/29306305-8bd4e552-81cf-11e7-9461-c9321a39d11a.png)

**Comment by stealingchen** [comment]
![Uploading 1111server.png…]()

**Comment by stealingchen** [comment]
![Uploading 1111server.png…]()
![Uploading 1111server.png…]()

**Comment by xrmx** [comment]
@stealingchen can we close this?

**Comment by stealingchen** [comment]
yes,thank you.you can

**Comment by Shaikhfahad2001** [comment]
i got the same error what should i do can someone help me pls
