### ISSUE TITLE
tcp socket client and uwsgi

### ISSUE THREAD

**Issue by ogta** [unbit/uwsgi#1618]
How can  **_tcp socket client_** in python talk with  uwsgi ?

my architectures are

tcp socket client -> nginx -> uwsgi
tcp socket client  -> uwsgi

**Comment by xrmx** [comment]
Do you want to talk with uwsgi or some apps behind it? Also why not http?

**Comment by ogta** [comment]
@xrmx  Tcp is necessity for architectures. i want to talk with uwsgi application and this uwsgi application talk with other applications

**Comment by unbit** [comment]
Hi, the protocol is described here: http://uwsgi-docs.readthedocs.io/en/latest/Protocol.html

**Comment by ogta** [comment]
@unbit @xrmx 

this is my test script and there is no request in uwsgi console.

https://gist.github.com/ogta/aae2bcfda27834b4a9166cfb23f07a41

but return b'' 

Am i missing something ?

**Comment by unbit** [comment]
@ogta i do not seen any protocol implementation in your code. You are sending a random byte

**Comment by ogta** [comment]
@unbit i added socket.IPPROTO_TCP in my client but result is same. Can you explain your solution?

**Comment by unbit** [comment]
@ogta sorry i fear i do not understand what you are trying to accomplish. If you want to speak directly via TCP to a uWSGI server (or a http server or whatever you want) you need to send and receive particular sequence of data (the protocol). You cannot send them random data.

For http you send something like
```
GET / HTTP/1.0\r\n
\r\n
```

for uwsgi you send a serialized dictionary encoded like shown in the previous link
