### ISSUE TITLE
uwsgi permission problem

### ISSUE THREAD

**Issue by AnushaY1** [unbit/uwsgi#1624]
CentOS release 6.5
1. testcon.conf
server {
     listen       80 default_server;
     location / {
         include       /etc/nginx/uwsgi_params;
         uwsgi_pass    unix:/var/www/testapp/azureapi.sock;
        }

}
2.  config.ini

 [uwsgi]
socket=/var/www/testapp/azureapi.sock
chdir = /var/www/testapp
master=true
callable = app
wsgi-file = /var/www/testapp/test.py
plugin = python

[uwsgi]
#uid = uwsgi
gid = uwsgi
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
chmod-socket = 660
#emperor-tyrant = true
cap = setgid,setuid

commenting uid and emperor-tyrant then only my application working otherwise it is nt working.
can anyone explain reason behind that.

thanks

**Comment by funkybob** [comment]
What is the owner/group of the vassal ini file itself?

**Comment by AnushaY1** [comment]
owner/group ---> uwsgi/nginx

**Comment by funkybob** [comment]
And what user/group is nginx running as?
Also what owner/group are you seeing on the created socket file?

**Comment by AnushaY1** [comment]
nginx running  as nginx user
socket file - uwsgi/nginx

**Comment by funkybob** [comment]
Given the emperor isn't opening a socket, not a lot of sense putting the chmod-socket there instead of in the config.ini.

Also, _where_ are you seeing a permissions error? 
What is reporting it, when trying to access what?
I'm _guessing_ it's nginx trying to access the socket file?

**Comment by AnushaY1** [comment]
issue is running uWSGI as uwsgi(uid =uwsgi) , socket is not created[centos 6.5].

error log
bind(): Permission denied [core/socket.c line 230]
Mon Sep  4 13:42:36 2017 - [emperor] curse the uwsgi instance azurewsgi.ini (pid: 1791)
Mon Sep  4 13:42:36 2017 - [emperor] removed uwsgi instance azurewsgi.ini

nginx error.log
2017/09/04 14:30:12 [crit] 1781#0: *3 connect() to unix:/var/www/azure/azureapi.sock failed (2: No such file or directory) while connecting to upstream, client: 10.129.140.119, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/var/www/azure/azureapi.sock:"

config.ini
[uwsgi]
socket = /var/www/azure/azureapi.sock
chdir = /var/www/azure
master=true
callable = app
plugin    = python
wsgi-file = /var/www/azure/azure_api.py
process   = 5
threads = 2
uid = uwsgi
gid = nginx


/etc/uwsgi.ini
[uwsgi]
#uid = uwsgi
gid = nginx
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
chmod-socket = 660
#emperor-tyrant = true
cap = setgid,setuid

**Comment by AnushaY1** [comment]
i am facing below error
nginx error log
2017/09/04 14:43:31 [error] 2528#0: *2 connect() to unix:/var/www/azure/azureapi.sock failed (111: Connection refused) while connecting to upstream, client: 10.129.140.119, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/var/www/azure/azureapi.sock:", host: "10.129.135.43", referrer:
application directory 
drwxr-xr-x.  2 uwsgi nginx 4.0K Sep  4 14:43 azure 

socket file created 
 srwxrwxrwx  1 uwsgi nginx    0 Sep  4 14:43 azureapi.sock

config.ini
[uwsgi]
socket = /var/www/azure/azureapi.sock
chdir = /var/www/azure
master=true
callable = app
plugin    = python
wsgi-file = /var/www/azure/azure_api.py
process   = 5
threads = 2
uid = uwsgi
gid = nginx

/etc/uwsgi.ini

[uwsgi]
uid = uwsgi
gid = nginx
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
chmod-socket = 660
emperor-tyrant = true
cap = setgid,setuid

testcon.conf
server {
listen 80 default_server;
location / {
include /etc/nginx/uwsgi_params;
uwsgi_pass unix:/var/www/azure/azureapi.sock;
}
}

**Comment by funkybob** [comment]
In that case what are the permissions for each dir /var/www/azure/ ?

Are they ok to let your nginx process traverse them?

Also,having "chmod-socket" in your emperor ini file is still pointless.

**Comment by AnushaY1** [comment]
--> /var/www/azure/

drwxr-xr-x. 8 root  root  4.0K Sep  4 14:49 ..
-rw-r--r--  1 uwsgi nginx  21K Sep  4 15:42 azure_api.py
srwxrwxrwx  1 root  nginx    0 Sep  6 13:12 azureapi.sock
drwxr-xr-x. 2 uwsgi nginx 4.0K Sep  6 13:12 .

azureapi.sock socket file is created root user only. if i given uwsgi user ,the socket file is not created. 

config.ini
[uwsgi]
socket = /var/www/azure/azureapi.sock
chdir = /var/www/azure
master=true
callable = app
plugin = python
wsgi-file = /var/www/azure/azure_api.py
process = 5
threads = 2
uid = uwsgi
gid = nginx


removed chmod-socket in ini file
