### ISSUE TITLE
Milliseconds in json log-encoder

### ISSUE THREAD

**Issue by moisizz** [unbit/uwsgi#1631]
I'm trying to send uwsgi-logs to LogFaces, so i use something like this in config:

`log-encoder = json:uwsgiLogger {"a": "app name", "h": "hostname", "g": "uwsgi-logger", "t": ${unix}, "p": "INFO", "m": "${msg}"}`

LogFaces expects timestamp in milliseconds. But according to json encoder documentation there is only ${unix} for seconds and ${micros} for microseconds. Is it possible to send milliseconds?

**Comment by unbit** [comment]
Implemented in #1631 as "${millis}".

@xrmx safe for backport

**Comment by moisizz** [comment]
Thank you very much

**Comment by funkybob** [comment]
Is this issue considered closed, now?
