### ISSUE TITLE
Apache httpd project looking into doing its own implementation

### ISSUE THREAD

**Issue by jimjag** [unbit/uwsgi#1636]
Just a FYI that the Apache httpd project is looking to create its own uWSGI module for the mod_proxy system (https://lists.apache.org/thread.html/df494432296a598b2213e76cb721e153c9fb36947b5fe9a1a9ac892c@%3Cdev.httpd.apache.org%3E). 

Cheers!

**Comment by unbit** [comment]
Hi Jim, thanks for the info ! I noted that there are concerns about the GPL2. As this module has never been part of our commercial distribution i think we can move it to a more permissive one and eventually remove it from future releases. Let me know what you tihink it is better.

**Comment by jimjag** [comment]
Wow! If it would be possible/feasible to "donate" the module to the ASF under the ALv2, that would be incredible. I would be most willing to help in any way.

**Comment by unbit** [comment]
@jimjam, absolutely this is not a problem (well it would be an honour indeed ;). Is there any procedure to follow or just re-licensing the code and publicly announcing the 'donation'  is enough ?

**Comment by jimjag** [comment]
For completeness, for an actual "formal" donation, there is also a small form (a software grant) that would be filed. That also helps w/ the reach of whatever marketing/PR you may want to do regarding the donation. It can also be done simply by, once relicensed, we note on this Issue that you guys are cool w/ the ASF copying the module, as permitted by the ALv2. Even though such permission is never really needed, the ASF has a long standing policy of only using code that the original copyright owners are OK with us using, even if the license would allow us to reuse it no matter what :)

**Comment by unbit** [comment]
@jimjag the module has been relicensed

**Comment by jimjag** [comment]
That is super great news! Is it OK if I push a copy of the module to the official HTTPD repo, with all attributions intact?

**Comment by unbit** [comment]
@jimjag  yes, for sure

**Comment by funkybob** [comment]
With the relicencing complete, should this ticket now be closed?

**Comment by jimjag** [comment]
Fantastic! Thx! I will start the xfer of the source code to the ASF. Cheers!

**Comment by minfrin** [comment]
Backported to httpd v2.4.30.
