### ISSUE TITLE
BUG Report: spool decorator does not remove spooler folder when done

### ISSUE THREAD

**Issue by mbande** [unbit/uwsgi#1643]
i have a @spool decorated function, calling it with:
```my_func.spool(task_id=123, priority=b'456')```
as i used priority, a folder is created for the task, but when the task finishes, the folder is not removed.
even by returning SPOOL_OK

**Comment by xrmx** [comment]
It does not remove it because the spooler directory should be always there, if it's not there created only for convenience.

**Comment by mbande** [comment]
@xrmx i mean the folder created for task, which is named after priority parameter, not the spooler directory itself!

**Comment by xrmx** [comment]
Yeah, but i don't see any promise of cleaning up the created directories in the documentation. Wouldn't trying to remove it be racy but also prone to failure if we have other spoolfiles inside?

**Comment by mbande** [comment]
docs stated that spool files will be removed, I think that the folder should also be removed, as they are created automatically by spooler, and leaving them there will make the directory messy.
assuming that there should not be 2 tasks with the same priority, and the subdirectory is locked as spoolfile itself, no race condition will happen, right?

**Comment by xrmx** [comment]
Spool files are not directories :) How can the code assumes that your use case is the only possible one?
