### ISSUE TITLE
Could we get a better logformat for dates?

### ISSUE THREAD

**Issue by mark0978** [unbit/uwsgi#1669]
YYYY-MM-DD HH:MM:SS.DDDDDD would be nice, easy to sort, easy to pattern match, easy to feed into something like logstash.  The current versions available in the docs aren't very nice for non-human readers.

**Comment by gowhari** [comment]
There is `log-date = %%Y-%%m-%%d %%H:%%M:%%S` and it works for non http request, but for http request `logformat` uses one of format functions.

I think it will be nice if `logformat` supports in addition to `%(ctime)` and `%(ltime)` a new function e.g. `%(ftime)` of `%(date)` that formats date with the string defined in `log-date`

**Comment by mark0978** [comment]
I don't think those are documented anywhere (maybe)

**Comment by est** [comment]
It was added back in 2013 

https://github.com/unbit/uwsgi/commit/d320075ab05a776c5d52de1afd165b394939f128

but later the `uwsgi_lf_ftime` was deleted for some reason.

**Comment by est** [comment]
Hey guys I think I found a solution:


    logformat = %(ftime)  %(method) %(var.REQUEST_SCHEME)://%(host)%(uri) %(proto) %(status) 
    logformat-strftime = true
    logdate = %%m-%%d %%H:%%M:%%S

Annnnd it's done.


Explanation:

https://github.com/unbit/uwsgi/blob/ce787a6e3210333a71f5074e5775885428e8b73c/core/logging.c#L1184


```
static ssize_t uwsgi_lf_ftime(struct wsgi_request * wsgi_req, char **buf) {
	if (!uwsgi.logformat_strftime || !uwsgi.log_strftime) {
		return uwsgi_lf_ltime(wsgi_req, buf);
	}
	*buf = uwsgi_malloc(64);
	time_t now = wsgi_req->start_of_request / 1000000;
	size_t ret = strftime(*buf, 64, uwsgi.log_strftime, localtime(&now));
	if (ret == 0) {
		*buf[0] = 0;
		return 0;
	}
	return ret;
}
```
We have ensure both `uwsgi.logformat_strftime`  and `uwsgi.log_strftime` exists, these two are defined in ini  as `logformat-strftime`  and `logdate`. I think I'll add a PR to the docs.
