### ISSUE TITLE
Does uwsgi support python's sanic?

### ISSUE THREAD

**Issue by x0v** [unbit/uwsgi#1671]
I was reading uwsgi docs. It clearly demonstrates the support for deploying flask/Django application.
I was trying to deploy my [sanic](https://github.com/channelcat/sanic) application with uwsgi but didn't succeded. 

after I saw [this issue](https://github.com/channelcat/sanic/issues/250) I want to clarify if uwsgi supports deploying sanic application or not?

**Comment by unbit** [comment]
Currently you can try to run it via the aiohttp worker adapter described here: https://github.com/unbit/uwsgi-docs/blob/master/WorkerOverride.rst

but we are investigating a more advanced asyncio support (independent by the WSGI standard)

**Comment by x0v** [comment]
ok @unbit I'll try. thanks
