### ISSUE TITLE
tcp_wrappers dependency

### ISSUE THREAD

**Issue by thekad** [unbit/uwsgi#1689]
Hi,

I am the fedora maintainer for uwsgi, recently there's been talk about deprecating the 20yo tcp_wrappers package (background: https://fedoraproject.org/wiki/Changes/Deprecate_TCP_wrappers) and I got a bugzilla assigned: https://bugzilla.redhat.com/show_bug.cgi?id=1518795 I can't see a clear cut replacement for `hosts_ctl` used in `plugins/router_access/router_access.c`
I could:
* add the resources expected from `tcpd.h` to `uwsgi.h` (I could probably do this on my own)
* change router_access to not use `hosts_ctl` and use... something else

Thoughts?

**Comment by xrmx** [comment]
An alternative would be to not build that plugin

**Comment by thekad** [comment]
You are not wrong, I was looking for a way to keep offering that plugin and not obsolete it, but if there is no other option...

**Comment by thekad** [comment]
Will deprecate that plugin on fedora 28 :man_shrugging:
