### ISSUE TITLE
[Django views.py]No http request, how to preload data in django as the web opens

### ISSUE THREAD

**Issue by stealingchen** [unbit/uwsgi#1701]
No http request, how to preload data in django as the web opens，somebody can help me？thank you！

from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse
import os,base64
from django.views.decorators.csrf import csrf_exempt
from PIL import Image
from lstmcrf_model.source.transfer_old import transform
from lstmcrf_model.main_entity import main
# Create your views here.
def index(request):
    return render(request,'lstmcrf/index.html')

**Comment by xrmx** [comment]
I'm not sure i've understand what the issue, also no need to paste random code.
