### ISSUE TITLE
Issue with uWSGI HTTPS configuration

### ISSUE THREAD

**Issue by asimmehmood201** [unbit/uwsgi#1724]
Hello, 

I am using the following config for uWSGI

_[uwsgi]
master = true
module = test:app
shared-socket = :443

http = 0.0.0.0:8000
https = =0,server.crt,server.key
https = 0.0.0.0:443

logformat = %(ltime) %(method) %(uri) %(proto) %(status)_

But i am getting the following output in curl

_root@ubuntu:~/certs# curl https://test.com/ -v  --cacert cacert.crt -k
*   Trying 172.17.0.2...
* TCP_NODELAY set
* Connected to test.com (172.17.0.2) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: cacert.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):_

no reply from server after Client Hello. Port 443 is open but it seems that https part is not responding
also when I use the --https option it gives an error
uwsgi: unrecognized option '--https'
getopt_long() error

**Comment by xrmx** [comment]
Have you built uwsgi with ssl support?

**Comment by asimmehmood201** [comment]
i am using the environment provided by the vendor. seems ssl support was not added while building it.
