### ISSUE TITLE
uWSGI not serving python script calling a python script

### ISSUE THREAD

**Issue by milkpirate** [unbit/uwsgi#1750]
I am running script called `Sherlock_Wrapper.py` which contains some flasks and is processing the arguments given in the URL via GET, that runs another script called `Sherlock_RolesWrapper.py` with that arguments and returns the output to uWSGI. Or it is supposed to.

When the flask route directly returns a string it is working fine but having another layer (the `Sherlock_RolesWrapper.py` script) seems to crash uWSGI.

The communication between `Sherlock_Wrapper.py` and `Sherlock_RolesWrapper.py` works via `subprocess.check_output(...)`.

First line seems interesting because `--page` is an argument to the `Sherlock_RolesWrapper.py` script.

	/usr/local/bin/uwsgi: unrecognized option '--page'
	getopt_long() error
	[2018-02-22 10:49:24,377] ERROR in app: Exception on /sherlockRoles.json [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
		return cors_after_request(app.make_response(f(*args, **kwargs)))
	  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "./Sherlock_Wrapper.py", line 122, in processRoleRequest
		result = subprocess.check_output(cmd)
	  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
		raise CalledProcessError(retcode, cmd, output=output)
	CalledProcessError: Command '['/usr/local/bin/uwsgi', './Sherlock_RolesWrapper.py', '--page', '1']' returned non-zero exit status 1
	[pid: 44|app: 0|req: 4/3] 172.17.0.1 () {42 vars in 967 bytes} [Thu Feb 22 10:49:24 2018] GET /sherlockRoles.json?cities=Munich&levelUpper=7&levelLower=13&pageSize=10&pageNumber=1&_=1519296564224 => generated 291 bytes in 89 msecs (HTTP/1.1 500) 4 headers in 145 bytes (1 switches on core 1)
	Thu Feb 22 10:49:27 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
	Thu Feb 22 10:49:27 2018 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /autoCompletion.js?param=skill (172.17.0.1)
	IOError: write error
	[pid: 44|app: 0|req: 4/4] 172.17.0.1 () {40 vars in 698 bytes} [Thu Feb 22 10:49:23 2018] GET /autoCompletion.js?param=skill => generated 0 bytes in 4239 msecs (HTTP/1.1 200) 4 headers in 0 bytes (0 switches on core 0)

Am I missing something? Could you please have a look at that issue?

**Comment by xrmx** [comment]
You are confusing uwsgi with python

**Comment by milkpirate** [comment]
No, I am not!

The above is the excerpt of the log file `/var/log/uwsgi/%n.log` corresponding to the following `sherlock_uwsgi.ini`:

	[uwsgi]
	#application's base folder
	base = /var/backend/
	chdir = %(base)

	#python module to import
	application = Sherlock_Wrapper
	module = %(application)

	#socket file's location
	socket = /var/backend/%n.sock

	#permissions for the socket file
	chmod-socket    = 666

	#the variable that holds a flask application inside the module imported at line #6
	callable = application

	#location of log files
	logto = /var/log/uwsgi/%n.log

	# run as non-privileged www-data
	uid = 33
	gid = 33

	# run threaded
	threads = 2

**Comment by xrmx** [comment]
See this error, you are really using uwsgi as interpreter for a script passing scripts parameters to uwsgi:

```
CalledProcessError: Command '['/usr/local/bin/uwsgi', './Sherlock_RolesWrapper.py', '--page', '1']' returned non-zero exit status 1
```

You really don't want to do that.

**Comment by milkpirate** [comment]
Well yes. I see the problem. But this is nothing under my control. I am wondering too why uwsgi does that.

Simplified the `Sherlock_Wrapper.py` looks like this:

	#!/usr/bin/env python
	# -*- coding: utf-8 -*-

	import subprocess

	from flask			import Flask, Response, request, jsonify
	from flask_cors		import CORS, cross_origin

	application = Flask(__name__)
	cors = CORS(application)

	serverRoleUrl = "/sherlockRoles.json"

	def main():
		application.run(port=8080)

		
		
		
	@cross_origin()
	@application.route("/dummyData.json", methods=['GET'])
	def wokingFlask():
		dummyData = {}
		dummyData["content"] = 123
		return Response(result, mimetype='application/json')

		
		
		
	@cross_origin()
	@application.route("/sherlockRoles.json", methods=['GET'])
	def notWorkingFlask():
		pageNumber = request.args.get("pageNumber")
		
		cmd = [
			sys.executable,
			os.path.join( os.path.dirname(__file__), "Sherlock_RolesWrapper.py"),
			'--page', pageNumber
		]
		
		result = subprocess.check_output(cmd)
		result = result.strip()
		
		return Response(result, mimetype='application/json')

		

	if __name__ == "__main__":
		main()

The `workingFlask` isnt calling another script an uwsgi translates and works fine. But when another python script gets called in order to generate the response (i.e. `notWorkingFlask`) the procedure results in a failure and an log entry like above.

**Comment by xrmx** [comment]
Your script assumes to be called under a python interpreter not under an application server like uwsgi.

**Comment by milkpirate** [comment]
Which script? `Sherlock_Wrapper.py` or `Sherlock_RolesWrapper.py`?

If `Sherlock_Wrapper.py` remove shebang to fix?
If `Sherlock_RolesWrapper.py` remove `sys.executable` in `cmd` list to fix?

**Comment by milkpirate** [comment]
@xrmx could you please clarify?
