### ISSUE TITLE
Please set up the uWSGI logo to appear as the favicon in readthedocs.

### ISSUE THREAD

**Issue by DanAtShenTech** [unbit/uwsgi#1755]
When I have multiple readthedocs tabs open side-by-side, I can't tell which tab is for which set of documentation.  [Here is an example of  a site that has done this](http://linuxmint-installation-guide.readthedocs.io/en/latest/).

**Comment by xrmx** [comment]
Documentation issues are tracked at unbit/uwsgi-docs

**Comment by DanAtShenTech** [comment]
Closing in favor of https://github.com/unbit/uwsgi-docs/issues/396
