### ISSUE TITLE
Nginx Running .py file as exe

### ISSUE THREAD

**Issue by PythonNubie** [unbit/uwsgi#1756]
Hello world, I have a python flask application that is doing something a little funny. when i type in the remoter server IP/run.py, and exe window pops up with the local host URL //127.0.0.1:5000 when i enter that into my remote server URL my run.py page loads. but with the wrong URL. How can i fix this? Thanks in advance.

**Comment by xrmx** [comment]
I'm not sure i understand what this is about.

**Comment by PythonNubie** [comment]
I wish I could post pictures, its hard to describe.
Open browser>type in server name/run.py
and executable downloads with the ip of 127.0.0.1:5000 and not the server.

**Comment by xrmx** [comment]
So you are saying that a file is downloaded? If so then your http server is handling the request instead of forwarding it to your python application.

**Comment by PythonNubie** [comment]
Right, how do I change it to where the run.py will load?

**Comment by xrmx** [comment]
You already have opened #1752, closing this one.
