### ISSUE TITLE
Gevent loop engine running failed-ValueError: fd must be non-negative: -1

### ISSUE THREAD

**Issue by cw1427** [unbit/uwsgi#1761]
I'm running uwsgi with gevent in a docker container, got an gevent loop engine execute error:

 1521452984 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55fff51487a0 pid: 1 (default app)
    60 1521452984 - uWSGI running as root, you can use --uid/--gid/--chroot options
    61 1521452984 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
    62 1521452984 - *** uWSGI is running in multiple interpreter mode ***
    63 1521452984 - spawned uWSGI master process (pid: 1)
    64 1521452984 - spawned uWSGI worker 1 (pid: 9, cores: 10)
    65 1521452984 - spawned uWSGI worker 2 (pid: 10, cores: 10)
    66 1521452984 - spawned uWSGI worker 3 (pid: 11, cores: 10)
    67 1521452984 - *** running gevent loop engine [addr:0x55fff2f814d0] ***
    68 1521452984 - spawned uWSGI worker 4 (pid: 12, cores: 10)
    69 Traceback (most recent call last):
    70 Traceback (most recent call last):
    71 Traceback (most recent call last):
    72 Traceback (most recent call last):
    73   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    74   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    75   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    76   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    77   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
    78   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
    79   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
    80   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
    81 ValueErrorValueError: ValueError: fd must be non-negative: -1ValueError: fd must be non-negative: -1
    82 : fd must be non-negative: -1
    83 fd must be non-negative: -1
    84
    85 1521452985 - DAMN ! worker 1 (pid: 9) died :( trying respawn ...
    86 1521452985 - Respawned uWSGI worker 1 (new pid: 13)
    87 1521452985 - DAMN ! worker 2 (pid: 10) died :( trying respawn ...
    88 1521452985 - Respawned uWSGI worker 2 (new pid: 14)
    89 1521452985 - DAMN ! worker 3 (pid: 11) died :( trying respawn ...
    90 1521452985 - Respawned uWSGI worker 3 (new pid: 15)
    91 1521452985 - DAMN ! worker 4 (pid: 12) died :( trying respawn ...
    92 1521452985 - *** running gevent loop engine [addr:0x55fff2f814d0] ***
    93 1521452985 - Respawned uWSGI worker 4 (new pid: 16)
    94 Traceback (most recent call last):
    95 Traceback (most recent call last):
    96   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    97   File "gevent.libev.corecext.pyx", line 490, in gevent.libev.corecext.loop.io (src/gevent/libev/gevent.corecext.c:6721)
    98   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
    99   File "gevent.libev.corecext.pyx", line 850, in gevent.libev.corecext.io.__init__ (src/gevent/libev/gevent.corecext.c:11208)
   100 ValueError: ValueErrorfd must be non-negative: -1:

Below is my uwsgi ini file config:

 1 [uwsgi]
  2 module = wsgi_handler:app
  3 socket = :8080
  4 master = 1
  5 processes = 4
  6 enable-threads = true
  7 thunder-lock=true
  8 #threads = 20
  9 gevent = 10
 10 gevent-monkey-patch=true
 11 #req-logger = file:/bsm/logs/uwsgi-reqlog
 12 logdate= %%s
 13 logto=/bsm/logs/uwsgi-log
 14 #logger = file:/bsm/logs/uwsgi-log
 15 memory-report = true
 16 max-requests=1000000
 17 socket-timeout = 3600

**Comment by xrmx** [comment]
Which version of uwsgi and gevent?

**Comment by cw1427** [comment]
uwsgi: 2.0.16
python: 2.7.14
gevent: 1.2.2

**Comment by jokey2k** [comment]
Reproduced in docker with nginx and Flask-SocketIO

**Comment by jokey2k** [comment]
uwsgi 2.0.17, gevent 1.2.2
both python 3.6.4 and 2.7.15 verified.

Are there some hints on where to start with debugging? never looked into uwsgi debugging until now.

**Comment by skolipaka** [comment]
@cw1427 @Zahlii @jokey2k I am having same issue. Could you please let me know if you got a workaround for this?

**Comment by unbit** [comment]
You are running without the master. Most of the uWSGI features are disabled without it (and gevent requires a bunch of them)

**Comment by cw1427** [comment]
@unbit what do you mean "running without the master" ? the uWSGI master?

**Comment by soon** [comment]
Any news?

**Comment by cw1427** [comment]
I figured out this issue. That is because I setup an extra uwsgi environment: UWSGI_INI  by mistake, which uwsgi would run error to find it in backend.  
Just remove this env parameter and gevent run well.
