### ISSUE TITLE
Can not run vassal with the uid,gid in the vassal config file while emperor-tyrant is enabled

### ISSUE THREAD

**Issue by dreamerxiong** [unbit/uwsgi#1776]
Hi,

I am now deploying my uwsgi application with the emperor mode, I need to run my applications with different users. So I followed the [Doc](http://uwsgi-docs.readthedocs.io/en/latest/Emperor.html) to configure my uwsgi application and run it with the emperor-tyrant enabled, but my application instances can not change to the uid/gid of my vassal config file.  Instead, while I disabled emperor-tyrant, it worked as expected. Here are my configuration files:

<pre>
/etc/uwsgi.ini
[uwsgi]
master = true
uid = 995
gid = 992
safe-pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
logto = /var/log/uwsgi/emperor.log
touch-reload = true
emperor-tyrant = true
cap = setgid,setuid
</pre>

<pre>
/etc/uwsgi.d/helloworld.ini
[uwsgi]
uid = 1001
gid = 1002
master = true
single-interpreter = true
socket = /run/uwsgi/%n.sock
chdir = /var/www/sites/helloworld
module = app:application
logto = /var/log/uwsgi/%n.log
plugins=python
processes = 4
chmod-socket = 660
#chown-socket = nginx:nginx
cap = setuid,setgid,chown
</pre>

Error log:
<pre>cannot setgid() as non-root user</pre>

As the offical [doc](http://uwsgi-docs.readthedocs.io/en/latest/Emperor.html#tyrant-mode-secure-multi-user-hosting) says:
<pre>
In Tyrant mode the Emperor will run the vassal using the UID/GID of the vassal configuration file 

If you have built a uWSGI version with Setting POSIX Capabilities options enabled, you can run the Emperor as unprivileged user but maintaining the minimal amount of root-capabilities needed to apply the tyrant mode
</pre>

If i need to run my uwsgi with multi-user hosting, should I enable or disable emperor-tyrant mode? Any suggestions or ideas from your side will be very appreciated.

**Comment by unbit** [comment]
HI, tyrant mode allows you to enforce unprivileged uid/gid for your vassals. In such a case the Emperor should be run as root, but if you have posix capabilities support (and they are still not so common) you could use the setuid/setgid trick. Btw, if your users do not have access to Emperor stuff you can run it as root.
