### ISSUE TITLE
How to completely isolate a vassal from system python with djangorecipe buildout

### ISSUE THREAD

**Issue by sandroden** [unbit/uwsgi#1777]
Hi,

I recently realized that uwsgi vassals are not completely isolated from system python when using [buildout](http://www.buildout.org/en/latest). 

In this setup, i start from an "empty" virtualenv (base2 in my case) and use its python interpreter to bootstrap a setup whose main file will be a wsgi (django.wsgi in my case) that I declare in the .ini file.
Buildout ceates the wsgi file composing the complete `sys.path`. It just works pretty well and running from the shell, you're completely isolated from system Python.

In my .ini file I don't declare a virtualenv, the virtualenv used to start (base2) doesn't really contain anything (apart from the binary interpreter).

I noticed recently that this environment is not really isolated and an error in a namespaced package broke the import system dramatically.

Is there a way to force it to be isolated? I see that if I could declare the virtualenv directive it would really run isolated, but my base2 virtualenv is "empty" and uwsgi would complain:

```
Set PythonHome to /var/www/.virtualenvs/base2                                                             │
ImportError: No module named site    
```      

As a last trial I popped the system path from the sys.path, but again uwsgi complains it didn't find the application.. 

At this point I run out of ideas...

sandro

**Comment by xrmx** [comment]
Providing the uwsgi config file would help :) Have you tried using a virtualenv and adding the buildout paths as pythonpath?

Anyway even virtualenvs may break if the system python they are created with change so if you need real isolation take a look at namespaces http://uwsgi-docs.readthedocs.io/en/latest/Namespaces.html

Also for reference you already filed an issue to buildout too: https://github.com/buildout/buildout/issues/446

**Comment by sandroden** [comment]
I did try to add the directive to the virtualenv, but when I did I made a mistake (/var instead of /home) so it complained it 

```
Set PythonHome to /var/www/.virtualenvs/base2
ImportError: No module named site
```

Fixing this typo and adding the virtualenv directive everythig works as expected. Thanks for forcing me to re-check it. Issue closed. 

Just for completeness, here is the configuration that I was using.
The configuration of a django.wsgi file created by buildout is similar to this (truncated as is not needed):
```

#!/home/www/.virtualenvs/base2/bin/python

import sys
sys.path[0:0] = [
  '/home/www/.buildout/eggs/Django-1.10.6-py2.7.egg',
  '/home/www/.buildout/eggs/ipython-5.1.0-py2.7.egg',
  ...
  '/home/www/.buildout/eggs/PyYAML-3.11-py2.7-linux-x86_64.egg',
  '/home/www/3palchi-test/apps',
  ]
```
An the .isi file:
```
[uwsgi]
env = DJANGO_SETTINGS_MODULE=web.settings
prj_dir = /home/www/3palchi
wsgi-file = %(prj_dir)/bin/django.wsgi
socket = /var/run/uwsgi/3palchi.sock
pidfile = /var/run/uwsgi/3palchi.pid
socket-timeout = 200
buffer-size = 10000
processes = 2
threads = 4
enable-threads = True
uid = www-data
gid = www-data
req-logger = file:/var/log/uwsgi/3palchi-access.log
logger = file:/var/log/uwsgi/3palchi-errors.log
touch-logreopen = /var/log/uwsgi/touch-logrotate
chmod-socket    = 664
plugins = python2,logfile
```
