### ISSUE TITLE
send post fields in cron-curl

### ISSUE THREAD

**Issue by git001** [unbit/uwsgi#1785]
I haven't seen `CURLOPT_POSTFIELDS` or any other option for posting a request in

https://github.com/unbit/uwsgi/blob/master/plugins/curl_cron/curl_cron.c

similar to 

https://github.com/unbit/uwsgi/blob/master/plugins/alarm_curl/alarm_curl_plugin.c

I wan't to run a health check with a json payload in curl-cron.

I assume this is not possible yet just a GET Call is possible right?

I think this is the right syntax.

```
[uwsgi]
; every two hours
cron-curl= 0 -2 -1 -1 -1 https://my.domain.com/url
```

How about to add a similar syntax as in alarm_curl or cron2

https://uwsgi-docs.readthedocs.io/en/latest/AlarmSubsystem.html#curl
https://uwsgi-docs.readthedocs.io/en/latest/Cron.html#new-syntax-for-cron-options

```
[uwsgi]
; every two hours
; simple GET Request
cron-curl2= minute=0,hour=-2,domain=my.domain.com /url
; Post request
cron-curl2= minute=0,hour=-2,domain=my.domain.com,method=POST,payload=THEPAYLOAD,headers="Content-Type: application/json;User-Agent: my Cron Agent 007" /url

```

**Comment by unbit** [comment]
Hi, i think it would be a good addition, would you like to make a pull request ?

**Comment by git001** [comment]
> Hi, i think it would be a good addition, would you like to make a pull request ?

Yes I'm in the learning and reading phase of the source.
Should I go with the `master` and make the PR's for that branch?

**Comment by git001** [comment]
Sorry had no time to work on PR.
Will close it for now.
