### ISSUE TITLE
Random segfaults running as Python lib on MacOS

### ISSUE THREAD

**Issue by ipmb** [unbit/uwsgi#1796]
I have a Django management command setup to import and run uWSGI compiled as a library via `ctypes`. It works great on Linux, but immediately segfaults 70-85% of the time when I run it on MacOS. The Python loading code is here: https://github.com/lincolnloop/saltdash/blob/75c44bbbc185964dbeffac3ea89ccb2ebcf4205a/saltdash/dash/management/commands/uwsgi.py

I build uWSGI as a lib with pip: https://github.com/lincolnloop/saltdash/blob/75c44bbbc185964dbeffac3ea89ccb2ebcf4205a/Makefile#L68-L69

The segfaults look like this:

```
!!! uWSGI process 20242 got Segmentation Fault !!!
*** backtrace of 20242 ***
0   libuwsgi.so                         0x0000000104b1822c uwsgi_backtrace + 44
1   libuwsgi.so                         0x0000000104b18763 uwsgi_segfault + 51
2   libsystem_platform.dylib            0x00007fff981d3b3a _sigtramp + 26
3   libxpc.dylib                        0x00007fff98217163 xpc_array_apply + 64
4   libuwsgi.so                         0x0000000104acb090 parse_sys_envs + 496
5   libuwsgi.so                         0x0000000104b19f59 uwsgi_setup + 5673
6   libuwsgi.so                         0x0000000104b18919 uwsgi_init + 9
7   _ctypes.cpython-36m-darwin.so       0x0000000103b86427 ffi_call_unix64 + 79
8   ???                                 0x00007fff5d6f32b0 0x0 + 140734760956592
*** end of backtrace ***
```

Here is a sample of the exit codes from 100 runs:

```
$ for i in {1..100}; do manage.py uwsgi --help > /dev/null 2>&1; echo $?; done | sort | uniq -c
  14 0
  86 1
```

**Comment by ipmb** [comment]
I have a minimal test case of this now:

```bash
git clone https://github.com/lincolnloop/uwsgi-pylib.git
cd uwsgi-pylib
pip install -e .[test]
while true; do pytest uwsgi_pylib/tests/tests.py::test_django --quiet; done
```

It works reliably if I run directly (see other tests), but intermittently fails when wrapped in a Django management command, and only on MacOS.

**Comment by rdeioris** [comment]
thank you ! will be super-useful. i will be back in the office next week and i will work on it

**Comment by ipmb** [comment]
Looks like this is a dupe of #1762.
