### ISSUE TITLE
safe-pidfile2 and ftok do not work together after reboot

### ISSUE THREAD

**Issue by raratiru** [unbit/uwsgi#1798]
I configure uWSGI to run as root with dropped privileges because I want to control it with `rcctl` and delegate the relevant sources through `login.conf`. 

According to [this issue](https://github.com/unbit/uwsgi-docs/issues/281) `safe-pidfile2` is suggested as a better alternative to `pidfile2`. On the other hand, in an effort to deal with the issue of [orphaned semaphores](https://github.com/unbit/uwsgi/issues/1508), I used `ftok` and rebooted.
```
# cat /home/user/uwsgi.ini
[uwsgi]
# Run as nobody
uid           = 32767
gid           = 32767
socket        = /tmp/uwsgi.sock
safe-pidfile2 = /tmp/uwsgi.pid
ftok          = /tmp/uwsgi.pid
master        = true
daemonize2    = /var/log/uwsgi/%n.log 
logto         = /var/log/uwsgi/%n_details.log
```
However, uWSGI will not start with both `ftok` and `safe-pidfile2`:

`# /home/user/.virtualenvs/uwsgi/bin/uwsgi --ini /home/user/uwsgi.ini`

```
# cat /var/log/uwsgi/uwsgi_details.log
*** Starting uWSGI 2.0.17 (64bit) on [Fri Jun  1 02:38:05 2018] ***
compiled with version: 4.2.1 Compatible OpenBSD Clang 5.0.1 (tags/RELEASE_501/final) on 29 May 2018 18:57:10
os: OpenBSD-6.3 GENERIC#3
nodename: my-node
machine: amd64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/user
detected binary path: /home/user/.virtualenvs/uwsgi/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
setgid() to 32767
setuid() to 32767
your processes number limit is 1310
your memory page size is 4096 bytes
detected max file descriptor number: 4096
lock engine: ipcsem
uwsgi_lock_ipcsem_init()/ftok(): No such file or directory [core/lock.c line 508]
uwsgi_ipcsem_clear()/semctl(): Invalid argument [core/lock.c line 643]
```

Changing `safe-pidfile2` with `pidfile2` uWSGI will start without problem.

Is it safe to ommit `safe-pidfile2` in favor of `pidfile`?

**Comment by unbit** [comment]
Hi, both are perfectly valid based on your setup. From what you are describing, you want your pidfile to be created before you drop privileges.

**Comment by raratiru** [comment]
Thank you for your answer. I am glad that both `pidfile` and `safe-pidfile` could work, although my setup is not ready yet, I will have httpd as a proxy for my single threaded uSGI served Django implementation. 

 I also tried with `safe-pidfile` instead of `safe-pidfile2` but still no luck, the error remains the same, could it be relevant to #371 ?

For the time being, #720 gave me the idea to try `pidfile` and use a `master-fifo` file to handle the relevant signals as a more robust choice.

**Comment by raratiru** [comment]
According to the [ftok()](http://man7.org/linux/man-pages/man3/ftok.3.html) manpage, 

> The ftok() function uses the identity of the file named by the given
>        pathname (which must refer to an existing, accessible file) and the
>        least significant 8 bits of proj_id (which must be nonzero) to
>        generate a key_t type System V IPC key, suitable for use with
>        msgget(2), semget(2), or shmget(2).

therefore setting `ftok          = /path/to/uwsgi.ini` works very well!
