### ISSUE TITLE
Mules with lazy-apps

### ISSUE THREAD

**Issue by dmoisizz** [unbit/uwsgi#1800]
I have some strange behaviour when using uwsgi mules in lazy-apps mode. For some reasons target parameter of uwsgi decorators and .add_timer() calls are ignored and task always goes to all workers and hangs application, so it stop answering via http socket.

I'm using uwsgi 2.0.17 inside docker with centos7 and python3.6.

Imagine ini config
```
[uwsgi]
http-socket = 8000
wsgi-file = wsgi.py
processes = 2
lazy-apps = true
mule
import = tasks
```

and some python code in tasks.py

```
import time
import requests
import threading
from uwsgidecorators import timer

@timer(10, target='mule')
def background_task(*args):
    for i in range(0, 50):
        print(threading.current_thread().name, i, requests.get('https://google.com').status_code)
        time.sleep(0.1)
```

Lets run this app. We have this log in console, so timers and mules was initialized:
```
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: mules)
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 11, cores: 1)
spawned uWSGI worker 2 (pid: 12, cores: 1)
spawned uWSGI mule 1 (pid: 13)
```

Now if you try to make http request to 8000 - you will get answer. But after 10 seconds timer  starts execution of background_task and print results start to appear in console:
```
uWSGIWorker1Core0 0 200
uWSGIWorker2Core0 0 200
uWSGIWorker1Core0 1 200
uWSGIWorker2Core0 1 200
uWSGIWorker1Core0 2 200
uWSGIWorker2Core0 2 200
uWSGIWorker1Core0 3 200
...
```

And at the same time http request to 8000 takes forever like if all workers was busy. And also you can see that task goes not to signe mule (target='mule') but to all workers.

Now, lets remove lazy-apps = true from ini-config and try again. You will see:
```
MainThread 0 200
MainThread 1 200
MainThread 2 200
MainThread 3 200
MainThread 4 200
MainThread 5 200
...
```

and also http-requests are works normaly.

I even tried to use something like this in timer decorator: @timer(10, target='WRONG_TARGET')
with lazy-apps:
```
uWSGIWorker1Core0 0 200
uWSGIWorker2Core0 0 200
uWSGIWorker1Core0 1 200
uWSGIWorker2Core0 1 200
...
```

without lazy-apps:

```
^^^ UNSUPPORTED SIGNAL TARGET: WRONG_TARGET ^^^
```

**Comment by dmoisizz** [comment]
Hmm, i think my problem is connected with this https://github.com/unbit/uwsgi/issues/861

If i replace `import = tasks` with `shared-pyimport = tasks` then even with lazy-apps it works fine, task goes to mule and http-socket answers well.

Is this right way to use mules with lazy-apps?

**Comment by unbit** [comment]
Hi, yes your "fix" is right, as when in lazy-apps mode, the ,aster does not load code (unless you force it with shared import)

**Comment by dmoisizz** [comment]
Thank you!
