### ISSUE TITLE
Info regarding ASGI

### ISSUE THREAD

**Issue by pdonadeo** [unbit/uwsgi#1830]
@unbit Any chance to see the asgi branch merged?

**Comment by unbit** [comment]
The branch is suspended while waiting for some kind of sponsorship :) We are currently focused on asyncio.

**Comment by pdonadeo** [comment]
@unbit thanks for your reply. I'm going to close but I ask you how can I contact you for the sponsorship :)

**Comment by unbit** [comment]
Hi Paolo, you can drop a mail to info at unbit.it

**Comment by pdonadeo** [comment]
Thanks!

**Comment by onegreyonewhite** [comment]
Smthing changed?
