### ISSUE TITLE
Tracebacker logs intermittently on harakiris.

### ISSUE THREAD

**Issue by thedracle** [unbit/uwsgi#1833]
I have a difficult to track down harakiri that involves a deadlock in cryptography and _openssl.so.

I have tracebacker enabled, and some of our harakiris contain tracebacker logs, but all of those that are due to this native deadlock do not.

I am using UWSGI 1.4.10, and Python 2.7.12.

**Comment by xrmx** [comment]
What  about reproducing with latest release?

**Comment by thedracle** [comment]
I will have to wait for us to update UWSGI on our core production platform, we aren't getting enough traffic in dev/staging to trigger the intermittent deadlock that is causing this to occur.

Are there any particular bug fixes to the harakiri traceback logging stuff that you think might be relevant?
