### ISSUE TITLE
running uwsgi is ok ,but get web failed

### ISSUE THREAD

**Issue by Chen-kaiyuan** [unbit/uwsgi#1850]
Hi, I during use uwsgi found  a issue .
If ,running uwsgi --http-socket :9090 --wsgi-file test.py in centos and the result is ok . 
But unable to accessible web?

![image](https://user-images.githubusercontent.com/17740259/43945171-f1e3a52c-9cb3-11e8-91d6-db0225e1d137.png)
![image](https://user-images.githubusercontent.com/17740259/43945195-01c958b0-9cb4-11e8-8be8-fda872c3f7db.png)

So，help me , Thanks

**Comment by xrmx** [comment]
You are confusing http and http-socket
