### ISSUE TITLE
uwsgi: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such  file or directory

### ISSUE THREAD

**Issue by xingfukun** [unbit/uwsgi#1862]
uwsgi: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such 
file or directory

**Comment by GabrielC101** [comment]
Same issue. 

Happens when running uwsgi from a python virtual environment that was created on my desktop, and is mounted in a docker container. It works in desktop, but not in container.

I realize I'm probably pushing the bounds of what's feasible . . . but I did get the same error.

**Comment by xrmx** [comment]
You are linking against an ssl that's not there anymore, easier way to fix it is to rebuild uwsgi.
