### ISSUE TITLE
chdir(): permission to denied to folder that has access rights

### ISSUE THREAD

**Issue by PDiracDelta** [unbit/uwsgi#1867]
www-data has gid and uid 33:
`sudo cat /etc/passwd | grep www-data`

> www-data: x :33:33:www-data:/var/www:/usr/sbin/nologin

(I added spaces around the 'x' otherwise it becomes :x:)

When I start the uwsgi app, it fails and the log shows:

> Thu Sep 13 12:48:47 2018 - setgid() to 33
> Thu Sep 13 12:48:47 2018 - setuid() to 33
> Thu Sep 13 12:48:47 2018 - chdir() to /home/pdiracdelta/www/QCQuan/qcquan_web/qcquan_web
> Thu Sep 13 12:48:47 2018 - chdir(): Permission denied [core/uwsgi.c line 2592]

However, www-data has permissions in this folder:
`ls -la /home/pdiracdelta/www/QCQuan/qcquan_web | grep qcquan_web`

> drwxrwxr-- 5 pdiracdelta www-data    4096 Sep 13 11:15 qcquan_web

related: https://serverfault.com/questions/872271/uwsgi-permission-denied-on-chdir-that-does-have-permissions-for-that-uid

**Comment by unbit** [comment]
Hi, the permissions of the final dir are irrelevant if the outer directories have no enough rights. Check that all the paths parts are ok.

**Comment by PDiracDelta** [comment]
Sorry, it seems my understanding of file permissions was way poorer than I thought.
Also, there were symlinks involved, and even after I adjusted the permissions of all parent paths (through a symlink) I still had to also adjust the permissions of all the 'true' parent dirs of the symlink target.

Thanks for your quick response!
