### ISSUE TITLE
Format consistency

### ISSUE THREAD

**Issue by Miniwoffer** [unbit/uwsgi#1877]
Hi i was wondering if there is a format standard for the c code in this project, when reading through the source there is some inconsistency. I am willing to go through the code and make sure it conforms to a standard i just needs some pointer to what format is preferred.

**Comment by unbit** [comment]
This one: https://github.com/unbit/uwsgi/blob/master/uwsgi.h#L3

**Comment by Miniwoffer** [comment]
If you want i can make a markdown document that explains the style, in either this repo or the docs.
