### ISSUE TITLE
Share dynamic data in memory between workers.

### ISSUE THREAD

**Issue by tomaso909** [unbit/uwsgi#1882]
I have a web app written in Dajngo with uWSGI but I have run across the following issue:

The app allows performing scientific simulations to the user. When a client logs in and opens one of his projects, a Simulation object is initialized and stored in a dict as {request.user:Simulation}. Initializing this Simulation object can take about 10 seconds so it is only done at the beginning. Every time the user interacts with his simulation on the client side, a particular view queries the Simulation object to the global dict and applies any changes, retrieves data, saves the simulation, runs the simulation, etc.

The problem with this approach is that it only works with 1 worker since additional workers do not have access to the Simulation objects inside the global dict. I have been reading the uWSGI documentation and I think it might be possible to implement what I need using the uWSGI queue framework.

I think I could define a queue with a single slot with a very large allocated space (e.g. 1GB) as:

`uwsgi --socket :3031 --queue 1 --queue-blocksize 1073741824`

Then, every time I modify the object in a view I would do something as follows:
```python
# views.py
def do_something(request):
    simulations = uwsgi.queue_get(1) # Retrieve global dict containing all Simulation objects.
    simulations[request.user].modify_some_parameters() # Modify user's Simulation.
    data = simulations[request.user].retrieve_some_data() # Get some data from user's Simulation.
    uwsgi.queue_set(1,simulations) # Save modified user's Simulation in global dict.
    return HttpResponse(json.dumps({'parameter':data['parameter']}))
```

Is this a valid pattern ?
Is it possible to store custom objects in uWSGI queues or only python types ?
Does it make sense to initialize such a large queue-blocksize (since I do not know the required space beforehand) or I will run into problems ?

**Comment by unbit** [comment]
Hi, use the caching framework the queue one is basically abandonware by years.
