### ISSUE TITLE
pip install uwsgi fails on windows

### ISSUE THREAD

**Issue by Wellige** [unbit/uwsgi#1930]
If I try to install uwsgi on windows, I get an error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\cygwin64\tmp\pip-install-1y21m1\uwsgi\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: 'module' object has no attribute 'uname'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\cygwin64\tmp\pip-install-1y21m1\uwsgi\

```

I found out, that the following code does not work under windows python:  `os.uname()`
But the following code is supposed to work cross-platform: `platform.uname()`

I hope you can fix this issue for windows users. Thank you!

**Comment by unbit** [comment]
Hi, there is no support for windows, but you can use uWSGI in the linux subsystem in windows 10.

**Comment by dinuta** [comment]
why is that? what if i want to burn my app inside uwsgi and create a binary for win ?
https://uwsgi-docs.readthedocs.io/en/latest/Embed.html 

otherwise what should be the solution for multi-platform binaries? (pyinstaller?)

**Comment by antlancer-solutions** [comment]
Try this to skip errored package 
`FOR /F %k in (requirements.txt) DO pip install %k`

this command will install pip requirements line by line and if there is an error on some of packages it will not freeze the rest of installations.

I have the same issue and several OS issues in many cases
There is a work around sometimes is working to skip 'errored' packages if not affect the major app
or to modify manually every pip that is not compatible which is possible but too headache depending on number of modifications needed

**Comment by jmarshall9120** [comment]
@antlancer-solutions 's solution worked for me, but I had to put it into powershell:

`Get-Content ./requirements.txt | ForEach-Object -Process {pip install $_}`

**Comment by zamantech** [comment]
https://github.com/unbit/uwsgi/issues/2085
