### ISSUE TITLE
uWSGI segfaults when value of --wsgi-env-behavior is invalid

### ISSUE THREAD

**Issue by untitaker** [unbit/uwsgi#1951]
Calling uWSGI with a bad value for `--wsgi-env-behavior` will segfault on the first request.

## Application

Literally anything. Just take any hello world WSGI app:

```python
# save as app.py

def application(environ, start_response):
    # This is just hello world
    status = '200 OK'
    response_headers = [('Content-type', 'text/plain')]
    start_response(status, response_headers)
    yield b'.'
```

## Config

```shell
uwsgi --http :9000 --module app:application --wsgi-env-behavior=potato
```

## Environment information

Pretty sure this happens independent of environment. Anyway, OS X 10.14.2 with Python 2.7 installed via Homebrew.

## Possible cause

This will not initialize `up.wsgi_env_create` or `up.wsgi_env_destroy` if the value is invalid: https://github.com/unbit/uwsgi/blob/43b465ce8945570ee9730bfad4b625a58d136463/plugins/python/python_plugin.c#L1145-L1156

**Comment by unbit** [comment]
Fixed, thanks a lot for the report
