### ISSUE TITLE
The extra processes

### ISSUE THREAD

**Issue by dqchouyang** [unbit/uwsgi#1955]
set
'processes = 4
master = true'
in uwsgi.ini file
but find 6 processes on computer,  why? Is it related to the father process?

ps -ef | grep uwsgi
root     29180     1  0 17:00 ?        00:00:08 /usr/bin/uwsgi --ini wsgi.ini
root     30172 29180  0 17:54 ?        00:00:00 /usr/bin/uwsgi --ini wsgi.ini
root     30173 29180  0 17:54 ?        00:00:00 /usr/bin/uwsgi --ini wsgi.ini
root     30174 29180  0 17:54 ?        00:00:00 /usr/bin/uwsgi --ini wsgi.ini
root     30175 29180  0 17:54 ?        00:00:00 /usr/bin/uwsgi --ini wsgi.ini
root     30176 29180  0 17:54 ?        00:00:00 /usr/bin/uwsgi --ini wsgi.ini

**Comment by xrmx** [comment]
1 master, 4 are processes and the other one may be the spooler? Hard to tell without the ini. Anyway not an issue and better discussed in the mailing list.
