### ISSUE TITLE
/usr/sbin/uwsgi: invalid option -- 'H'

### ISSUE THREAD

**Issue by TheDavidFactor** [unbit/uwsgi#1957]
I'm trying to specify a virtualenv and can't get it to work. I get an "unrecognized option" error for

- --virtualenv
- --venv
- --home
- --pyhome

I'm running uwsgi 2.0.17.1 on Fedora 29. uwsgi from the standard repo

The options are listed in the docs here:
https://uwsgi-docs.readthedocs.io/en/latest/Options.html#home
But I can't it get it to work

**Comment by xrmx** [comment]
It's explained in this chapter:
https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#installing-uwsgi-with-python-support

**Comment by TheDavidFactor** [comment]
I installed the python plugin, but forgot to load it. My bad!
