### ISSUE TITLE
segmentation fault with python3.7 and autoreload

### ISSUE THREAD

**Issue by tianwen20** [unbit/uwsgi#1968]
!!! uWSGI process 11459 got Segmentation Fault !!!
*** backtrace of 11459 ***
uwsgi(uwsgi_backtrace+0x2e) [0x607fde]
uwsgi(uwsgi_segfault+0x21) [0x608371]
/lib64/libc.so.6(+0x36280) [0x7fe319041280]
uwsgi(PyBytes_AsString+0x4) [0x4dbbc4]
uwsgi(uwsgi_python_autoreloader_thread+0x152) [0x61eba2]
/lib64/libpthread.so.0(+0x7dd5) [0x7fe31d150dd5]
/lib64/libc.so.6(clone+0x6d) [0x7fe319108ead]
*** end of backtrace ***

configuration:

```
http = :1899

plugin=python

#the local unix socket file than commnuincate to Nginx   用于和 nginx 进行数据交互的端口
socket = :1880
socket-timeout = 600
limit-as = 1024
# the base directory (full path)  django 程序的主目录
chdir = /data/wwwroot/wechat1

# Django's wsgi file
wsgi-file = wechat1/wsgi.py

#启用主进程
master = true

# maximum number of worker processes

processes = 3
pidfile = /data/wwwroot/wechat1/uwsgi.pid

#thread numbers startched in each worker process
threads = 2
 
#monitor uwsgi status  通过该端口可以监控 uwsgi 的负载情况
stats = 127.0.0.1:1829

#启用线程
enable-threads = true

#设置自动中断时间
harakiri = 60

#设置缓冲
post-buffering = 4096


# clear environment on exit
vacuum = true

# 后台运行,并输出日志
daemonize = /data/wwwroot/wechat1/log/uwsgi.log

py-autoreload=1
```

**Comment by lifefeel** [comment]
I'm using Python 3.7 on Ubuntu 16.04. uwsgi version is 2.0.17.1.

 I have the same problem.

**Comment by jarojasm95** [comment]
Same problem, seems to happen when auto-reloading is enabled

**Comment by akiym** [comment]
same problem in #1825? uwsgi still have not been released...

**Comment by xrmx** [comment]
@akiym ah! thanks for the reminder
