### ISSUE TITLE
sudo -H pip3 install uwsgi - fails

### ISSUE THREAD

**Issue by sloughin** [unbit/uwsgi#1971]
I see that others have had issues with using pip to install uwsgi on ubuntu, but the issue was closed without any apparent resolution.  What I'm seeing in the log are many complaints about various object files from the libpython3.6m.a library where it says (for example)  "reloaction R_X86_64_32 against symbol '_Py_NoneStruct' can not be used when making a PIE object; recompile with -fPIC...  

After reporting many such errors (see full message output below), it fails *** error linking uWSGI *** and says 'Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize: __file___= ..." failed with error code = 1 in /tmp/pip-install-ik33_81y/uwsgi

So before closing this, please indicate what the recommended resolution is.  I'm ok with RTFM if you point to the relevant section of TFM.  Thanks! 

[errormsg.txt](https://github.com/unbit/uwsgi/files/2797123/errormsg.txt)

**Comment by xrmx** [comment]
@sloughin is the python custom compiled?

**Comment by xrmx** [comment]
@sloughin /usr/local/bin/python3.6 looks strange for a standard distro python

**Comment by sloughin** [comment]
Yes, I was disappointed that python3.7 wasn't apparently ready for ubuntu, but here's what I have...

steve@steve-VC66:~$ python3 --version
Python 3.6.3
steve@steve-VC66:~$ sudo -H apt-get install python3
[sudo] password for steve: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
steve@steve-VC66:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by xrmx** [comment]
@sloughin the ubuntu one is not in /usr/local/ though, please reproduce building against the ubuntu packaged one in /usr.

**Comment by sloughin** [comment]
Do you mean python 2.7?
```
which python
/usr/bin/python
steve@steve-VC66:~$ python --version
Python 2.7.15rc1
```

So, as it turns out, I can install it for python2.7...
```
/usr/local/bin$ sudo -H pip install uwsgi
Collecting uwsgi
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/a2/c9/a2d5737f63cd9df4317a4acc15d1ddf4952e28398601d8d7d706c16381e0/uwsgi-2.0.17.1.tar.gz (800kB)
    100% |████████████████████████████████| 808kB 1.2MB/s 
Building wheels for collected packages: uwsgi
  Running setup.py bdist_wheel for uwsgi ... done
  Stored in directory: /root/.cache/pip/wheels/32/d6/90/0239cc69219013d9f402b098b7c5ef7454792c21acd1d6c24e
Successfully built uwsgi
Installing collected packages: uwsgi
Successfully installed uwsgi-2.0.17.1
steve@steve-VC66:/usr/local/bin$ 
```
I had hoped to run with python 3 though...

**Comment by xrmx** [comment]
Who talked about python2? The python3 you are using is not the one from ubuntu. Even the versions are different.
