### ISSUE TITLE
ImportError: No module named caffe

### ISSUE THREAD

**Issue by Samweli** [unbit/uwsgi#1972]
Hi, I have installed (compiled) caffe with anaconda on my ubuntu 14.04 server, I can access and import caffe in shell environment but uwsgi cant load the flask app which import the caffe module, logging import error of the module. I'm using uwsgi in emperor mode

`*** Operational MODE: preforking ***`
`Traceback (most recent call last):`
  `File "./wsgi.py", line 1, in <module>`
    `from server import app`
  `File "./server.py", line 39, in <module>`
    `from spot import *`
  `File "./spot.py", line 1, in <module>`
    `import caffe`
`ImportError: No module named caffe`
`unable to load app 0 (mountpoint='') (callable not found or import error)`

**Comment by xrmx** [comment]
Your logs says you can't import caffe, not sure we can help with that.
