### ISSUE TITLE
ImportError: No module named 'wsgi'

### ISSUE THREAD

**Issue by jostidetosti** [unbit/uwsgi#1973]
Steps to reproduce:

On a Raspberry Pi 2 with Raspbian GNU/Linux 9 (stretch).

    sudo pip install uwsgi
    uwsgi --socket 0.0.0.0:8080 --protocol=http -w wsgi

Result:

    *** Starting uWSGI 2.0.17.1 (32bit) on [Thu Jan 31 12:25:18 2019] ***
    compiled with version: 6.3.0 20170516 on 31 January 2019 12:15:38
    os: Linux-4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018
    nodename: bv-pi2
    machine: armv7l
    clock source: unix
    pcre jit disabled
    detected number of CPU cores: 4
    current working directory: /home/pi/temp
    detected binary path: /usr/local/bin/uwsgi
    *** WARNING: you are running uWSGI without its master process manager ***
    your processes number limit is 7345
    your memory page size is 4096 bytes
    detected max file descriptor number: 1024
    lock engine: pthread robust mutexes
    thunder lock: disabled (you can enable it with --thunder-lock)
    uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
    Python version: 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
    *** Python threads support is disabled. You can enable it with --enable-threads ***
    Python main interpreter initialized at 0x20550e0
    your server socket listen backlog is limited to 100 connections
    your mercy for graceful operations on workers is 60 seconds
    mapped 64392 bytes (62 KB) for 1 cores
    *** Operational MODE: single process ***
    ImportError: No module named 'wsgi'
    unable to load app 0 (mountpoint='') (callable not found or import error)
    *** no app loaded. going in full dynamic mode ***
    *** uWSGI is running in multiple interpreter mode ***
    spawned uWSGI worker 1 (and the only) (pid: 1149, cores: 1)

Context:
I'm trying to follow [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-uwsgi-and-nginx-to-serve-python-apps-on-ubuntu-14-04).

**Comment by xrmx** [comment]
Re-read the tutorial more carefully then. You are not doing what's written in there.
