### ISSUE TITLE
nginx+uwsgi+websocket cause performance deterioration

### ISSUE THREAD

**Issue by LoveXiaoLiu** [unbit/uwsgi#1993]
> example: I start 5 workers, and then 5 clients of websocket connect to the web server(uwsgi), and then the 6th connection can't connect to the uwsgi. (websocket connection always occupy this process)

my uwsgi configuration:
```
......
safe-pidfile = /tmp/master.pid
enable-threads = true
master = true
processes = 16
socket = 0.0.0.0:9090
vacuum = true
buffer-size = 64000
max-requests = 10000
listen = 2048
http-websockets = true
......
```

### In summary：so much websocket connection occupy so much processes, cause other request can't be handle, so cause concurrent low

**Comment by unbit** [comment]
Hi, this is the expected behaviour if you do not use some "alternative" way of concurrency (gevent, generally).

Each process/thread can manage only a single connection

**Comment by LoveXiaoLiu** [comment]
> Hi, this is the expected behaviour if you do not use some "alternative" way of concurrency (gevent, generally).
> 
> Each process/thread can manage only a single connection

thank you very much, i am trying the way of `gevent`

**Comment by LoveXiaoLiu** [comment]
@unbit excuse me，ask one more question. which IO model UWSGI used？（blocking IO、noblocking IO、IO multiplexing、signal-driven IO、asynchronous IO）. I guess that use BIO.

**Comment by unbit** [comment]
It depends on the selected loop engine. process/thread is blocking IO (with strict timeouts), async engines are generally plain I/O multiplexing

**Comment by LoveXiaoLiu** [comment]
@unbit I have a doubt，in this case, uwsgi depends on the selected loop engine. I think one new connection is coming in for one worker process,the selected loop engine of this worker process will spawn a thread to handle this request, every subsequent requests also will spawn a new thread.

so i don't understand why subsequent requests can't be handle immediately！

thank you very very much

**Comment by unbit** [comment]
This is not how uWSGI works. It never spawns new threads/processes on requests (for both security and performance reasons). The number of threads/processes/core is fixed and they simply dequeue requests

**Comment by LoveXiaoLiu** [comment]
Thank you for answering my questions.^~^
