### ISSUE TITLE
my attach-daemon2 touch not work

### ISSUE THREAD

**Issue by LoveEatCandy** [unbit/uwsgi#2024]
my uwsgi.ini settings about attach-daemon2 doesn't work.
please tell me the problem,thanks.

[uwsgi]
socket = /tmp/web2py2000.socket
pythonpath = /home/www-data/web2py2000/
mount = /=wsgihandler:application
processes = 2
master = true
harakiri = 60
reload-mercy = 8
cpu-affinity = 1
stats = /tmp/stats2000.socket
max-requests = 2000
limit-as = 512
reload-on-as = 256
reload-on-rss = 192
uid = www-data
gid = www-data
touch-reload = /home/www-data/web2py/routes.py
attach-daemon2 = cmd=python web2py.py -S player -M -R applications/player/private/tools/run_mprpc.py, pidfile=/tmp/mprpc.pid, touch=/home/www-data/web2py/applications/player/private/tools/run_mprpc.py,chdir=/home/www-data/web2py

**Comment by Loveeatcandy** [comment]
the touch paramiter not work

**Comment by edufelipe** [comment]
@LoveEatCandy If you add a `pidfile` config without adding `daemonize` then your code needs to `fork()` and write its new pid to that pidfile, otherwise this won't work.

So I suggest either adding `daemonize=1` to your config to fix this issue.
