### ISSUE TITLE
Flask to uwsgi stuck threads

### ISSUE THREAD

**Issue by batchenr** [unbit/uwsgi#2027]
im Using Python 3.7.3, uwsgi 2.0.18, (docker container image python:3-stretch)

We have development environment where we are running our code on flask and we change it to uwsgi when we test it on production. Im running a py script which get live-stream pcm audio from redis (another container)

Now, when we run it on flask all works fine! when we run it on uwsgi threads gets stuck and die.

uwsgi settings :

```
[uwsgi]
http =  :5000
socket = :3031
wsgi-env-behaviour=holy
master=1
uid=1000
gid=2000
master=1
processes = 1
threads = 1
protocol = uwsgi
wsgi-file = server.py
chdir = /app/base/
callable = app
http-raw-body
single-interpreter
paste-logger = true
honour-stdin
#logto = /tmp/errlog
vacuum = true
harakiri-verbose = true
harakiri = 60
cpu-affinity =3
http-timeout = 60
optimize = 2
http-keepalive
listen=30
workers = 40
ugreen
reaper
start_response-nodelay
greenlet

```
logs :

```
HARAKIRI: -- wchan> 0
Wed Jun  5 15:55:48 2019 - HARAKIRI !!! worker 24 status !!!
Wed Jun  5 15:55:48 2019 - HARAKIRI [core 0] XX.XX.XX.XX- GET /pcm_json since 1559750087
Wed Jun  5 15:55:48 2019 - HARAKIRI !!! end of worker 24 status !!!
Wed Jun  5 15:55:48 2019 - *** HARAKIRI ON WORKER 27 (pid: 32, try: 1) ***

DAMN ! worker 10 (pid: 15) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 10 (new pid: 64)

```
whats the major difference between flask and uwsgi regarding post and get requests ?

EDIT:

this is the code sendind request :

```
conn = http.client.HTTPConnection(server, port)
 headers = { "ID": ID, "debugLevel": 1, "Multipart": 1, "Audio": 1, "Accept": "application/json" } conn.request("GET", "/pcm", "", headers)
 ret = conn.getresponse() 

```
this is another error i see in cli

`Unhandled exception in thread started by <function get_pcm>
`

**Comment by kbutz** [comment]
This should probably be posted to StackOverflow since it isn't describing an issue with uWSGI.

It might be possible that you're seeing unexpected behavior with your redis client and uWSGI's pre-fork behavior. You could try `lazy-apps=true` to initialize your workers/processes post-fork. I've had similar unexpected behavior sharing mysql connections pre-fork.

Again, this is more in the "trouble-shooting" domain, and probably better posted to StackOverflow.

**Comment by batchenr** [comment]
Hey,
 i did post there as well.(at StackOverflow )
i also made some progress and now i dont get the 
`Unhandled exception in thread started by <function pcm>`

now i get pcm files  and in some point it gets stuck \ hangs and thats it.
i just dont get how in flask i didnt have any issues and in uwsgi i do have.

do uwsgi need python code tuning ? changing something ? 
we are using requests and http.client is there another library to use?

this is my current settings : 
```
[uwsgi]
http =  :5000
socket = :3031
wsgi-env-behaviour=holy
master=1
uid=1000
gid=2000
master=1
processes = 1
threads = 1
protocol = uwsgi
wsgi-file = server.py
chdir = /app/base/
callable = app
http-raw-body
single-interpreter
paste-logger = true
honour-stdin
#logto = /tmp/errlog
vacuum = true
harakiri-verbose = true
harakiri = 20
cpu-affinity =3
http-timeout = 20
optimize = 2
http-keepalive
listen=30
workers = 40
ugreen
reaper
start_response-nodelay
greenlet
offload-threads=30
post-buffering = 8192
lazy-apps=true
```
is there a way of saying to uwsgi if he gets stuck \ thread got closed - to just continue  ?
i just want it to keep going 
please help.

**Comment by batchenr** [comment]
So, i figured what made the uwsgi workers crash :

`" harakiri = 60" 
`in my uwsgi.ini conf , because our workers connection is for long time ( giving livestream) i guess harakiri thought it was overload or taking to much time so after 60 sec it would crash it.

for our server - multi-connection and livestream this settings works :

```
[uwsgi]
http =  :5000
socket = :3031
wsgi-env-behaviour=holy
master=1
uid=1000
gid=2000
master=1
threads = 4
protocol = uwsgi
wsgi-file = machine.py
chdir = /app
callable = app
http-raw-body
single-interpreter
paste-logger = true
honour-stdin
cpu-affinity =3
http-timeout = 60
optimize = 2
http-keepalive
listen=30
workers = 80
ugreen
reaper
start_response-nodelay
greenlet
offload-threads = 10

```
