### ISSUE TITLE
504 Gateway Time-out nginx/1.10.3 (Ubuntu)

### ISSUE THREAD

**Issue by uannabi** [unbit/uwsgi#2046]
I'm trying to host django 1.11 application on ubuntu 16.4 server using Nginx. But After running the server I'm getting 504 Gateway Time-out

here is my all port log
````
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      3209/redis-server 1
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      15218/nginx -g daem
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1204/sshd
tcp6       0      0 :::9200                 :::*                    LISTEN      28810/java
tcp6       0      0 :::9300                 :::*                    LISTEN      28810/java
tcp6       0      0 :::22                   :::*                    LISTEN      1204/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           963/dhclient`
```


Gunicorn.conf
````
command=/home/ubuntu/miniconda3/envs/ok/bin/gunicorn --access-logfile - --workers 3 --limit-request-line 8000 --bind unix:/home/ubuntu/app/socks/ok.sock configuration.wsgi:application
directory=/home/ubuntu/app/onekkom/backend
user=ubuntu
group=www-data
chmod=664
autostart=true
autorestart=true
stderr_logfile=/var/log/ok_prod_gunicorn.err.log
stdout_logfile=/var/log/ok_prod_gunicorn.out.log`
```
Nginx error log
`*```
1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 118.179.95.25, server: 18.136.204.142, requ$

2019/07/24 18:13:13 [error] 15221#15221: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 118.179.95.25, server: 18.136.204.142, requ$

2019/07/24 18:20:17 [error] 15485#15485: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 118.179.95.25, server: 18.136.204.142, requ$`
```
**Any one have any idea about this issue? any sort of help will be appreciated**

**Comment by xrmx** [comment]
Are you really opening a bug on the uwsgi repo while using gunicorn?

**Comment by uannabi** [comment]
yes

**Comment by uannabi** [comment]
> Are you really opening a bug on the uwsgi repo while using gunicorn?
yes

**Comment by xrmx** [comment]
If you can't configure gunicorn I'd advise you to look at the gunicorn documentation then or ask on stackoverflow.
