### ISSUE TITLE
--ssl-verify-depth option not working in 2.0.18

### ISSUE THREAD

**Issue by gnb** [unbit/uwsgi#2070]
I'm working on enabling authentication by client certificate for an internal tool.  The corporate client certificates have an issuer chain which includes an intermediate cert, and thus need a verification depth of > 1 to be successfully verified by OpenSSL.  I am using uwsgi's `--ssl-verify-depth` option added in 2.0.16 to override the uwsgi default verify depth of 1, but the value I pass is mysteriously not being used.

I enabled `--show-config` and it shows that the option is indeed being passed on the command line

```
2019-06-01 17:06:23 -0700 - log-req-encoder = format ${msg}
2019-06-01 17:06:23 -0700 - workers = 14
2019-06-01 17:06:23 -0700 - http-keepalive = true
2019-06-01 17:06:23 -0700 - http-auto-gzip = true
2019-06-01 17:06:23 -0700 - enable-threads = true
2019-06-01 17:06:23 -0700 - memory-report = true
2019-06-01 17:06:23 -0700 - ssl-verify-depth = 8   <----
2019-06-01 17:06:23 -0700 - ;end of configuration
```

I wrote a preload shim which intercepts the OpenSSL function to set the verify depth and prints its arguments

```
#include <openssl/ssl.h>
#include <stdio.h>

void SSL_CTX_set_verify_depth(SSL_CTX *ctx, int depth)
{
    {
        FILE *fp = fopen("/tmp/foo.txt", "a");
        if (fp) {
            fprintf(fp, "XXX SSL_CTX_set_verify_depth(ctx=%p, depth=%d)\n", ctx, depth);
            fclose(fp);
        }
    }
}
```

and it shows that OpenSSL is being fed the value 1, not 8

```
XXX SSL_CTX_set_verify_depth(ctx=0x1bb3bd0, depth=1)
```

I looked briefly through the code.  It seems pretty simple but I can't see how it could behave this way, unless perhaps

- something is wrong with `uwsgi_opt_set_int()` and it's not being called or falling back to it's own default value of 1
- the global `uwsgi` structure is overwritten somehow

I'm working around  this by using a variant of that preload shim that just throws away its arguments, resulting in OpenSSL using its built-in default verify depth rather than uwsgi's default verify depth.  Obviously this is awful and I'd like to see a fix in uwsgi.

**Comment by awelzel** [comment]
Hey @gnb ,

I tried to reproduce - initially I did not manage, but fuzzing around a bit:
 - the ssl-verify-depth option needs to come *after* the socket option

That is:

**Comment by gnb** [comment]
Hi @awelzel 

Now I see what's happening.  The SSL context is set up *during* argument parsing, not after.  Specifically, `uwsgi_opt_https()` calls `uwsgi_ssl_new_server_context()` which calls `SSL_CTX_set_verify_depth()` with the value of the global `uwsgi.ssl_verify_depth`.  If the options are in the order `https`, `ssl-verify-depth`, then that global hasn't been set yet, but it will be very shortly afterward.

I have verified that reversing the order of the options makes client certs works properly for me.   Thanks!

Perhaps this would be a good thing to add to the documentation, say [in this section](https://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html#client-certificate-authentication)

**Comment by gnb** [comment]
Closing this issues as the root cause is clear and easy to work around.

**Comment by xrmx** [comment]
@gnb care to open a PR on unbit/uwsgi-docs?
