### ISSUE TITLE
pip install uwsgi==2.0.13.1

### ISSUE THREAD

**Issue by tajalagawani** [unbit/uwsgi#2076]
Collecting uwsgi==2.0.13.1
  Using cached https://files.pythonhosted.org/packages/83/22/47b6ff871a5f01b9f660121cf61ba1eccbf7886b5cbe24caacccd0d00d07/uwsgi-2.0.13.1.tar.gz
Building wheels for collected packages: uwsgi
  Building wheel for uwsgi (setup.py): started
  Building wheel for uwsgi (setup.py): finished with status 'error'
  Running setup.py clean for uwsgi
Failed to build uwsgi
Installing collected packages: uwsgi
  Running setup.py install for uwsgi: started
    Running setup.py install for uwsgi: finished with status 'error'

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  ERROR: Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pycharm-packaging/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pip-wheel-so0JfT --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying uwsgidecorators.py -> build/lib
  warning: build_py: byte-compiling is disabled, skipping.
  
  installing to build/bdist.macosx-10.14-x86_64/wheel
  running install
  using profile: buildconf/default.ini
  detected include path: ['/usr/local/include', '/Users/tajalagawani/miniconda3/bin/../lib/clang/4.0.1/include', '/usr/include', '/System/Library/Frameworks', '/Library/Frameworks']
  Patching "bin_name" to properly install_scripts dir
  detected CPU cores: 8
  configured CFLAGS: -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format -Wno-format-security -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -mmacosx-version-min=10.5 -DUWSGI_LOCK_USE_OSX_SPINLOCK -DUWSGI_EVENT_USE_KQUEUE -DUWSGI_EVENT_TIMER_USE_KQUEUE -DUWSGI_EVENT_FILEMONITOR_USE_KQUEUE -I/Users/tajalagawani/miniconda3/include -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.13.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="13" -DUWSGI_VERSION_REVISION="1" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -I/usr/local/Cellar/yajl/2.1.0/include/ -DUWSGI_JSON -DUWSGI_JSON_YAJL -I/Users/tajalagawani/miniconda3/include/libxml2 -I/Users/tajalagawani/miniconda3/include -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
  *** uWSGI compiling server core ***
  [thread 1][clang] core/utils.o
  [thread 2][clang] core/protocol.o
  [thread 3][clang] core/socket.o
  [thread 4][clang] core/logging.o
  [thread 5][clang] core/master.o
  [thread 6][clang] core/master_utils.o
  [thread 7][clang] core/emperor.o
  [thread 0][clang] core/notify.o
  core/utils.c:3875:18: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
                                  va_start(ap, kv_separator);
                                               ^
  core/utils.c:3832:73: note: parameter of type 'char' is declared here
  int uwsgi_kvlist_parse(char *src, size_t len, char list_separator, char kv_separator, ...) {
                                                                          ^
  1 error generated.
  ----------------------------------------
  ERROR: Failed building wheel for uwsgi
    ERROR: Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pycharm-packaging/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pip-record-FRXiUI/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    using profile: buildconf/default.ini
    detected include path: ['/usr/local/include', '/Users/tajalagawani/miniconda3/bin/../lib/clang/4.0.1/include', '/usr/include', '/System/Library/Frameworks', '/Library/Frameworks']
    Patching "bin_name" to properly install_scripts dir
    detected CPU cores: 8
    configured CFLAGS: -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format -Wno-format-security -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -mmacosx-version-min=10.5 -DUWSGI_LOCK_USE_OSX_SPINLOCK -DUWSGI_EVENT_USE_KQUEUE -DUWSGI_EVENT_TIMER_USE_KQUEUE -DUWSGI_EVENT_FILEMONITOR_USE_KQUEUE -I/Users/tajalagawani/miniconda3/include -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.13.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="13" -DUWSGI_VERSION_REVISION="1" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -I/usr/local/Cellar/yajl/2.1.0/include/ -DUWSGI_JSON -DUWSGI_JSON_YAJL -I/Users/tajalagawani/miniconda3/include/libxml2 -I/Users/tajalagawani/miniconda3/include -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);UDEP(ping);UDEP(cache);UDEP(nagios);UDEP(rrdtool);UDEP(carbon);UDEP(rpc);UDEP(corerouter);UDEP(fastrouter);UDEP(http);UDEP(signal);UDEP(syslog);UDEP(rsyslog);UDEP(logsocket);UDEP(router_uwsgi);UDEP(router_redirect);UDEP(router_basicauth);UDEP(zergpool);UDEP(redislog);UDEP(mongodblog);UDEP(router_rewrite);UDEP(router_http);UDEP(logfile);UDEP(router_cache);UDEP(rawrouter);UDEP(router_static);UDEP(sslrouter);UDEP(spooler);UDEP(cheaper_busyness);UDEP(symcall);UDEP(transformation_tofile);UDEP(transformation_gzip);UDEP(transformation_chunked);UDEP(transformation_offload);UDEP(router_memcached);UDEP(router_redis);UDEP(router_hash);UDEP(router_expires);UDEP(router_metrics);UDEP(transformation_template);UDEP(stats_pusher_socket);" -DUWSGI_LOAD_EMBEDDED_PLUGINS="ULEP(python);ULEP(gevent);ULEP(ping);ULEP(cache);ULEP(nagios);ULEP(rrdtool);ULEP(carbon);ULEP(rpc);ULEP(corerouter);ULEP(fastrouter);ULEP(http);ULEP(signal);ULEP(syslog);ULEP(rsyslog);ULEP(logsocket);ULEP(router_uwsgi);ULEP(router_redirect);ULEP(router_basicauth);ULEP(zergpool);ULEP(redislog);ULEP(mongodblog);ULEP(router_rewrite);ULEP(router_http);ULEP(logfile);ULEP(router_cache);ULEP(rawrouter);ULEP(router_static);ULEP(sslrouter);ULEP(spooler);ULEP(cheaper_busyness);ULEP(symcall);ULEP(transformation_tofile);ULEP(transformation_gzip);ULEP(transformation_chunked);ULEP(transformation_offload);ULEP(router_memcached);ULEP(router_redis);ULEP(router_hash);ULEP(router_expires);ULEP(router_metrics);ULEP(transformation_template);ULEP(stats_pusher_socket);"
    *** uWSGI compiling server core ***
    [thread 0][clang] core/utils.o
    core/protocol.o is up to date
    [thread 2][clang] core/socket.o
    [thread 3][clang] core/logging.o
    [thread 4][clang] core/master.o
    [thread 5][clang] core/master_utils.o
    [thread 6][clang] core/emperor.o
    [thread 7][clang] core/notify.o
    [thread 1][clang] core/mule.o
    core/utils.c:3875:18: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
                                    va_start(ap, kv_separator);
                                                 ^
    core/utils.c:3832:73: note: parameter of type 'char' is declared here
    int uwsgi_kvlist_parse(char *src, size_t len, char list_separator, char kv_separator, ...) {
                                                                            ^
    1 error generated.
    ----------------------------------------
ERROR: Command "/usr/local/opt/python@2/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pycharm-packaging/uwsgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pip-record-FRXiUI/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x6/ynnx12554s1ch93rlckmh49w0000gn/T/pycharm-packaging/uwsgi/

**Comment by xrmx** [comment]
Use latest uwsgi. This is the second non-issue you open in a few hours, please investigate your problems more before reporting them here.

**Comment by royt-via** [comment]
@xrmx can you elaborate? why should one use the latest uwsgi if he has a reason to use that specific version (2.0.13.1)?
there shouldn't be any breaking changes between them (even though seems like there are)

**Comment by tajalagawani** [comment]
I think that the requirements file was created automatically and kept the pre-existing version on the main developer’s device.
For me I installed the latest uwsgi version and it seems to be working fine .
