### ISSUE TITLE
Can uwsgi support Windows platform directly not by Cygwin?

### ISSUE THREAD

**Issue by zgpnuaa** [unbit/uwsgi#2085]
uWsgi is great. I have a django application written in linux with uwsgi server, i wanan migrate it to Windows platform, but uwsgi cant be install on Windows conveniently.
Is there a difficult by pip install uwsgi on Windows?
It will be better to support Windows platform.
Thank you.

**Comment by xrmx** [comment]
Just use Windows subsystem for linux then.

**Comment by Gilthans** [comment]
I don't understand why this issue was closed.
The comment closing the issue makes no sense and doesn't respond to the original request.
