### ISSUE TITLE
How to run uwsgi server for django using Nginx?

### ISSUE THREAD

**Issue by ajipmdkr** [unbit/uwsgi#2101]
My uwsgi server is run using crontab commands, can you suggest a better way to run the uwsgi server for django using Nginx??
FYI:-
https://github.com/unbit/uwsgi/issues/2100

**Comment by xrmx** [comment]
Have you tried reading the documentation? https://uwsgi-docs.readthedocs.io/en/latest/
Please stop opening any new issue for the very same problem.
