### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by bpdev97** [unbit/uwsgi#2113]
Hi, I was unable to find anything related to python 3.8 support. Is python 3.8 support is already in the pipeline or can it already be used in some official capacity? Thanks!

**Comment by awelzel** [comment]
Hey @bpdev97 ,

this is no statement about official support, but uwsgi builds and starts inside a `python:3.8-buster` docker container/environment, maybe give it a try?

When #2114 is merged Python 3.8 will be very "lightly" tested in the travis pipeline as well.
