### ISSUE TITLE
Ubuntu error while building uwsgi 3.0 branch (pcre is still off): /uwsgi.h:1191:2: error: unknown type name ‘pcre’

### ISSUE THREAD

**Issue by hungcaovu** [unbit/uwsgi#2116]
While building the uwsgi  i wanna route plugins were built with define: UWSGI_ROUTING ON.
Then i turn on routing. It shown the error:

*** uWSGI compiling server core ***
[thread 0][x86_64-linux-gnu-gcc -pthread] core/utils.o
[thread 1][x86_64-linux-gnu-gcc -pthread] core/protocol.o
In file included from core/protocol.c:1:0:
./uwsgi.h:1191:2: error: unknown type name ‘pcre’
  pcre *pattern;
  ^~~~
In file included from core/utils.c:1:0:
./uwsgi.h:1191:2: error: unknown type name ‘pcre’
  pcre *pattern;
  ^~~~
./uwsgi.h:1192:2: error: unknown type name ‘pcre_extra’
  pcre_extra *pattern_extra;
  ^~~~~~~~~~
./uwsgi.h:1192:2: error: unknown type name ‘pcre_extra’
  pcre_extra *pattern_extra;
  ^~~~~~~~~~
(env) root@ubuntu-s-2vcpu-2gb-sgp1-01:~/uwsgi/uwsgi# UWSGI_PROFILE_OVERRIDE=routing=true python uwsgiconfig.py --build

Please show me how to fix it.
I am building the plugin for uwsgi, do you have any guideline for that.

Thanks,
Hung

**Comment by hungcaovu** [comment]
I solved it by installing pcre lib.

**Comment by xiaohesen** [comment]
> I solved it by installing pcre lib.

install command is apt install libpcre++-dev ?
