### ISSUE TITLE
Logging X-Forwarded-For header

### ISSUE THREAD

**Issue by nodje** [unbit/uwsgi#2134]
I can't seem to find a way to log the `X-Forwarded-For` header passed by Nginx.

Is there a way to achieve this?

**Comment by b0g3r** [comment]
@nodje, yes, sure: https://uwsgi-docs.readthedocs.io/en/latest/Options.html#log-x-forwarded-for

**Comment by nodje** [comment]
thanks a million, I really couldn't find anything on the web, and the readthedocs search yields nothing for `x-forwarded-for`
(that's a problem IMHO)

Am I right in understanding that I just need to put this in my .ini file ?
```
log-x-forwarded-for = true
```

**Comment by b0g3r** [comment]
Yes, I found an [example](https://github.com/changecoin/changetip-slack/blob/e10b9c1205a5ae8ab8074f520aa0b5ff5d562af0/uwsgi.ini#L18) on GitHub:

**Comment by nodje** [comment]
mighty good!
