### ISSUE TITLE
Chunked request decoding for CGI scripts

### ISSUE THREAD

**Issue by efficiosoft** [unbit/uwsgi#2140]
Hi all,

I'm trying to serve git-http-backend using uWSGI's cgi plugin. Arbitrarily large pulls and also small pushes (few KiB) work well so far, but as soon as I try to push around 2 MiB+, the request hangs and is finally killed by CGI timeout after 60 seconds. I tried the same push via Apache CGI and that worked even for 100 MiB.

Here is how to reproduce it easily:

uwsgi.ini:
```
[uwsgi]
plugin = cgi,router_uwsgi
master = true
http-socket = :8081
threads = 4
# Might need to be changed to /usr/libexec/git-core/git-http-backend for some distros
cgi = /usr/lib/git-core/git-http-backend
route-run = addvar:GIT_PROJECT_ROOT=.
route-run = addvar:GIT_HTTP_EXPORT_ALL=1
# git-http-backend only accepts pushes from authenticated users
route-run = addvar:REMOTE_USER=foo
route-run = uwsgi:,9,0
```

Then I ran uWSGI and did:
```
# git --version
git version 2.20.1
# git init --bare repo
Initialized empty Git repository in /home/roschi/repo/
# git clone http://localhost:8081/repo clone
Cloning into 'clone'...
warning: You appear to have cloned an empty repository.
# cd clone
# cp ../large_file .
# git add .
# git commit -m test
[master (root-commit) d581323] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 large_file
# git push
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
error: RPC failed; curl 55 Send failure: Connection reset by peer
fatal: the remote end hung up unexpectedly
Writing objects: 100% (3/3), 2.43 MiB | 41.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Here is uWSGI's output:
```
# uwsgi --ini uwsgi.ini
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18-debian (64bit) on [Fri Apr  3 10:59:09 2020] ***
compiled with version: 8.2.0 on 10 February 2019 02:42:46
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: xxx
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/roschi
detected binary path: /usr/bin/uwsgi-core
*** dumping internal routing table ***
[rule: 0] action: addvar:GIT_PROJECT_ROOT=.
[rule: 1] action: addvar:GIT_HTTP_EXPORT_ALL=1
[rule: 2] action: addvar:REMOTE_USER=foo
[rule: 3] action: uwsgi:,9,0
*** end of the internal routing table ***
your processes number limit is 62445
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8081 fd 3
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 208576 bytes (203 KB) for 4 cores
*** Operational MODE: threaded ***
initialized CGI path: /usr/lib/git-core/git-http-backend
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19672)
spawned uWSGI worker 1 (pid: 19673, cores: 4)
[pid: 19673|app: -1|req: -1/1] 127.0.0.1 () {36 vars in 482 bytes} [Fri Apr  3 10:59:27 2020] GET /repo/info/refs?service=git-upload-pack => generated 38 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 189 bytes (0 switches on core 1)
[pid: 19673|app: -1|req: -1/2] 127.0.0.1 () {36 vars in 484 bytes} [Fri Apr  3 10:59:48 2020] GET /repo/info/refs?service=git-receive-pack => generated 180 bytes in 6 msecs (HTTP/1.1 200) 4 headers in 190 bytes (0 switches on core 0)
[pid: 19673|app: -1|req: -1/3] 127.0.0.1 () {34 vars in 463 bytes} [Fri Apr  3 10:59:48 2020] POST /repo/git-receive-pack => generated 0 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 183 bytes (0 switches on core 2)
CGI timeout !!!
fatal: the remote end hung up unexpectedly
[pid: 19673|app: -1|req: -1/4] 127.0.0.1 () {36 vars in 514 bytes} [Fri Apr  3 10:59:48 2020] POST /repo/git-receive-pack => generated 0 bytes in 60047 msecs (HTTP/1.1 200) 4 headers in 183 bytes (0 switches on core 1)
```

Things I tried so far, none of which seemed to have an effect:
* `--cgi-buffer-size=100000000`
* running without master
* `--processes=4`` instead of `--threads=4`
* `--ugreen --async=100` instead of `--threads=4`
* `--offload-threads=1`
* uWSGI on alpine via Docker instead of Debian host

Does anyone have an idea what's happening here?

Thanks and all the best
Robert

**Comment by efficiosoft** [comment]
Hi again,

I think I've got one step further. The problem might be related to chunked encoding. I did `export GIT_CURL_VERBOSE=1` and there's a difference in how it sends small and large pushes.

This is a small one (~200 bytes) which succeeds:
```
...
* Connected to localhost (127.0.0.1) port 8081 (#1)
> POST /repo/git-receive-pack HTTP/1.1
Host: localhost:8081
User-Agent: git/2.20.1
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 370

* upload completely sent off: 370 out of 370 bytes
< HTTP/1.1 200 OK
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Content-Type: application/x-git-receive-pack-result
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 1
To http://localhost:8081/repo
 * [new branch]      master -> master
```

And this is a larger one (>1 MiB) that fails:
```
...
* Connected to localhost (127.0.0.1) port 8081 (#2)
> POST /repo/git-receive-pack HTTP/1.1
Host: localhost:8081
User-Agent: git/2.20.1
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Transfer-Encoding: chunked

Writing objects:  66% (2/3), 1.84 MiB | 2.06 MiB/s

... here it hangs for 60 seconds ...

< HTTP/1.1 200 OK
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Content-Type: application/x-git-receive-pack-result
* no chunk, no close, no size. Assume close to signal end
<
* Send failure: Connection reset by peer
* Closing connection 2
error: RPC failed; curl 55 Send failure: Connection reset by peer
fatal: the remote end hung up unexpectedly
Writing objects: 100% (3/3), 2.43 MiB | 41.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

I now also tried without luck:
* `--http-raw-body`

Could it be that somehow uWSGI doesn't forward chunks to the CGI script? Or is this something related to buffering?

**Comment by efficiosoft** [comment]
Me again...

I nailed it down.

CGI has no clue about chunked transfers, it always expects a Content-Length header to know how many bytes to read from stdin.

Now, there is the way Apache handles things:
When it forwards a chunked request to CGI, it decodes the chunk stream and forwards the original body. However, it leaves the `Transfer-Encoding: chunked` header in place, which I somehow consider weird behavior since the stream that's forwarded is no longer chunked, but nevermind. When the chunked stream ends, Apache inserts EOF and the script stops reading.

As far as git-http-backend is concerned, it simply seems to read until EOF whenever the Content-Length header is missing... which kind of makes sense to me, but that doesn't play well with uWSGI, because uWSGI never sends EOF.

Do you think uWSGI could/should be modified to do the chunk decoding while streaming chunked requests to CGI? Of course it would need to terminate the stream with EOF. The then obsolete `Transfer-Encoding: chunked` header could also be removed in the same run.

Best regards
Robert

**Comment by efficiosoft** [comment]
Tried to write a proxy script that transparently handles the stream dechunking, but it seems uWSGI forwards no data to stdin at all when the request is chunked, even a `sys.stdin.buffer.read(1)` blocks forever.

**Comment by efficiosoft** [comment]
Hi again,

Sorry for bumping this again so early, but is there any chance to get chunked requests decoding for CGI, maybe even backported to 2.0 (unless you have plans to release 2.1 in the near future of course)?

Is there anything I could do to support it being implemented? Maybe it's just a small change, but I'm totally unfamiliar with the codebase and my C is not fluent enough I fear. However, I would be very happy to donate for it, write docs and of course do testing once available.

This would really help my (albeit small) project because right now everything can run fully in uWSGI, from HTTP termination over routing and caching to the backends, and deploying and maintaining an Apache just for the purpose of calling a single CGI script feels quite unergonomic.

I'm not sure, but maybe the work related to `--wsgi-manage-chunked-input` done already (https://github.com/unbit/uwsgi/issues/1428) could help in the CGI case as well?

Thanks and best regards
Robert

**Comment by rdeioris** [comment]
Hi this is how you can manage chunked input in a plugin: https://github.com/unbit/uwsgi/blob/master/plugins/python/wsgi_handlers.c#L66

And here is how the cgi plugin manage it in a "raw" way:

https://github.com/unbit/uwsgi/blob/master/plugins/cgi/cgi_plugin.c#L709

Just call the smart chunked function instead of uwsgi_request_body_read if is_chunked is true

**Comment by efficiosoft** [comment]
Hi @rdeioris 

Thanks for your reply!

I actually went through these two functions this morning. What makes me uncertain is that this approach would first send the whole request body to the script and only then start reading the reply, effectively not allowing the script to send until it has read the whole request. While this is probably not needed by my particular application (git), it would limit the functionality somehow... Not sure how Apache behaves in this regard though.

For WSGI this seems not to be an issue since there read and write can be called explicitly by the app whenever it wants to.

Or am I missing something here and 2-way communication is a completely different issue anyway?

**Comment by rdeioris** [comment]
Hi, if you follow the code you should note that the cgi process is started before reading the request body, so the uWSGI worker will be busy while receiving the input but the cgi process can consume it concurrently (apache works in the same way). Just ensure you are reading little chunks (iirc should be 8k for the cgi plugin)

**Comment by efficiosoft** [comment]
Yes, that's clear to me so far, but what if the CGI process reads some chunks and then tries to start writing the, potentially large, response before it has consumed the whole request, wouldn't this write operation block because the uWSGI side is still in the input-reading phase and doesn't read from the CGI process's stdout yet?

**Comment by efficiosoft** [comment]
Wow, I plugged something together that works - albeit with the said restrictions, but it works great! Do you want a PR for this already without the ability for back and forth reads/writes?

**Comment by rdeioris** [comment]
@efficiosoft yep for sure, make a pull request!

**Comment by efficiosoft** [comment]
Hi @rdeioris 

Just did some more testing and chunked input handling for CGI seems to work perfect with `http-socket`. With the HTTP load balancer in front though, it's not reliable.

In ~25% of cases, the chunked smart read function returns the first chunk with `pos = 0`, causing my code to assume input was terminated and then closing stdin. uWSGI says this in the log (the "chunk received: ..." is just some debug logging telling the size returned by chunked smart read; the "fatal: ..." comes from git-http-backend because stdin got closed):

```
[pid: 4398|app: -1|req: -1/10] 127.0.0.1 () {40 vars in 524 bytes} [Sun Apr 19 12:52:31 2020] GET /repo/info/refs?service=git-receive-pack => generated 182 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 190 bytes (0 switches on core 3)
[pid: 4398|app: -1|req: -1/11] 127.0.0.1 () {38 vars in 503 bytes} [Sun Apr 19 12:52:33 2020] POST /repo/git-receive-pack => generated 0 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 183 bytes (0 switches on core 1)
chunk received: 0
fatal: the remote end hung up unexpectedly
[pid: 4398|app: -1|req: -1/12] 127.0.0.1 () {40 vars in 552 bytes} [Sun Apr 19 12:52:33 2020] POST /repo/git-receive-pack => generated 0 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 183 bytes (0 switches on core 2)
```

It can be reproduced with this config against #2147, compiled with cgi, http and corerouter plugins:

```
[uwsgi]
strict = true
plugins = 0:cgi,http
master = true
need-app = false
http = :8081
http-chunked-input = true
threads = 4
cgi = /usr/lib/git-core/git-http-backend
route-run = addvar:GIT_PROJECT_ROOT=.
route-run = addvar:GIT_HTTP_EXPORT_ALL=1
route-run = addvar:REMOTE_USER=foo
```

And this is what git client shows:

```
$ git clone http://localhost:8081/repo clone
$ cd clone
$ export GIT_CURL_VERBOSE=1

# And then repeat until it fails:
$ dd if=/dev/urandom of=large_file bs=1024 count=10000 && git add . && git commit -m test && git push
...
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555680ca980)
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /repo/info/refs?service=git-receive-pack HTTP/1.1
Host: localhost:8081
User-Agent: git/2.20.1
Accept: */*
Accept-Encoding: deflate, gzip
Accept-Language: C, *;q=0.9
Pragma: no-cache

< HTTP/1.1 200 OK
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Content-Type: application/x-git-receive-pack-advertisement
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
* Expire in 0 ms for 6 (transfer 0x5555680ca980)
* Couldn't find host localhost in the .netrc file; using defaults
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555680ca980)
* Expire in 200 ms for 4 (transfer 0x5555680ca980)
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555680ca980)
* Connected to localhost (127.0.0.1) port 8081 (#1)
> POST /repo/git-receive-pack HTTP/1.1
Host: localhost:8081
User-Agent: git/2.20.1
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 4

* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 200 OK
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Content-Type: application/x-git-receive-pack-result
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 1
* Expire in 0 ms for 6 (transfer 0x5555680ca980)
* Couldn't find host localhost in the .netrc file; using defaults
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555680ca980)
* Expire in 200 ms for 4 (transfer 0x5555680ca980)
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555680ca980)
* Connected to localhost (127.0.0.1) port 8081 (#2)
> POST /repo/git-receive-pack HTTP/1.1
Host: localhost:8081
User-Agent: git/2.20.1
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Transfer-Encoding: chunked

< HTTP/1.1 200 OK
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Content-Type: application/x-git-receive-pack-result
* no chunk, no close, no size. Assume close to signal end
<
* Send failure: Connection reset by peer
* Closing connection 2
error: RPC failed; curl 55 Send failure: Connection reset by peer
fatal: the remote end hung up unexpectedly
Writing objects: 100% (3/3), 9.77 MiB | 33.23 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Do you have any idea what's failing here?

**Comment by efficiosoft** [comment]
Ah, also tried with `--http-auto-chunked`, `--http-keepalive=1` and adding keepalive headers, no luck though.

**Comment by efficiosoft** [comment]
So I now basically switched to nginx as HTTP load balancer in front with `proxy_pass` to an uWSGI `http-socket`, `proxy_buffering off`, `proxy_request_buffering off` and `proxy_http_version 1.1` for chunked requests/responses to work. `uwsgi_pass` seems to be no option because it never passes chunked requests through, regardless of the setting of `uwsgi_buffering` and `uwsgi_request_buffering`.

I like this setup even more because it gives more flexibility with nginx's massive configurability, and it seems to be very reliable from my testing so far.

Do you have any plans of releasing a new uWSGI in the near future with my PR included? Actually building from source is not a big deal, but it feels a bit uncomfortable to use the dev version in production...

Thanks a lot for your help so far!
Robert
