### ISSUE TITLE
Wheels for uwsgi

### ISSUE THREAD

**Issue by bsolomon1124** [unbit/uwsgi#2162]
Hello, I noticed that uWSGI as of 2.0.18 [provides only an sdist](https://pypi.org/project/uWSGI/2.0.18/#files) and no wheels.

I am asking this out of curiosity rather than criticism: is there a reasoning and background for not providing wheels for uWSGI? What factors are stopping that from happening or making it difficult?

**Comment by xrmx** [comment]
See https://github.com/unbit/uwsgi/issues/1218
