### ISSUE TITLE
"TypeError: 'module' object is not callable"

### ISSUE THREAD

**Issue by diogobaeder** [unbit/uwsgi#2177]
Hi folks,

I've been having this error lately, running uwsgi + gevent + Flask: `TypeError: 'module' object is not callable`. However, no traceback is shown so that I can at least have a hint of where the issue is happening - I only see the exception message. Since there hasn't been any uwsgi release lately, I'm suspecting it's either on gevent or Flask, but I need more information from the error to track that down.

Is there anything I can do to spit out that traceback in the output? Or perhaps something I can run to emulate an application run to provoke that error and have the traceback in the output?

Thanks,
Diogo

**Comment by diogobaeder** [comment]
Actually, I just found out that this problem started happening with gevent 1.5.0, but with 1.4.0 uwsgi runs fine with no complaints.

Even with the latest gevent version, the application itself seems to run fine, I can make requests to it and get responses fine, but I keep getting those exceptions in the output.

Maybe there has been a change in the gevent API that uwsgi hasn't adapted to, yet?

**Comment by LKI** [comment]
may relates to #2144 ,which is fix in #2149 and not released yet

**Comment by LKI** [comment]
you may use `uwsgi==2.0.18 + gevent==1.4.0`, and wait for the fix to be released

**Comment by diogobaeder** [comment]
Yeah, those are the versions I'm using now, thanks! Is there an ETA for the next uwsgi version?

**Comment by LKI** [comment]
I think there isn't a milestone yet, see #2037, many of us are desire for a new release

**Comment by diogobaeder** [comment]
Thanks a lot! I'll close this ticket now.
