### ISSUE TITLE
PyPy 7.3.1 - ModuleNotFoundError: No module named 'os' - Issue setting pypy-home value

### ISSUE THREAD

**Issue by cmanallen** [unbit/uwsgi#2195]
* uwsgi 2.0.18
* Pypy 7.3.1 (Debian Buster)
* Running as root
* which pypy3 => `/opt/pypy/bin/pypy3`
* which uwsgi => `/opt/pypy/bin/uwsgi`

**Shell**

```
docker-compose run api uwsgi --ini uwsgi.ini
```

**uwsgi.ini**

```
[uwsgi]
chdir               = /app/project/
module              = wsgi:application

socket              = /tmp/uwsgi.sock
chmod-socket        = 666

enable-threads      = true
single-interpreter  = true
wsgi-disable-file-wrapper = true

threads             = 2
processes           = 5

## PyPy3 related settings
plugins = pypy
pypy-wsgi = project.wsgi:application
pypy-wsgi-file = /app/project/wsgi.py
pypy-home = /opt/pypy
pypy-lib = /opt/pypy/bin/libpypy3-c.so
```

Setting pypy-home to `/opt/pypy` raises this exception:

```
debug: OperationError:
debug:  operror-type: ModuleNotFoundError
debug:  operror-value: No module named 'os'
unable to set pypy home to "/opt/pypy"
```

Setting pypy-home to `/opt/pypy/bin/pypy3` suppresses the error but I still get this message: `unable to set pypy home to "/opt/pypy/bin/pypy3"`.

This configuration (minus the pypy section) worked with python 3.6.10.

**Comment by byo** [comment]
Hi @cmanallen, did you manage to solve it? I've encountered same issue when using [official pypy docker image](https://hub.docker.com/_/pypy) with django and uwsgi.

It looks like the image has changed a lot between the `3.6-7.3.0` and `3.6-7.3.1`, for example installation paths for pypy are now different:
```
$ docker run -it --rm --entrypoint /bin/bash pypy:3.6-7.3.0-slim which pypy3
/usr/local/bin/pypy3
$ docker run -it --rm --entrypoint /bin/bash pypy:3.6-7.3.1-slim which pypy3
/opt/pypy/bin/pypy3
```
however simple altering of paths in the uwsgi.ini (that worked in the old image version) did not fix the issue.

**Comment by cmanallen** [comment]
@byo I was not able to get it working.  I had to alter the pypy_setup files found online to get it to an almost working state.  I do not recommend attempting to get it to work.  Its clearly an unsupported extension.  You would have to have an unreasonable amount of faith in uwsgi to deploy this to production.

I ended up installing `gunicorn` instead which took very little time to setup.  I load tested uwsgi + python-3.7.7 versus gunicorn + pypy3.6-7.3.1.  uwsgi + python-3.7.7 was basically 6x gunicorn's performance.  Gunicorn was very unstable under load and would frequently lock up the server (I used a variety of configurations and worker types).  Whereas uwsgi would just raise some 500 exception and drop the request.  Latencies were (obviously) terrible under load for both types but uwsgi kept the server in a usable state.  Gunicorn hilariously returned a 500 error after 3 minutes of waiting even with the worker timeout set to 30 seconds.

Speaking of latencies, pypy3.6 + gunicorn produced latencies that were 5x my average on python-3.7.7 + uwsgi (steady 150ms vs. fluctuating 250-650ms).  This was on a server with zero load on it.

My application is a typical REST API.  SQLAlchemy's ORM and JSON (de)seraialization is probably my biggest compute.  If you have a different use case pypy3 may be worth it but I do NOT recommend gunicorn or uwsgi.

For now I plan to stay with uwsgi + python-3.7.7 since its both supported and performant enough for my needs.

---

If you do try to install pypy3 + uwsgi, I want to give you some tips.

1. Install your dependencies in a virtual environment (even on docker).  It makes the process of finding pypy_home much, much simpler (believe me...).

2. You will need to modify the pypy_setup file (even the ones you find online).  It has some errors in it when it comes to assigning the application to the `wsgi_application` global.

3. Some aspect of the pypy_setup cffi is wrong.  It doesn't pass the application to uwsgi correctly.  I don't know how to fix this.  This is the part that will require the most effort.  If you come up with a solution please let me know.

**Comment by byo** [comment]
Thanks @cmanallen for sharing your findings.

Currently I just hardcoded the `7.3.0` in my setup. Will see whether `cpython` is good enough for my case. `pypy` was needed to improve performance when the project was still using python2, maybe python3 is good enough now.
