### ISSUE TITLE
Unable to load app 0 (mountpoint = '') with Python 3.8.4

### ISSUE THREAD

**Issue by rhideg** [unbit/uwsgi#2206]
We tried to run one of our backend applications the same way as usual and after the python upgrade (to 3.8.4) it gave the following error(s). (We've downgraded our python version to 3.8.3 and it works perfectly.)

![Imgur](https://i.imgur.com/9e0PeKJ.png)

**Comment by xrmx** [comment]
@rhideg looks like an issue with sqlalchemy / flask_sqlachemy
