### ISSUE TITLE
offload threads conflict with cache2

### ISSUE THREAD

**Issue by yoobles** [unbit/uwsgi#2215]
I was recently trying to cache some HTML responses with uwsgi. I ran into an issue where every so often uwsgi would return an empty response. On other requests uwsgi would properly return the cached data. This would result in the browser showing an error about an invalid response. 

So every so often on one of the cached endpoints, you would get an error. Obviously not useful for production.

This was extremely difficult to debug because uwsgi has so many different options. I narrowed it down to be due to offload threads. 

Very similar issue to https://github.com/unbit/uwsgi/issues/925. 

If you enable offload threads and then attempt to cache a response, that response will occasionally fail. 

This was on uwsgi 2.0.19.1. The relevant switches as follows:

```
    --offload-threads 8 \
    --cache2="name=cache,items=100" \
    --route='^/$ cache:key=${REQUEST_URI},name=cache' \
```

As referenced in #925, adding `no_offload=true` to the cache key route fixes the issue.

**Comment by xrmx** [comment]
Looks like it's the same issue, closing this. Please update the other one any missing information, thanks.
