### ISSUE TITLE
Python requests to uwsgi simple app => BadStatusLine

### ISSUE THREAD

**Issue by Sebastiencreoff** [unbit/uwsgi#2216]
Hello,

I used uwsgi for about month now and it was working well until now.
Now, each time it try to a simple calls throw requests python package to uwsgi, I have this following error:

```Client Connection Error: ('Connection aborted.', BadStatusLine('Status: 200 Ok\r\n',))````

I tested with a simple application and I have the same:

`
import uwsgi
import os

print("!!! uWSGI version:", uwsgi.version)

def application(env, start_response):

    start_response('200 Ok', [('Content-type', 'text/plain')])
    return  [b"hello world"]
`
and a simple requests:
`root@e496f166b01f:/app# 
python 
Python 3.6.11 (default, Jun 30 2020, 19:21:43) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.post('http://localhost')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1364, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: Status: 200 Ok

`
python versions:

aiohttp                3.6.2
aiohttp-jinja2         1.2.0
async-timeout          3.0.1
attrs                  19.3.0
certifi                2020.6.20
chardet                3.0.4
click                  7.1.2
clickclick             1.2.2
connexion              2.7.0
Flask                  1.1.2
idna                   2.10
idna-ssl               1.1.0
importlib-metadata     1.7.0
inflection             0.5.0
itsdangerous           1.1.0
Jinja2                 2.11.2
jsonschema             3.2.0
MarkupSafe             1.1.1
multidict              4.7.6
openapi-spec-validator 0.2.9
pip                    20.2.1
pyrsistent             0.16.0
python-dateutil        2.8.1
PyYAML                 5.3.1
requests               2.24.0
setuptools             47.3.1
six                    1.15.0
swagger-ui-bundle      0.0.8
typing                 3.7.4.3
typing-extensions      3.7.4.2
urllib3                1.25.9
uWSGI                  2.0.19.1
Werkzeug               0.15.6
wheel                  0.34.2
yarl                   1.5.1
zipp                   3.1.0

uwsgi configuration file:
`[uwsgi]

http-socket = :80

module = wsgi.app

;;;;;;; Custom configuration ;;;;
log-config = config/logging_config.yml

pidfile = /tmp/api.pid
`
If you have any idea about how to solve, I would appreciate it. Thanks

**Comment by xrmx** [comment]
What have you changed? I guess http-socker for http? http-socket is to speak with proxy, is http is to speak directly to client

**Comment by Sebastiencreoff** [comment]
Thanks for this guess, I will try again with http configuration. I do not really known what I have change. I just know it was working previously but it looks really strange.

**Comment by Sebastiencreoff** [comment]
Same error.

How I generate this error:
I have a docker image where I set my software inside. To generate my software, I do a 'pip install .' 
- If I launch my docker without a volume mounted for sources. Then it works. 
If I add a volume inside this docker, then I do a 'pip install -e .' on my source folder inside my docker and in this case, it raises this error. 

I really do not understand this behavior.

**Comment by awelzel** [comment]
Hello @Sebastiencreoff , are you by any chance using the `-c` parametere in your command-line to start `uwsgi` ?

`-c` will enable cgi mode. That would explain the BadStatusLine error you're seeing:
```
# uwsgi will  actually run in CGI mode
$ uwsgi -c config.ini

# other terminal
$ curl localhost:8080
curl: (1) Received HTTP/0.9 when not allowed

# ... this is because the first line is a Status: 200 Ok instead of HTTP/1.1 200 Ok

$ nc localhost 8080
GET / HTTP/1.1^M
Host: localhost^M
^M
Status: 200 Ok
Content-Type: text/plain
```
Remove `-c` if you use it.

I would agree that `-c` should be a shortcut for `--config`, but that's not the case: It's a shortcut for `--cgi-mode`.

Hope that helps.

**Comment by Sebastiencreoff** [comment]
Hi @awelzel,

Thanks a lot for your comment. It fixs my issue.

My bad,

Sorry for that.
I will close this issue.
