### ISSUE TITLE
how can i  exec a  function  while  uwsgi start?

### ISSUE THREAD

**Issue by uct8086** [unbit/uwsgi#2247]
i just want  exec a function when uwsgi start (python vertion)
like this:

   
if __name__ == '__main__':
        fun()

**Comment by marc1n** [comment]
You can use `eval` option (https://uwsgi-docs.readthedocs.io/en/latest/Options.html#eval), for example:

```
uwsgi --http=:1234 --eval='print("\nHello!\n" * 2)'
```

**Comment by uct8086** [comment]
@marc1n thx , i resolved this problem
