### ISSUE TITLE
Usage of NID_X9_62_prime256v1 results in weaker key exchange rating

### ISSUE THREAD

**Issue by spacesynth** [unbit/uwsgi#2259]
Usage of ```NID_X9_62_prime256v1``` results in weaker key exchange rating.
It should be dropped in favour of the more secure ```NID_secp384r1```.

As Let's Encrypt certs and all state of the art browser Chrome, Firefox, etc. support P384, you downgrade the security by performing the actual key exchange only over a 256-bit prime field.

I will attempt to recompile an own version supporting it in the meantime. Literally NGINX and regular SSL context support defining either ```set_ecdh_curve secp384r1;``` or ```sslcontext.set_ecdh_curve("secp384r1")```.

It should be an option in here as well.

**Comment by vaporwave9** [comment]
Two line fix at:
https://github.com/unbit/uwsgi/blob/master/core/ssl.c#L278
```
#ifdef NID_secp384r1
        EC_KEY *ecdh = EC_KEY_new_by_curve_name(NID_secp384r1);
```
Followed by building from source:
```python3 uwsgiconfig.py --build```
Yields:
![grafik](https://user-images.githubusercontent.com/64961250/100613742-4fbc4380-3315-11eb-9ab0-8eb8c11cd7f8.png)
![grafik](https://user-images.githubusercontent.com/64961250/100613752-534fca80-3315-11eb-864a-2fc38bad857e.png)

Pros:
Future ready for crypto freaks.
Con:
Some 10 year old legacy device might have trouble connecting.

**Comment by vaporwave9** [comment]
I am still watching this and interested in an official statement.

**Comment by vaporwave9** [comment]
I am still watching this with interest in an official statement.
