### ISSUE TITLE
Missing uwsgi.dll

### ISSUE THREAD

**Issue by jmelich** [unbit/uwsgi#2260]
After some installation tries there is no way to get uwsgi.dll in /usr/lib/uwsgi/uwsgi.dll on a Ubuntu 18 and neither in a Ubuntu 20.

I've also searched in entire system and there isn't the file.

From the official documentation: if i do `apt-get install build-essential python mono-xsp4 asp.net-examples`
i'll get "At the end of the procedure (if all goes well) you will get the path to the uwsgi.dll assembly."
[Link to documentation section](https://uwsgi-docs.readthedocs.io/en/latest/Mono.html#building-uwsgi-mono)

**Comment by xrmx** [comment]
The github actions that builds the mono plugin prints this:
*** uwsgi.dll available in /home/runner/work/uwsgi/uwsgi/plugins/mono/uwsgi.dll ***
