### ISSUE TITLE
--log-filter option is missing

### ISSUE THREAD

**Issue by borune-k12** [unbit/uwsgi#2272]
I've installed latest version of uwsgi (2.0.19.1) on Ubuntu and there is no option _**--log-filter**_, which should be there according the [docs](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#log-filter)

**Comment by xrmx** [comment]
They're probably building without pcre support:

```
~/src/uwsgi$ ./uwsgi --version
2.0.19.1
~/src/uwsgi$ ./uwsgi --log-filter
./uwsgi: option '--log-filter' requires an argument
getopt_long() error
```
