### ISSUE TITLE
[strict-mode] unknown config directive: log-route

### ISSUE THREAD

**Issue by jamercee** [unbit/uwsgi#2275]
We created the following config based on guidance https://uwsgi-docs.readthedocs.io/en/latest/Logging.html#log-routing

```
[uwsgi]
logger = file:/var/log/service.log
logger = errorlogger syslog:bvservice_p1
log-route = errorlogger (HTTP/1.\d [45]\d\d)
strict = true

```
uwsgi 2.0.19.1 reports
`[strict-mode] unknown config directive: log-route`

**Comment by xrmx** [comment]
It requires libpcre and your uwsgi is not build with libpcre support.

**Comment by jamercee** [comment]
Perfect -- thanks.
