### ISSUE TITLE
Support direct pip installation on windows platform

### ISSUE THREAD

**Issue by Gilthans** [unbit/uwsgi#2319]
While supporting uwsgi via cygwin installation from source is awesome, it is very cumbersone for windows users. It is especially cumbersome to set up appropriate docker files for a windows machine with uwsgi.
It would be more awesome to have prebuilt binaries so that `pip install uwsgi` would work.

Are there bottlenecks to this currently?
Is there a plan to add such support?

**Comment by xrmx** [comment]
There is no plan to have uwsgi run on windows. If cygwin or WSL is not an option then change your plan.
