### ISSUE TITLE
Proper way to utilize locks to coordinate worker processes when updating cache

### ISSUE THREAD

**Issue by nnoto** [unbit/uwsgi#2322]
The service i'm working uses the uwsgi cache to record statistics about the service. When an API call is made to the service, the uwsgi process that handles the request is responsible for updating different values in the cache. However, without proper locking when the worker processes are interacting with the cache, one process may overwrite data from another if both are updating the cache simultaneously.

I originally was using the following routine:
``` python
if not uwsgi.is_locked():
    uwsgi.lock()
    if uwsgi.cache_exists("key1"):
         key1_data = uwsgi.cache_get("key1")
         # update key1_data with additional values
         uwsgi.cache_update("key1", updated_key1_data)
    else:
        uwsgi.cache_set("key1", new_data)
    uwsgi.unlock()

```

but it seems this strategy could still encounter a race condition in various places, such as if uwsgi.is_locked() evaluates to false for some Process A, but Process B acquires the lock before Process A can. Would Process A then wait at "uwsgi.lock()" until the lock was available again? Or alternatively a situation where Process A reads the cache, process B updates the cache, and Process A then updates the cache, overwriting the new changes from Process B.

After realizing this may not be the most ideal solution, I stumbled across the uwsgi decorators for Python. 
It's somewhat challenging to test this is working correctly, so I was wondering if the following function with lock decorator would satisfy the usecase I described and handle the locking issues. That is, if the following function is the only way my uwsgi workers are updating the cache, would the decorator block other uwsgi workers trying to call this function while one worker process is executing the function? and would those other uwsgi workers then begin executing the function in turn as the lock becomes available?

``` python
@lock
def update_uwsgi_cache(data):
    if uwsgi.cache_exists("key1"):
         key1_data= uwsgi.cache_get("key1")
         # update key1_data with additional values from data param
         uwsgi.cache_update("key1", updated_key1_data)
    else: 
        uwsgi.cache_set("key1", data)

```

**Comment by xrmx** [comment]
It looks like the decorated functions will do what you want. Using something `cache_inc` may simplify things though, it's not documented but it's implemented in the source code :sweat_smile:
