### ISSUE TITLE
uWSGI reports every request is processed on the same core.

### ISSUE THREAD

**Issue by itsjohncs** [unbit/uwsgi#233]
We are running uWSGI on a multicore server. uWSGI is reporting that _core 0_ is the only core that is being used despite `uwsgitop` reporting that many workers are being utilized. The affinity has been set correctly for each of the worker processes (I went and examined proc myself), so I don't see any reason for this. As far as I can see our configuration is set up correctly.

This is one of the log messages from our syslog that uWSGI puts out, notice that it says `(1 switches on core 0)`. Every single log message like this has that `on core 0` at the end. _(Note: I redacted a few things)_

```
Apr 16 09:38:05 server uwsgi-foobar: [pid: 99999|app: 0|req: 3572/3919] 1.1.1.1 () {40 vars in 627 bytes} [Tue Apr 16 09:38:05 2013] GET /delicious => generated 1469 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 247 bytes (1 switches on core 0)
```

Below is our configuration file (redacted again):

```
[uwsgi]
socket=/some_unix_socket.sock
module=foo.bar:app
pidfile=/something_reasonable
single-interpreter=true
chmod-socket=666
workers=16
master=true
vacuum=true
log-syslog=uwsgi-foobar
cpu-affinity=4
stats=/tmp/stats.socket
```

**Comment by hungnv132** [comment]
@brownhead @unbit I have the same problem, how to fix this? Please!

**Comment by hungnv132** [comment]
My config:
`[uwsgi]
project         = blog
base            = /home/hungnv132/project
chdir           = /home/hungnv132/project/blog
module          = blog.wsgi:application
home            = /home/hungnv132/project/env
env             = DJANGO_SETTINGS_MODULE=blog.settings.production
uid             = www-data
gid             = www-data
processes       = 4
workers         = 4
http            = 0.0.0.0:8080
chmod           = 664
master          = true
~                        `
