### ISSUE TITLE
Compilation in Python 3.10

### ISSUE THREAD

**Issue by jrd** [unbit/uwsgi#2330]
`pyloader.c` assumes the minor version is [one digit](https://github.com/unbit/uwsgi/blob/master/plugins/python/pyloader.c#L49).
This should be changed at python 3.10 home is `/lib/python3.10` which make 16 characters (counting final null byte).

Appart that error, it seems it runs fine on 3.10 (beta 2).

**Comment by unbit** [comment]
@jrd great, would you like to make a pull request ?

**Comment by jrd** [comment]
Yes if I have the time this week I will ;-)

**Comment by jrd** [comment]
Here it is #2331

**Comment by jrd** [comment]
Any news @unbit about this MR?
