### ISSUE TITLE
pyuwsgi doesn't have 2.0.20 release on PyPI

### ISSUE THREAD

**Issue by messense** [unbit/uwsgi#2366]
https://github.com/unbit/uwsgi/releases/tag/2.0.20
https://pypi.org/project/pyuwsgi/

**Comment by xrmx** [comment]
cc @ipmb

**Comment by ipmb** [comment]
✅ done!

Changes are in https://github.com/lincolnloop/pyuwsgi-wheels and release is at https://pypi.org/project/pyuwsgi/2.0.20/

This includes wheels for musl and Python 3.10 as well.

**Comment by messense** [comment]
Great! Thank you!
