### ISSUE TITLE
Licensing issue - some files have headers specifying a different license from the global one

### ISSUE THREAD

**Issue by NielsDoucet** [unbit/uwsgi#2401]
While performing our OSS-related due diligence, we found that the following files are not marked with the GPL 2 linking exception:
- [apache2/mod_Ruwsgi.c](https://github.com/unbit/uwsgi/blob/master/apache2/mod_Ruwsgi.c)
- [apache2/mod_proxy_uwsgi.c](https://github.com/unbit/uwsgi/blob/master/apache2/mod_proxy_uwsgi.c)
- [plugins/router_xmldir/router_xmldir.c](https://github.com/unbit/uwsgi/blob/master/plugins/router_xmldir/router_xmldir.c)
- [apache2/mod_uwsgi.c](https://github.com/unbit/uwsgi/blob/master/apache2/mod_uwsgi.c)
- [core/uwsgi.c](https://github.com/unbit/uwsgi/blob/master/core/uwsgi.c)

They are marked solely as under GPL 2. Is this intentional or an oversight? We're just trying to fully understand our obligations with respect to this package. Thanks!

**Comment by rdi-mindesk** [comment]
Hi @NielsDoucet , the project will be moved to MIT in the next few weeks, but definitely it is an oversight

**Comment by NielsDoucet** [comment]
Thank you for the fast response. While the migration to the MIT license is ongoing, should I open a PR to remove the deviating license headers from these files?

**Comment by unbit** [comment]
@NielsDoucet yes please :) would be really appreciated
