### ISSUE TITLE
Traefik and uwsgi causes uploads to error

### ISSUE THREAD

**Issue by dunkfordyce** [unbit/uwsgi#2410]
I am running a wsgi application in uwsgi which handles file uploads. I can run this behind nginx with both `socket` and `http-socket` without errors. 

If I however try and use [traefik ](https://traefik.io/) I occasionly get 

  ```[uwsgi-body-read] Error reading 42930 bytes. Content-Length: 1049841 consumed: 512650 left: 537191 message: Success```
and 
  ```IOError: error during readline(65536) on wsgi.input```

I realise this may not be a bug in uwsgi but maybe someone has an idea on the solution?

**Comment by robert-graham** [comment]
What happens if you use `http11-socket` instead? Asking because there can be http and tcp keepalive mismatches between uWSGI and upstream proxies and it sometimes depends on the protocol version you're using for the socket. I ran into a similar bug (I think) running uWSGI behind linkerd, which does this seamless upgrade of http 1.1->2 behind the scenes and doesn't handle it gracefully when uWSGI wants to end the connection.

**Comment by dunkfordyce** [comment]
Thanks for the suggestion. While it doesnt work it does at least give a different error message 
  ```[uwsgi-body-read] Error reading 49125 bytes. Content-Length: 1049837 consumed: 49125 left: 1000712 message: Resource temporarily unavailable
```

**Comment by dunkfordyce** [comment]
Researching that error message I increased the `listen` option which changes the error to:
  `[pid: 84|app: 0|req: 1002/1002] 0.0.0.0 () {64 vars in 2789 bytes} [Thu Mar  3 08:42:21 2022] POST /myaccount/files/upload => generated 159 bytes in 481 msecs (HTTP/1.1 202) 5 headers in 153 bytes (62 switches on core 1)
...The work of process 84 is done. Seeya!`

At which point traefik complains with:
  `time="2022-03-03T08:42:22Z" level=debug msg="'502 Bad Gateway' caused by: readfrom tcp 10.0.3.154:52358->10.0.3.156:9000: write tcp 10.0.3.154:52358->10.0.3.156:9000: use of closed network connection"`

It seems like the traefik is taking the closed connection as an error when it shouldnt..?

**Comment by robert-graham** [comment]
What happens if you make this post request directly to uWSGI, bypassing traefik? My guess is that the solution will be in the traefik config, but I'm not familiar enough with it to say. Might help to include your traefik and uWSGI configs.

**Comment by dunkfordyce** [comment]
I appear to have solved the issue with the following:
 * use http11-socket 
 * increasing `listen` value ( not sure if this is actually required )
 * [this issue](https://github.com/traefik/traefik/issues/3237#issuecomment-514178590) hinted at setting maxIdleConnsPerHost which seems to have fixed it. I needed the following traefik configuration to make it work:
    ``` 
    serversTransports:
      mytransport:
        disableHTTP2: true
        maxIdleConnsPerHost: -1
    ```

Thanks for the help
