### ISSUE TITLE
uwsgi Compile error, python=3.8.0

### ISSUE THREAD

**Issue by lla-lla** [unbit/uwsgi#2427]
I get this error when running "pip install uwsgi==2.0.18 or pip install uwsgi" in a python 3.8.0 environment:
ubuntu version: 18.04
python version: 3.8.0
gcc version: 7.5 / 4.8
![1649761799(1)](https://user-images.githubusercontent.com/74390960/162947497-b248a953-508e-4e2d-914e-577b4149756d.png)
![1649761225(1)](https://user-images.githubusercontent.com/74390960/162947573-49420a78-8683-450a-8798-ce4a3791e5cf.png)
![1649761204(1)](https://user-images.githubusercontent.com/74390960/162947602-0225830b-9cdb-43a7-9a55-c53046fff26c.png)
![1649761947(1)](https://user-images.githubusercontent.com/74390960/162947819-bd349b0b-a141-4074-bb8b-0ec57a2795c5.png)

**Comment by xrmx** [comment]
Reproduce with latest release and post text and not a screenshot please.
