### ISSUE TITLE
PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by bohdansolovey** [unbit/uwsgi#2440]
uwsgi version: uwsgi==2.0.20
python version: [CPython 3.10.4]
image: python:3.10-slim 
`
uwsgi.cache_get(key, cls.cache_name) 
`
fails because of 
`PY_SSIZE_T_CLEAN macro must be defined for '#' formats`
is there any fix for this?

**Comment by tebi-cloud** [comment]
We have exactly the same problem, the only thing that works is downgrading to the previous Python version.

**Comment by xrmx** [comment]
It should already fixed in the uwsgi-2.0 branch so you can install that with pip.

**Comment by bohdansolovey** [comment]
thank you

**Comment by jlecount** [comment]
Also hoping this might be merged soon - i'm not too comfortable running production services off non-mainline branches.  Is there a plan for when this might happen?
