### ISSUE TITLE
Consider porting to PCRE2

### ISSUE THREAD

**Issue by musicinmybrain** [unbit/uwsgi#2486]
The original PCRE library [has just reached end-of-life with release 8.45](https://pcre.org/), and is now unmaintained. Please consider porting to PCRE2.

Fedora Linux has [deprecated](https://www.fedoraproject.org/wiki/PcreDeprecation) the original PCRE library, meaning no new packages may depend on it, and in the medium term the current maintainers would like to retire it, which would affect the [`uwsgi` package](https://src.fedoraproject.org/rpms/uwsgi) in Fedora.

**Comment by coolo** [comment]
Not that it's not just Fedora. Basically every Linux distribution out there has interest to remove PCRE 8.45

**Comment by xrmx** [comment]
Both RHEL 7 and ubuntu 18.04 seems to have pcre2 so hopefully we can avoid maintaining support for both.

**Comment by diederikdehaas** [comment]
Debian has an issue for this too: https://bugs.debian.org/999936

**Comment by utkonos** [comment]
All the libpcre3 packages in Ubuntu have "Old" in the package description now.

https://packages.ubuntu.com/kinetic/libpcre3-dev

**Comment by dvzrv** [comment]
I have just added a [TODO for Arch Linux to move to pcre2](https://archlinux.org/todo/move-to-pcre2/).

@xrmx it would be great if https://github.com/unbit/uwsgi/pull/2543 could be merged and released! :)

**Comment by xrmx** [comment]
This was released in 2.0.25
