### ISSUE TITLE
linux-arm64 support

### ISSUE THREAD

**Issue by WMRamadan** [unbit/uwsgi#2488]
**Problem:**

conda package uwsgi does not exist for linux-arm64 platform.

**Solution:**

provide a build for linux-arm64 platform.

**Specs:**

Conda Channel: conda-forge
python: 3.8

**Comment by xrmx** [comment]
You should file conda issues on conda, not here.

**Comment by rafrafek** [comment]
@WMRamadan if the issue still persists you can report it here: 
https://github.com/conda/conda/issues 
please include link to this issue in the new issue, so it will be visible for people landing here.
