### ISSUE TITLE
Question: uwsgi and pypi

### ISSUE THREAD

**Issue by paaguti** [unbit/uwsgi#2490]
Hi,

I see that the last version in pypi is from 2021. Will it run with Python3.10? I have experienced issues with Ryu when porting it to Python 3.10 and they were generated by Lock handling in the uWSGI version defined in the requirements file.

**Comment by ravermeister** [comment]
Hi, 
I have problems installing uwsgi with python3.11 and 3.10. only 3.9 workds. Will there be a new pypi release soon?

**Comment by rectalogic** [comment]
3.10 definitely has issues if you use any uwsgi native apis https://github.com/unbit/uwsgi/issues/2418

**Comment by xrmx** [comment]
In the meantime you can install from the uwsgi-2.0 branch which will be tagged as 2.0.21.
