### ISSUE TITLE
Please create a new version (2.0.20.1) that include the PHP plugin fixes

### ISSUE THREAD

**Issue by nilsfr** [unbit/uwsgi#2492]
As the php plugin that comes with release 2.0.20 do not work with PHP 8 or 8.1 I would appreciate if you can create a new version that includes the PHP fixes.

The plugin has been removed from Ubuntu Jammy (22.04) <https://bugs.launchpad.net/ubuntu/+source/uwsgi-plugin-php/+bug/1960356> because it do not work.

I built the plugin from the uwsgi-2.0 branch and it works.

**Comment by xrmx** [comment]
Dup of #2490
