### ISSUE TITLE
Create new release to support Python 3.11

### ISSUE THREAD

**Issue by robd003** [unbit/uwsgi#2501]
Currently when trying to install uwsgi via pypi it will fail on Python 3.11

However installing from the master branch works fine. Could you please create a new release so Python 3.11 users won't encounter issues?

**Comment by xrmx** [comment]
Have you tried 2.0.21? https://pypi.org/project/uWSGI/2.0.21/

**Comment by robd003** [comment]
Holy crap, that was just published 4 minutes ago. Re-running test!

**Comment by robd003** [comment]
Works perfectly, thanks!
