### ISSUE TITLE
Missing release notes for 2.0.21

### ISSUE THREAD

**Issue by intgr** [unbit/uwsgi#2503]
Hi! The release notes page in documentation does not have any information about the recently released uWSGI 2.0.21: https://uwsgi-docs.readthedocs.io/en/latest/#release-notes

Thanks for your continued maintenance of uWSGI.

**Comment by xrmx** [comment]
Changelog is there it's just not linked, see https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.21.html . Care to open a pr on uwsgi-docs repo index.rst?

**Comment by intgr** [comment]
Ah I see, created https://github.com/unbit/uwsgi-docs/pull/515
