### ISSUE TITLE
Python's ctypes broken under Python 3.11 (_dlopen TypeError)

### ISSUE THREAD

**Issue by tgs** [unbit/uwsgi#2513]
The following minimal app works for me in uwsgi 2.0.21 under Python 3.9, but not 3.11:

```
import ctypes

def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return [b"Hello World"]
```

I get this traceback:
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import ctypes
  File "/opt/python-3.11/lib/python3.11/ctypes/__init__.py", line 466, in <module>
    pythonapi = PyDLL(None)
                ^^^^^^^^^^^
  File "/opt/python-3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Could you take a look?

**Comment by xrmx** [comment]
Have you tried importing it from a python3.11 repl?

**Comment by tgs** [comment]
Yes, it works fine from the repl

**Comment by xrmx** [comment]
Adding these into your module:

```
import sys
import ctypes
print("ctypes", ctypes)
print("version", sys.version)
```

does print the following:

```
ctypes <module 'ctypes' from '/usr/lib/python3.11/ctypes/__init__.py'>
version 3.11.0+ (main, Nov  4 2022, 09:23:33) [GCC 12.2.0]
```

So maybe some paths are off and your python does not find what it needs.

**Comment by tgs** [comment]
>>> import sys
    >>> import ctypes
    >>> print("ctypes", ctypes)
    ctypes <module 'ctypes' from '/opt/python-3.11/lib/python3.11/ctypes/__init__.py'>
    >>> print("version", sys.version)
    version 3.11.1 (main, Dec  7 2022, 09:19:46) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]


It's possible that it's specific to my organization's python install, I'll try it somewhere else...

**Comment by tgs** [comment]
Ugh, it works fine in a `pyenv` install of python 3.11, that's distressing.  Sorry I didn't try that before opening the bug, thanks for your help.

**Comment by tgs** [comment]
It seems to be related to our copy of Python linking OpenSSL statically, rather than to the new Python version per se.

(no need for a response unless this twigs an idea, just leaving a note in case this happens to someone else)

**Comment by tgs** [comment]
Summary from my very intrepid coworker Paul:

Our local method of linking Python 3.11.1 statically to an Openssl 1.1.1k library using the extra LDFLAGS "-Bsymbolic" appears to somehow trigger this issue. When that flag is removed from the Python 3.11.1 build against said static library the issue does not occur.

History of that flag comes from a prior static link to work around CentOS 7 distro OpenSSL older versions in the Cryptography Python module. A dynamic OpenSSL 1.1.1 library is not currently available in this environment. Linking dynamically confirmed to not cause same problem in other test outside the environment.
