### ISSUE TITLE
How to catch the signal of harakiri?

### ISSUE THREAD

**Issue by Liubey** [unbit/uwsgi#2530]
I mean, I use dd-trace or opentelemetry sdk to report trace data.
When harakiri occurred, the worker just killed(whatever killed by signal 9 or signal 15)
So, how to setup a signal to catch harakiri? 
Cause the request/response of harakiri is very important, and I don't want to miss it.

**Comment by xrmx** [comment]
This has been fixed in https://github.com/unbit/uwsgi/pull/2523

**Comment by Liubey** [comment]
@xrmx 
look at this issue, I can not prove the signal is fired.
https://github.com/unbit/uwsgi/issues/2696
