### ISSUE TITLE
A lot of uWSGI core dumps generated on shutdown!?

### ISSUE THREAD

**Issue by lorandvarga** [unbit/uwsgi#2540]
Hello,

This might not necessarily be a bug but not sure where to post (it might be). (Using django==3.2.19, uWSGI==2.0.21 and python3.10)

I'm getting:
`
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::runtime_error'
what(): Accessing state after destruction.
DAMN ! worker 1 (pid: 2591) MISTERIOUSLY killed by signal 6 :( trying respawn ...
`
and can't seem to find any route cause for it.
What I do see is that a lot of core dumps are generated and there seems to be a segmentation fault (or something similar - null pointer related) in libssl?

The core dumps end in:
`
 0x00007f21de95b000  0x00007f21de95c000  0x0000000000000085
        /usr/lib/x86_64-linux-gnu/libssl.so.1.1
    0x00007f21de95c000  0x00007f21de965000  0x0000000000000085
        /usr/lib/x86_64-linux-gnu/libssl.so.1.1
    0x00007f21de965000  0x00007f21de969000  0x000000000000008e
        /usr/lib/x86_64-linux-gnu/libssl.so.1.1
    0x00007f21de969000  0x00007f21de96c000  0x0000000000000000
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de96c000  0x00007f21de97d000  0x0000000000000003
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de97d000  0x00007f21de983000  0x0000000000000014
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de983000  0x00007f21de984000  0x000000000000001a
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de984000  0x00007f21de985000  0x000000000000001a
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de985000  0x00007f21de986000  0x000000000000001b
        /lib/x86_64-linux-gnu/libz.so.1.2.11
    0x00007f21de986000  0x00007f21de987000  0x0000000000000000
        /lib/x86_64-linux-gnu/libdl-2.31.so
    0x00007f21de987000  0x00007f21de989000  0x0000000000000001
        /lib/x86_64-linux-gnu/libdl-2.31.so
    0x00007f21de989000  0x00007f21de98a000  0x0000000000000003
        /lib/x86_64-linux-gnu/libdl-2.31.so
    0x00007f21de98a000  0x00007f21de98b000  0x0000000000000003
        /lib/x86_64-linux-gnu/libdl-2.31.so
    0x00007f21de98b000  0x00007f21de98c000  0x0000000000000004
        /lib/x86_64-linux-gnu/libdl-2.31.so
    0x00007f21de98c000  0x00007f21de999000  0x0000000000000000
        /lib/x86_64-linux-gnu/libm-2.31.so
    0x00007f21de999000  0x00007f21dea33000  0x000000000000000d
        /lib/x86_64-linux-gnu/libm-2.31.so
    0x00007f21dea33000  0x00007f21deace000  0x00000000000000a7
        /lib/x86_64-linux-gnu/libm-2.31.so
    0x00007f21deace000  0x00007f21deacf000  0x0000000000000141
        /lib/x86_64-linux-gnu/libm-2.31.so
    0x00007f21deacf000  0x00007f21dead0000  0x0000000000000142
        /lib/x86_64-linux-gnu/libm-2.31.so
    0x00007f21dead0000  0x00007f21dead6000  0x0000000000000000
        /lib/x86_64-linux-gnu/libpthread-2.31.so
    0x00007f21dead6000  0x00007f21deae6000  0x0000000000000006
        /lib/x86_64-linux-gnu/libpthread-2.31.so
    0x00007f21deae6000  0x00007f21deaec000  0x0000000000000016
        /lib/x86_64-linux-gnu/libpthread-2.31.so
    0x00007f21deaec000  0x00007f21deaed000  0x000000000000001b
        /lib/x86_64-linux-gnu/libpthread-2.31.so
    0x00007f21deaed000  0x00007f21deaee000  0x000000000000001c
        /lib/x86_64-linux-gnu/libpthread-2.31.so
    0x00007f21deaf4000  0x00007f21deaf5000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deaf5000  0x00007f21deaf6000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deaf6000  0x00007f21deaf7000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deaf7000  0x00007f21deaf8000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deaf8000  0x00007f21deaf9000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deaf9000  0x00007f21deafa000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deafa000  0x00007f21deafb000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deafb000  0x00007f21deafc000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deafc000  0x00007f21deafd000  0x0000000000000000
        /lib/x86_64-linux-gnu/ld-2.31.so
    0x00007f21deafd000  0x00007f21deb1d000  0x0000000000000001
        /lib/x86_64-linux-gnu/ld-2.31.so
    0x00007f21deb1d000  0x00007f21deb25000  0x0000000000000021
        /lib/x86_64-linux-gnu/ld-2.31.so
    0x00007f21deb25000  0x00007f21deb26000  0x0000000000000000
        /dev/zero (deleted)
    0x00007f21deb26000  0x00007f21deb27000  0x0000000000000029
        /lib/x86_64-linux-gnu/ld-2.31.so
    0x00007f21deb27000  0x00007f21deb28000  0x000000000000002a
        /lib/x86_64-linux-gnu/ld-2.31.so
  CORE                 0x00000200	NT_FPREGSET (floating point registers)
  LINUX                0x00000a88	NT_X86_XSTATE (x86 XSAVE extended state)
   description data: 7f 03 00
`
Can anyone give some pointers on how I could debug more? I'm stuck.
Is there an underlying incompatibility between python3.10 and uwsgi?

Thank you!

**Comment by xrmx** [comment]
My guess is that you are using something shipping its own openssl version that is incompatible with the one linked with uwsgi, e.g. pyscopg2. Stop linking uwsgi to ssl or compile your packages against the same openssl.

**Comment by lorandvarga** [comment]
I am using psycopg2 (was using the psycopg2-binary but changed to psycopg2 to see if that makes a difference - it doesn't) but not entirely sure it's to blame. The error seems to be happening inside a threading library (but not fluent enough to build the app with debug signals enabled and the readelf does not give me any clear pointers). It seems to happen only on worker shutdown but this is totally uncharted territory for me. I do have some threading going on in my app so wondering if that could be the culprit. Are there any uwsgi docs around "stop linking uwsgi to ssl". Maybe those will trip me off to some correct path.

Thank you!

**Comment by lorandvarga** [comment]
Turns out this was caused by NewRelic python agent. Closing.
