### ISSUE TITLE
Python - Module uwsgiconfig using os.uname instead of os.name

### ISSUE THREAD

**Issue by centroculturaconocimiento** [unbit/uwsgi#2549]
Hi there,

When I run this command:

`pip install uwsgi==2.0.18`

I got this message:
```
 uwsgi_os = os.uname()[0]
      AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
 line 3, in <module>
import uwsgiconfig as uc

```

My OS is:;
![image](https://github.com/unbit/uwsgi/assets/140395288/3aeb81a2-b7e4-4ba1-b576-a2c4ef2a9432)

Python: 3.10
Pip: 23.2.1

Since I run this command by using PyCharm, this ide creates a temp folder which is non accessible due to this deletion.

Best regards.

**Comment by centroculturaconocimiento** [comment]
I have modified the line where os.uname is used to os.name and it works.
![image](https://github.com/unbit/uwsgi/assets/140395288/bef8c3c5-0c50-4eb5-befd-04e686711807)

**Comment by xrmx** [comment]
Hello, a couple of things:
- uwsgi does not work on windows
- as a general rule on reporting issues you are not using latest release so bug reports have little to no value.

**Comment by centroculturaconocimiento** [comment]
Thanks for clariyfing this point, @xrmx 
Best regards.
