### ISSUE TITLE
Missing release notes and git tag for version 2.0.22

### ISSUE THREAD

**Issue by intgr** [unbit/uwsgi#2550]
uWSGI version 2.0.22 recently appeared on PyPI (https://pypi.org/project/uWSGI/#history), but other sources don't list this version.

* The changelog does not have this version: https://uwsgi-docs.readthedocs.io/en/latest/#release-notes
* There is no git tag even: https://github.com/unbit/uwsgi/tags

I finally found this file in the `uwsgi-docs` repo, not sure if it's complete, it was last changed in March: https://github.com/unbit/uwsgi-docs/blob/master/Changelog-2.0.22.rst

**Comment by xrmx** [comment]
@intgr docs were building :sweat_smile: code was tagged but there was a typo in the command and so not pushed. You should find everything up now.

**Comment by intgr** [comment]
OK looks like we can consider this resolved now, thanks!
