### ISSUE TITLE
JRE path not found when building under C7 (missing variable expansion)

### ISSUE THREAD

**Issue by Lalufu** [unbit/uwsgi#2552]
The 2.0.22 release included a patch that reworked the include/lib search for the JVM plugin a bit.

It looks like this should be a format string but is missing the `% (jvm,)` bit?
https://github.com/unbit/uwsgi/blob/b3e09ceadc68086e9e0e5b636f1830a18a08e291/plugins/jvm/uwsgiplugin.py#L39

**Comment by xrmx** [comment]
Indeed, what's c7 btw?

**Comment by Lalufu** [comment]
Ah, sorry, that would be CentOS7, the only RHEL version for which the
jvm plugin gets built, that's how I noticed.

**Comment by xrmx** [comment]
Anyay I don't expect a change of behaviour from since 2.0.22 since the new path would never run.

**Comment by Lalufu** [comment]
Maybe the CI has a Java where the correct path doesn't contain `jre`, so
the code still produces the correct LIBPATH?
