### ISSUE TITLE
Latest stable vs LTS

### ISSUE THREAD

**Issue by dalmadebreceni** [unbit/uwsgi#2558]
Pypi installs release 2.0.22 as latest stable (and marks 2.0.20 as red, being too old).
According to https://uwsgi-docs.readthedocs.io/en/latest/Download.html, the newest Stable/LTS release is still 2.0.20.
The source for 2.0.21 and 2.0.22 is available only at pythonhosted.org (and not on projects.unbit.it as up to 2.0.20).
This is a bit confusing, since in the first link there is no clear difference between latest stable and LTS, it just refers to both as 2.0.20. 
https://uwsgi-docs.readthedocs.io/en/latest/Install.html says, latest stable can be downloaded with pip.
I could not find any history about LTS releases, the changelog does not distinctively mark any as LTS.
Please add some info to the documentation, which version is meant to be LTS, if it's any different from stable.

**Comment by xrmx** [comment]
It's the same, updated the uwsgi-docs page.
