### ISSUE TITLE
Issue with pgAdmin4 web

### ISSUE THREAD

**Issue by naturel-eol** [unbit/uwsgi#2565]
Hi,
I installed pgAdmin4 (v7.4) web with uWSGI (v2.0.15).
When I launch a backup proccess in pgAdmin UI, I have this error : 

```
2023-09-29 11:24:29,609: DEBUG  pgadmin:        **Process Watcher Err:/usr/bin/uwsgi-core: option '--file' is ambiguous; possibilities: '--file-serve-mode' '--fileserve-mode' '--file-write'**
getopt_long() error
``` 
I think the problem comes from uWSGI_core which interprets the backup command for postgres.
The  backupo command is like  this
```
pg_dump --file "test-bkp.sql" --host="xxxxxxxxxxxxxxxxx.eu-west-3.rds.amazonaws.com" --port="5432" --username="xxxx" --verbose --format=c --blobs "xxxxx"
``` 
How can I solve this please ?
Thank

**Comment by xrmx** [comment]
You have to fix whatever is using uwsgi-core as a binary instead of pg_dump.
