### ISSUE TITLE
Do cron jobs respect ranges?

### ISSUE THREAD

**Issue by jfmatth** [unbit/uwsgi#2568]
Hi, 

I love UWSGI, and until recently didn't know how robust it is.

I have a need to have the cron feature respect ranges instead of what looks like just single entries.

For example, I would like to run a script every minute from 6 to 10 every day during the week.  In crontab, that would be 
```
* 6-10 * * 1-5
```

When I put that equivalent into the cron format for UWSGI 
```
cron = -1 6-10 -1 -1 1-5 ./bin/cron_job.sh

```
it doesn't say it's invalid, but also doesn't work :(

Thoughts?

**Comment by xrmx** [comment]
Indeed it doesn't

**Comment by jfmatth** [comment]
Thanks @xrmx  for the quick response.  I ended up using https://github.com/agronholm/apscheduler instead.

I love UWSGI, thank you for this project.
