### ISSUE TITLE
uwsgi compilation failed with openssl-1.1 python3.10

### ISSUE THREAD

**Issue by davixx** [unbit/uwsgi#2598]
Hello,

I don't know if I'm not satisfying a requirement ; but when setting ssl = True into my compilation profile, compilation fails ; below an extract (attached the entire script that generate the error, and it's entire output)

> [...]
> python3.10 uwsgiconfig.py --build custom.ini
> core/subscription.o: In function `uwsgi_remove_subscribe_node':
> subscription.c:(.text+0x942): undefined reference to `EVP_MD_CTX_destroy'
> subscription.c:(.text+0x991): undefined reference to `EVP_MD_CTX_destroy'
> core/subscription.o: In function `subscription_new_sign_ctx':
> subscription.c:(.text+0x13c5): undefined reference to `EVP_MD_CTX_create'
> subscription.c:(.text+0x1456): undefined reference to `EVP_MD_CTX_destroy'
> core/ssl.o: In function `uwsgi_ssl_init':
> ssl.c:(.text+0x2ec): undefined reference to `SSL_library_init'
> ssl.c:(.text+0x2f1): undefined reference to `SSL_load_error_strings'
> ssl.c:(.text+0x2f6): undefined reference to `OPENSSL_add_all_algorithms_noconf'
> core/ssl.o: In function `uwsgi_ssl_new_server_context':
> [...]

Thanks :)

[uwsgi_ssl_compilation_issue.txt](https://github.com/unbit/uwsgi/files/14069090/uwsgi_ssl_compilation_issue.txt)
[uwsgi_compilation.log](https://github.com/unbit/uwsgi/files/14069091/uwsgi_compilation.log)

**Comment by xrmx** [comment]
Does something like this work for you?

```
diff --git a/uwsgi.h b/uwsgi.h
index 69f9fbf8..b192c42c 100755
--- a/uwsgi.h
+++ b/uwsgi.h
@@ -368,6 +368,14 @@ extern int pivot_root(const char *new_root, const char *put_old);
 #include <openssl/ssl.h>
 #include <openssl/err.h>
 
+// some helpers got renamed in 1.1.0 and compat removed in some late 1.1.1 versions
+#ifndef EVP_MD_CTX_destroy
+#define EVP_MD_CTX_destroy EVP_MD_CTX_new
+#endif
+#ifndef EVP_MD_CTX_destroy
+#define EVP_MD_CTX_destroy EVP_MD_CTX_free
+#endif
+
 #if OPENSSL_VERSION_NUMBER < 0x10100000L
 #define UWSGI_SSL_SESSION_CACHE
 #endif
```

**Comment by xrmx** [comment]
Or even better this one

```
diff --git a/uwsgi.h b/uwsgi.h
index 69f9fbf8..e5966590 100755
--- a/uwsgi.h
+++ b/uwsgi.h
@@ -366,6 +366,7 @@ extern int pivot_root(const char *new_root, const char *put_old);
 #ifdef UWSGI_SSL
 #include <openssl/conf.h>
 #include <openssl/ssl.h>
+#include <openssl/evp.h>
 #include <openssl/err.h>
 
 #if OPENSSL_VERSION_NUMBER < 0x10100000L
```

**Comment by xrmx** [comment]
BTW pip install uwsgi works nicely out of the box in debian bullseye that has openssl 1.1.1w
