### ISSUE TITLE
-Wformat-signedness causes compilation error with CLANG 16.0.6

### ISSUE THREAD

**Issue by karolyi** [unbit/uwsgi#2602]
Hey,

the commit https://github.com/unbit/uwsgi/commit/a6f841f2a9d58c2b3a3928f3f03d343c1ae2e996 causes a compilation error on my FreeBSD:

`error: unknown warning option '-Wformat-signedness' [-Werror,-Wunknown-warning-option]`

Please make it optional.

**Comment by xrmx** [comment]
Thanks for reporting, should probably add clang to the ci

**Comment by karolyi** [comment]
Similar: https://github.com/madrisan/nagios-plugins-linux/issues/17
