### ISSUE TITLE
Workers segfaulting (threading related?)

### ISSUE THREAD

**Issue by sentrivana** [unbit/uwsgi#2604]
Hey folks, some of our users are seeing [workers dying/segfaulting](https://github.com/getsentry/sentry-python/issues/2699#issuecomment-1925432010) after a recent update to a new version of the Sentry Python SDK. We narrowed the issue down to a new feature that sets up an instance of [a class](https://github.com/getsentry/sentry-python/blob/c77a1235f4d4f4d88129c13fa9586840ede48ce4/sentry_sdk/metrics.py#L406) that doesn't do much else than set up a background thread, a lock and a threading event to wait on. (Most of the functions in the file are never used since there are no metrics actually being emitted, so all the thread is doing is waiting on an event periodically.)

The segfaults seem to all be happening on uWSGI 2.0.23. Is this something that you've seen before? Are there known limitations when it comes to threads or threading events?

Please see https://github.com/getsentry/sentry-python/issues/2699#issuecomment-1925432010 for the most info we have so far on the subject -- I'm still trying to repro and maybe get a core dump to inspect, but no success so far.

**Comment by xrmx** [comment]
@sentrivana any chance you can have any of the affected people helping by testing a one line change in their config (see
 https://github.com/getsentry/sentry-python/issues/2699#issuecomment-1934896252) ? Looks more useful that dunking on uwsgi.

**Comment by sentrivana** [comment]
Hey @xrmx, not my intention at all to dunk on uWSGI. Thanks a lot for following up on the original issue -- I'll close this.

**Comment by xrmx** [comment]
@sentrivana it wasn't you dunking on uwsgi, don't worry :)
