### ISSUE TITLE
flag -Wformat-signedness

### ISSUE THREAD

**Issue by amkv** [unbit/uwsgi#2609]
it seems this flag breaks installation with gcc.x86_64 0:4.8.5-44.0.3.el7 - it doesn't recognize it

**Comment by frenzymadness** [comment]
I have the same problem building uwsgi from source on RHEL 7 with Python 3.8.

```
gcc: error: unrecognized command line option ‘-Wformat-signedness’
```

**Comment by xrmx** [comment]
Does your gcc have -dumpversion ?

**Comment by frenzymadness** [comment]
> Does your gcc have -dumpversion ?

Yes, I have gcc on RHEL 7 and it supports that option:
```
# rpm -qv gcc
gcc-4.8.5-44.el7.x86_64
# gcc -dumpversion
4.8.5
```
