### ISSUE TITLE
Why does uwsgi-docs suggests using uwsgi-2.0.20?

### ISSUE THREAD

**Issue by aizyuval** [unbit/uwsgi#2629]
I have followed the [quickstart](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html) and couldn't build from source.
The link for uwsgi downloads uwsgi-2.0.20.
 `wget https://projects.unbit.it/downloads/uwsgi-latest.tar.gz`

I have switched to using the latest tag 2-0.20 and it compiles well. This seems to me as this is just forgotten. But if not, is there any reason to it?

**Comment by xrmx** [comment]
Feel to open a PR on uwsgi https://github.com/unbit/uwsgi-docs/ to remove that paragraph fro the doc
