### ISSUE TITLE
Missing release notes for 2.0.25

### ISSUE THREAD

**Issue by intgr** [unbit/uwsgi#2633]
Previous uWSGI versions have included release notes at https://uwsgi-docs.readthedocs.io/en/latest/#release-notes

But it is missing a page for uWSGI 2.0.25.

**Comment by intgr** [comment]
The release notes exist in `uwsgi-docs` repo: https://github.com/unbit/uwsgi-docs/blob/master/Changelog-2.0.25.rst

I guess there was a docs build failure or similar issue.

**Comment by xrmx** [comment]
Wrong repo, and i rebuilt the docs
