### ISSUE TITLE
Integrate uwsgi with fastapi

### ISSUE THREAD

**Issue by Rojas-Andres** [unbit/uwsgi#2639]
I have a simple fastapi application but I am implementing uwsgi but when doing it I have this error TypeError: FastAPI.__call__() missing 1 required positional argument: 'send' I have been validating a lot and apparently it is a uwsgi error

[uwsgi]
module = api.main:app
socket = /var/uwsgi/fastapi.sock
socket-timeout = 300

strict = true
master = true

**Comment by xrmx** [comment]
uwsgi speaks wsgi, fastapi speaks asgi. They don't talk to each other. You have to stick with other asgi application servers.
