### ISSUE TITLE
Run without libxml2

### ISSUE THREAD

**Issue by OscarVanL** [unbit/uwsgi#2687]
Hi,

I'm trying to reduce the size of my service's container image. I am using `python3.12-slim-bookworm` as my base container, which requires me to install the `libxml2` apt package to install and run uWSGI.

Installing `libxml2` pulls in several other packages like `libicu72` that add quite a bit of size to the resultant container image.

I tried a multistage docker build where `libxml2-dev` is only installed when building the uWSGI wheel, then copying the resultant venv into a production/deploy image without `libxml2`, but uWSGI prints errors at startup with this approach.

I'm not 100% sure what uWSGI uses `libxml2` for, from the docs I see it's used for some XML-RPC wrapper functionality that I do not utilise. Is there a way to disable this functionality in uWSGI at runtime so I can use my multistage container build approach to remove the need for this OS package?

Thank you!

**Comment by niol** [comment]
Try compiling uwsgi with `xml = false` in the buildconf.

**Comment by OscarVanL** [comment]
Is there any way I can easily provide compile args if I’m installing the package with pip?

**Comment by D3X** [comment]
@OscarVanL you can use the undocumented environment variable `UWSGI_PROFILE_OVERRIDE`. You can set it to `xml=false` to disable the xml features.
