### ISSUE TITLE
On demand vassals with subscription requests

### ISSUE THREAD

**Issue by tomkins** [unbit/uwsgi#300]
I've been testing the new 1.9.1 on demand vassals, but for my use case it doesn't quite feel right. Switching to it means losing the fastrouter subscription system, as the vassal hasn't spawned to send any subscription requests.

I'd like to see: --emperor-on-demand-config-directory directory-name - a more flexible approach than the extension/directory on demand options, and a bit simpler for users than the exec option.

A sample config for this could be:

```
# /etc/uwsgi/sites/example.org.conf
[vassal]
socket = :0
ondemand-config = /home/vassal/conf/uwsgi.ini

# Emperor sends subscription requests on behalf of the vassal
subscribe-to = 192.168.1.1:3000:www.example.org
subscribe-to = 192.168.1.1:3000:www.example.net

# Secured subscription
# This file could be owned by root, /home/vassal/conf/uwsgi.ini could be owned by the user
subscribe-to = 192.168.1.1:3000:www.example.com,0,SHA1:/etc/uwsgi/certs/private.pem
```

The emperor would create the socket in a similar way to the other on demand options, the vassal config file which uWSGI spawns would be given in the on demand config file (in this case, /home/vassal/conf/uwsgi.ini).

With the subscribe-to options in the config, the emperor would start sending heartbeats to a fastrouter on behalf of the vassal (as it hasn't spawned yet). This means on demand vassals could be deployed to multiple servers, with the subscription server and fastrouter dealing with dead nodes (something the current on demand system can't do?).

Maybe there's a better way of doing this, but to me it seems like a good way of mixing on demand vassals, dynamic port assignment, and the fastrouter - something which the current on demand options are missing?

**Comment by unbit** [comment]
Thanks to intellisurvey sponsorship the feature has been included. Docs will be out soon as well as the merge of the intellisurvey branch with master.
