### ISSUE TITLE
Cycling redirect if request uri is URL

### ISSUE THREAD

**Issue by arantir** [unbit/uwsgi#372]
Try send request to something like
http://yoursite.com/http://anysite.com 
or
http://yoursite.com/https://anysite.com 
and you will get cycling redirecting with "301 MOVED PERMANENTLY" to the same request uri.

I really need this stuff to make easy api for my application...
I use django, nginx and uwsgi. My app handle such request correctly (when running under django server), nginx handle them correctly too (I have a lot of other sites under nginx and have a chance to test).

The interesting thing is that is redirects only paths starts from **valid** urls with http and https protocol, but doesn't if it's "http//.." or "ftp://".
It feels like someone **specially**  provide such annoying thing :D

**Comment by xrmx** [comment]
I think we can close this.
