### ISSUE TITLE
SegFault with 1.9.15 and Python 2.7.3

### ISSUE THREAD

**Issue by jorgevila** [unbit/uwsgi#390]
Hi,

we have experiencing this issue, and we do not know how to follow it up.

Could you please help us?

Thank you

---

**\* Starting uWSGI 1.9.15 (64bit) on [Tue Sep 24 18:36:58 2013] ***
compiled with version: 4.4.6 20110731 (Red Hat 4.4.6-3) on 18 September 2013 19:08:00
os: Linux-2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011
nodename: mpoznvnsdptcbe1
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /opt/pdi/Cashlog_Subscriptions_WA/usr/scripts
detected binary path: /usr/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
**\* WARNING: you are running uWSGI as root !!! (use the --uid flag) **\* 
your processes number limit is 1024
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
uWSGI http bound on :15100 fd 3
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 6
Python version: 2.7.3 (default, Jul 31 2012, 19:07:13)  [GCC 4.1.2 20080704 (Red Hat 4.1.2-46)]
Python main interpreter initialized at 0x21fadb0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 415440 bytes (405 KB) for 8 cores
**\* Operational MODE: preforking+threaded ***
added cashlogSubscriptions to pythonpath.
!!! uWSGI process 1927 got Segmentation Fault !!!
**\* backtrace of 1927 ***
/usr/bin/uwsgi(uwsgi_backtrace+0x29) [0x455d79]
/usr/bin/uwsgi(uwsgi_segfault+0x21) [0x455f01]
/lib64/libc.so.6() [0x312ec32900]
/usr/lib64/libcrypto.so.10(EVP_PKEY_CTX_dup+0x20) [0x313b8c7870]
/usr/lib64/libcrypto.so.10(EVP_MD_CTX_copy_ex+0xbd) [0x313b8bb89d]
/opt/Python-2.7.3/lib/python2.7/lib-dynload/_hashlib.so(+0x19ea) [0x7f478475d9ea]
/opt/Python-2.7.3/lib/python2.7/lib-dynload/_hashlib.so(+0x1d70) [0x7f478475dd70]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x63f9) [0x7f478c77e1a9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6f48) [0x7f478c77ecf8]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x8c9) [0x7f478c77fab9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f478c77fb32]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2) [0x7f478c7930f2]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x10364e) [0x7f478c79564e]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x103dc0) [0x7f478c795dc0]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x104292) [0x7f478c796292]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x118) [0x7f478c796528]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0xe49fd) [0x7f478c7769fd]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyObject_Call+0x68) [0x7f478c6d7c88]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x56) [0x7f478c777046]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x381c) [0x7f478c77b5cc]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x8c9) [0x7f478c77fab9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f478c77fb32]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2) [0x7f478c7930f2]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x10364e) [0x7f478c79564e]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x103dc0) [0x7f478c795dc0]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x104311) [0x7f478c796311]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x118) [0x7f478c796528]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0xe49fd) [0x7f478c7769fd]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyObject_Call+0x68) [0x7f478c6d7c88]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x56) [0x7f478c777046]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x381c) [0x7f478c77b5cc]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x8c9) [0x7f478c77fab9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f478c77fb32]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2) [0x7f478c7930f2]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x10364e) [0x7f478c79564e]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x103dc0) [0x7f478c795dc0]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x104292) [0x7f478c796292]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15d) [0x7f478c79656d]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0xe49fd) [0x7f478c7769fd]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyObject_Call+0x68) [0x7f478c6d7c88]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x56) [0x7f478c777046]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x381c) [0x7f478c77b5cc]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x8c9) [0x7f478c77fab9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f478c77fb32]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2) [0x7f478c7930f2]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x10364e) [0x7f478c79564e]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x103dc0) [0x7f478c795dc0]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x104292) [0x7f478c796292]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15d) [0x7f478c79656d]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0xe49fd) [0x7f478c7769fd]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyObject_Call+0x68) [0x7f478c6d7c88]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x56) [0x7f478c777046]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x381c) [0x7f478c77b5cc]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x8c9) [0x7f478c77fab9]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f478c77fb32]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2) [0x7f478c7930f2]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x10364e) [0x7f478c79564e]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x103dc0) [0x7f478c795dc0]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0x104292) [0x7f478c796292]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15d) [0x7f478c79656d]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(+0xe49fd) [0x7f478c7769fd]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyObject_Call+0x68) [0x7f478c6d7c88]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x56) [0x7f478c777046]
/opt/Python-2.7.3/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x381c) [0x7f478c77b5cc]
**\* end of backtrace ***

**Comment by leonard-chen** [comment]
how do you solve this problem, please tell me , thank you
