### ISSUE TITLE
Linux clone() calls not used on Itanium

### ISSUE THREAD

**Issue by jonassmedegaard** [unbit/uwsgi#395]
Itanium (IA64) apparently needs extra care to do clone() calls correctly, which caused issue #391.

Issue #391 was solved by working around the underlying problem, which therefore remain: Linux clone() calls are not used on Itanium.

If not solved, I suggest to leave this issue open, and improve status quo by a) explicitly mentioning the exception of IA64 at all places documenting Linux namespace protection, and b) add a log warning at all places in code where uwsgi.ns flag is inspected but current architecture is IA64 (which involves limiting the ifdef's till _after checking that flag).

**Comment by xrmx** [comment]
Closing as documentation has been updated.
