### ISSUE TITLE
TemplateDoesNotExist in directory app

### ISSUE THREAD

**Issue by aztrock** [unbit/uwsgi#457]
I have an app in django 1.5.5 and python 2.7 and everything works perfect, but after a while and do not know why or for what reason, all templates that are within the apps fail to meet and begins to look TemplateDoesNotExist

I have to reload uwsgi daemon for perfect working again.
# /etc/init.d/uwsgi reload

and everything returns to normal.

but after a while and turns out TemplateDoesNotExist.

**Comment by howiezhao** [comment]
Same situation, same problem, I use the latest version of uWSGI.
