### ISSUE TITLE
Python tracebacker doesn't log traceback on harakiris

### ISSUE THREAD

**Issue by tahajahangir** [unbit/uwsgi#506]
The doc at http://uwsgi-docs.readthedocs.org/en/latest/Tracebacker.html#combining-the-tracebacker-with-harakiri says:

> If a request is killed by the harakiri feature, a traceback is automatically logged during the Harakiri phase.

But (probably after change in #480 ) tracebacker doesn't log traceback on harakiris.

**Comment by squarelover** [comment]
This seems to be happening again in both versions 2.0.15 and 2.0.18
