### ISSUE TITLE
error：‘UWSGI_EVENT_IN’ not declared

### ISSUE THREAD

**Issue by fqbqrr** [unbit/uwsgi#520]
In win7,python3 cygwin,
I tried many times but it always says like this:
core/event.c: 在函数‘event_queue_read’中:
core/event.c:1412:9: 错误：‘UWSGI_EVENT_IN’未声明(在此函数内第一次使用)
core/event.c:1412:9: 附注：每个未声明的标识符在其出现的函数内只报告一次
core/event.c: 在函数‘event_queue_write’中:
core/event.c:1416:9: 错误：‘UWSGI_EVENT_OUT’未声明(在此函数内第一次使用)
core/event.c:1417:1: 错误：在有返回值的函数中，控制流程到达函数尾 [-Werror=retur
n-type]
core/event.c: 在函数‘event_queue_read’中:
core/event.c:1413:1: 错误：在有返回值的函数中，控制流程到达函数尾 [-Werror=retur
n-type]
cc1: all warnings being treated as errors.

**Comment by Harrybebst** [comment]
Oh,I get the same problem at uwsgi in windows (- _ - !) .I try my best to find solution tp solve it.But it didn't work. This is my machine's environment :Win10、python 2.7 .For expamle,
1.I try to change os.uname() to platform.uname() ,but it also says error.
2.I download and install cygwin,and use it to install uwsgi,but it failed either.
Now, I still don't know how to install uwsgi in windows. I knew a way to replace it. That's flask. Hope I can use it well!
