### ISSUE TITLE
uwsgi-body-read error on POST operations when using mongrel2 plugin

### ISSUE THREAD

**Issue by timconnolly** [unbit/uwsgi#558]
As discussed on irc:
https://botbot.me/freenode/uwsgi/msg/11679007/

For all POST operations, uwsgi generates an error when the WSGI application attempts to read the request data. uwsgi reports 0 bytes consumed.

Example of a logged error when the POST operation is attempted:
[uwsgi-body-read] Error reading 15 bytes. Content-Length: 15 consumed: 0 left: 15 message: Client closed connection

The same operation works as expected when using --http instead of going through the mongrel2 plugin with the --zeromq option.

unbit found that the logic for handling an in-memory body was not correct.

**Comment by manjusv** [comment]
@timconnolly @unbit  I get a similar error when I try to upload huge number of image files using multiple processses. I get the same error
[uwsgi-body-read] Error reading 15 bytes. Content-Length: 15 consumed: 0 left: 15 message: Client closed connection
what was the solution for this issue? was there any fix? Thanks in advance.
