### ISSUE TITLE
operror-type: AssertionError with PyPy plugin on 2.0.4

### ISSUE THREAD

**Issue by btegs** [unbit/uwsgi#628]
When using uWSGI 2.0.4 standalone and loading the PyPy plugin on Ubuntu 14.04, I get a debug: operror-type: AssertionError when loading any script. I got PyPy 2.2.1 from the repositories via a simple "apt-get install pypy" Here are my steps:

1.) I downloaded from http://projects.unbit.it/downloads/uwsgi-2.0.4.tar.gz, extracted, changed to the uwsgi-2.0.4, and opened up a terminal.

2.) I ran "UWSGI_BIN_NAME=/home/teg/uwsgi_test/uwsgi make PROFILE=nolang" to create a uwsgi executable but not include the default Python. Otherwise I get an issue about loading both Python and PyPy and how it is evil.

3.) While still in the uwsgi-2.0.4 directory in the terminal, I ran "python2.7 uwsgiconfig.py --plugin plugins/pypy" to create a pypy_plugin.so file for which I copied to /home/teg/uwsgi_test/

4.) Changed directories to /home/teg/uwsgi_test/ opened up a terminal, and ran "wget http://projects.unbit.it/downloads/pypy/libpypy-c-x86_64_20130524.so" to get the required file.

5.) Created this .ini file and named conf.ini:
[uwsgi]
plugins = /home/teg/uwsgi_test/pypy
http = :8080
chdir = home/teg/uwsgi_test/
processes = 2
master=true
disable-logging = false
catch-exceptions = false
post-buffering = 8192
vacuum = true
listen = 120
pypy-home = /usr/bin
pypy-lib = /home/teg/uwsgi_test/libpypy-c-x86_64_20130524.so

6.) Created a simple hello.py with this code and put in the /uwsgi_test/ directory:
def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return ["Hello World"]

7.) Ran the script via "/home/teg/uwsgi_test/uwsgi --ini conf.ini --pypy-wsgi hello.py" in the terminal.

8.) Got this error:
[uWSGI] getting INI configuration from conf.ini
*** Starting uWSGI 2.0.4 (64bit) on [Thu May 15 13:43:23 2014] ***
compiled with version: 4.8.2 on 15 May 2014 12:05:24
os: Linux-3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
nodename: ubuntu1
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/teg/uwsgi_test
detected binary path: /home/teg/uwsgi_test/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 126913
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:38360 (port auto-assigned) fd 3
debug: OperationError:
debug:  operror-type: AssertionError
debug:  operror-value: 

Is this a common error that many of you are of or is it a configuration issue? It only seems to affect PyPy and not standard Python when following the docs. There is also someone else with this issue at https://serverfault.com/questions/592413

**Comment by xrmx** [comment]
This should be fixed, see http://uwsgi-docs.readthedocs.org/en/latest/PyPy.html . Closing.
