### ISSUE TITLE
uWSGI does not load environment variables from executed files

### ISSUE THREAD

**Issue by utapyngo** [unbit/uwsgi#629]
I am trying to configure nginx+uWSGI to serve my Django application and avoid putting env vars into uWSGI config (since manage.py also needs them).

In uWSGI ini-file I have:

```
uid = username
gid = username
exec-pre-app = . /home/username/.env
```

(note that I tried to source the file, but I also tried exec-pre-app = /home/username/.env)

In /home/username/.env:

```
#!/bin/sh
export DJANGO_SITE_KEY="..."
```

In uWSGI logs I see this line:

```
running ". /home/username/.env" (pre app)...
```

But my Django app is unable to access the environment variable with `os.environ`.

**Comment by alanjds** [comment]
What if I want the filename to be an externally configured variable?

The following does not work right now because [how uWSGI parses config files](http://uwsgi-docs.readthedocs.io/en/latest/ParsingOrder.html?highlight=how#how-uwsgi-parses-config-files). 
```ini
[uwsgi]
print = ENVFILE: $(ENVFILE)
for-readline = $(ENVFILE)
  env = %(_)
  print = environment set: %(_)
endfor ==
```

Any ideas?

**Comment by tegaphilip** [comment]
This just saved me a lot of headache. Thanks @unbit

**Comment by Thibaut-Fatus** [comment]
This is a bit old, but does this solution work with globally set environment variables in /etc/environment ?

Since manage.py commands uses the variables defined here this would be the only place where they're stored ?

**Comment by noodlebreak** [comment]
Wouldn't it be better to simply have a directive like this:

```
env_file = /path/to/env/file
```

And using this, all the env vars are loaded.

**Comment by jirutka** [comment]
> just place each of them (one per line) in a text file in the form
> 
> VAR=VALUE
> 
> then in uWSGI config
> 
> ```ini
> [uwsgi]
> for-readline = yourfile
>   env = %(_)
> endfor = 
> ```

This doesn’t work when you have some variables with quoted value (e.g. `FOO="lorem ipsum"`) or comments in the vars file. So it’s really not a proper solutin.

**Comment by gaozhidf** [comment]
try something like this
```
for line in `cat your_env_file`; do if [[ $line != \#* ]];then export $line; fi;done
```

**Comment by Impdevil** [comment]
I'm trying to import my .env file, and the examples above havent helped, can some one please explain to me how to bring in those variables stored there so i can access them when running in uwsgi with nginx?

**Comment by swats-the-floran** [comment]
ffs please make it easier. i wasted the whole day solving this problem and still no result.
