### ISSUE TITLE
mules and signals

### ISSUE THREAD

**Issue by prymitive** [unbit/uwsgi#643]
2.0.5 introduced graceful reload for mules but I'm unable to intercept any signal in mule code, it works if I run it without uWSGI (`python x.py`). Is it uWSGI interfering with mule signals?

Test case below, touching /tmp/reload.txt or sending SIGHUP directly to my mule doesn't do anything.

x.py

```
import os
import signal
from time import sleep

def hand(*args, **kwargs):
    print(('EXITING', args, kwargs))

for sig in [signal.SIGTERM, signal.SIGINT, signal.SIGHUP,
            signal.SIGQUIT]:
    signal.signal(sig, hand)

while True:
    print(('ALIVE', os.getpid()))
    sleep(1)
```

```
# /usr/bin/uwsgi --plugins-dir /usr/lib/uwsgi/plugins --plugin python27 -M -s /tmp/mule.socket --mule=/tmp/x.py --touch-reload=/tmp/reload.txt
*** Starting uWSGI 2.0.5-upaas (64bit) on [Sun Jun  1 19:43:58 2014] ***
[...]
spawned uWSGI mule 1 (pid: 4619)
unable to stat() /tmp/reload.txt, events will be triggered as soon as the file is created
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
Sun Jun  1 19:44:06 2014 - *** /tmp/reload.txt has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4618)...
('ALIVE', 4619)
worker 1 buried after 1 seconds
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
('ALIVE', 4619)
^C('ALIVE', 4619)
SIGINT/SIGQUIT received...killing workers...
goodbye to uWSGI.
('ALIVE', 4619)
```

**Comment by tspike** [comment]
@unbit I'm running into a similar problem, we need to do some cleanup on mule exit. I confirm that `--py-call-osafterfork` allows this test case to work, but I'm nervous to use it based on your reply to [another issue](https://github.com/unbit/uwsgi/issues/803):

`you cannot (by default) sanely override signals in uWSGI (unless you specify --py-call-osafterfork but this will break lot of internal behaviours)`

What exactly are the implications of this option?

Thanks for all your work on uwsgi.

**Comment by unbit** [comment]
Just pay attention to override signals only in the mule you should be safe
