### ISSUE TITLE
Broken chain reloading

### ISSUE THREAD

**Issue by oas89** [unbit/uwsgi#649]
uWSGI does not check any longer if newly spawned worker is ready, so in case of long-initializing app we can have no workers ready to manage requests at time.

There is attempt to fix broken behaviour of chain reloading:

```
diff --git a/core/master_checks.c b/core/master_checks.c
index 2f35c32..a2af9ac 100644
--- a/core/master_checks.c
+++ b/core/master_checks.c
@@ -50,8 +50,9 @@ void uwsgi_master_check_chain() {

        uwsgi_block_signal(SIGHUP);
        int i;
-       for(i=uwsgi.status.chain_reloading;i<=uwsgi.numproc;i++) {
+       for(i=1;i<=uwsgi.numproc;i++) {
                struct uwsgi_worker *uw = &uwsgi.workers[i];
+               if (uw->accepting == 0) break;
                if (uw->pid > 0 && !uw->cheaped) {
                        if (uw->cursed_at == 0) {
                                uwsgi_curse(i, SIGHUP);
```

**Comment by lawlmart** [comment]
I'm finding the verbosity of this extremely annoying. Is there any way to cut it down? "chain is still waiting for worker" is logged for what seems over 100 times per second during the entire chain reload.

**Comment by unbit** [comment]
--log-drain "chain is still waiting for worker"

will do the trick :)

By the way, the frequency is 1 announce per-second, if you get 100 of them it means your worker is taking 100 seconds to die. Maybe i would tune a bit --worker-reload-mercy to be less tolerant and brutally kill the worker sooner

**Comment by lawlmart** [comment]
Awesome, thanks for the tip, that'll fix me -- still don't think we're on the same page regarding the underlying issue however. I'm getting a massive number of logs *per second* not one per second. It's reloading one worker at a time (as I understand it), and if that worker is only announcing once per second that doesn't square with what I'm experiencing. It feels more like there's a run on loop thats logging constantly while the worker is restarting.

**Comment by mattupstate** [comment]
Just noticed this as well. My worker(s) are taking about 2 seconds to reload but I'm getting thousands of the `chain is still waiting...` logs.

**Comment by unbit** [comment]
This is caused by implicit/explicit --log-master (like when using loggers) without --threaded-logger. The latest patch includes an additional check that avoid to generate more than one logline per second
