### ISSUE TITLE
No way to run sync with gevent

### ISSUE THREAD

**Issue by mikekap** [unbit/uwsgi#652]
`--gevent 1` causes uwsgi to fail starting:
the gevent loop engine requires async mode (--async <n>)

Why would you want to do this? So you can have a background greenlet occasionally poll your dependencies, even if this particular process hasn't seen a request in a while. That is, what I want is the gevent event loop engine, but not async requests.

**Comment by DennyD17** [comment]
Hi!
How does it work? 
Tried to run with --gevent 1 --async 1 --- got the error _"the gevent loop engine requires async mode (--async <n>)"_
Tried to run just with --async 1 --- no concurrence inside a request
