### ISSUE TITLE
502 Bad Gateway- NGiNX / uWSGI / Django

### ISSUE THREAD

**Issue by pnovotnak** [unbit/uwsgi#682]
I see lots of the following in my logs, and get complaints from users of the website when working in the site's Django admin:

`recv() failed (104: Connection reset by peer) while reading response header from upstream, client`

I've tried lots of things, and actually found a descriptor leak in the codebase, but nothing so far has helped. I've just applied [a buffer size increase](http://stackoverflow.com/a/22792850/1342445), and I'll report back if it solves he issue.

It's a large site, and there are a lot of third party modules that set cookies. I count 24 of them, if that makes a difference.

**Comment by kishan3** [comment]
@pnovotnak In which file to set this. can you tell?

**Comment by tiantaozhang** [comment]
because the default buffer-size is 4k, buffer-size = 65535 solved for me too
