### ISSUE TITLE
UserError: Failure to import uwsgi

### ISSUE THREAD

**Issue by danishabdullah** [unbit/uwsgi#686]
Whenever I import anything from uwsgidecorators it fails with the following error.

I am running uwsgi 2.0.6 on python 2.7.7

``` python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-00a6fdfbe065> in <module>()
----> 1 from uwsgidecorators import *

/home/danishabdullah/anaconda/lib/python2.7/site-packages/uwsgidecorators.py in <module>()
      8     import pickle
      9
---> 10 import uwsgi
     11
     12 if uwsgi.masterpid() == 0:

ImportError: No module named uwsgi
```

Edit 1: My bad...  it works fine when running in a uwsgi process.
Edit 2: I have changed the title of the issue to reflect my error.

**Comment by Deepakdubey90** [comment]
Hi , 
I am executing the celery file, having 'import uwsgi, its throwing error like'
error >>>>>>>>>>>>>>> 
  import uwsgi
ImportError: No module named uwsgi

**Comment by unbit** [comment]
@Deepakdubey90 Hi, the 'uwsgi' module exists only into the uwsgi process. celery is an external process.

**Comment by Deepakdubey90** [comment]
@unbit , Thanks .
Is there a way to handle such kind of activity.

**Comment by unbit** [comment]
@Deepakdubey90 nope because it has no meaning to interface to uwsgi api from a non uwsgi process. What you are trying to accomplish ?

**Comment by Deepakdubey90** [comment]
@unbit , I am trying to excecute celery periodically in pyhton app.
 If I am running the wsgi server from shell, and running celery as well from another shell, So it should not raise import error for wsgi right?

**Comment by Deepakdubey90** [comment]
Thanks @unbit
