### ISSUE TITLE
forkpty plugin fails to build on the Hurd

### ISSUE THREAD

**Issue by jonassmedegaard** [unbit/uwsgi#694]
Recent attempt at enabling most possible plugins in Debian packaging of uWSGI revealed that the forkpty plugin apparently fails to build on the Hurd:

https://buildd.debian.org/status/fetch.php?pkg=uwsgi&arch=hurd-i386&ver=2.0.6~dfsg-7%2Bexp2&stamp=1407054296

**Comment by xrmx** [comment]
@jonassmedegaard what version are you trying to compile? from the commits it looks like this has only hit master and not uwsgi-2.0.

**Comment by xrmx** [comment]
@jonassmedegaard  so just need to carry ca8ab125b43995c42714227b3ab065990eae4411 as debian patch

**Comment by jonassmedegaard** [comment]
Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
> @jonassmedegaard so just need to carry ca8ab12 as debian patch

Yes, that is what I did already - sorry I forgot to mention:
https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/020140820~e04e19a.patch/

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Quoting Jonas Smedegaard (2015-10-13 16:52:11)
> Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
> > @jonassmedegaard so just need to carry ca8ab12 as debian patch
> 
> Yes, that is what I did already - sorry I forgot to mention:
> https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/020140820~e04e19a.patch/

Whoops, I was too quick: I understand now that I missed a followup 
commit.  Thanks!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Quoting Jonas Smedegaard (2015-10-13 16:54:11)
> Quoting Jonas Smedegaard (2015-10-13 16:52:11)
> > Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
> > > @jonassmedegaard so just need to carry ca8ab12 as debian patch
> > 
> > Yes, that is what I did already - sorry I forgot to mention:
> > https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/020140820~e04e19a.patch/
> 
> Whoops, I was too quick: I understand now that I missed a followup 
> commit.  Thanks!

Hmm - how is a fix for freebsd vs. dragonflybsd gonna help with Hurd?

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Quoting Jonas Smedegaard (2015-10-13 16:57:33)
> Quoting Jonas Smedegaard (2015-10-13 16:54:11)
>> Quoting Jonas Smedegaard (2015-10-13 16:52:11)
>>> Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
>>>> @jonassmedegaard so just need to carry ca8ab12 as debian patch
>>>
>>> Yes, that is what I did already - sorry I forgot to mention: 
>>> https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/020140820~e04e19a.patch/
>>
>> Whoops, I was too quick: I understand now that I missed a followup 
>> commit.  Thanks!
>
> Hmm - how is a fix for freebsd vs. dragonflybsd gonna help with Hurd?

I think I got it now (you really meant commit afcb3e1).

Compiling now...

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by xrmx** [comment]
Il 13/10/2015 17:12, Jonas Smedegaard ha scritto:
> Quoting Jonas Smedegaard (2015-10-13 16:57:33)
>  > Quoting Jonas Smedegaard (2015-10-13 16:54:11)
>  >> Quoting Jonas Smedegaard (2015-10-13 16:52:11)
>  >>> Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
>  >>>> @jonassmedegaard so just need to carry ca8ab12 as debian patch
>  >>>
>  >>> Yes, that is what I did already - sorry I forgot to mention:
>  >>>
> https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/020140820~e04e19a.patch/
>  >>
>  >> Whoops, I was too quick: I understand now that I missed a followup
>  >> commit. Thanks!
>  >
>  > Hmm - how is a fix for freebsd vs. dragonflybsd gonna help with Hurd?
>
> I think I got it now (you really meant commit afcb3e1).

That's for pty though, so it's pty of forkpty that fails? :)

I put the wrong sha1 when i responded the first time i intended the one in the 
patch above.

-- 
Riccardo Magliocchetti
@rmistaken

http://menodizero.it

**Comment by jonassmedegaard** [comment]
Quoting Riccardo Magliocchetti (2015-10-13 17:17:24)
> Il 13/10/2015 17:12, Jonas Smedegaard ha scritto:
>> Quoting Jonas Smedegaard (2015-10-13 16:57:33)
>>> Quoting Jonas Smedegaard (2015-10-13 16:54:11)
>>>> Quoting Jonas Smedegaard (2015-10-13 16:52:11)
>>>>> Quoting Riccardo Magliocchetti (2015-10-13 12:47:41)
>>>>>> @jonassmedegaard so just need to carry ca8ab12 as debian patch
>>>>>
>>>>> Yes, that is what I did already - sorry I forgot to mention:
>>>>>
>> https://sources.debian.net/src/uwsgi/2.0.11.2-1/debian/patches/
> 020140820~e04e19a.patch/
>>>>
>>>> Whoops, I was too quick: I understand now that I missed a followup
>>>> commit. Thanks!
>>>
>>> Hmm - how is a fix for freebsd vs. dragonflybsd gonna help with 
>>> Hurd?
>>
>> I think I got it now (you really meant commit afcb3e1).
>
> That's for pty though, so it's pty of forkpty that fails? :)
>
> I put the wrong sha1 when i responded the first time i intended the one in the
> patch above.

I already had a local fix for pty. I wanted to fix forkpty.

I cherry-picked e04e19a and dropped a local patch for pty (by mistake!)

So my aim was forkpty, but failure was pty.

I now cherry-picked afcb3e1 uploaded to Debian.  I will let you know in 
a few hours it succesfully autobuilds on Hurd - i.e. if _both_ your 
patches worked.

Sorry for (my parts of) the confusion :-/

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
It worked!

**Comment by xrmx** [comment]
Thanks for sorting this out!
