### ISSUE TITLE
xattr plugin fails to build on kFreeBSD

### ISSUE THREAD

**Issue by jonassmedegaard** [unbit/uwsgi#696]
Building xattr plugin for kFreeBSD archs fails:

https://buildd.debian.org/status/fetch.php?pkg=uwsgi&arch=kfreebsd-amd64&ver=2.0.6%7Edfsg-8%2Bexp1&stamp=1408456324

https://buildd.debian.org/status/fetch.php?pkg=uwsgi&arch=kfreebsd-i386&ver=2.0.6%7Edfsg-8%2Bexp1&stamp=1408456864

I suspect linkage against libattr would work, bbut I am unaware if that requires adaptations of the code.

**Comment by xrmx** [comment]
Closing as documentation has been updated.
