### ISSUE TITLE
how to transfer object to spool?

### ISSUE THREAD

**Issue by xurwxj** [unbit/uwsgi#743]
when uwsgi spooler work with django, how to transfer model instance, request, etc. to spooler?
also how to get context work in spooler?

uwsgi spooler only support str param now.

**Comment by bwesen** [comment]
In case someone else comes here (like me), yes, I get the same problem (now with Django 2.2). Even after calling django.setup(), templates are not found but everything else works (I realize this has nothing to do with uwsgi but it must be a pretty common use-case though, spooling email sending and stuff that needs templates).

**Comment by NotANormalNerd** [comment]
Hello fellow developers,

If you are here, you seem to be in confusion and distress. 
The correct solution for the problem above and others (not having a correctly setup django environment in your uwsgi spooler) is twofold:

1. set `--spooler-chdir` to your Django Applications root directory.
2. do a `import django; django.setup(set_prefix=False)` in your `tasks.py`

This way, the spooler (which should be seen as a completely different python process) will change into the correct location and sets up the Django environment correctly.

Hope this helps someone!
Best regards, Dennis
