### ISSUE TITLE
uwsgi/websockets has too strict dependency beeing built against libssl

### ISSUE THREAD

**Issue by harmv** [unbit/uwsgi#744]
## description

When using websockets, uwsgi insists on beeing built against libssl.

Although typically websocket app deployments  might
1. not need wss at all
2. or have uwsgi behing a webserver (eg nginx) that terminates all sll
  
From a deployment point of view, its not clean to have an additional, unneeded required package. 

## steps to reproduce
1. use websockets feature on ubuntu 14.04 (default uwsgi version)
    deploy uwsgi app behind nginx
2. not using https or wss

## result

uwsgi gives this error

    Tue Oct 14 09:34:05 2014 - you need to build uWSGI with SSL support to use the websocket handshake api function !!!

## expected result

As uwsgi is not doing any ssl wss stuff, it should not complain about needing beeing built against libssl.
I would only expect the SSL requirement, when uwsgi has to do wss related stuff.

**Comment by xrmx** [comment]
On debian / ubuntu nginx package depends on openssl's libssl so closing this.
