### ISSUE TITLE
how to gracefully exit from application when use uwsgi websocket?

### ISSUE THREAD

**Issue by xinghua** [unbit/uwsgi#769]
hi, 

when use websocket in uwsgi,  if client close websocket connection,  I will get en exception like " "unable to receive websocket message", so
i catch it as below:
        try:
             message = uwsgi.websocket_recv()
        except IOError:
             ### how to do?
a compliant method to return ['  '],  but uwsgi will raise a exception "headers already sent",  
so what should i do?

thanks

**Comment by rockallite** [comment]
See the code example here:
http://uwsgi-docs.readthedocs.io/en/latest/articles/OffloadingWebsocketsAndSSE.html#common-pitfalls

**Comment by Ericwonne** [comment]
What if someone is using django?
