### ISSUE TITLE
statsd plugin unavailable in 2.0.8 after installing from pip

### ISSUE THREAD

**Issue by Fiedzia** [unbit/uwsgi#773]
ubuntu 14.10, python3.4, uwsgi in virtualenv using pip install uwsgi

uwsgi --plugin-list 2>&1| grep stats
stats_pusher_socket

stats_pusher_statsd seems to be missing.
strings venv/bin/uwsgi | grep statsd
# nothing here

How can I get it?

**Comment by harishkashyap** [comment]
@Fiedzia this still doesn't work for me in the latest uwsgi

**Comment by akx** [comment]
This _might_ be caused by a cached uwsgi wheel without the plugin built in (since the `pip` caching algorithm doesn't know about the arbitrary envvar.

Try with `UWSGI_EMBED_PLUGINS=stats_pusher_statsd pip install --no-cache-dir uwsgi`, maybe?
