### ISSUE TITLE
'log-master' disables all logging

### ISSUE THREAD

**Issue by rectalogic** [unbit/uwsgi#806]
In 2.0.9, this logs nothing to the specified file:

    uwsgi --http :9090 --daemonize2 /tmp/uwsgi.log --logto /tmp/uwsgi.log --master --log-master --processes 2

In 1.9.16 the above works.

Removing `--log-master` makes it log to the file in 2.0.9:

    uwsgi --http :9090 --daemonize2 /tmp/uwsgi.log --logto /tmp/uwsgi.log --master --processes 2

(without also specifying `--logto`, pre-daemonization logging goes to the console)

**Comment by unbit** [comment]
This is a really painful part of the code. There are a bunch of tickets about the integration of log-master with logto/logto2 and daemonize/daemonize2. The last patch (that broke your usage) is this one: https://github.com/unbit/uwsgi/pull/642

Frankly i think that reintroducing the check for daemonize2 will not be a problem, maybe @prymitive could give a look too
