### ISSUE TITLE
gcc: Error: not recognized commandline option »-rdynamic«

### ISSUE THREAD

**Issue by jxsl13** [unbit/uwsgi#817]
tried compiling it on a windows server via cygwin

**Comment by unbit** [comment]
Which gcc version ? does it build removing it from uwsgiconfig.py ?

**Comment by jxsl13** [comment]
sadly I switched to linux server .. so I cannot answer any further questions :/

**Comment by unbit** [comment]
sadly ? you have done the right thing :)
