### ISSUE TITLE
transformation_gzip never works for me on v2.0.9

### ISSUE THREAD

**Issue by nikolay** [unbit/uwsgi#819]
Here's my config:

```ini
[uwsgi]
http = 0.0.0.0:80
listen = 4096

stats = /var/run/uwsgi.sock

master = true
thunder-lock = true
workers = 32
max-requests = 1024
buffer-size = 65535
vacuum = true

route-if = contains:${HTTP_ACCEPT_ENCODING};gzip goto:mygzipper
route-run = last:

route-label = mygzipper
route = ^/$ gzip:

module = mycompany.api
callable = app

need-app = true
```
I tried replacing this with `http-auto-gzip` and setting the `uWSGI-Encoding` header, but, again, it never works. When I installed uWSGI, here's the log with the activated modules:

```
pcre = True
kernel = Linux
malloc = libc
execinfo = False
ifaddrs = True
ssl = False
zlib = True
locking = pthread_mutex
plugin_dir = .
timer = timerfd
yaml = embedded
json = False
filemonitor = inotify
routing = True
debug = False
capabilities = False
xml = expat
event = epoll
```

**Comment by nikolay** [comment]
Closing as replacing `route` with `response-route` fixed the issue, but the documentation needs improvement as it's a bit confusing at the moment.

**Comment by unbit** [comment]
response-route is not related here, as transformations can be defined until the last moment. Maybe with response-route you are bypassing something related with your app.
