### ISSUE TITLE
gzip transformation is not working (most of the time)

### ISSUE THREAD

**Issue by nikolay** [unbit/uwsgi#822]
I have the following configuration and sometimes it works, most of the time - it doesn't.

```
response-route-if = contains:${HTTP_ACCEPT_ENCODING};gzip gzip:
route-run = last:
```
When I try to manually fetch via `curl -s -H "Accept-Encoding: gzip" url | gunzip`, I see the proper content, but also this error at the end:
```
gzip: stdin: unexpected end of file
```
I know about `--compressed` option of `curl`, just wanted to debug as I get empty responses most of the time with it.

**Comment by unbit** [comment]
Ensure your app does not add header like Content-Length that will break the final response. Eventually add -N --raw to get the low-level output that should clarify what is happening

**Comment by nikolay** [comment]
@unbit Is it possible that the bug is because I had `route-run = last:` and not `response-route-run = last:`? I just tried with the following and it seems to work consistently:
```
response-route-if = contains:${HTTP_ACCEPT_ENCODING};gzip gzip:
response-route-run = chunked:
response-route-run = last:
```

**Comment by unbit** [comment]
It works constantly because of chunked the "cleans" (well, more or less) headers generated by your app.

If you report the headers that your app generates we can surely understand what is going on

**Comment by xrmx** [comment]
>6 months without followup, closing.
