### ISSUE TITLE
WARNING: Can't find section "uwsgi" in INI configuration file uwsgi.ini

### ISSUE THREAD

**Issue by neo-hu** [unbit/uwsgi#823]
[default]
umask = 002
virtualenv = /var/www/env
master = true
no-orphans = true
gid = www-data
uid = www-data
threads = 1
env = DJANGO_SETTINGS_MODULE=project.settings

[server1]
ini = :default
...

[server2]
ini = :default
.....

wsgi --ini uwsgi.ini

WARNING: Can't find section "uwsgi" in INI configuration file uwsgi.ini?

**Comment by RobertTian** [comment]
Change [default]  to [uwsgi]  ?

**Comment by RobertTian** [comment]
OR: uwsgi --ini uwsgi.ini:server1 
OR: uwsgi --ini uwsgi.ini:server2

**Comment by xrmx** [comment]
This looks like user error with a prompt suggesion on how to fix things, closing then.
