### ISSUE TITLE
Gevent monkey patching is not working

### ISSUE THREAD

**Issue by cenkalti** [unbit/uwsgi#826]
This is the minimum application for demonstrating the problem.
```bash
$ pip freeze
Flask==0.10.1
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
gevent==1.0.1
greenlet==0.4.5
itsdangerous==0.24
uWSGI==2.0.9
wsgiref==0.1.2
```
```ini
# uwsgi.ini

[web]
strict = true
http = 0.0.0.0:8080

master = true
processes = 4

file = app.py
callable = app

gevent = 1024
gevent-monkey-patch = true
```
```python
# app.py

# from gevent.monkey import patch_all; patch_all()

from threading import Lock

from flask import Flask

app = Flask(__name__)

@app.route("/")
def index():
    l = Lock()
    print type(l), l
    return "hello world"
```

When I run uwsgi and make a request via curl:
```
uwsgi --ini uwsgi.ini:web
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.9 (64bit) on [Wed Jan 28 01:13:49 2015] ***
compiled with version: 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56) on 28 January 2015 00:58:05
os: Darwin-14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64
nodename: tardis.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/cenk/projects/uwsgi_gevent_bug
detected binary path: /Users/cenk/.virtualenvs/env/bin/uwsgi
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 4864
- async cores set to 1024 - fd table size: 4864
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8080 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:57132 (port auto-assigned) fd 3
Python version: 2.7.6 (default, Sep  9 2014, 15:04:36)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
Python main interpreter initialized at 0x7ff5da601170
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 53027840 bytes (51785 KB) for 4096 cores
*** Operational MODE: preforking+async ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7ff5da601170 pid: 62055 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 62055)
spawned uWSGI worker 1 (pid: 62056, cores: 1024)
spawned uWSGI worker 2 (pid: 62057, cores: 1024)
spawned uWSGI worker 3 (pid: 62058, cores: 1024)
spawned uWSGI worker 4 (pid: 62059, cores: 1024)
*** running gevent loop engine [addr:0x1083b80e0] ***
spawned uWSGI http 1 (pid: 62060)
<type 'thread.lock'> <thread.lock object at 0x10bfea290>
[pid: 62056|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 294 bytes} [Wed Jan 28 01:14:01 2015] GET / => generated 11 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 79 bytes (3 switches on core 1023)
```
Note the line: ```<type 'thread.lock'> <thread.lock object at 0x10bfea290>```
After I patching the modules manually (by enabling the commented out line in app.py) The line prints as: ```<class 'gevent._semaphore.Semaphore'> <Semaphore counter=1 _links[0]>```

I have tested both in OS X and Linux.
Is this a bug in uWSGI or am I doing something wrong?

**Comment by unbit** [comment]
``--gevent-monkey-patch`` is called before entering the main loop, so if you load modules on startup they will not be "monkey-patched". In 2.1 you have ``--gevent-early-monkey-patch`` to simplify the configuration, but in 2.0 you need to call the function in your code

**Comment by cenkalti** [comment]
Just wondering, is this documented in somewhere?
At http://uwsgi-docs.readthedocs.org/en/latest/Gevent.html#monkey-patching it says:
> uWSGI uses native gevent api, so it does not need monkey patching. That said, your code may need it, so remember to call gevent.monkey.patch_all() at the start of your app. As of uWSGI 1.9, the convenience option --gevent-monkey-patch will do that for you.

From this paragraph I understand that if I use ```--gevent-monkey-patch``` option uWSGI does the monkey-patching before **starting** my application. But it must be patched before **loading** my application. I think this should be clear in documents.

**Comment by unbit** [comment]
Feel free to make a pull request in uwsgi-docs

**Comment by jianbin-wei** [comment]
@unbit --gevent-early-monkey-patch was added in #701 in 9/2014.  Is there any specific reason it is not in uwsgi 2.0.x after almost 2 years?  Do we have a timeline of 2.1.x release?

**Comment by unbit** [comment]
@jianbin-wei sorry no timeline for 2.1, i think during the summer we will start releasing development tarballs, but it would require lot of time to have a stable (2.2) version. Just make a pull request with the backport as i do not think is too much invasive.

**Comment by jianbin-wei** [comment]
@unbit created pull request #1254
