### ISSUE TITLE
Sticky sessions in fastrouter/httprouter

### ISSUE THREAD

**Issue by unbit** [unbit/uwsgi#83]
When some kind of async database replica is in place, having the same client connecting to the same backend is the best solution to avoid incongruences in responses (mainly caused by sync gaps)

Sticky sessions are a common technique, but as always i want to give them to uWSGI users with little effort from a code-changing point of view.

My idea is setting a cookie in the fastrouter with the address of the backend (encrypted).

The encrypted blob should contain the ip address of the client, the backend node (obviously), a random IV and should support different kind of keys (from preshared keys to the same certificate used by the secured subscription system)

If the fastrouter find the cookie already set in the request it will simply decrypt it and use the supplied address.

Obviously an api function could be added (like uwsgi.sticky()) to generate the encrypted blob from the app only for the requests requiring it.

**Comment by EndenDragon** [comment]
@unbit How does one implement the iphash? I'm from https://github.com/miguelgrinberg/Flask-SocketIO/issues/535 and I do not know where to start.

**Comment by johaven** [comment]
> now it is easy to implement custom algos for routers. The uWSGI 2.1 iphash one should be used for stickyness

When this will be available ?
