### ISSUE TITLE
Emperor should register vassals in service discovery

### ISSUE THREAD

**Issue by thedrow** [unbit/uwsgi#830]
This will allow upstream proxies to be aware of how much processing power a certain application has and can request new vassals to be spawned accordingly.
If an Emperor is run on each server this can aid autoscaling when run in Broodlord mode.

**Comment by unbit** [comment]
I have opened the https://github.com/unbit/uwsgi-etcd repository to discuss about better integration with services discovery and distributed configurators. Currently the consul plugin by @Ultrabug is the best base to start with (and it could be improved too with more features). I will post an RFC in the issues with a preliminary analysis

**Comment by thedrow** [comment]
Great!
Thanks.

**Comment by ultrabug** [comment]
Looking forward to it, thx for the heads up @unbit

**Comment by unbit** [comment]
https://github.com/unbit/uwsgi-etcd/issues/1 i have started here
