### ISSUE TITLE
Unable to build on Solaris 11

### ISSUE THREAD

**Issue by ntamblyn** [unbit/uwsgi#831]
using profile: buildconf/core.ini
detected include path: ['/opt/csw/lib/gcc/i386-pc-solaris2.10/4.9.2/include', '/usr/local/include', '/opt/csw/include', '/opt/csw/lib/gcc/i386-pc-solaris2.10/4.9.2/include-fixed', '/usr/include']
detected CPU cores: 16
configured CFLAGS: -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_PORT -DUWSGI_EVENT_TIMER_USE_PORT -DUWSGI_EVENT_FILEMONITOR_USE_PORT -I/usr/include/pcre -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="1" -DUWSGI_VERSION_MINOR="0" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_SSL -I/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\""
*** uWSGI compiling server core ***
[thread 2][/opt/csw/bin/gcc-4.9] core/utils.o
[thread 0][/opt/csw/bin/gcc-4.9] core/protocol.o
[thread 1][/opt/csw/bin/gcc-4.9] core/socket.o
[thread 4][/opt/csw/bin/gcc-4.9] core/logging.o
[thread 5][/opt/csw/bin/gcc-4.9] core/master.o
[thread 6][/opt/csw/bin/gcc-4.9] core/master_utils.o
[thread 8][/opt/csw/bin/gcc-4.9] core/emperor.o
[thread 9][/opt/csw/bin/gcc-4.9] core/mule.o
[thread 7][/opt/csw/bin/gcc-4.9] core/notify.o
[thread 11][/opt/csw/bin/gcc-4.9] core/subscription.o
[thread 10][/opt/csw/bin/gcc-4.9] core/stats.o
[thread 12][/opt/csw/bin/gcc-4.9] core/sendfile.o
[thread 13][/opt/csw/bin/gcc-4.9] core/async.o
[thread 14][/opt/csw/bin/gcc-4.9] core/master_checks.o
[thread 15][/opt/csw/bin/gcc-4.9] core/fifo.o
[thread 3][/opt/csw/bin/gcc-4.9] core/offload.o
[thread 12][/opt/csw/bin/gcc-4.9] core/io.o
[thread 7][/opt/csw/bin/gcc-4.9] core/static.o
[thread 15][/opt/csw/bin/gcc-4.9] core/websockets.o
[thread 13][/opt/csw/bin/gcc-4.9] core/spooler.o
[thread 14][/opt/csw/bin/gcc-4.9] core/snmp.o
[thread 9][/opt/csw/bin/gcc-4.9] core/exceptions.o
[thread 3][/opt/csw/bin/gcc-4.9] core/config.o
[thread 10][/opt/csw/bin/gcc-4.9] core/setup_utils.o
[thread 0][/opt/csw/bin/gcc-4.9] core/clock.o
[thread 5][/opt/csw/bin/gcc-4.9] core/init.o
[thread 15][/opt/csw/bin/gcc-4.9] core/buffer.o
[thread 7][/opt/csw/bin/gcc-4.9] core/reader.o
[thread 14][/opt/csw/bin/gcc-4.9] core/writer.o
[thread 10][/opt/csw/bin/gcc-4.9] core/alarm.o
[thread 11][/opt/csw/bin/gcc-4.9] core/cron.o
[thread 9][/opt/csw/bin/gcc-4.9] core/hooks.o
[thread 0][/opt/csw/bin/gcc-4.9] core/plugins.o
[thread 13][/opt/csw/bin/gcc-4.9] core/lock.o
[thread 6][/opt/csw/bin/gcc-4.9] core/cache.o
[thread 12][/opt/csw/bin/gcc-4.9] core/daemons.o
core/hooks.c:392:12: error: conflicting types for ‘sethostname’
 extern int sethostname(char *, int);
            ^
In file included from ./uwsgi.h:229:0,
                 from core/hooks.c:1:
/usr/include/unistd.h:473:12: note: previous declaration of ‘sethostname’ was here
 extern int sethostname(const char *, size_t);
            ^
[thread 5][/opt/csw/bin/gcc-4.9] core/errors.o
[thread 4][/opt/csw/bin/gcc-4.9] core/hash.o

**Comment by xrmx** [comment]
Does it work if you remove the extern in core/hooks.c:392 ?

**Comment by ntamblyn** [comment]
now i am getting 

`*** uWSGI linking ***
/opt/csw/bin/gcc-4.9 -o uwsgi -L/lib -L/opt/csw/lib core/utils.o core/protocol.o core/socket.o core/logging.o core/master.o core/master_utils.o core/emperor.o core/notify.o core/mule.o core/subscription.o core/stats.o core/sendfile.o core/async.o core/master_checks.o core/fifo.o core/offload.o core/io.o core/static.o core/websockets.o core/spooler.o core/snmp.o core/exceptions.o core/config.o core/setup_utils.o core/clock.o core/init.o core/buffer.o core/reader.o core/writer.o core/alarm.o core/cron.o core/hooks.o core/plugins.o core/lock.o core/cache.o core/daemons.o core/errors.o core/hash.o core/master_events.o core/chunked.o core/queue.o core/event.o core/signal.o core/strings.o core/progress.o core/timebomb.o core/ini.o core/fsmon.o core/mount.o core/metrics.o core/plugins_builder.o core/sharedarea.o core/rpc.o core/gateway.o core/loop.o core/cookie.o core/querystring.o core/rb_timers.o core/transformations.o core/uwsgi.o proto/base.o proto/uwsgi.o proto/http.o proto/fastcgi.o proto/scgi.o proto/puwsgi.o core/zlib.o lib/sun_fixes.o core/regexp.o core/routing.o core/yaml.o core/ssl.o core/legion.o core/xmlconf.o core/dot_h.o core/config_py.o plugins/python/python_plugin.o plugins/python/pyutils.o plugins/python/pyloader.o plugins/python/wsgi_handlers.o plugins/python/wsgi_headers.o plugins/python/wsgi_subhandler.o plugins/python/web3_subhandler.o plugins/python/pump_subhandler.o plugins/python/gil.o plugins/python/uwsgi_pymodule.o plugins/python/profiler.o plugins/python/symimporter.o plugins/python/tracebacker.o plugins/python/raw.o plugins/gevent/gevent.o plugins/gevent/hooks.o plugins/ping/ping_plugin.o plugins/cache/cache.o plugins/nagios/nagios.o plugins/rrdtool/rrdtool.o plugins/carbon/carbon.o plugins/rpc/rpc_plugin.o plugins/corerouter/cr_common.o plugins/corerouter/cr_map.o plugins/corerouter/corerouter.o plugins/fastrouter/fastrouter.o plugins/http/http.o plugins/http/keepalive.o plugins/http/https.o plugins/http/spdy3.o plugins/ugreen/ugreen.o plugins/signal/signal_plugin.o plugins/syslog/syslog_plugin.o plugins/rsyslog/rsyslog_plugin.o plugins/logsocket/logsocket_plugin.o plugins/router_uwsgi/router_uwsgi.o plugins/router_redirect/router_redirect.o plugins/router_basicauth/router_basicauth.o plugins/zergpool/zergpool.o plugins/redislog/redislog_plugin.o plugins/mongodblog/mongodblog_plugin.o plugins/router_rewrite/router_rewrite.o plugins/router_http/router_http.o plugins/logfile/logfile.o plugins/router_cache/router_cache.o plugins/rawrouter/rawrouter.o plugins/router_static/router_static.o plugins/sslrouter/sslrouter.o plugins/spooler/spooler_plugin.o plugins/cheaper_busyness/cheaper_busyness.o plugins/symcall/symcall_plugin.o plugins/transformation_tofile/tofile.o plugins/transformation_gzip/gzip.o plugins/transformation_chunked/chunked.o plugins/transformation_offload/offload.o plugins/router_memcached/router_memcached.o plugins/router_redis/router_redis.o plugins/router_hash/router_hash.o plugins/router_expires/expires.o plugins/router_metrics/plugin.o plugins/transformation_template/tt.o plugins/stats_pusher_socket/plugin.o -lpthread -lm -lz -lsendfile -lrt -R/usr/lib -lpcre -luuid -lssl -lcrypto -lxml2 -lsocket -lnsl -lrt -ldl -lm -lpython2.7 -lcrypt
Undefined			first referenced
 symbol  			    in file
EC_KEY_free                         core/ssl.o
SSL_get0_next_proto_negotiated      plugins/http/spdy3.o
SSL_CTX_set_next_protos_advertised_cb plugins/http/https.o
EC_KEY_new_by_curve_name            core/ssl.o
ld: fatal: symbol referencing errors. No output written to uwsgi
*** error linking uWSGI ***`

**Comment by ntamblyn** [comment]
Managed to get this to build now by commenting out the ldflags option -L/lib in the uwsgiconfig.py

**Comment by xrmx** [comment]
@ntamblyn I think this should be closed when it works out of the box :) Could you please a diff of all your changes? thanks

**Comment by ntamblyn** [comment]
i am not entirely sure how to do that over github , do you mean i just diff the files i have changed and post them within this comment box ? Sorry i am new to github

**Comment by xrmx** [comment]
Yes, paste the git diff here. Bonus points if you quote it inside "```"

**Comment by ntamblyn** [comment]
okay here we go - I hope the format is okay :)

``` 
diff --git a/opt/old-uwsgi/uwsgi-2.0.9/core/hooks.c b/opt/uwsgi-2.0.9/core/hooks.c
index 8ada89b..0d10fdf 100644
--- a/opt/old-uwsgi/uwsgi-2.0.9/core/hooks.c
+++ b/opt/uwsgi-2.0.9/core/hooks.c
@@ -389,7 +389,7 @@ static int uwsgi_hook_chown2(char *arg) {
 
 
 #ifdef __sun__
-extern int sethostname(char *, int);
+/*extern int sethostname(char *, int);*/
 #endif
 static int uwsgi_hook_hostname(char *arg) {
 #ifdef __CYGWIN__
```

```
diff --git a/opt/old-uwsgi/uwsgi-2.0.9/uwsgiconfig.py b/opt/uwsgi-2.0.9/uwsgiconfig.py
index 84e8ef1..e2fc16a 100644
--- a/opt/old-uwsgi/uwsgi-2.0.9/uwsgiconfig.py
+++ b/opt/uwsgi-2.0.9/uwsgiconfig.py
@@ -813,7 +813,7 @@ class uConf(object):
             self.libs.append('-lsendfile')
             self.libs.append('-lrt')
             self.gcc_list.append('lib/sun_fixes')
-            self.ldflags.append('-L/lib')
+            #self.ldflags.append('-L/lib')
             if not uwsgi_os_v.startswith('Nexenta'):
                 self.libs.remove('-rdynamic')

```

**Comment by xrmx** [comment]
@ntamblyn that's great! thanks

**Comment by xrmx** [comment]
@ntamblyn any chance you can try latest git with this patch applied?

```
diff --git a/core/hooks.c b/core/hooks.c
index 0e6c536..6842cbc 100644
--- a/core/hooks.c
+++ b/core/hooks.c
@@ -389,8 +389,10 @@ static int uwsgi_hook_chown2(char *arg) {
 
 
 #ifdef __sun__
+#if !defined(UWSGI_SUNOS_UNISTD_SETHOSTNAME)
 extern int sethostname(char *, int);
 #endif
+#endif
 static int uwsgi_hook_hostname(char *arg) {
 #ifdef __CYGWIN__
        return -1;
diff --git a/uwsgiconfig.py b/uwsgiconfig.py
index f4bc2db..da85f5e 100644
--- a/uwsgiconfig.py
+++ b/uwsgiconfig.py
@@ -770,7 +770,12 @@ class uConf(object):
             self.libs.append('-lsendfile')
             self.libs.append('-lrt')
             self.gcc_list.append('lib/sun_fixes')
-            self.ldflags.append('-L/lib')
+            sunos_major = int(uwsgi_os_k.split('.')[0])
+            sunos_minor = int(uwsgi_os_k.split('.')[1])
+            if sunos_major == 5 and sunos_minor > 10:
+                self.cflags.append('-DUWSGI_SUNOS_UNISTD_SETHOSTNAME')
+            else:
+                self.ldflags.append('-L/lib')
             if not uwsgi_os_v.startswith('Nexenta'):
                 self.libs.remove('-rdynamic')
 
```

**Comment by ntamblyn** [comment]
That patch works like a charm , good job :+1: 

However i am now trying to install with the psgi plugin and i get 

```
python uwsgiconfig.py --plugin plugins/psgi core
using profile: buildconf/core.ini
detected include path: ['/opt/csw/lib/gcc/i386-pc-solaris2.10/4.9.2/include', '/usr/local/include', '/opt/csw/include', '/opt/csw/lib/gcc/i386-pc-solaris2.10/4.9.2/include-fixed', '/usr/include']
*** uWSGI building and linking plugin plugins/psgi ***
Warning (mostly harmless): No library found for -ldb-4.8
[/opt/csw/bin/gcc-4.9] ./psgi_plugin.so
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
gcc-4.9: error: language chip=pentium_pro not recognized
*** unable to build psgi plugin *** 
```

**Comment by unbit** [comment]
It looks like your perl environment has been built with sunstudio and not with a free compiler.

You can edit plugins/psgi/uwsgiplugin.py to remove unsupported CFLAGS

**Comment by janorn** [comment]
Any chance your patch @xrmx will be added to a new release? It works fine for building uwsgi on Solaris 11.2.

**Comment by unbit** [comment]
@xrmx can you refactor it to support gcc/clang too and make a pull request for 2.1 (eventually i can backport it) ?

**Comment by xrmx** [comment]
@unbit wsure, ill open a pull request later today
