### ISSUE TITLE
PHP gateway interface?

### ISSUE THREAD

**Issue by WST** [unbit/uwsgi#832]
Is there any chance of implementing some kind of gateway interface for the PHP plugin?
I know that there are no standards for PHP, similar to Python’s WSGI, Ruby’s Rack, Lua’s WSAPI and others. But the idea of not having to run the same initialization code over and over again on each request, looks pretty sweet for me (and, I beleive, would be appreciated by others). I realize that it’s my second feature request, and you would probably like more if I reported a bug, but, to be honest, the bugs did not happen to me yet, though I already used uWSGI for quite a long time for a lot of PHP, Python and Ruby applications.

**Comment by unbit** [comment]
I think you should propose it to some php-centric community to come out with a specification but, frankly, i have no idea if it would of interest. AFAIK the only similar approach is the one followed by the Photon project (http://www.photon-project.com/). It uses zeromq.

Probably a psgi like interface would be more than enough:

```php
function application($environ) {

}
```

**Comment by WST** [comment]
Sure, the interface should just do what it’s expected to do, and doesn’t have to be any complex. I also share your doubt that it makes sense to propose a new standard, as, I beleive, this idea is quite obvious and many people could already suggest it.

It is often beleived that PHP is not designed for running looped applications, for example, there is an article about it: http://software-gunslinger.tumblr.com/post/47131406821/php-is-meant-to-die
However, from my own experience I can say that the danger of memory leaks is hyperbolized. I used to run an XMPP bot written in PHP for weeks without significant changes in memory consumption (and it was some early PHP 5.x version, now the things became even better). Finally, uWSGI is smart enough to restart the worker processes from time to time, depending on your settings.

The obvious fact is that this interface (if implemented) shouldn’t replace the “classic” way of running PHP applications, as it would make it impossible to use uWSGI as a drop-in replacement for such tools as php-fpm or Apache with mod_php.

**Comment by unbit** [comment]
Well, find a name for it and i will create a repository for experimenting :)

**Comment by WST** [comment]
Well, if you are expecting my code contributions, I doubt I’m a right person to be asked — though I really love uWSGI, my knowledge in C programming and general theory of multi-threaded asynchronous applications is poor and probably only enough to create guestbook-like CGI applications. Diving into such a complex network application is clearly beyond my abilities.

About the name — as there is no standard for it, the interface does not really need a name, but well, if you are planning to develop it as a standalone plugin, you may find a name like “phpsgi” useful.

**Comment by unbit** [comment]
I was only looking for a name  :) Yes, i will build an external plugin (and eventually merge it back with the official php one). But i will absolutely ask you for tests/reports and for gathering people willing to try it :)

**Comment by WST** [comment]
Sure, I am doing a lot of work trying to tell my friends that uWSGI is awesome and worth trying, but most of them are skeptical about it: creators of the “noodles code” don’t want to know anything but Apache, more advanced PHP coders say “why need anything if there is the awesome php-fpm”, Ruby developers say “uWSGI? I’ve heard it’s something for Python”, Python developers say it’s too new and untested, and so on… Sometimes when I try to explain the goals of uWSGI, they say “damn, it’s not UNIX way at all when one app does everything” or “wow, so many features, it will cost a terrible lot of resources, doesn’t worth trying”. But at least I can promise my own participation in the testing, of course.

**Comment by unbit** [comment]
Well ok ;) But regarding the UNIX way, uWSGI is really UNIXish as it is composed by lot of different (very little, check the plugins dir) pieces that you can combine together to build something bigger (or to pair it with other tools). And even with all of those features, its memory footprint is always littler than the other tools around, so you now have an answer for those kind of users :)

**Comment by unbit** [comment]
Here it is: https://github.com/unbit/uwsgi-phpsgi/

**Comment by WST** [comment]
Wow, that was fast.

Ok, it does not work through the native “uwsgi” protocol yet, right?
So I run it using an HTTP socket.
http://yamato.averkov.net:9090/foo?bar=baz

Note that the variable $env['COUNTRY'] is set through the vassal configuration file
route-run = addvar:COUNTRY=${geoip[country_code]}

As soon as I have more spare time, I will write a more complex test app.

**Comment by unbit** [comment]
All of the non-php related features works, so you can use uwsgi protocol too. (The modifier1 is currently 0, maybe in the future we can use an official one). Btw, i cosinder this issue closed as future development will continue on the uwsgi-phpsgi repository
