### ISSUE TITLE
Stats server over HTTP

### ISSUE THREAD

**Issue by iiSeymour** [unbit/uwsgi#834]
Is it possible to get the stats over HTTP?

**Comment by unbit** [comment]
check the --stats-http option

**Comment by iiSeymour** [comment]
Adding `stats-http = 127.0.0.1:9002` to my ini file has no effect? I see no output related to this option on stdout and `curl 127.0.0.1:9002` just gives

    curl: (7) Failed connect to 127.0.0.1:9002; Connection refused

However `stats = 127.0.0.1:9002` works as expect

    *** Stats server enabled on 127.0.0.1:9002 fd: 18 ***

I'm running:

```bash
$ uwsgi --version                                                                                                                                                                                          
2.0.9
```

Any ideas?

**Comment by iiSeymour** [comment]
Should have [RTFM](http://uwsgi-docs.readthedocs.org/en/latest/Options.html#stats-http). 

    stats = 127.0.0.1:9002
    stats-http = true

It would be useful to have the `stats-http` option on the [StatsServer](http://uwsgi-docs.readthedocs.org/en/latest/StatsServer.html) page.

**Comment by unbit** [comment]
feel free to make a pull request to the uwsgi-docs repository. Docs contributions are really appreciated.
Thanks
