### ISSUE TITLE
missing sharedarea waiting and websocket routines in python module

### ISSUE THREAD

**Issue by xtfxme** [unbit/uwsgi#837]
The python plugin does not expose these methods (note: the docs *do* mention this):

```
sharedarea_wait
websocket_send_from_sharedarea
websocket_send_binary_from_sharedarea
```

These would be **incredibly** useful for a backend application we are writing (threaded/multiprocess asynchronous websocket router... probably the exact thing these methods were introduced for ;)

They look pretty simple, so I'm fairly sure I can implement, but I figure I'd ask first since I'm slow at C :)

**Comment by unbit** [comment]
They was added only to perl, probably they can be ported to python too. A pull request would be accepted :)

**Comment by xtfxme** [comment]
http://lists.unbit.it/pipermail/uwsgi/2014-April/007305.html

i think we are going to do something with redis :) it's used elsewhere, and will provide more assurances.

thanks!
