### ISSUE TITLE
touch-reload style for clearing the cache

### ISSUE THREAD

**Issue by unbit** [unbit/uwsgi#85]
In a project (my company website) i have added 

touch-reload = .git/index

to trigger an instance reload whenever the git repository changes. This is mainly to clear the uWSGI cache as each page (after generated) is put there and served using the 'cache internal router'

Reloading the whole server (only to clear the cache) seems overkill, so a

--touch-cache-clear <file>

would be a great (and cheap) solution

**Comment by fheslouin** [comment]
I'm looking for a command to clear the cache on certain URI for instance. 

Is `touch-reload = .git/index` the only solution ?

**Comment by unbit** [comment]
you could map a file monitor to a uwsgi.cache_clear() api command:

```python
uwsgi.register_file_monitor(0, "/tmp", "worker", do_clear_cache)

def do_clear_cache(signal_number, filename):
    uwsgi.cache_clear()
```

**Comment by fheslouin** [comment]
Thanks @unbit, is there anything that could be used with the internal routing such as http://uwsgi-docs.readthedocs.io/en/latest/InternalRouting.html#the-first-example
