### ISSUE TITLE
Memory leak with psgi multi app setup

### ISSUE THREAD

**Issue by raigad** [unbit/uwsgi#850]
Hi , 
I am experiencing some memory leak with following setup 

```
[uwsgi]
plugins=psgi
socket=127.0.0.1:3000
#port for stats
stats=127.0.0.1:3001
memory-report=1
master=true
processes= 5
uid=userid
gid=userid

logformat= %(addr) - %(host) - [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
daemonize=/var/logs/uwsgi/error.log
req-logger = file:/var/logs/uwsgi/access.log

#mount web apps
mount=app1=/path/to/app1.pl
mount=app2=/path/to/app2.pl

#mount mobile apps
mount=app3=/path/to/app3.pl
mount=app4=/path/to/app4.pl

```

With above setup I get huge memory leak. Interesting thing is that when the master is set to false and process to 1 then there is no or very little memory leak.
```
master=false
processes= 1
```
I also tried with following setup and there is still memory leak
```
master=false
processes= 4
```

To me it seems that there is issue with psgi plugin managing memory for different proceses.

please also refer to:
https://github.com/unbit/uwsgi/pull/833
http://lists.unbit.it/pipermail/uwsgi/2014-November/007746.html

Please let me know if you need any further information to reproduce :) 
Thanks
Regards
Rohit

**Comment by unbit** [comment]
Very probably your app is not fork-friendly. Try adding lazy-apps = true

**Comment by raigad** [comment]
Yes I tried with lazy=true , then memory leak is not that significant but it is still leaking slowly.

**Comment by unbit** [comment]
lazy has other mechanics, try lazy-apps (it only changes the load timing)

**Comment by raigad** [comment]
I am using lazy-apps now the memory usage seems to be stable for now. I will keep close eye on that, If anything changes I will keep you posted. 
many thanks for prompt reply :+1:
