### ISSUE TITLE
Erroneous logging in hr_ssl_read() on success (2.0.9)

### ISSUE THREAD

**Issue by aldem** [unbit/uwsgi#855]
Hi,

Experimenting with HTTPS, and noticed this kind of messages logged:

> [uwsgi-http key:  client_addr: 127.0.0.1 client_port: 59613] hr_ssl_read(): Success [plugins/http/https.c line 383]

Lots of this (several lines per request) on normal (no client side errors) HTTPS traffic.

Command line:

> uwsgi --master --https :3000,localhost.crt,localhost.key --env RAILS_ENV=production --rack config.ru --processes 4 --post-buffering 65536 --lazy-apps

(the app is Redmine 3.0 - if this matters somehow)

**Comment by xrmx** [comment]
Looks like fixed already in 35701f6ac661b1f1c9884b658efe6d62fb1a1913 . Closing.
