### ISSUE TITLE
Make using sendfile() a configuration option instead of compiled in.

### ISSUE THREAD

**Issue by CleanCut** [unbit/uwsgi#862]
Using `sendfile()` breaks uwsgi in Docker Containers inside of Linux VirtualBox VMs running on top of OS X.  Unfortunately, this is exactly the new workflow we are trying to use for our development department at my day job. :-(

Technically, this is a VirtualBox upstream bug.  No one at VirtualBox seems interested in fixing it.  I have also not been able to figure out how to fix the bug in VirtualBox myself, yet.

However, a lot of other software that is affected by this bug (Apache and Nginx, for example) provide configuration options in the config files to disable the use of `sendfile()`.  This makes it easy to work around the problem.  With uwsgi, usage of `sendfile()` seems to be compiled in unconditionally on Linux.

Here are the upstream bugs:

https://www.virtualbox.org/ticket/12597
https://www.virtualbox.org/ticket/9069

Here's what I do to experience the problem:

1. On OS X 10.10 "Yosemite"...
2. Install [Boot2Docker](http://boot2docker.io), which is just VirtualBox + a headless Linux VM with the docker daemon pre-installed, combined with the docker client for OS X.
3. Create a CentOS 6-based docker container with a uwsgi application files mounted from a volume from the host OS X operating system.  This linux-container on linux-vm is where uwsgi gets installed.  It looks something like `docker run --name my-uwsgi-app -v /Users/cleancut/my-uwsgi-app:/app -p 8888:8888 centos6-based-image`
4. Load the app (I have nginx elsewhere configured to connect to the uwsgi app via a uwsgi connection).
5. Change one of the static files in `/users/cleancut/my-uwsgi-app`.  For example, modify a `.js` file.
6. Reload the app.  Insanity ensues.  The only way to get the static file to show up properly after the change is to shut down the docker container and the headless Linux VM it is running on, and then start it all back up again. :-(

If I can figure out a way to add this without too much trouble, I'll submit a pull request.

If I (or someone else) can fix the upstream bug, then this may bee moot.

Otherwise, I'll probably end up making a custom fork of uwsgi that just has `sendfile()` unconditionally disabled.  Assuming uwsgi can function without it on Linux.

**Comment by unbit** [comment]
Can't you use --disable-sendfile ?

**Comment by CleanCut** [comment]
@unbit And this is why I communicate with the ones in the know.  My google-fu must be weak today.

I searched and looked at help and still, I completely missed that.  Sorry for the distracting noise.

**Comment by CleanCut** [comment]
Using `--disable-sendfile` appears to solve the bug.  Thank you!
