### ISSUE TITLE
Empty rack request triggered when using Ruby 2.2.1 + rack 1.6.0

### ISSUE THREAD

**Issue by darthmdh** [unbit/uwsgi#868]
I upgraded Redmine to v3.0, and rebuilt the ruby base using ruby 2.2.1.  If I run Redmine via the built-in webrick server it runs fine.

I rebuilt the uwsgi rack plugin against the new ruby version, and adapted the configuration to use the new plugin ("plugin" and "rvm" options updated to point to new locations)

Redmine fails to run via uwsgi.  In production nginx front-ends using its uwsgi proxy, but if I take nginx out of the picture (bind uwsgi to a http socket and connect directly) exactly the same error is logged;

    RACK app 0 loaded in 3 seconds at 0xce1 (GC frequency: AGGRESSIVE)
    Empty RACK request.  skip.
    [pid: 19651|app: -1|req: -1/1] () {0 vars in 768 bytes} [Wed Mar 11 00:55:00 2015] => generated 0 bytes in 0 msecs (0) 0 headers in 0 bytes (0 switches on core 0)

There's nothing logged on the Redmine side because the request doesn't get past uwsgi.

My suspicion is that the rack plugin is not compatible with Ruby 2.2.1 or rack 1.6.0.

Prior to upgrading anything, the earlier Redmine version (2.5) ran fine using Ruby 2.1.5 & rack 1.4.5.
Uwsgi docs only talk about Ruby <= 1.9, none of which are supported upstream anymore.

Edit: I've reverted Ruby to the older version (2.1.5); the Redmine 3.0 setup retains Rails 4.2 and rack 1.6.0, however it works fine - issue seems to be rack plugin built against Ruby 2.2.1.

**Comment by unbit** [comment]
There are no known incompatibilities with ruby 2.2, but the problem could be rack 1.6 expecting some CGI var not exposed by uWSGI (or some non-standard-covered assumption like the need for HTTP_HOST to be equal to SERVER_NAME). Can you try with a simple hello world rack app ?

**Comment by darthmdh** [comment]
Rack 1.6 works fine (see edited comment).  Reverting just Ruby from 2.2.1 to 2.1.5 resolves the issue with uwsgi compatibility.

Using app.ru from http://uwsgi-docs.readthedocs.org/en/latest/RackQuickstart.html it fails with exactly the same message using the ruby 2.2.1-based rack plugin.

$ uwsgi --plugins http,rack221 --http-socket 8080 --http-modifier1 7 --rack app.ru
$ curl -I http://localhost:8080
[...]
Empty RACK request. skip.
[pid: 31961|app: -1|req: -1/1] () {0 vars in 382 bytes} ...

$ uwsgi --plugins http,rack215 --http-socket 8080 --http-modifier1 7 --rack app.ru
[pid: 32053|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 382 bytes} ...

**Comment by unbit** [comment]
It looks like your wsgi_request structure is somewhat different between the uwsgi binary and the rack221 plugin. That error (Empty RACK request. skip.) is generated before ruby api is called. How do you build the plugin ? I suggest you to use the 2.x way using the uwsgi binary itself:

```sh
PATH=path_to_ruby_bin_dir:$PATH uwsgi --build-plugin "plugins/rack rack221"
```

this ensure the correct structures are used

**Comment by darthmdh** [comment]
I follow the build instructions here:  https://uwsgi-docs.readthedocs.org/en/latest/Install.html#installing-from-source

I dropped my own buildconf/ INI file in which contains:

[uwsgi]
main_plugin = 
inherit = base
embedded_plugins = null
plugin_dir = /usr/local/lib/uwsgi

I then compile it per the vendor docs

    $ python uwsgiconfig.py --build myconfig
    $ for i in plugins/*; do python uwsgiconfig.py --plugin $i myconfig; done

And then the added python & ruby plugins to be referenced by version:

    $ source activate /path/to/python27
    $ python uwsgiconfig.py --plugin plugins/python myconfig python27
    $ source deactivate
    $ source activate /path/to/python34
    $ python uwsgiconfig.py --plugin plugins/python myconfig python34
    $ source deactivate
    $ rvm use ruby-2.2.1
    $ python uwsgiconfig.py --plugin plugins/rack myconfig rack221

And copy the new uwsgi into place:

    $ service uwsgi stop
    $ sudo mv /usr/local/bin/uwsgi /usr/local/bin/uwsgi-old
    $ sudo cp uwsgi /usr/local/bin
    $ service uwsgi start

For redmine specifically, I would then:

    $ rvm use ruby-2.1.5@redmine300
    $ python uwsgiconfig.py --plugin plugins/rack myconfig rack215

and in the uwsgi INI for redmine, use the options

    rvm = ruby-2.1.5@redmine300
    gemset = ruby-2.1.5@redmine300
    plugins = rack215
    rack = %(base)/config.ru
    socket-modifier1 = 7
    rbrequire = bundler/setup
    env = BUNDLE_GEMFILE=%(base)/Gemfile
    env = RAILS_ENV=production

(plus the usual socket, buffer & logging options)

I've just rebuilt it against uwsgi 2.0.10 so will see if there's been any difference if I switch it to ruby 2.2.1 again.

**Comment by darthmdh** [comment]
It's now working with 2.0.10.  Based on the timestamp of uwsgi-old I think what I'd done is built against HEAD instead of a versioned tag (after I moved the uwsgi repository location on the fs), so the core and plugins deviated.  This caused the newly-built rack221 plugin to fail whilst the original rack215 plugin worked fine.  Now everything is rebased it works as intended.

In the future I will ensure to rebuild the whole system when using a modular build, not just rebuild one plugin.
