### ISSUE TITLE
GridFS plugin is not compatible with mongo-cxx-driver

### ISSUE THREAD

**Issue by voxik** [unbit/uwsgi#882]
```
python uwsgiconfig.py --plugin plugins/gridfs fedora
using profile: buildconf/fedora.ini
detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/5.0.0/include', '/usr/local/include', '/usr/include']
*** uWSGI building and linking plugin plugins/gridfs ***
[gcc -pthread] gridfs_plugin.so
plugins/gridfs/gridfs.cc: In function 'void uwsgi_gridfs_do(wsgi_request*, uwsgi_gridfs_mountpoint*, char*, int)':
plugins/gridfs/gridfs.cc:45:3: error: 'scoped_ptr' is not a member of 'mongo'
   mongo::scoped_ptr<mongo::ScopedDbConnection> conn( mongo::ScopedDbConnection::getScopedDbConnection(ugm->server, ugm->timeout) );
   ^
plugins/gridfs/gridfs.cc:45:3: note: suggested alternative:
In file included from /usr/include/boost/scoped_ptr.hpp:14:0,
                 from /usr/include/mongo/logger/message_log_domain.h:18,
                 from /usr/include/mongo/logger/logger.h:19,
                 from /usr/include/mongo/util/assert_util.h:27,
                 from /usr/include/mongo/bson/bsontypes.h:20,
                 from /usr/include/mongo/bson/bsonelement.h:25,
                 from /usr/include/mongo/bson/bsonobj.h:27,
                 from /usr/include/mongo/client/bulk_operation_builder.h:20,
                 from /usr/include/mongo/client/dbclientinterface.h:29,
                 from /usr/include/mongo/client/dbclient_rs.h:23,
                 from /usr/include/mongo/client/dbclient.h:59,
                 from plugins/gridfs/gridfs.cc:3:
/usr/include/boost/smart_ptr/scoped_ptr.hpp:41:25: note:   'boost::scoped_ptr'
 template<class T> class scoped_ptr // noncopyable
                         ^
plugins/gridfs/gridfs.cc:45:21: error: 'ScopedDbConnection' is not a member of 'mongo'
   mongo::scoped_ptr<mongo::ScopedDbConnection> conn( mongo::ScopedDbConnection::getScopedDbConnection(ugm->server, ugm->timeout) );
                     ^
plugins/gridfs/gridfs.cc:45:61: error: 'mongo::ScopedDbConnection' has not been declared
   mongo::scoped_ptr<mongo::ScopedDbConnection> conn( mongo::ScopedDbConnection::getScopedDbConnection(ugm->server, ugm->timeout) );
                                                             ^
plugins/gridfs/gridfs.cc:45:130: error: 'conn' was not declared in this scope
   mongo::scoped_ptr<mongo::ScopedDbConnection> conn( mongo::ScopedDbConnection::getScopedDbConnection(ugm->server, ugm->timeout) );
                                                                                                                                  ^
*** unable to build gridfs plugin ***
```

This seems to be due to this change in legacy mongo-cxx-driver 1.0.0+:

https://jira.mongodb.org/browse/CXX-336
https://github.com/mongodb/mongo-cxx-driver/pull/167

**Comment by unbit** [comment]
So the plugin itself should implement pooling... this will require a heavy rewrite :(

**Comment by voxik** [comment]
The Jira ticket references this project: https://github.com/Climax777/mongo-cxx-pool

Just dummy question, is the pooling required? Is it enough to just connect/disconnect to DB?

**Comment by unbit** [comment]
Absolutely not required, but improves performance a lot

**Comment by WeirdCarrotMonster** [comment]
I've just encountered the same problem, so i tried to crudely patch gridfs.cc. Here's what i got: https://gist.github.com/WeirdCarrotMonster/c80795b4c2d04245eb17

Current issues:
1. I don't know how to call mongo::client::terminate at exit to properly free resources, yet it doesn't seem important, unless plugin gets unloaded.
2. Old trick with <replica>/servers doesn't seem to work anymore. There is two different classes to handle connections to replica sets and mongod servers. I'll add configuration argument for replica set name.

I'll post an update toworrow.

**Comment by unbit** [comment]
I think we can use the @WeirdCarrotMonster approach, and then investigate pooling support

**Comment by voxik** [comment]
I have used the first 3 patches from @WeirdCarrotMonster and I can build uwsgi for Fedora now. I have not tested the functionality though.

From my POV, you can close this issue. Or do you prefer to keep it open for future reference, if you are going to implement the pooling later?

Thank you.

**Comment by xrmx** [comment]
Closing, since this has been reported fixed. Anyone feel free to open a new issue about missing connection pooling especially if you are going to contribute code :)
