### ISSUE TITLE
Cannot switch to new fifo slot

### ISSUE THREAD

**Issue by NamNguyen911** [unbit/uwsgi#895]
When i try the zerg-dance, i use this config to set 3 fifo slot for my instance:
[uwsgi]
#slot 0
master-fifo = /tmp/new.fifo
#slot 1
master-fifo = /tmp/running.fifo
#slot 2
master-fifo = /tmp/sleeping.fifo
After that, i try this command 'echo 1 > /tmp/new.fifo' and this showed in the log 'active master fifo is now /tmp/running.fifo'. I think it's totally fine until i try 'echo s > /tmp/running.fifo' and nothing happend, it only show stats when i use this command 'echo s > /tmp/new.fifo'. It means the active master fifo actually is still in slot 0. So why is this, why 'echo 1 > /tmp/new.fifo' not switch master fifo to running.fifo?
More information with ls -l, the pipe is new.fifo, not running.fifo:
prw-------  1 new.fifo
-rw-r--r--@ 1 running.fifo

**Comment by NamNguyen911** [comment]
Well, the feature 'set the fifo slot' seem to be not working on MacOs, i try on ubuntu for the example above and it's work

**Comment by unbit** [comment]
Thanks for your report, i will try to understand why it is not working on osx
