### ISSUE TITLE
  If the environmental variable `UWSGI_VERSION` exists, uwsgi would simply print the version and do nothing

### ISSUE THREAD

**Issue by xuhdev** [unbit/uwsgi#898]
To reproduce, simply run:

    UWSGI_VERSION=2.0.10 ./uwsgi

**Comment by unbit** [comment]
It is the expected behaviour, as it is like you run uwsgi with --version:

http://uwsgi-docs.readthedocs.org/en/latest/Configuration.html#environment-variables
