### ISSUE TITLE
@lock Python decorator can block all workers

### ISSUE THREAD

**Issue by tcqwerty** [unbit/uwsgi#899]
uWSGI 2.0.10 on Linux; Python 2.7.6.
Let's say you have a UWSGI app with the following timed tasks:

    @timer(3)
    @lock
    def tester_a(num):
        print "running a"
        import time
        time.sleep(120)
        print "a is done sleeping"

    @timer(4)
    def tester_b(num):
        print "running b"

When you start it, what's going to happen is that tester_a will be run, tester_b will be run, then 6 seconds after start, it will come time to run tester_a again. However, it's locked. Now, I thought that the worker will see that it's locked, and move on, but it will not. Instead, it will sit there waiting for tester_a to unlock. If you have 5 workers, you'll see:
running a
running b
running b
running b
running b
At this point, worker 1 is still running time.sleep(), and all other workers are waiting in line to run tester_a(). Nothing else will be run until the 2 minute mark when tester_a returns. This will free up one worker, which, 3 seconds later, will end up waiting for the lock.

The behavior I would expect would be that if a worker tries to run a locked function, it will move on, and the locked function will be run on the first available worker once the first run finishes.

**Comment by unbit** [comment]
This is a completely different kind of lock (if we can call it 'lock'), and i am not even sure it is something we can implement with current shared memory technologies :)

**Comment by tcqwerty** [comment]
Can you put something into the docs, at least? The whole reason I was using lock was because the function could sometimes take much longer than the timer interval. (Usually takes one second, but could take up to 15 minutes.) Having the entire app go down was somewhat unexpected.

**Comment by unbit** [comment]
Hmm, not quite sure to follow you, but locking (or 'mutex' if it could help) is a pretty standard concept. Deadlocks (like the one you implemented) are part of the game. To be clear, only one execution context (process/thread) can hold a specific lock, no other one can acquire it until it is released.

**Comment by xrmx** [comment]
Looks like we can close this.
