### ISSUE TITLE
glusterfs plugin

### ISSUE THREAD

**Issue by mahsa-frj** [unbit/uwsgi#906]
hi, i compile uwsgi with glusterfs plugin, but when i use this command:
./uwsgi --master --http-socket=:9999 --http-socket-modifier1=27 --glusterfs-mount=mountpoint=/,volume=uwsgi,server=x.x.x.x:0  --threads=30, i get this output

*** Starting uWSGI 2.0.10 (64bit) on [Tue May  5 14:57:01 2015] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-7) on 05 May 2015 13:44:07
os: Linux-3.19.5-100.fc20.x86_64 #1 SMP Mon Apr 20 19:51:16 UTC 2015
nodename: uwsgi1
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/ossl/Downloads/uwsgi-2.0.10
detected binary path: /home/ossl/Downloads/uwsgi-2.0.10/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3898
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...1083 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :9999 fd 3
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 742688 bytes (725 KB) for 30 cores
*** Operational MODE: threaded ***
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5637)
spawned uWSGI worker 1 (pid: 5638, cores: 30)
[glusterfs] mounting / ...
GlusterFS app/mountpoint 0 (/) loaded in 0 seconds at 0xf6ea80
[glusterfs] try connect to x.x.x.x:0 for mountpoint / on worker 1 ...
[glusterfs] worker 1 connected to x.x.x.x:0
and when curl x.x.x.x:9999, the output is NotFound

[pid: 5638|app: 0|req: -1/1] x.x.x.x () {30 vars in 487 bytes} [Tue May  5 14:59:03 2015] GET / => generated 9 bytes in 24 msecs (HTTP/1.1 404) 2 headers in 71 bytes (0 switches on core 0)

please help me, thanks for your reply.

**Comment by unbit** [comment]
You got the answer on irc (you are asking a non-existent object: /), can we close this ?

**Comment by mahsa-frj** [comment]
no the / directory exist, and no i didn't get it on irc..., can explain more about this directory?(/)
which directory is specified in this section: --glusterfs-mount=mountpoint= ??

**Comment by unbit** [comment]
the / directory does not exist in gluster, the plugin calls glfs_open() so you must point it on a file not a "dir" (albeit the directory term here is not right)

**Comment by unbit** [comment]
Just to be clear:

curl http://x.x.x.x:9999/ -> wrong

curl http://x.x.x.x:9999/afileinthebrick -> ok

**Comment by mahsa-frj** [comment]
i use two machine, and gluster is running on 2 machine, i peer it, and create the volume and start it, i didn't mount it, ok! and  use the command to specify in first comment, where does i have problem?
i use this command to create volume in glusterfs:
gluster volume create uwsgi replica 2 uwsgi1:/data/ uwsgi2:/data/
and then i use this command:
./uwsgi --master --http-socket=:9999 --http-socket-modifier1=27 --glusterfs-mount=mountpoint=/,volume=uwsgi,server=x.x.x.x:0 --threads=30
