### ISSUE TITLE
Spaces and tabs are mixed to indent the codes.

### ISSUE THREAD

**Issue by Algy** [unbit/uwsgi#913]
I've read source codes of 2.0.10 with vim editor setting up ts=4 option. I found some lines use 8-width spaces for indentation, while others use tabs. Even worse, Some lines of them are mixing 8 spaces and tabs.

Here are the number of lines where spaces/tabs are used and they are mixed in "/core" directory.
```
# Where tabs are used
$ egrep -n -R "^\t+" *.c  | wc -l
30134
# Where spaces are used
$ egrep -n -R "^( )+" *.c  | wc -l
6025
# where they are mixed.
$ egrep -n -R "^([ \t]*( )[ \t]*\t[ \t]*|[ \t]*\t[ \t]*( )[ \t]*)" *.c  | wc -l
438
```

**Comment by unbit** [comment]
The indent line is on top of uwsgi.h. Unfortunately we should periodically re-run it over the sources, but this does not happen enough frequently.

**Comment by methane** [comment]
There are two `-npsl` in
`/* indent -i8 -br -brs -brf -l0 -npsl -nip -npcs -npsl -di1 -il0 */`

**Comment by xrmx** [comment]
I think we can close this in favor of pull request #913. Thanks!
