### ISSUE TITLE
Mules are not being restarted on touch-chain-reload 

### ISSUE THREAD

**Issue by offline** [unbit/uwsgi#915]

**Comment by ramnes** [comment]
I can confirm this.

We were hit by that issue in production yesterday, and sadly discovered that touch-chain-reload doesn't reload mules nor spoolers.

This is a serious flaw in the touch-chain-reload feature, which is an awesome feature but that we can't use anymore in our current use-case.

Ping @ultrabug @Shir0kamii

**Comment by unbit** [comment]
Please make a pull-request but ensure it is governed by an option, as we do not change established behaviours

**Comment by ultrabug** [comment]
Sorry @unbit but are you saying this is the intended behaviour ?

**Comment by unbit** [comment]
Yes, chain reloading is intended only for workers, but i have nothing against adding the recycling of mules and spoolers in the same action
