### ISSUE TITLE
uwsgitop display problem on high numbers of requests

### ISSUE THREAD

**Issue by offline** [unbit/uwsgi#916]
It's starts good
![good](https://cloud.githubusercontent.com/assets/42720/7554678/e6e25fec-f739-11e4-82ef-5590fc6578fe.png)

But when number of requests per worker reach more than 10 millions, the requests per second column move beneath exceptions
![bad](https://cloud.githubusercontent.com/assets/42720/7560798/240ba226-f7cf-11e4-947f-8619aff08667.png)

**Comment by unbit** [comment]
we should add k,m,g, t ... suffix to req too (and make %.2f approximation for RunT)

**Comment by xrmx** [comment]
@offline could you please move this bug to uwsgitop issue tracker? https://github.com/unbit/uwsgitop

**Comment by xrmx** [comment]
Moved to https://github.com/unbit/uwsgitop/issues/38 closing.
