### ISSUE TITLE
error message always shows default callable name, very confusing

### ISSUE THREAD

**Issue by abe-winter** [unbit/uwsgi#919]
I'm a new uwsgi user and I got thrown for a loop by the logging error here:
https://github.com/unbit/uwsgi/blob/e45f710694f18052aa00ee5bb866d9aeca76fb80/plugins/python/pyloader.c#L605

My situation was that `callable` was set to `app` in the uwsgi conf but my uwsgi program (a flask app) used `APP`. The log message put my debugging efforts on a false trail by making me think callable was set to its default, i.e. my configuration was wrong.

Please remove the hardcoded string `"application"` from the error message. Even better, show the actual value of the `callable` param.

**Comment by unbit** [comment]
yes, it seems really reasonable, feel free to make a pull request. Thanks

**Comment by abe-winter** [comment]
ok, will do.
