### ISSUE TITLE
Error handling for mmap() in ugreen plugin won't work

### ISSUE THREAD

**Issue by Algy** [unbit/uwsgi#920]
(v 2.0.10)
When mmap() failed, it is supposed to return MAP_FAILED, as described in man page.

> RETURN VALUES
>   Upon successful completion, mmap() returns a pointer to the mapped region.  
>   Otherwise, a value of MAP_FAILED is returned and errno is set to indicate the error.

However, from ugreen.c:105 to 107, the return value of mmap() **plus uwsgi.page_size** is assigned to 'ug.contexts[i].uc_stack.ss_sp' and then it is compared to MAP_FAILED to test if mmap() failed, which is definitely wrong.
 ```c
105         ug.contexts[i].uc_stack.ss_sp = mmap(NULL, ug.u_stack_size + (uwsgi.page_size*2) , PROT_READ | PROT_WRITE | PROT_EXEC, MAP_ANON | MAP_PRIVATE, -1, 0) + uwsgi.page_size;
106 
107         if (ug.contexts[i].uc_stack.ss_sp == MAP_FAILED) {
108             uwsgi_error("mmap()");
109             exit(1);
110         }
```

**Comment by unbit** [comment]
Nice catch, would you like to do a pull request ?

**Comment by Algy** [comment]
Sure. Which commit should my branch based on?

**Comment by unbit** [comment]
master, i will backport to stable by myself. thanks

**Comment by Algy** [comment]
#921
