### ISSUE TITLE
Error in shared memory allocation calculation

### ISSUE THREAD

**Issue by offline** [unbit/uwsgi#922]
When I try to give a big number in --sharedarea configuration, calculation is wrong

For exampe, this is what happens when i set sharedarea = 666000

it should be around 3GB, but it tries to allocate 17592186042921MB instead.. 

writing pidfile to /tmp/uwsgi.pid
detected binary path: /var/www/.env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 483020
your memory page size is 4096 bytes
detected max file descriptor number: 200000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
unable to allocate 18446744072142524416 bytes (17592186042921MB)
mmap(): Cannot allocate memory [core/utils.c line 2225]

**Comment by offline** [comment]
The strange thins is when I set sharedarea = 1100000 it starts, but uwsgi.sharedarea_read32 function returns error.

**Comment by unbit** [comment]
is it a 32bit or 64bit arch ?

**Comment by offline** [comment]
64bit
uname -a
Linux mobfox 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by unbit** [comment]
ok, it was a missing typecast, you can use the keyval mode to bypass it (using size=xxx_bytes instead of pages)

**Comment by offline** [comment]
It works, but the uwsgi_sharedarea_read32() function still returns error.

uwsgi.sharedarea_read32(0, 10737276)             
*** ValueError: error calling uwsgi_sharedarea_read32()


in .ini i tried sharedarea = size=4300000000
which prints at startup:
sharedarea 0 created at 0x7f3515b68000 (1049805 pages, area at 0x7f3515b69000)

**Comment by offline** [comment]
when I try to read from a smaller value - it works

uwsgi.sharedarea_read32(0, 1073727) 
0

**Comment by unbit** [comment]
i have added a test for big ranges (uwsgi t/sharedarea/bigranges.ini) please pull and re-run, it should be fixed now

**Comment by offline** [comment]
(.env) andrey@andrey-work:/tmp/utestme$ ./uwsgi t/sharedarea/bigranges.ini
[uWSGI] getting INI configuration from t/sharedarea/bigranges.ini
*** Starting uWSGI 2.1 (64bit) on [Wed May 13 16:58:22 2015] ***
compiled with version: 4.8.2 on 13 May 2015 16:56:47
os: Linux-3.16.0-36-generic #48~14.04.1-Ubuntu SMP Wed Apr 15 13:11:28 UTC 2015
nodename: andrey-work
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /tmp/utestme
detected binary path: /tmp/utestme/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 31074
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)






sharedarea 0 created at 0x7fe48547a000 (1049805 pages, area at 0x7fe48547b000)
uwsgi socket 0 bound to UNIX address /tmp/foo fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1d0bdf0
your mercy for graceful operations on workers is 60 seconds
your request buffer size is 4096 bytes
mapped 72792 bytes (71 KB) for 1 cores
*** Operational MODE: command ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 25174, cores: 1)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK

**Comment by offline** [comment]
Now I need to understand how to run my project with newly compiled version. I've always used uwsgi from pip. When I run it from build directory it gives me ImportError: No module named site

**Comment by offline** [comment]
sorry, I compiled it with 2.7 python and tried to run python3 project, thats why it didn't find site module. (by the way, python3 test fail because of sintax in test (long integers)

 Everything is working now in compiled version.
