### ISSUE TITLE
can i do something before uwsgi master kill worker

### ISSUE THREAD

**Issue by bluezone2015** [unbit/uwsgi#924]
I made some statis in uwsgi app, the statis data will send to mysql every 5 mins, but if master killed the worker random, some statis data will lose.

If i can get something such as signal, then i can send the latest statis to mysql before it killed.

Can anyone help me, thanks a lot.

**Comment by unbit** [comment]
Workers can die constantly for hundreds of reasons, i would generate statis directly in the master (you can spawn a python thread into it)

**Comment by xrmx** [comment]
I think we can close this.
