### ISSUE TITLE
 uWSGI cpu counsume 100%

### ISSUE THREAD

**Issue by jjjan** [unbit/uwsgi#937]
hello,
i have problem when try open a web page  uWSGI cpu goes100% and nginx 502 bad gateway comes up!
i have 4 GB ram
4 core cpu 2 ghz
 after a lot's of page refresh it's up the webpage any idea about this problem?

**Comment by unbit** [comment]
Profile your app, probably you have some blocking loop or similar. Eventually report both nginx and uwsgi configurations and versions
