### ISSUE TITLE
import references are not reused across submodules

### ISSUE THREAD

**Issue by parasyte** [unbit/uwsgi#941]
I don't know how to better explain the bug, but I've provided an example minimal project that demonstrates: https://github.com/parasyte/uwsgi-bug It can be reproduced equally with the python and pypy plugins.

Interesting that `aliasconfig` is not affected...

**Comment by unbit** [comment]
This is expected for "wsgi" modules (check PyImport_ImportModule api call). You can bypass it importing src/main.py before the wsgi load (using --shared-pyimport) or using --wsgi-file instead of --wsgi

**Comment by unbit** [comment]
And obviously if you use wsgi = main:app the problem will not arise as the pythonpath includes src

**Comment by parasyte** [comment]
You're absolutely right! This isn't a bug at all. Just a misconfiguration. It was a surprising behavior, but it makes sense now. Thank you!
