### ISSUE TITLE
Allow the configuration of the openssl DH parameters

### ISSUE THREAD

**Issue by edevil** [unbit/uwsgi#946]
It would be nice to be able to supply the DH parameters used by OpenSSL. Basically a clone of the nginx "ssl_dhparam" parameter or the Apache "SSLOpenSSLConfCmd DHParameters" option.

Thanks.

**Comment by unbit** [comment]
You can append your dhparams in the crt file, they will be automatically managed by the ssl context creator:

https://github.com/unbit/uwsgi/blob/master/core/ssl.c#L255

**Comment by edevil** [comment]
Great! I'll try it.

**Comment by unbit** [comment]
Can we close it ?

**Comment by xrmx** [comment]
>3 months without followup, closing.
