### ISSUE TITLE
pcre support on Heroku for use with django-websocket-redis

### ISSUE THREAD

**Issue by papasax** [unbit/uwsgi#947]
Hi,

I installed uWSGI on Heroku in emperor mode with pcre support. The emperor is configured to route the websocket and the request to two instances of uwsgi.
route = ^/ws uwsgi:/var/tmp/web.socket,0,0
route = ^/ uwsgi:/var/tmp/django.socket,0,0
 
uwsgi is compiled with pcre:
 ################# uWSGI configuration #################
remote:            pcre = True
remote:            kernel = Linux
remote:            malloc = libc
remote:            execinfo = False
remote:            ifaddrs = True
remote:            ssl = True
remote:            zlib = True
remote:            locking = pthread_mutex
remote:            plugin_dir = .
remote:            timer = timerfd
remote:            yaml = embedded
remote:            json = False
remote:            filemonitor = inotify
remote:            routing = True
remote:            debug = False
remote:            capabilities = False
remote:            xml = libxml2
remote:            event = epoll
remote:            ############## end of uWSGI configuration #############

However when i launch uwsgi --pcre-jit i get this message:
*** Starting uWSGI 2.0.10 (64bit) on [Mon Jun 22 22:51:56 2015] ***
compiled with version: 4.8.2 on 22 June 2015 22:37:39
os: Linux-3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015
nodename: 2bba099f-37e1-4ee2-aaa2-2400a68e6530
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app
detected binary path: /app/.heroku/python/bin/uwsgi

This used to work a few weeks ago!

What am i doing wrong?

**Comment by xrmx** [comment]
@papasax have you solved your issue?

**Comment by papasax** [comment]
Yes. This was answered here: http://stackoverflow.com/questions/30991198/uwsgi-with-pcre-support.
" jit is only an optimization,it is not required for uWSGI internal routing, any pcre version will be good for it –  roberto Jun 23 at 9:22"
I'm closing the issue.
