### ISSUE TITLE
puwsgi protocol appears broken?

### ISSUE THREAD

**Issue by xtfxme** [unbit/uwsgi#948]
After setting up a socket with `--puwsgi-socket` I am unable to make any requests:

```
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/puwsgi.c line 56]
Traceback (most recent call last):
  File "../sockfun.py", line 131, in <module>
    response = client.recv(8192)
socket.error: [Errno 104] Connection reset by peer
```

`puwsgi` protocol seems left behind, as it does not interact with `wsgi_req->uh->_pktsize` like `uwsgi` proto does (so `wsgi_req->len` is always 0).

I was looking into it as a fast way to pump data into a worker from another local process.

**Comment by unbit** [comment]
yep, it has never been ported to the 2.1 api. Would you like to make a pull request ? (you already spotted the error)

**Comment by xtfxme** [comment]
I can try again tonight -- I did exactly that last night, and it allowed one request to be processed, but the second failed with another error. It was late though, so that's as far as I went.

The `puwsgi` proto is essentially the `uwsgi` proto back-to-back, with no bodies, right? Will the WSGI callable be called multiple times with the same socket connection?
