### ISSUE TITLE
emperor on-demand crash when vassal has another defined socket

### ISSUE THREAD

**Issue by Glandos** [unbit/uwsgi#965]
When doing test with uwsgi and searx, I was testing --emperor-on-demand-dir and my vassal has already an option for the socket file, which ends in .sock instead of .socket

I got a backtrace in the vassal.

I was running uwsgi 2.0.7 on Debian/testing.

**Comment by unbit** [comment]
Can you report the backtrace ?

**Comment by Glandos** [comment]
Hmm. I should have reported it yesterday. I'm totally unable to reproduce the backtrace. I had it twice yesterday (after commenting/uncommenting the socket option in the INI vassal file), and now, even with the old one. I can't have the backtrace.

So, let's say it's closed.
