### ISSUE TITLE
blocking requests even there are multiple processes ?

### ISSUE THREAD

**Issue by yueyoum** [unbit/uwsgi#971]
I have a simple python file:
```python
import os
from bottle import Bottle, request

import time

application = Bottle()


@application.get("/")
def index():
    print os.getppid(), os.getpid()

    start = time.time()
    task()
    end = time.time()

    return str(end-start)


def task():
    res = 0
    for i in xrange(1, 1000):
        for j in xrange(1, 10000):
            res += i ** 2.1 / float(j)

    return res
```

the uWSGI configure file is:
```
[uwsgi]
master = true
processes = 4
threads = 1
enable-threads = true
module = app1:application
http = 127.0.0.1:9090
```

I have tested many times, 
I made requests from my browser's multiple tab, 
uWSGI handle this requests one by one,
which means, the second request started only after the first one was finished.

Why this?

uWSGI has 4 processes,  I saw even the second request and the first one is handled by the
different uwsgi processes, the seconds MUST wait the first one finish...

**Comment by unbit** [comment]
because browsers tend to not open more than a couple of requests to the same url, it is a common error when testing :) use curl or other similar tools to make this kind of tests

**Comment by unbit** [comment]
can we close it ?

**Comment by yueyoum** [comment]
yes,   we can close it.
i tested it with  a command line tool,  
uwsgi handle the multi requests at the same time.
