### ISSUE TITLE
mod_proxy_uwsgi: uds not working, dns lookup failure

### ISSUE THREAD

**Issue by BinaryKhaos** [unbit/uwsgi#973]
After trying really hard to get mod_proxy_uwsgi working with uds, I am convinced I have hit a bug either in Apache or uwsgi.

The error message is always a variation of: "AH00898: DNS lookup failure for: \xe8:&{\xcd\x0c returned by /" where the actual unicode string varies depending on the configuration.

What is interesting, I can give whatever path to a uds I want (either existent or not) and it does not make the slightest difference when it comes to error messages. The same goes for permissions.

I have tested this w/ uwsgi 2.0.11 and Apache 2.4.12 as well as 2.4.16 -- both make absolutely no difference at all.

As wsgi application I am taking a vanilla Django 1.8.3 installation w/ Python 3.4.3 (same version that uwsgi is running on). Here the (test and not production) configuration for the app:

```
[uwsgi]
uid=someuser
gid=someuser
virtualenv=/home/someuser/.virtualenvs/testenv/
chdir=/home/someuser/public/testsite.test/
module=helloworld.wsgi:application
socket=/tmp/uwsgi-testsite.test.sock
master=True
need-plugin=python34
```

uwsgi is configured in emperor mode -- which works fine. The vassal however never becomes loyal with the uds configuration (and no access is logged on uwsgi). If, on the other hand, a tcp socket is used (socket=127.0.0.1:9999), it works just fine.

Here the relevant Apache configuration for the vhost:

```
<VirtualHost 10.0.0.1:80>
  ServerName testsite.test

  <Location "/">
    ProxyPass unix:/tmp/uwsgi-testsite.test.sock|uwsgi://
#    ProxyPass uwsgi://127.0.0.1:9999/
  </Location>
</VirtualHost>
```

According to the docs, postings and some source code I read, the syntax is just fine. And like I said, what is strange is that I can pass whatever path I like, it never raises a different error message at all. Simply the unicode string varies, nothing more.

If there is anything else I can help with to debug this further, please let me know. I would have gladly jumped right in and tried to hunt this pesky bug down myself but right now I am rather limited in time and unfortunately I have a feeling this could take quite some time for someone not familiar with either the Apache or the uwsgi code base.

**Comment by xrmx** [comment]
@BinaryKhaos do the changes in @niol pull request fixes the issue for you?

**Comment by xrmx** [comment]
This should be fixed in master, please reopen if it's not the case
