### ISSUE TITLE
uwsgi php plugin link error  "ld: library not found for -lphp5"

### ISSUE THREAD

**Issue by xudeheng** [unbit/uwsgi#976]
I have already set environment vars:

export LD_LIBRARY_PATH="/usr/local/Cellar/php55/5.5.27_2/lib"
export UWSGICONFIG_PHPLIBDIR="/usr/local/Cellar/php55/5.5.27_2/lib"
export UWSGICONFIG_PHPPATH="/usr/local/Cellar/php55/5.5.27_2/bin/php-config"
export UWSGICONFIG_PHPDIR="/usr/local/Cellar/php55/5.5.27_2"

**Comment by xrmx** [comment]
@xudeheng have you solved this?

**Comment by xrmx** [comment]
3 months without followup, closing.
