### ISSUE TITLE
uWSGI cpu counsume 100% sometimes

### ISSUE THREAD

**Issue by RaynorZhong** [unbit/uwsgi#979]
CentOS + Nginx+ uWSGI + Django

uWSGI

    # mysite_uwsgi.ini file
    [uwsgi]
    # Django-related settings
	# the base directory (full path)
	chdir           = /usr/share/nginx/contact
	# Django's wsgi file
	module          = contact.wsgi
	# the virtualenv (full path)
	# home            = /usr/local/bin/virtualenv

	# process-related settings
	# master
	master          = true
	# maximum number of worker processes
	processes       = 5
	# the socket (use the full path to be safe
	socket          = /usr/share/nginx/contact/contact.sock
	# ... with appropriate permissions - may be needed
	chmod-socket    = 666
	# clear environment on exit
	vacuum          = true
	# log
	pidfile = /tmp/contact-master.pid
	daemonize = /var/log/uwsgi/contact.log
	die-on-term = true
	max-requests = 5000

Nginx

	# mysite_nginx.conf

	# the upstream component nginx needs to connect to
	upstream django {
	    server unix:///usr/share/nginx/contact/contact.sock; # for a file socket
	    # server 127.0.0.1:8001; # for a web port socket (we'll use this first)
	}
	# configuration of the server
	server {
	    # the port your site will be served on
	    listen      8000;
	    # the domain name it will serve for
	    server_name twbbres.91act.com; # substitute your machine's IP address or FQDN
	    charset     utf-8;

	    # max upload size
	    client_max_body_size 75M;   # adjust to taste

	    # Django media
	    location /media  {
	        alias /usr/share/nginx/media;  # your Django project's media files - amend as required
	    }

	    location /static {
	        alias /usr/share/nginx/static; # your Django project's static files - amend as required
	    }

	    # Finally, send all non-media requests to the Django server.
	    location / {
	        uwsgi_pass  django;
	        include     /usr/share/nginx/contact/uwsgi_params; # the uwsgi_params file you installed
	    }
	}

when the project is runing , cpu counsume 100% sometimes, and I hava no idear what to do?

**Comment by unbit** [comment]
You can strace the process to check what is going on, or use the python tracebacker:

http://uwsgi-docs.readthedocs.org/en/latest/Tracebacker.html
