### ISSUE TITLE
more detailed version string

### ISSUE THREAD

**Issue by swuecho** [unbit/uwsgi#984]
currently only major.minor, such as 2.1

if commit can be embeded to version string, it will be great. such as 2.1.ca673dfc

**Comment by unbit** [comment]
This was a followed practice in development branches, then (i do not know why) we stopped doing it.

Reintroduced back in https://github.com/unbit/uwsgi/commit/eab664ae8bb8d1b53e5124edae6bb6d8410d1fe9
