### ISSUE TITLE
'module' object has no attribute 'spool'

### ISSUE THREAD

**Issue by mhassan1991** [unbit/uwsgi#989]
I am getting above error when following line in my code run in django project. 
uwsgi.spool({'data' :message_data})
I have made configuration for spooler. My .ini file is as follow.

[uwsgi]
socket = /tmp/uwsgi_worksteps.socket
processes = 4
threads = 2
wsgi-file = apache/django.wsgi
uid = deploy
gid = www-data
python-path =
touch-chain-reload = /srv/www/worksteps/current
chdir = /srv/www/worksteps/current
virtualenv = /srv/www/worksteps/shared/env
master = true
max-requests = 1
chmod = 770
hook-post-fork = chdir:/srv/www/worksteps/current
spooler = /srv/www/worksteps/current/spooler
spooler-import = /srv/www/worksteps/current/testing/tasks
spooler-processes = 5

Is there any thing wrong?

**Comment by xrmx** [comment]
Hello, github issues are not the right tool for asking for help with configurations. I suggest you to take a look at http://uwsgi-docs.readthedocs.org/en/latest/PythonDecorators.html ad use the spooler decorators instead of calling uwsgi directly

**Comment by xrmx** [comment]
@mhassan1991 have you resolved the issue? it could be that spooler-import likes python path more than filesystem path

**Comment by mhassan1991** [comment]
I changed two things. 
1- spooler-import = /srv/www/worksteps/current/testing/tasks.py
2- spooler = spooler

No this is working fine.

**Comment by xrmx** [comment]
Closing then, thanks for confirming you have resolved the issue.
