### ISSUE TITLE
uwsgi silently fails with exec-as-root

### ISSUE THREAD

**Issue by laurivosandi** [unbit/uwsgi#992]
When I start ``uwsgi /etc/uwsgi/apps-enabled/blah`` everything works as expected because the ``PATH`` environment variable contains ``/usr/local/bin``, but ``service uwsgi start`` fails silently when I for example specify a command that is in ``/usr/local/bin`` for ``exec-as-root``. I managed to work around the issue by specifying full path for the command, but it would be nice for uwsgi to give a hint about the issue. I am not 100% sure this is problem with uwsgi or Ubuntu 14.04 LTS's packaging.

**Comment by unbit** [comment]
Every error in exec-as-* functions is written into logs. If none of the logs setup by the debian/ubuntu packages are reporting it, you should report to package maintainer:

```
./uwsgi --exec-as-root bah
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jul 30 04:42:18 2015] ***
compiled with version: 4.1.2 20080704 (Red Hat 4.1.2-54) on 30 July 2015 04:37:09
os: Linux-2.6.18-348.1.1.el5 #1 SMP Tue Jan 22 16:19:19 EST 2013
nodename: centos64
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/uwsgi
detected binary path: /root/uwsgi/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
running "bah" (as root)...
/bin/sh: bah: command not found
command "bah" exited with non-zero code: 127
```

**Comment by xrmx** [comment]
3 months without followup, closing.
