### ISSUE TITLE
hi,all,how to use the whitelist feature?

### ISSUE THREAD

**Issue by ranlei** [unbit/uwsgi#994]
Because the document is too simple, I don't know how to configure the blacklist, can you give an example？

I set my options in uwsgi.ini:
whitelist = /path/templist

templist file like this list:
10.151.112.4
10.194.102.4
 
startup errors：

uWSGI error: forbidden option "master" (by whitelist)

**Comment by xrmx** [comment]
Hello, a github issue is the wrong way to ask for help configuring uwsgi. The uwsgi mailing list is. When you ask for help also please always report the uwsgi version, all the configuration, everything else relevant. Thanks.

**Comment by ranlei** [comment]
@xrmx tks，I‘ve learned
