### ISSUE TITLE
Uwsgi keeps timing out. 

### ISSUE THREAD

**Issue by radding** [unbit/uwsgi#996]
I am running a flask application using nginx as my front end server. When testing the site in a browser, nginx returns a 504 time out error from uwsgi. I checked the logs and it doesn't look like call gets propagated to my application (no log entries corresponding to a call). The first couple of requests work but then the process hangs. It also looks like the load isn't distributed across worker processes. I used uwsgitop when the application goes into this bad state and this is what the output looks like :
    
    uwsgi-2.0.9 - Mon Aug  3 17:07:02 2015 - req: 2 - RPS: 0 - lq: 0 - tx: 23.0K
    node: url.url.url.com - cwd: / - uid: 65534 - gid: 65534 - masterpid: 11555
    WID    %       PID     REQ     RPS     EXC     SIG     STATUS  AVG     RSS     VSZ     TX      RunT    
    2      0.0     11582   0       0       0       0       idle    0ms     0       0       0       0
    3      0.0     11583   0       0       0       0       idle    0ms     0       0       0       0
    4      0.0     11584   0       0       0       0       idle    0ms     0       0       0       0
    5      0.0     11585   0       0       0       0       idle    0ms     0       0       0       0
    6      0.0     11586   0       0       0       0       idle    0ms     0       0       0       0
    1      100.0   11581   2       0       0       0       busy    972ms   0       0       23.0K   2001

Using strace reveals these lines repeated over and over again:

    clock_gettime(CLOCK_MONOTONIC, {5972918, 980693088}) = 0
    gettimeofday({1438621896, 813692}, NULL) = 0
    clock_gettime(CLOCK_MONOTONIC, {5972918, 981098109}) = 0
    epoll_ctl(25, EPOLL_CTL_MOD, 34, {EPOLLOUT, {u32=34, u64=1146756268066}}) = 0
    clock_gettime(CLOCK_MONOTONIC, {5972918, 981309558}) = 0
    epoll_wait(25, {{EPOLLOUT, {u32=34, u64=1146756268066}}}, 64, 3332) = 1
    clock_gettime(CLOCK_MONOTONIC, {5972918, 981384025}) = 0
    sendto(34, "\0\0\0\10\377\377\377\376\0\0\0\v", 12, 0, NULL, 0) = 12
    clock_gettime(CLOCK_MONOTONIC, {5972918, 981792784}) = 0
    futex(0xb58680, FUTEX_WAKE_PRIVATE, 1)  = 1
    epoll_ctl(25, EPOLL_CTL_MOD, 34, {EPOLLIN, {u32=34, u64=1151051235362}}) = 0
    epoll_ctl(25, EPOLL_CTL_ADD, 32, {EPOLLIN, {u32=32, u64=8589934624}}) = -1 EEXIST (File exists)
    clock_gettime(CLOCK_MONOTONIC, {5972918, 982173090}) = 0
    epoll_wait(25, {{EPOLLIN, {u32=34, u64=1151051235362}}}, 64, 3232) = 1
    clock_gettime(CLOCK_MONOTONIC, {5972918, 982293851}) = 0
    clock_gettime(CLOCK_MONOTONIC, {5972918, 982485366}) = 0
    epoll_ctl(25, EPOLL_CTL_ADD, 34, {EPOLLIN, {u32=34, u64=1155346202658}}) = -1 EEXIST (File exists)
    clock_gettime(CLOCK_MONOTONIC, {5972918, 982641452}) = 0
    epoll_wait(25, {{EPOLLIN, {u32=34, u64=1151051235362}}}, 64, 6666) = 1
    clock_gettime(CLOCK_MONOTONIC, {5972918, 982744348}) = 0
    recvfrom(34, "\0\0\0\20", 4, 0, NULL, NULL) = 4
    clock_gettime(CLOCK_MONOTONIC, {5972918, 983030985}) = 0
    epoll_ctl(25, EPOLL_CTL_ADD, 34, {EPOLLIN, {u32=34, u64=1155346202658}}) = -1 EEXIST (File exists)
    clock_gettime(CLOCK_MONOTONIC, {5972918, 983168952}) = 0
    epoll_wait(25, {{EPOLLIN, {u32=34, u64=1151051235362}}}, 64, 6666) = 1
    clock_gettime(CLOCK_MONOTONIC, {5972918, 983272341}) = 0
    recvfrom(34, "\377\377\377\376\0\0\0b\0\1A\r\0\0\0\0", 16, 0, NULL, NULL) = 16
    clock_gettime(CLOCK_MONOTONIC, {5972918, 983586701}) = 0
    epoll_ctl(25, EPOLL_CTL_ADD, 34, {EPOLLIN, {u32=34, u64=1155346202658}}) = -1 EEXIST (File exists)
    epoll_ctl(25, EPOLL_CTL_ADD, 32, {EPOLLIN, {u32=32, u64=8589934624}}) = -1 EEXIST (File exists)
    clock_gettime(CLOCK_MONOTONIC, {5972918, 983842654}) = 0
    epoll_wait(25,

where the file handles are:

    uwsgi_pyt 10472 nobody   34u  IPv4           38132233       0t0      TCP 10.128.41.117:42903->10.128.41.68:2181 (CLOSE_WAIT
    uwsgi_pyt 10472 nobody   25u  0000                0,9         0     3866 anon_inode
    uwsgi_pyt 10472 nobody   32r  FIFO                0,8       0t0 38132232 pipe

and finally the uwsgi.ini file:

    [uwsgi]
    master              = true
    wsgi-file           = /opt/bnci/bc/tools/Cudaspt/flaskApp/__init__.py
    module              = flaskApp
    callable            = app
    enable-threads      = true
    socket              = /var/tmp/cudaspt.sock
    gid                 = nobody
    uid                 = nobody
    chmod-socket        = 777
    daemonize           = /var/log/bmas/cudaspt.log
    pythonpath          = /opt/bnci/bc/tools/Cudaspt
    workers             = 6
    max-requests        = 1000
    stats               = 127.0.0.1:1717

The site is hosted on a gentoo server using uwsgi version 2.0.9. If I restart the uwsgi app, it will sometimes work and sometimes it won't. sometimes the error is on the first request, sometimes it is on subsequent requests. I have also noticed that calling lsof will usually force the program to work again.

**Comment by unbit** [comment]
That strace is not from a uWSGI code path (well, honestly as soon as i have seen it it looked to me as a gevent one) so you should investigate your app. You can try the pytracebacker. Regarding request distribution it is the expected behaviour, the kernel will try to choose the best worker based on various factors.

**Comment by radding** [comment]
That may be it. I use Gevent in several other places. And might have forgotten to call patch_all at the beginning of the project.

**Comment by unbit** [comment]
You cannot use gevent in a blocking app. You need to eventually use the uWSGI gevent plugin.

**Comment by radding** [comment]
Yes, I know. The flask web app is a front end to an existing project that does use gevent. I rebuilt and reinstalled uwsgi with the gevent pluggin and it seems to have fixed the problem.
