### ISSUE TITLE
uwsgi how can I distinguish vassals entry log?

### ISSUE THREAD

**Issue by promogest** [unbit/uwsgi#997]
I have a web app deployed with nginx and uwsgi in emperor mode and 20 vassals. All is working good but i have only one log file and i like it because it is easy to monitor but i can't distinguish the different request by vassals. When i have an error i don't know which vassals crashed only why.

this is a line of the log:

[pid: 890|app: 0|req: 9/9] 87.19.11.228 () {42 vars in 738 bytes} [Mon Aug 3 21:56:38 2015] GET /pg/VD/UI => generated 51341 bytes in 52 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
thanks 
F.

**Comment by unbit** [comment]
```ini
log-prefix = foobar
```

will do the trick

**Comment by promogest** [comment]
i works thanks

**Comment by promogest** [comment]
solved putting this line in each .ini vassal:
log-format = vassalname %(addr) - pid: %(pid) - user:%(user) - [%(ltime) - %(msecs)] "%(method) %(uri) %(proto) %(host)" %(status) size:%(size) "%(referer)" "%(uagent)"
